### ISSUE TITLE
error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f14008c declared here is not defined

### ISSUE THREAD

**Issue by bphown** [iBotPeaches/Apktool#2194] opened 2019-10-08 12:02 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - apkmirror

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: max res 23, skipping values-sw600dp-v26
W: max res 23, skipping values-v27
W: max res 23, skipping values-v26
W: max res 23, skipping values-v28
W: max res 23, skipping values-vrheadset-v26
W: max res 23, skipping layout-v29
W: max res 23, skipping values-v24
W: max res 23, skipping values-sw600dp-v27
W: max res 23, skipping layout-v26
W: max res 23, skipping drawable-v26
W: max res 23, skipping values-v29
W: max res 23, skipping values-v25
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7814: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f14008c declared here is not defined.
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7815: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f14008d declared here is not defined.
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7816: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f14008e declared here is not defined.
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7817: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f14008f declared here is not defined.
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7818: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f140090 declared here is not defined.
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7812: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f140139 declared here is not defined.
W: /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res/values/public.xml:7813: error: Public symbol style/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f14013a declared here is not defined.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3487169604542110648.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 23, --max-sdk-version, 23, --max-res-version, 23, --version-code, 390404305, --version-name, 78.0.3904.43, --no-version-vectors, -F, /tmp/APKTOOL8271252030109074115.tmp, -0, arsc, -0, pak, -0, dat, -0, bin, -0, txt, -0, webp, -0, res/-E.9.png, -0, res/09.9.png, -0, res/0H.9.png, -0, res/1c.9.png, -0, res/33.9.png, -0, res/3P.9.png, -0, res/3g.9.png, -0, res/45.9.png, -0, res/4_.9.png, -0, res/4i.9.png, -0, res/4m.9.png, -0, res/5F.9.png, -0, res/5H.9.png, -0, res/5n.9.png, -0, res/5v.9.png, -0, res/5z.9.png, -0, res/6w.9.png, -0, png, -0, res/72.9.png, -0, res/7F.9.png, -0, res/7F1.9.png, -0, res/7P.9.png, -0, res/7T.9.png, -0, res/8V.9.png, -0, res/8w.9.png, -0, res/93.9.png, -0, res/9X.9.png, -0, res/9q.9.png, -0, res/A4.9.png, -0, res/AB.9.png, -0, res/Ae.9.png, -0, res/BN.9.png, -0, res/CA.9.png, -0, res/Cg.9.png, -0, res/Ci.9.png, -0, res/DG.9.png, -0, res/Dt.9.png, -0, res/Du.9.png, -0, res/ER.9.png, -0, res/Eb.9.png, -0, res/Eq.9.png, -0, res/F6.9.png, -0, res/F8.9.png, -0, res/FM.9.png, -0, res/Fd.9.png, -0, res/Fr.9.png, -0, res/Fx.9.png, -0, res/Fx1.9.png, -0, res/GE.9.png, -0, res/GI.9.png, -0, res/GT.9.png, -0, res/HK.9.png, -0, res/I4.9.png, -0, res/Ik.9.png, -0, res/J6.9.png, -0, res/J8.9.png, -0, res/Kp.9.png, -0, res/L2.9.png, -0, res/LG.9.png, -0, res/LL.9.png, -0, res/La.9.png, -0, res/Lh.9.png, -0, res/Lq.9.png, -0, res/Ml.9.png, -0, res/Ml1.9.png, -0, res/Mo.9.png, -0, res/Mr.9.png, -0, res/NG.9.png, -0, res/NM.9.png, -0, res/NP.9.png, -0, res/Na.9.png, -0, res/Of.9.png, -0, res/Of1.9.png, -0, res/P5.9.png, -0, res/Pi.9.png, -0, res/Q1.9.png, -0, res/QD.9.png, -0, res/Qp.9.png, -0, res/R4.9.png, -0, res/RB.9.png, -0, res/RC.9.png, -0, res/Rg.9.png, -0, res/SO.9.png, -0, res/Sc.9.png, -0, res/T2.9.png, -0, res/TF.9.png, -0, res/To.9.png, -0, res/U0.9.png, -0, res/UI.9.png, -0, res/UQ.9.png, -0, res/UY.9.png, -0, res/Us.9.png, -0, res/V-.9.png, -0, res/V-1.9.png, -0, res/V3.9.png, -0, res/VK.9.png, -0, res/VQ.9.png, -0, res/WM.9.png, -0, res/We.9.png, -0, res/Wy.9.png, -0, res/X3.9.png, -0, res/X7.9.png, -0, res/XK.9.png, -0, res/XT.9.png, -0, res/Xp.9.png, -0, res/Xs.9.png, -0, res/YT.9.png, -0, res/Yq.9.png, -0, res/Z8.9.png, -0, res/ZB.9.png, -0, res/_6.9.png, -0, res/_O.9.png, -0, res/au.9.png, -0, wav, -0, res/bC.9.png, -0, res/bL.9.png, -0, res/bf.9.png, -0, res/bu.9.png, -0, res/cM.9.png, -0, res/ca.9.png, -0, res/ca1.9.png, -0, res/cj.9.png, -0, res/cl.9.png, -0, res/d1.9.png, -0, res/d4.9.png, -0, res/dH.9.png, -0, res/dX.9.png, -0, res/dv.9.png, -0, res/e4.9.png, -0, res/eB.9.png, -0, res/eG.9.png, -0, res/fZ.9.png, -0, res/fv.9.png, -0, res/gG.9.png, -0, res/gL.9.png, -0, res/gV.9.png, -0, res/gz.9.png, -0, res/h0.9.png, -0, res/hA.9.png, -0, res/hi.9.png, -0, res/iI.9.png, -0, res/iM.9.png, -0, res/is.9.png, -0, res/iy.9.png, -0, res/j-.9.png, -0, res/jF.9.png, -0, res/jF1.9.png, -0, res/jI.9.png, -0, res/jK.9.png, -0, res/jO.9.png, -0, res/jh.9.png, -0, res/jn.9.png, -0, res/lN.9.png, -0, res/lQ.9.png, -0, res/ld.9.png, -0, res/m2.9.png, -0, res/m9.9.png, -0, res/mg.9.png, -0, res/n9.9.png, -0, res/nI.9.png, -0, res/oO.9.png, -0, res/oi.9.png, -0, res/pD.9.png, -0, res/pb.9.png, -0, res/ql.9.png, -0, res/qr.9.png, -0, res/qv.9.png, -0, res/rU.9.png, -0, res/rb.9.png, -0, res/sc.9.png, -0, res/st.9.png, -0, res/tM.9.png, -0, res/tj.9.png, -0, res/tr.9.png, -0, res/tw.9.png, -0, res/uB.9.png, -0, res/uH.9.png, -0, res/ub.9.png, -0, res/v6.9.png, -0, res/vy.9.png, -0, res/w1.9.png, -0, res/wK.9.png, -0, res/wL.9.png, -0, res/wc.9.png, -0, res/wg.9.png, -0, res/wi.9.png, -0, res/wi1.9.png, -0, res/wk.9.png, -0, res/x5.9.png, -0, res/xR.9.png, -0, res/xZ.9.png, -0, res/xo.9.png, -0, res/xz.9.png, -0, res/yO.9.png, -0, res/yV.9.png, -0, res/yn.9.png, -0, res/zl.9.png, -0, res/zx.9.png, -0, arsc, -I, framework/1.apk, -S, /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/res, -M, /home/user/apktool/com.chrome.beta_78.0.3904.43-390404305_minAPI19_maxAPI23(armeabi-v7a)(nodpi)_apkmirror.com/AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool d com.chrome.beta_78.0.3904.43.apk`
2. `apktool b com.chrome.beta_78.0.3904.43`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2019-11-17 14:40
Thanks for the report! This is a duplicate of a known issue - #1474

**Closed by iBotPeaches** 2019-11-17 14:40 UTC
