### ISSUE TITLE
[BUG] Apk decompile Error

### ISSUE THREAD

**Issue by jamiekarvans** [iBotPeaches/Apktool#3189] opened 2023-07-21 09:04 UTC
Hi trying to decompile APK using latest version and it works well except for this one gives me this error:
```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (bad compression method)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (bad compression method)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
	... 3 more
Caused by: java.util.zip.ZipException: invalid CEN header (bad compression method)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
```

Can someone help with the issue or decompile the file?
here is the apk file [https://s13.uupload.ir/files/matiex/test66.apk](https://s13.uupload.ir/files/matiex/test66.apk)

**Comment by iBotPeaches** [comment] 2023-07-21 10:28
This is actually caused by a recent Java update that made things quite strict. It was reported here and slated for a hotfix this weekend - https://github.com/iBotPeaches/Apktool/issues/3170

Fixed in this commit: https://github.com/iBotPeaches/Apktool/pull/3178

If you want to workaround it. Set these system properties for your java:
 * `jdk.util.zip.disableZip64ExtraFieldValidation` - true
 * `jdk.nio.zipfs.allowDotZipEntry` - true

**Closed by iBotPeaches** 2023-07-21 10:28 UTC
