### ISSUE TITLE
-d (--debug) does not add debuggable=true to AndroidManifest.xml

### ISSUE THREAD

**Issue by Surendrajat** [iBotPeaches/Apktool#2364] opened 2020-06-14 03:44 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - elementary OS 5.1.5
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```bash
$ java -jar /home/surendra/.apklab/apktool_2.4.1.jar b /home/surendra/test --debug
SmaliDebugging has been removed in 2.1.0 onward. Please see: https://github.com/iBotPeaches/Apktool/issues/1061
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
$
```

### Steps to Reproduce
1. `apktool b /decoded/source/dir/ -d` or `apktool b /decoded/source/dir/ --debug`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`) NA

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? NA
3. Are you using the latest apktool version? YES

**Comment by Surendrajat** [comment] 2020-06-14 03:47
By support, I mean adding `debuggable=true` to AndroidManifest.xml is quite a handy feature and it'll be useful to be kept, which is not working now.

**Comment by Ticklefish** [comment] 2020-06-16 08:42
This option was removed in apktool 2.1.0:

> SmaliDebugging has been removed in 2.1.0 onward. Please see: https://github.com/iBotPeaches/Apktool/issues/1061

The option _is_ still mentioned in the online documentation but, looking at the link mentioned in the error text, it was removed from the code years ago.

**Comment by Surendrajat** [comment] 2020-06-16 08:59
@Ticklefish Yes. I'm aware of that and the original title of my issue was **Support -d (--debug) or Remove it from Apktool Documentation** but the reason I'm saying it doesn't work is that even though smali debugging is gone, adding `debuggable=true` to the Manifest, as in documentation, is quite a useful feature and I'd to have it in Apktool.

**Comment by Ticklefish** [comment] 2020-06-16 12:57
Hmm, I see what you mean. It looks like that part of the documentation is out of date. Something for @iBotPeaches to look at when they get a chance, perhaps.
The option has definitely gone, there's another reference to this here: https://github.com/OWASP/owasp-mstg/pull/1579

Adding that attribute to the XML is very easy though. Have you tried doing it manually?

**Comment by Surendrajat** [comment] 2020-06-16 13:08
@Ticklefish Yes I do it almost always and because it's a frequent task (decode -> make debuggable -> build) I want to have it in apktool. 

I'm also developing https://github.com/Surendrajat/APKLab on top of apktool, It will be nice if I can rely on apktool for this.

**Comment by iBotPeaches** [comment] 2020-06-27 19:20
Yeah so the `-d` parameter wasn't handled the best. It was of course deprecated then removed because SmaliDebugging was useless in comparison to smali-idea. 

However, a few alert users noticed that `-d` also automatically set the debug property during recompilation which was then no longer possible. So during the deprecation process and thus removal, I kept that feature. Then aapt2 came along and since it was deprecated (technically removed at that point) - I just forgot about it.

It seems at this point the command should just be re-labeled to "debug mode" that sets debuggable and double checking if it indeed works on aapt2/aapt1.

**Comment by iBotPeaches** [comment] 2020-11-28 13:09
aapt2
```
➜  debug git:(master) ✗ apktool d app-debug.apk -f
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  debug git:(master) ✗ apktool b app-debug -b --use-aapt2
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  debug git:(master) ✗ aapt d xmltree app-debug/dist/app-debug.apk AndroidManifest.xml
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=1)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
    A: android:compileSdkVersion(0x01010572)=(type 0x10)0x17
    A: android:compileSdkVersionCodename(0x01010573)="6.0-2438415" (Raw: "6.0-2438415")
    A: package="com.ibotpeaches.issue2317" (Raw: "com.ibotpeaches.issue2317")
    A: platformBuildVersionCode=(type 0x10)0x17
    A: platformBuildVersionName="6.0-2438415" (Raw: "6.0-2438415")
    E: uses-sdk (line=0)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x1e
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
    E: application (line=2)
      A: android:theme(0x01010000)=@0x7f0f018e
      A: android:label(0x01010001)=@0x7f0e001b
      A: android:icon(0x01010002)=@0x7f0c0000
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
      A: android:allowBackup(0x01010280)=(type 0x12)0xffffffff
      A: android:supportsRtl(0x010103af)=(type 0x12)0xffffffff
      A: android:extractNativeLibs(0x010104ea)=(type 0x12)0x0
      A: android:roundIcon(0x0101052c)=@0x7f0c0001
      A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
➜  debug git:(master) ✗ 
```
---

aapt1
```
➜  debug git:(master) ✗ apktool b app-debug -b -f
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources...
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  debug git:(master) ✗ aapt d xmltree app-debug/dist/app-debug.apk AndroidManifest.xml
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=1)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
    A: android:compileSdkVersion(0x01010572)=(type 0x10)0x17
    A: android:compileSdkVersionCodename(0x01010573)="6.0-2438415" (Raw: "6.0-2438415")
    A: package="com.ibotpeaches.issue2317" (Raw: "com.ibotpeaches.issue2317")
    A: platformBuildVersionCode=(type 0x10)0x1e
    A: platformBuildVersionName=(type 0x10)0xb
    E: uses-sdk (line=0)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x1e
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
    E: application (line=2)
      A: android:theme(0x01010000)=@0x7f0f018e
      A: android:label(0x01010001)=@0x7f0e001b
      A: android:icon(0x01010002)=@0x7f0c0000
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
      A: android:allowBackup(0x01010280)=(type 0x12)0xffffffff
      A: android:supportsRtl(0x010103af)=(type 0x12)0xffffffff
      A: android:extractNativeLibs(0x010104ea)=(type 0x12)0x0
      A: android:roundIcon(0x0101052c)=@0x7f0c0001
      A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
➜  debug git:(master) ✗ 
```

Closing as resolved.

**Comment by Surendrajat** [comment] 2020-11-28 13:49
Thanks a lot. But I see `-b` in the logs you posted. So is it `-d` or `-b` now? :)

Expecting a new release soon :crossed_fingers:

**Comment by iBotPeaches** [comment] 2020-11-28 14:10
Good catch. Double checking.

built apk from Studio, no debug
```
➜  debug git:(master) ✗ aapt d xmltree app-debug.apk AndroidManifest.xml
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
    A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
    A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
    A: package="com.ibotpeaches.issue2317" (Raw: "com.ibotpeaches.issue2317")
    A: platformBuildVersionCode=(type 0x10)0x1e
    A: platformBuildVersionName=(type 0x10)0xb
    E: uses-sdk (line=7)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x1e
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
    E: application (line=11)
      A: android:theme(0x01010000)=@0x7f0f0193
      A: android:label(0x01010001)=@0x7f0e001b
      A: android:icon(0x01010002)=@0x7f0c0000
      A: android:allowBackup(0x01010280)=(type 0x12)0xffffffff
      A: android:supportsRtl(0x010103af)=(type 0x12)0xffffffff
      A: android:extractNativeLibs(0x010104ea)=(type 0x12)0x0
      A: android:roundIcon(0x0101052c)=@0x7f0c0001
      A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
➜  debug git:(master) ✗ 
```

Decode without any flags.
```
➜  debug git:(master) ✗ apktool d app-debug.apk   
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

Rebuilt with aapt1 + debug

```
➜  debug git:(master) ✗ apktool b app-debug -d
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  debug git:(master) ✗ 
```
```
➜  dist git:(master) ✗ aapt d xmltree app-debug.apk AndroidManifest.xml | grep 'debuggable'
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
➜  dist git:(master) ✗ 
```

Confirmed aapt1. Now force aapt2 rebuild

```
➜  debug git:(master) ✗ apktool b app-debug -d -f --use-aapt2
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Smaling smali folder into classes.dex...
I: Building resources...
I: Using aapt2 - setting 'debuggable' attribute to 'true' in AndroidManifest.xml
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  debug git:(master) ✗ 
```
```
➜  dist git:(master) ✗ aapt d xmltree app-debug.apk AndroidManifest.xml | grep 'debuggable'
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
➜  dist git:(master) ✗ 
```

Will update docs to fix this confusion.

**Comment by iBotPeaches** [comment] 2020-11-28 14:12
Tool warning removed about smali-debugging mode - https://github.com/iBotPeaches/Apktool/commit/590f9c1392d6752048624cd0facc8a9de816f2d5

**Comment by iBotPeaches** [comment] 2020-11-28 14:15
Updated docs. Closing again. All looks okay - https://github.com/iBotPeaches/Apktool/commit/fc6c418f938ba513b693dfd918ea84fa7a9ecbdd

**Closed by iBotPeaches** 2020-11-28 14:15 UTC

**Comment by Surendrajat** [comment] 2020-11-28 14:32
Super. Was waiting to add this feature to https://github.com/Surendrajat/APKLab. Thanks again!
