### ISSUE TITLE
Error "The filename or extension is too long" when rebuild APK

### ISSUE THREAD

**Issue by JustDragon** [iBotPeaches/Apktool#1336] opened 2016-10-01 07:39 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/legacy-of-discord-furiouswings/com.gtarcade.lod/download?from=details

### Steps to Reproduce
1. Decompile APK.
2. Rebuild APK and you have this error.

**Comment by iBotPeaches** [comment] 2016-10-03 12:35
This is a known limitation on Windows. A lookup table to store files in a shorter directory name, but store them differently will have to be made which is a rather large change. Additionally a duplicate of #1272

**Closed by iBotPeaches** 2016-10-03 12:35 UTC

**Comment by JustDragon** [comment] 2016-10-18 01:04
I just notice that in Apktool 2.1.1 version, I don't have this error.

**Comment by Octolus** [comment] 2017-10-21 17:01
Any fix? I am running apktool_2.2.3

**Comment by Octolus** [comment] 2017-10-21 17:04
Caused by: java.io.IOException: Cannot run program "C:\Users\Octolus\AppData\Local\Temp\brut_util_Jar_2835839177993353302.tmp": CreateProcess error=206, Filnavnet eller filtypen er for lang
