### ISSUE TITLE
apktool not disassembling apks built in Android Studio 2.2

### ISSUE THREAD

**Issue by Fewmitz** [iBotPeaches/Apktool#1279] opened 2016-06-23 02:16 UTC
### Information
1. **Apktool Version (`apktool -version`)** -  2.1.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Built through Android Studio.

### Stacktrace/Logcat
Cant find 9patch chunk in file: "drawable-xxhdpi-v4/abc_textfield_default_mtl_alpha.9.Png". Renaming it to *.png
Can't find 9patch chunk in file: "drawable-xxhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png". Renaming it to *.png.

etc. No other errors.

### Steps to Reproduce
Currently using Android Studio 2.2 Preview 1. Compile Sdk Version is 6.0, Build Tools Version is 23.0.1. It seems like no matter what I do, apktool d fails. It doesn't crash, but it starts the decompliation process but has the above errors and at the end produces no smali for my code - there is com/android/tools/fd and com/android/tools/ir and nothing else.

I've also tested with the same IDE and targetting lower API levels (KitKat) and gotten the same results above. Further, I tried a blank install of apktool 2.1.1 with the default framework, and I get an undefined resource error. I used the nores option and was able to disassmble without the PNG warnings - is this an issue with baksmali maybe?

1. `apktool ` d

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

No custom ROM. I've tried both the framework in apktool and the framework from mra58k-factory-52364034. I'm running on a Nexus 5

### APK
If this APK can be freely shared, please upload/attach a link to it.

Doesn't seem to be specific to one APK.

**Comment by iBotPeaches** [comment] 2016-06-23 11:19
I use Android Studio to make all the Test Apks seen here - https://github.com/iBotPeaches/TestApks

I haven't encountered any problem using 9 patches decoding. This could be a problem with your `libpng` handler or something else. Uploading just one of the APKs that are experiencing this would help me identify if the issue is indeed in the decoding or isolated to your system.

**Comment by iBotPeaches** [comment] 2016-08-06 11:17
Gave this a shot to generate an apk that could duplicate this.

```
platformBuildVersionCode="23" platformBuildVersionName="6.0-2704002"
```

Never had a problem with Android Studio 2.2 and any apks. If you can post an APK, I can take a look at this again, but closing this as I can't duplicate.

**Closed by iBotPeaches** 2016-08-06 11:17 UTC
Labels: Waiting for issuer

**Comment by 0E800** [comment] 2017-03-16 18:17
FYI - I experiences same error on this APK.
https://github.com/xiaoqidun/anmpp/blob/master/anmpp_arm_x86.apk

````
apktool.bat d anmpp_arm_x86.apk
I: Using Apktool 2.2.2 on anmpp_arm_x86.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\User\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
````

**Comment by cccaballero** [comment] 2018-01-26 22:25
Same issue here, If I use build without changes, it will generate the apk, but Android says that the package is damaged

**Comment by Kitof** [comment] 2018-04-16 08:50
Same issue here with 2.3.2

**Comment by ChristophHeilmann** [comment] 2018-10-23 12:33
Is it really true? First the files are renamed and then they could not found because they are renamed? This would be very silly.

**Comment by TheHighriser** [comment] 2018-11-08 09:51
Why is this issue closed when it appears even with the newest version?

**Comment by MHaendel** [comment] 2018-11-14 14:11
`java -Xmx128m -jar C:/Users/MH/.apkstudio/vendor/apktool.jar -f d C:/Users/MH/Downloads/Odoo_v2.0.1_apkpure.com.apk -o C:/Users/MH/Downloads/Odoo_v2.0.1_apkpure.com
`

```I: Using Apktool 2.0.2 on Odoo_v2.0.1_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MH\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.```
