### ISSUE TITLE
Import aar to apk 

### ISSUE THREAD

**Issue by beshoo** [iBotPeaches/Apktool#2253] opened 2019-12-13 22:42 UTC
Dear all,
Lets say i have an aar lib and i want to include it in an apk. 
I apktool the apk. Now how can i add this aar file, since usually we imported the aar via android studio. 

I believe there is a way. 

Please advice

**Comment by iBotPeaches** [comment] 2019-12-16 12:08
There is no Apktool automated way. I believe a AAR is just a disguised JAR file with some additions so you could just pull out the classes/libraries/resources you need.

We could use some documentation for this, so if you end up doing it. Could you write up some steps?

Thanks!

---

Since not a bug report, closing.

**Closed by iBotPeaches** 2019-12-16 12:08 UTC

**Comment by beshoo** [comment] 2019-12-23 15:29
@iBotPeaches ,
The tree of the AAR is as following :
Volume serial number is C036-678F
```
│   AndroidManifest.xml
│   classes.jar
│   proguard.txt
│   R.txt
│
├───jni
│   ├───arm64-v8a
│   │       libgojni.so
│   │
│   ├───armeabi-v7a
│   │       libgojni.so
│   │
│   ├───x86
│   │       libgojni.so
│   │
│   └───x86_64
│           libgojni.so
│
└───res
```
The content of the AndroidManifest.xml is 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="go.peerproxyClientSdk.gojni">
<uses-sdk android:minSdkVersion="15"/></manifest>
```
I would like to ask you for help how can we implemnt this AAR.

**Comment by iBotPeaches** [comment] 2019-12-23 15:33
Looks about the same as an APK, minus a dex for a jar.
