### ISSUE TITLE
decode and build fails on  No resource identifier found for attribute

### ISSUE THREAD

**Issue by gilhartman** [iBotPeaches/Apktool#1386] opened 2016-12-21 08:29 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.2.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutLongLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutDisabledMessage' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:8: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:8: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:8: error: No resource identifier found for attribute 'shortcutLongLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:8: error: No resource identifier found for attribute 'shortcutDisabledMessage' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:12: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:12: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:12: error: No resource identifier found for attribute 'shortcutLongLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:12: error: No resource identifier found for attribute 'shortcutDisabledMessage' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:16: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:16: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:16: error: No resource identifier found for attribute 'shortcutLongLabel' in package 'android'
W:
W: /tmp/USAA_com.usaa.mobile.android.usaa/res/xml-v22/shortcuts.xml:16: error: No resource identifier found for attribute 'shortcutDisabledMessage' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/brut_util_Jar_9067794969590588724.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 178, --version-name, 8.19.3, -F, /var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/APKTOOL8106748322297109410.tmp, -0, arsc, -0, txt, -0, json, -0, vbl, -0, arsc, -I, /Users/gil/Library/apktool/framework/1.apk, -S, /tmp/USAA_com.usaa.mobile.android.usaa/res, -M, /tmp/USAA_com.usaa.mobile.android.usaa/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/brut_util_Jar_9067794969590588724.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 178, --version-name, 8.19.3, -F, /var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/APKTOOL8106748322297109410.tmp, -0, arsc, -0, txt, -0, json, -0, vbl, -0, arsc, -I, /Users/gil/Library/apktool/framework/1.apk, -S, /tmp/USAA_com.usaa.mobile.android.usaa/res, -M, /tmp/USAA_com.usaa.mobile.android.usaa/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/brut_util_Jar_9067794969590588724.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 178, --version-name, 8.19.3, -F, /var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/APKTOOL8106748322297109410.tmp, -0, arsc, -0, txt, -0, json, -0, vbl, -0, arsc, -I, /Users/gil/Library/apktool/framework/1.apk, -S, /tmp/USAA_com.usaa.mobile.android.usaa/res, -M, /tmp/USAA_com.usaa.mobile.android.usaa/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
```

### Steps to Reproduce
1. `apktool d USAA_com.usaa.mobile.android.usaa.apk `
2. `apktool b USAA_com.usaa.mobile.android.usaa/ -o output.apk`

* `apktool d --no-res ` and then `apktool b` works.

### Frameworks
Android 7.0 from Nexus 5X

### APK
https://play.google.com/store/apps/details?id=com.usaa.mobile.android.usaa&hl=en
Version 8.19.3, Requires Android 5.0 and up

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Not relevant
3. Are you using the latest apktool version? Yes

**Comment by iNdieboyjeff** [comment] 2016-12-21 15:44
I am also seeing this issue

**Comment by iBotPeaches** [comment] 2016-12-21 16:39
I think this is a duplicate of #1361 , but will wait until I download APK and confirm.

**Comment by iNdieboyjeff** [comment] 2016-12-22 08:27
I just cloned and compiled the repo (to build 2.2.2-58ab04-SNAPSHOT - and everything seemed to work again.

**Comment by iBotPeaches** [comment] 2016-12-22 12:58
Thanks. We were improperly handling certain dynamic attributes. Fixed here - https://github.com/iBotPeaches/Apktool/commit/983e0ad111cd9d4aff27c8e36b5a645b99044cc5

**Closed by iBotPeaches** 2016-12-22 12:58 UTC

**Comment by ljani** [comment] 2017-08-28 18:54
In case anyone else gets here from google, I still had this even after upgrading to v2.2.4. The solution was to run `apktool empty-framework-dir --force`.
