### ISSUE TITLE
Recompiling error with values-v23

### ISSUE THREAD

**Issue by Breathe-of-fate** [iBotPeaches/Apktool#1044] opened 2015-09-22 10:58 UTC
In every app contating values-v23 there is an error with compiling it. Add please API 23. Some apps rebuild if delete 2 lines in slyles, some doesn`t even rebuild.
https://play.google.com/store/apps/details?id=jp.keita.nakamura.timetable# - example of unrebuildable app.

**Comment by iBotPeaches** [comment] 2015-09-22 12:50
Duplicate of #999

**Closed by iBotPeaches** 2015-09-22 12:50 UTC
Labels: duplicate
