### ISSUE TITLE
[BUG] Could not decode attr value, using undecoded value instead

### ISSUE THREAD

**Issue by Nogias9x** [iBotPeaches/Apktool#2595] opened 2021-06-23 14:14 UTC
### Information
1. **Apktool Version**- **`2.5.1-192f9c-SNAPSHOT`** . I used this unreleased version to avoid [this bug](https://github.com/iBotPeaches/Apktool/issues/2249) on the latest official version 2.5.0
2. **Operating System** - Ubuntu 18.04.4 LTS
3. **APK From?** - Playstore

### Stacktrace/Logcat
```
# apktool install-framework oppo-reno5.apk;
I: Framework installed to: /root/.local/share/apktool/framework/1.apk
```
```
# apktool decode --force --output decompiled-app com.sea.foody.nowmerchant.apk
I: Using Apktool 2.5.1-192f9c-SNAPSHOT on com.sea.foody.nowmerchant.apk
I: Loading resource table...
I: Decoding Shared Library (com.sea.foody.nowmerchant.wallet), pkgId: 125
I: Decoding Shared Library (com.sea.foody.nowmerchant.wallet), pkgId: 125
I: Decoding Shared Library (com.sea.foody.nowmerchant.menu), pkgId: 126
I: Decoding Shared Library (com.sea.foody.nowmerchant.wallet), pkgId: 125
I: Decoding Shared Library (com.sea.foody.nowmerchant.menu), pkgId: 126
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7d050000
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
```
```
# apktool build --output rebuilt.apk decompiled-app
I: Using Apktool 2.5.1-192f9c-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: decompiled-apps/now/AndroidManifest.xml:176: error: Error: No resource type specified (at 'resource' with value '@2097479680').
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_74851867342448976142656677198759213131.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 146, --version-name, 2.55.1, --no-version-vectors, -F, /tmp/APKTOOL12825489718288660251.tmp, -e, /tmp/APKTOOL13971392642405725581.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, decompiled-apps/now/res, -M, decompiled-apps/now/AndroidManifest.xml]
```

### Steps to Reproduce
1. Download [target APK file](https://play.google.com/store/apps/details?id=com.sea.foody.nowmerchant&hl=vi&gl=US)
2. [Optional] Install framework from my phone where the target app runs well  `apktool install-framework oppo-reno5.apk;`
3. Decode the target APK file: `apktool decode --force --output decompiled-app com.sea.foody.nowmerchant.apk`
4. See unexpected log `Could not decode attr value...`
5. Rebuild the decoded app without changes: `apktool build --output rebuilt.apk decompiled-app;
 && ./scripts/sign-apk.sh rebuilt.apk;`
 6. See unexpected log `No resource type specified (at 'resource' with value '@2097479680')`

### Frameworks
[oppo-reno5.apk.zip](https://github.com/iBotPeaches/Apktool/files/6702384/oppo-reno5.apk.zip)

### APK
[com.sea.foody.nowmerchant.apk.zip](https://github.com/iBotPeaches/Apktool/files/6702391/com.sea.foody.nowmerchant.apk.zip)

### Questions to ask before submission
- [x] Have you tried `apktool d`, `apktool b` without changing anything? -- Yes
- [x]  If you are trying to install a modified apk, did you resign it? -- Yes
- [ ]  Are you using the latest apktool version? -- Not really. I'm using the latest version which has not released yet

**Comment by iBotPeaches** [comment] 2021-06-26 11:07
Looks like this is happening more and more. This started off being explored/fixed in https://github.com/iBotPeaches/Apktool/issues/2514, where we attempt to properly iterate/load framework ids if the framework is shared/internal, etc.

This application follows that exact pattern.

```
➜  2595 aapt d resources com.sea.foody.nowmerchant_143_apps.evozi.com.apk | grep 'Package Group'
Package Groups (3)
Package Group 0 id=0x7d packageCount=1 name=com.sea.foody.nowmerchant.wallet
Package Group 1 id=0x7e packageCount=1 name=com.sea.foody.nowmerchant.menu
Package Group 2 id=0x7f packageCount=1 name=com.sea.foody.nowmerchant
```

Will merge it into that other ticket and close this one.

Duplicate of #2514

**Closed by iBotPeaches** 2021-06-26 11:07 UTC

**Comment by Nogias9x** [comment] 2021-06-27 12:25
Thank you for the information @iBotPeaches.
Have an amazing week :)

**Comment by zcbxxx1** [comment] 2023-08-11 16:22
> ### 信息
> 
>     1. Apktool 版本 - 2.5.1-192f9c-SNAPSHOT。我在最新的正式版本2.5.0上使用了这个未发布的版本来避免这个bug
> 
>     2. 操作系统 - Ubuntu 18.04.4 LTS
> 
>     3. APK 来自？ - 应用商店
> 
> 
> ### 堆栈跟踪/Logcat
> 
> ```
> # apktool install-framework oppo-reno5.apk;
> I: Framework installed to: /root/.local/share/apktool/framework/1.apk
> ```
> 
> ```
> # apktool decode --force --output decompiled-app com.sea.foody.nowmerchant.apk
> I: Using Apktool 2.5.1-192f9c-SNAPSHOT on com.sea.foody.nowmerchant.apk
> I: Loading resource table...
> I: Decoding Shared Library (com.sea.foody.nowmerchant.wallet), pkgId: 125
> I: Decoding Shared Library (com.sea.foody.nowmerchant.wallet), pkgId: 125
> I: Decoding Shared Library (com.sea.foody.nowmerchant.menu), pkgId: 126
> I: Decoding Shared Library (com.sea.foody.nowmerchant.wallet), pkgId: 125
> I: Decoding Shared Library (com.sea.foody.nowmerchant.menu), pkgId: 126
> I: Decoding AndroidManifest.xml with resources...
> I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
> W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7d050000
> I: Regular manifest package...
> I: Decoding file-resources...
> I: Decoding values */* XMLs...
> I: Baksmaling classes.dex...
> I: Baksmaling classes2.dex...
> I: Baksmaling classes3.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> I: Copying META-INF/services directory
> ```
> 
> ```
> # apktool build --output rebuilt.apk decompiled-app
> I: Using Apktool 2.5.1-192f9c-SNAPSHOT
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes3 folder into classes3.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes2 folder into classes2.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> W: decompiled-apps/now/AndroidManifest.xml:176: error: Error: No resource type specified (at 'resource' with value '@2097479680').
> W: 
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_74851867342448976142656677198759213131.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 29, --version-code, 146, --version-name, 2.55.1, --no-version-vectors, -F, /tmp/APKTOOL12825489718288660251.tmp, -e, /tmp/APKTOOL13971392642405725581.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, decompiled-apps/now/res, -M, decompiled-apps/now/AndroidManifest.xml]
> ```
> 
> ### 重现步骤
> 
>     1. 下载目标APK文件
> 
>     2. [可选] 从我的手机安装框架，目标应用程序运行良好 apktool install-framework oppo-reno5.apk；
> 
>     3. 解码目标APK文件：apktooldecode --force --output decompiled-app com.sea.foody.nowmerchant.apk
> 
>     4. 查看意外日志无法解码 attr 值...
> 
>     5. 重新构建解码后的应用程序而不进行任何更改： apktool build --output rebuilt.apk decompiled-app； && ./scripts/sign-apk.sh rebuilt.apk;
> 
>     6. 查看意外日志未指定资源类型（在“资源”处，值为“@2097479680”）
> 
> 
> ### 构架
> 
> [oppo-reno5.apk.zip](https://github.com/iBotPeaches/Apktool/files/6702384/oppo-reno5.apk.zip)
> ### 应用程序
> 
> [com.sea.foody.nowmerchant.apk.zip](https://github.com/iBotPeaches/Apktool/files/6702391/com.sea.foody.nowmerchant.apk.zip)
> ### 提交前要问的问题
> 
>     * [x] 您是否尝试过 apktool d、apktool b 而不进行任何更改？ -  是的
> 
>     * [x] 如果您尝试安装修改过的 apk，您是否放弃了它？ -  是的
> 
>     * [ ] 您使用的是最新的 apktool 版本吗？ -  并不真地。我正在使用尚未发布的最新版本

if your system is based on the debin，please try to "apt install android-framework-res"
