### ISSUE TITLE
Not install vivo-res.apk correct.

### ISSUE THREAD

**Issue by phdanhlc** [iBotPeaches/Apktool#1256] opened 2016-05-25 02:07 UTC
### Information
1. **Apktool Version (`apktool 2.1.1`)** -
2. **Operating System (windows)** -
3. **APK From? (vivo x5max+ 4.4.4 official rom)** -

### Stacktrace/Logcat
C:\Users\Victim\Desktop\apktool 2.1.1>apktool b Settings
I: Using Apktool 2.1.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: W/ResourceType( 6356): ResTable_typeSpec entry count inconsistent: given 1, previously 1155
W: W/ResourceType( 6356): For resource 0x010100f5, entry index(245) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010100f4, entry index(244) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010103b4, entry index(948) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x01010034, entry index(52) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010100c4, entry index(196) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010100d9, entry index(217) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010103b3, entry index(947) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010100d7, entry index(215) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x01010095, entry index(149) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x01010097, entry index(151) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x01010059, entry index(89) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x01010056, entry index(86) is beyond type entryCount(1)
W: W/ResourceType( 6356): For resource 0x010100d4, entry index(212) is beyond type entryCount(1)
```

Now i attached some framework and settings 
http://www.mediafire.com/download/zi1f3kwu07sweje/Framework_and_settings_apk.rar
My step:
1. install framework-res.apk and mediatek-res.apk ok
2. install vivo-res.apk 
I: Arsc file contains multiple packages. Using package vivo as default.
I: Framework installed to: C:\Users\Victim\apktool\framework\3.apk
3.Decompile Settings.apk ok 
recompile build apk ok but apk forceclose.
And now my question is how to install vivo-res.apk correct resource package id

**Comment by iBotPeaches** [comment] 2016-05-26 16:19
These warnings are from aapt and a duplicate of #857

**Closed by iBotPeaches** 2016-05-26 16:19 UTC
Labels: Duplicate
