### ISSUE TITLE
Can't rebuild *simple* app :(

### ISSUE THREAD

**Issue by EugW** [iBotPeaches/Apktool#2200] opened 2019-10-22 14:35 UTC
### Information
1. Apktool v2.4.0
2. Windows
3. ROM, Havoc OS, framework-res.apk

### Stacktrace/Logcat

```
Extract:
java -jar apktool_2.4.0.jar d framework-res.apk
I: Using Apktool 2.4.0 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Rebuild:
D:\Evgeny\Documents\DEV\sysuimod>java -jar apktool_2.4.0.jar b framework-res
I: Using Apktool 2.4.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [C:\Users\Evgeny\AppData\Local\Temp\brut_util_Jar_4940370291710403871.tmp, p, --forced-package-id, 1, --min-sdk-version, 28, --target-sdk-version, 28, --version-code, 28, --version-name, 9, --no-version-vectors, -F, C:\Users\Evgeny\AppData\Local\Temp\APKTOOL8918182686986354789.tmp, -x, -0, arsc, -0, png, -0, res/drawable-hdpi-v4/ab_bottom_solid_dark_holo.9.png, -0, res/drawable-hdpi-v4/ab_bottom_solid_inverse_holo.9.png, -0, res/drawable-hdpi-v4/ab_bottom_solid_light_holo.9.png, -0, res/drawable-hdpi-v4/ab_bottom_transparent_dark_holo.9.png, -0, res/drawable-hdpi-...verylongtext..., -0, ogg, -0, arsc, -S, D:\Evgeny\Documents\DEV\sysuimod\framework-res\res, -M, D:\Evgeny\Documents\DEV\sysuimod\framework-res\AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool d  framework-res.apk`
2. `apktool b  framework-res`

### Frameworks
There is only one apk in folder /system/framework and it is framework-res.apk

### APK
https://drive.google.com/file/d/1tDl-5xa1JJxFzn_6i5II9X45D5fd0qZ4/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? -
3. Are you using the latest apktool version? Yes

**Comment by Ticklefish** [comment] 2019-10-31 11:21
This is the same issue as 2104: [https://github.com/iBotPeaches/Apktool/issues/2104](url)

**Comment by azamet90** [comment] 2019-12-29 07:11
> This is the same issue as 2104: [https://github.com/iBotPeaches/Apktool/issues/2104](url)

![image](https://user-images.githubusercontent.com/44042178/71553613-8ada3680-2a23-11ea-9000-4f5cd7ae8c7c.png)

**Comment by Ticklefish** [comment] 2019-12-29 12:45
Weird. You're right - if you click on the link it doesn't work. But if you type the URL in manually, it does. Don't ask me why...

**Comment by azamet90** [comment] 2019-12-29 13:09
> Weird. You're right - if you click on the link it doesn't work. But if you type the URL in manually, it does. Don't ask me why...

no the problem is using the www is doing it :D but anyways the apktool is not working :/ many people have this problem but no one is answering for workaround... looks like there is no fix for it and must to wait for update and who knows when it will be updated :(

**Comment by Ticklefish** [comment] 2019-12-29 14:08
I've been able to rebuild this file with apktool 2.4.1.

First I decompiled it:

> (java -Xmx1024m -jar user_files\APKTOOL\apktool_2.4.1.jar d --force-manifest     --only-main-classes  -f -p _WorkArea2\Frameworks _WorkArea2\_in\framework-res.apk -o _WorkArea2\_working\framework-res.apk) 
> 
> I: Using Apktool 2.4.1 on framework-res.apk
> I: Loading resource table...
> I: Decoding AndroidManifest.xml with resources...
> I: Regular manifest package...
> I: Decoding file-resources...
> I: Decoding values */* XMLs...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> 

Then recompiled it with aapt:

> (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all  -p _WorkArea2\Frameworks _WorkArea2\_working\framework-res.apk -o _WorkArea2\_out\framework-res.apk) 
> 
> -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> I: Using Apktool 2.4.1
> W: Could not find sources
> I: Building resources...
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1185: error: Resource entry Theme.Holo already has bag item textEditSuggestionItemLayout.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1184: Originally defined here.
> W: 
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1262: error: Resource entry Theme.Holo already has bag item preferenceFrameLayoutStyle.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1261: Originally defined here.
> W: 
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1271: error: Resource entry Theme.Holo already has bag item textEditSuggestionContainerLayout.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1270: Originally defined here.
> W: 
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1273: error: Resource entry Theme.Holo already has bag item textEditSuggestionHighlightStyle.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\styles.xml:1272: Originally defined here.
> W: 
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\LCHESN~1\AppData\Local\Temp\brut_util_Jar_1686865656043286175.tmp, p, --forced-package-id, 1, --min-sdk-version, 28, --target-sdk-version, 28, --version-code, 28, --version-name, 9, --no-version-vectors, -F, C:\Users\LCHESN~1\AppData\Local\Temp\APKTOOL8257541681821189656.tmp, -x, -e, C:\Users\LCHESN~1\AppData\Local\Temp\APKTOOL3529818289363922768.tmp, -0, arsc, -S, C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res, -M, C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\AndroidManifest.xml]
> 

This is saying there are some duplicate lines in "**styles.xml**". If I delete those and try recompiling again, it works.

> (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all  -p _WorkArea2\Frameworks _WorkArea2\_working\framework-res.apk -o _WorkArea2\_out\framework-res.apk) 
> 
> -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> I: Using Apktool 2.4.1
> W: Could not find sources
> I: Building resources...
> W: warning: string 'wfcSpnFormat' has no default translation.
> I: Copy original files...
> I: Copy AndroidManifest.xml...
> I: Copy META-INF...
> I: Building apk file...
> I: Copying unknown files/dir...
> I: Built apk...

This translation warning isn't an issue worth worrying about.

However, if I recompile with aapt2, I get something slightly different:

> (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all --use-aapt2 -p _WorkArea2\Frameworks _WorkArea2\_working\framework-res.apk -o _WorkArea2\_out\framework-res.apk) 
> 
> -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> I: Using Apktool 2.4.1
> W: Could not find sources
> I: Building resources...
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2522: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2523: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2524: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2525: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2526: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2527: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2528: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2529: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2530: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2531: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2532: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2533: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2534: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2535: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2536: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2537: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2538: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2539: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2540: error: invalid value for type 'attr'. Expected a reference.
> W: C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res\values\attrs.xml:2541: error: invalid value for type 'attr'. Expected a reference.
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\LCHESN~1\AppData\Local\Temp\brut_util_Jar_2820376893730624465.tmp, compile, --dir, C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\res, --legacy, -o, C:\TickleMyAndroid\_WorkArea2\_working\framework-res.apk\build\resources.zip]
> 

There are some lines in "**attrs.xml**" that are causing trouble. Those lines are these:

>     <item type="attr" name="APKTOOL_DUMMY_267">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_3a8">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_3c3">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_40e">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_40f">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_410">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_411">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_412">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_413">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_414">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_415">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_416">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_417">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_418">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_419">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_41a">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_41b">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_41c">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_41d">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_41e">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_41f">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_420">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_421">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_422">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_423">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_424">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_425">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_426">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_427">false</item>
>     <item type="attr" name="APKTOOL_DUMMY_428">false</item>
> 

This can be fixed, but then apktool gives different errors. So it's easier just to use aapt instead. 

It's not impossible that these dummy values might cause some trouble with the recompiled APK. Or they might not cause any trouble at all and the app will work just fine. The only way to tell is to try it and see what happens.
The dummy values are caused by something in the original APK that hasn't been put together in a standard way. You'd need to speak to the dev to sort that out, it's nothing something apktool can deal with.

Hope this helps!

**Comment by azamet90** [comment] 2019-12-29 14:23
> I've been able to rebuild this file with apktool 2.4.1.
> 
> First I decompiled it:
> 
> > (java -Xmx1024m -jar user_files\APKTOOL\apktool_2.4.1.jar d --force-manifest     --only-main-classes  -f -p _WorkArea2\Frameworks _WorkArea2_in\framework-res.apk -o _WorkArea2_working\framework-res.apk)
> > I: Using Apktool 2.4.1 on framework-res.apk
> > I: Loading resource table...
> > I: Decoding AndroidManifest.xml with resources...
> > I: Regular manifest package...
> > I: Decoding file-resources...
> > I: Decoding values _/_ XMLs...
> > I: Copying assets and libs...
> > I: Copying unknown files...
> > I: Copying original files...
> 
> Then recompiled it with aapt:
> 
> > (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all  -p _WorkArea2\Frameworks _WorkArea2_working\framework-res.apk -o _WorkArea2_out\framework-res.apk)
> > -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> > I: Using Apktool 2.4.1
> > W: Could not find sources
> > I: Building resources...
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1185: error: Resource entry Theme.Holo already has bag item textEditSuggestionItemLayout.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1184: Originally defined here.
> > W:
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1262: error: Resource entry Theme.Holo already has bag item preferenceFrameLayoutStyle.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1261: Originally defined here.
> > W:
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1271: error: Resource entry Theme.Holo already has bag item textEditSuggestionContainerLayout.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1270: Originally defined here.
> > W:
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1273: error: Resource entry Theme.Holo already has bag item textEditSuggestionHighlightStyle.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\styles.xml:1272: Originally defined here.
> > W:
> > brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\LCHESN~1\AppData\Local\Temp\brut_util_Jar_1686865656043286175.tmp, p, --forced-package-id, 1, --min-sdk-version, 28, --target-sdk-version, 28, --version-code, 28, --version-name, 9, --no-version-vectors, -F, C:\Users\Me\AppData\Local\Temp\APKTOOL8257541681821189656.tmp, -x, -e, C:\Users\Me\AppData\Local\Temp\APKTOOL3529818289363922768.tmp, -0, arsc, -S, C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res, -M, C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\AndroidManifest.xml]
> 
> This is saying there are some duplicate lines in "**styles.xml**". If I delete those and try recompiling again, it works.
> 
> > (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all  -p _WorkArea2\Frameworks _WorkArea2_working\framework-res.apk -o _WorkArea2_out\framework-res.apk)
> > -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> > I: Using Apktool 2.4.1
> > W: Could not find sources
> > I: Building resources...
> > W: warning: string 'wfcSpnFormat' has no default translation.
> > I: Copy original files...
> > I: Copy AndroidManifest.xml...
> > I: Copy META-INF...
> > I: Building apk file...
> > I: Copying unknown files/dir...
> > I: Built apk...
> 
> This translation warning isn't an issue worth worrying about.
> 
> However, if I recompile with aapt2, I get something slightly different:
> 
> > (java -jar user_files\APKTOOL\apktool_2.4.1.jar b --copy-original  --force-all --use-aapt2 -p _WorkArea2\Frameworks _WorkArea2_working\framework-res.apk -o _WorkArea2_out\framework-res.apk)
> > -c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
> > I: Using Apktool 2.4.1
> > W: Could not find sources
> > I: Building resources...
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2522: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2523: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2524: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2525: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2526: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2527: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2528: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2529: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2530: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2531: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2532: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2533: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2534: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2535: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2536: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2537: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2538: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2539: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2540: error: invalid value for type 'attr'. Expected a reference.
> > W: C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res\values\attrs.xml:2541: error: invalid value for type 'attr'. Expected a reference.
> > brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Me\AppData\Local\Temp\brut_util_Jar_2820376893730624465.tmp, compile, --dir, C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\res, --legacy, -o, C:\TickleMyAndroid_WorkArea2_working\framework-res.apk\build\resources.zip]
> 
> There are some lines in "**attrs.xml**" that are causing trouble. Those lines are these:
> 
> > ```
> > <item type="attr" name="APKTOOL_DUMMY_267">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_3a8">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_3c3">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_40e">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_40f">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_410">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_411">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_412">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_413">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_414">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_415">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_416">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_417">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_418">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_419">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_41a">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_41b">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_41c">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_41d">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_41e">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_41f">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_420">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_421">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_422">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_423">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_424">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_425">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_426">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_427">false</item>
> > <item type="attr" name="APKTOOL_DUMMY_428">false</item>
> > ```
> 
> This can be fixed, but then apktool gives different errors. So it's easier just to use aapt instead.
> 
> It's not impossible that these dummy values might cause some trouble with the recompiled APK. Or they might not cause any trouble at all and the app will work just fine. The only way to tell is to try it and see what happens.
> The dummy values are caused by something in the original APK that hasn't been put together in a standard way. You'd need to speak to the dev to sort that out, it's nothing something apktool can deal with.
> 
> Hope this helps!

yeah but your error is different then my https://github.com/iBotPeaches/Apktool/issues/2265
and thank you for answering

**Comment by Ticklefish** [comment] 2019-12-29 14:44
> yeah but your error is different then my #2265
> and thank you for answering

My reply was for this issue. The one you've linked to is a different issue entirely.

**Comment by iBotPeaches** [comment] 2020-11-28 21:57
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/2104

v2.5.0 will have a new mechanism for dummy resources so may be worth a double check there when released.

**Closed by iBotPeaches** 2020-11-28 21:57 UTC
