### ISSUE TITLE
Can not decode shared library apk.

### ISSUE THREAD

**Issue by duanqz** [iBotPeaches/Apktool#941] opened 2015-05-08 07:12 UTC
I am confronted by a shared library apk when decoding.

this apk was uploaded:
https://github.com/duanqz/holder/blob/master/sharedlibrary-could-not-decode.apk

the error report:
I: Using Apktool 2.0.0 on sharedlibrary-could-not-decode.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/duanqizhi/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=internal, name=layout_maxHeight, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=internal, name=layout_minHeight, value=0x000e00f1
Exception in thread "main" java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
	at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)

Enviorment:
APKTOOL 2.0.0
JDK 1.7

**Comment by iBotPeaches** [comment] 2015-05-08 18:13
Duplicate of #913

**Closed by iBotPeaches** 2015-05-08 18:13 UTC
