### ISSUE TITLE
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec

### ISSUE THREAD

**Issue by dravyanataraj** [iBotPeaches/Apktool#1188] opened 2016-03-08 00:23 UTC
The latest version of apktool is throwing below exception when trying to decompile an apk. I ahve seen this with few other apks as well. Looks like apktool did not decompile a particular resource?.
```
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010105a7
at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:46)
at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:47)
at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:105)
at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
at brut.apktool.Main.cmdDecode(Main.java:165)
at brut.apktool.Main.main(Main.java:81) 
```

**Comment by dravyanataraj** [comment] 2016-03-08 00:59
Deleting apktool/framework/1.apk did not work as well

**Comment by dravyanataraj** [comment] 2016-03-08 21:43
Hi iBotPeaches
Any update on this bug ?

**Comment by iBotPeaches** [comment] 2016-03-08 21:45
This bug isn't even a day old yet. Please upload an APK so I can investigate further. Though my gut is thats a duplicate of another bug.

**Comment by dravyanataraj** [comment] 2016-03-08 21:47
Thank you for responding. Take you time.
I am not allowed to share the apk file. This is our customer apk file.

**Comment by iBotPeaches** [comment] 2016-03-08 21:54
Sorry bout that. Hard for me to work on APKs by stack trace due the nature of the tool. Unlike code dumps, this error points at a pkgId of 1 (framework) resource being unavailable. This means framework. I can't investigate further to due to lack of APK.

If the packageId was meant to be 127 (0x7f) then thats a duplicate bug of #1157

**Closed by iBotPeaches** 2016-03-08 21:54 UTC
Labels: Waiting for issuer

**Comment by kalharbi** [comment] 2016-03-12 02:01
I saw this exception with a few apks. It went away when I pulled a new framework-res from my device at `/system/framework/framework-res.apk` and ran `apktool if framework-res.apk`.

**Comment by balaji7590** [comment] 2018-05-23 01:54
i got the same issue so Deleted apktool/framework/1.apk and copied framework-res.apk from virtual device 7.1.1 OS and end with this error
<script>
Exception in thread "main" brut.androlib.AndrolibException: Invalid value type: 0
	at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:62)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:211)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:199)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:169)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:125)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:657)
	at brut.androlib.Androlib.installFramework(Androlib.java:649)
	at brut.apktool.Main.cmdInstallFramework(Main.java:256)
	at brut.apktool.Main.main(Main.java:92)
</script>

I'm trying to test diva-beta.apk and apktool version 2.0.0rc2

can you plz let me know whether i need to make changes or issue with the apk or how to find whether issue with apk in future.
