### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by adamwolf** [iBotPeaches/Apktool#2338] opened 2020-04-24 16:50 UTC
I can't build this APK, whether I use --use-aapt2 or not, and whether I use master from today, or 2.4.1

### Information
1. Apktool 2.4.2-83a459-SNAPSHOT and Apktool 2.4.1
2. macOS

### Stacktrace/Logcat

```
$ java -jar new-apktool/Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar d base.apk; java -jar new-apktool/Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar b base rebuilt.apk
I: Using Apktool 2.4.2-83a459-SNAPSHOT on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/wolf/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
I: Using Apktool 2.4.2-83a459-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /Users/wolf/tmp/apktool-test/base/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/brut_util_Jar_26933508156427351381977336496729699262.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 382, --version-name, 23.0, --no-version-vectors, -F, /var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/APKTOOL18236448905366146164.tmp, -e, /var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/APKTOOL11992796537118899297.tmp, -0, arsc, -I, /Users/wolf/Library/apktool/framework/1.apk, -S, /Users/wolf/tmp/apktool-test/base/res, -M, /Users/wolf/tmp/apktool-test/base/AndroidManifest.xml]

$ java -jar new-apktool/Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar b base rebuilt.apk --use-aapt2
I: Using Apktool 2.4.2-83a459-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3180: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3181: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1'. Invalid character '$avd_hide_password__1'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3182: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2'. Invalid character '$avd_hide_password__2'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3183: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0'. Invalid character '$avd_show_password__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3184: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1'. Invalid character '$avd_show_password__1'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3185: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2'. Invalid character '$avd_show_password__2'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3186: error: resource 'drawable/$dark_stars_bg__0' has invalid entry name '$dark_stars_bg__0'. Invalid character '$dark_stars_bg__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3187: error: resource 'drawable/$ic_animated_bird_wings__0' has invalid entry name '$ic_animated_bird_wings__0'. Invalid character '$ic_animated_bird_wings__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3188: error: resource 'drawable/$ic_animated_bird_wings__1' has invalid entry name '$ic_animated_bird_wings__1'. Invalid character '$ic_animated_bird_wings__1'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3189: error: resource 'drawable/$ic_animated_bird_wings__10' has invalid entry name '$ic_animated_bird_wings__10'. Invalid character '$ic_animated_bird_wings__10'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3190: error: resource 'drawable/$ic_animated_bird_wings__11' has invalid entry name '$ic_animated_bird_wings__11'. Invalid character '$ic_animated_bird_wings__11'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3191: error: resource 'drawable/$ic_animated_bird_wings__12' has invalid entry name '$ic_animated_bird_wings__12'. Invalid character '$ic_animated_bird_wings__12'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3192: error: resource 'drawable/$ic_animated_bird_wings__13' has invalid entry name '$ic_animated_bird_wings__13'. Invalid character '$ic_animated_bird_wings__13'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3193: error: resource 'drawable/$ic_animated_bird_wings__14' has invalid entry name '$ic_animated_bird_wings__14'. Invalid character '$ic_animated_bird_wings__14'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3194: error: resource 'drawable/$ic_animated_bird_wings__15' has invalid entry name '$ic_animated_bird_wings__15'. Invalid character '$ic_animated_bird_wings__15'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3195: error: resource 'drawable/$ic_animated_bird_wings__16' has invalid entry name '$ic_animated_bird_wings__16'. Invalid character '$ic_animated_bird_wings__16'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3196: error: resource 'drawable/$ic_animated_bird_wings__17' has invalid entry name '$ic_animated_bird_wings__17'. Invalid character '$ic_animated_bird_wings__17'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3197: error: resource 'drawable/$ic_animated_bird_wings__18' has invalid entry name '$ic_animated_bird_wings__18'. Invalid character '$ic_animated_bird_wings__18'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3198: error: resource 'drawable/$ic_animated_bird_wings__19' has invalid entry name '$ic_animated_bird_wings__19'. Invalid character '$ic_animated_bird_wings__19'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3199: error: resource 'drawable/$ic_animated_bird_wings__2' has invalid entry name '$ic_animated_bird_wings__2'. Invalid character '$ic_animated_bird_wings__2'.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/brut_util_Jar_62025123148481482108268821509105909890.tmp, compile, --dir, /Users/wolf/tmp/apktool-test/base/res, --legacy, -o, /Users/wolf/tmp/apktool-test/base/build/resources.zip]

$ java -jar new-apktool/Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar b base rebuilt.apk --use-aapt2 --no-res
I: Using Apktool 2.4.2-83a459-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3180: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3181: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1'. Invalid character '$avd_hide_password__1'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3182: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2'. Invalid character '$avd_hide_password__2'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3183: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0'. Invalid character '$avd_show_password__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3184: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1'. Invalid character '$avd_show_password__1'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3185: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2'. Invalid character '$avd_show_password__2'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3186: error: resource 'drawable/$dark_stars_bg__0' has invalid entry name '$dark_stars_bg__0'. Invalid character '$dark_stars_bg__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3187: error: resource 'drawable/$ic_animated_bird_wings__0' has invalid entry name '$ic_animated_bird_wings__0'. Invalid character '$ic_animated_bird_wings__0'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3188: error: resource 'drawable/$ic_animated_bird_wings__1' has invalid entry name '$ic_animated_bird_wings__1'. Invalid character '$ic_animated_bird_wings__1'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3189: error: resource 'drawable/$ic_animated_bird_wings__10' has invalid entry name '$ic_animated_bird_wings__10'. Invalid character '$ic_animated_bird_wings__10'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3190: error: resource 'drawable/$ic_animated_bird_wings__11' has invalid entry name '$ic_animated_bird_wings__11'. Invalid character '$ic_animated_bird_wings__11'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3191: error: resource 'drawable/$ic_animated_bird_wings__12' has invalid entry name '$ic_animated_bird_wings__12'. Invalid character '$ic_animated_bird_wings__12'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3192: error: resource 'drawable/$ic_animated_bird_wings__13' has invalid entry name '$ic_animated_bird_wings__13'. Invalid character '$ic_animated_bird_wings__13'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3193: error: resource 'drawable/$ic_animated_bird_wings__14' has invalid entry name '$ic_animated_bird_wings__14'. Invalid character '$ic_animated_bird_wings__14'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3194: error: resource 'drawable/$ic_animated_bird_wings__15' has invalid entry name '$ic_animated_bird_wings__15'. Invalid character '$ic_animated_bird_wings__15'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3195: error: resource 'drawable/$ic_animated_bird_wings__16' has invalid entry name '$ic_animated_bird_wings__16'. Invalid character '$ic_animated_bird_wings__16'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3196: error: resource 'drawable/$ic_animated_bird_wings__17' has invalid entry name '$ic_animated_bird_wings__17'. Invalid character '$ic_animated_bird_wings__17'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3197: error: resource 'drawable/$ic_animated_bird_wings__18' has invalid entry name '$ic_animated_bird_wings__18'. Invalid character '$ic_animated_bird_wings__18'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3198: error: resource 'drawable/$ic_animated_bird_wings__19' has invalid entry name '$ic_animated_bird_wings__19'. Invalid character '$ic_animated_bird_wings__19'.
W: /Users/wolf/tmp/apktool-test/base/res/values/public.xml:3199: error: resource 'drawable/$ic_animated_bird_wings__2' has invalid entry name '$ic_animated_bird_wings__2'. Invalid character '$ic_animated_bird_wings__2'.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/brut_util_Jar_82195610175410317437128065524456760541.tmp, compile, --dir, /Users/wolf/tmp/apktool-test/base/res, --legacy, -o, /Users/wolf/tmp/apktool-test/base/build/resources.zip]

$ java -jar new-apktool/Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar b base rebuilt.apk --no-res
I: Using Apktool 2.4.2-83a459-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /Users/wolf/tmp/apktool-test/base/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/brut_util_Jar_128573260287314052571049845586554765848.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 28, --version-code, 382, --version-name, 23.0, --no-version-vectors, -F, /var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/APKTOOL1429971256974441029.tmp, -e, /var/folders/1v/jr2yn0f54dvcnyscspw2h5w80000gn/T/APKTOOL10358387702630012699.tmp, -0, arsc, -I, /Users/wolf/Library/apktool/framework/1.apk, -S, /Users/wolf/tmp/apktool-test/base/res, -M, /Users/wolf/tmp/apktool-test/base/AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool d base.apk; apktool b base rebuilt.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? both 2.4.1 and master from this morning

**Comment by KaustubhPatange** [comment] 2020-04-26 09:11
Duplicate issue #1811 

Fix:
`apktool b base.apk --use-aapt2`

**Comment by adamwolf** [comment] 2020-04-26 18:19
I tried --use-aapt2 and already pasted the output.

**Comment by chanhduc** [comment] 2020-04-27 10:26
Hi, if you don't have to modify apk's resource, let's try "-r" option when you run apktool to decode. Let's see if it helps.

**Comment by adamwolf** [comment] 2020-04-27 13:13
It does work if I use --no-res when I decode, and then use --use-aapt2 when I encode.  Any tips on getting to decode resources and then reencode them?

**Comment by alicanuzun** [comment] 2020-06-23 20:14
Hi, same issue here. When I don't use --use-aapt2 to build, it gives navigation error, when using --use-aapt2 different errors occurs. Any fix for this?

**Comment by iBotPeaches** [comment] 2020-09-13 16:51
Use aapt2. This is not a bug.

**Closed by iBotPeaches** 2020-09-13 16:51 UTC
