### ISSUE TITLE
Could not decode arsc file

### ISSUE THREAD

**Issue by srasthofer** [iBotPeaches/Apktool#964] opened 2015-05-29 15:18 UTC
During the decompilation of a malicious apk, I get the following exception:

```
java -jar apktool_2.0.0rc5.jar d -o /OUTPUT/ /HippoSMS/5c70988fc9751f283b2f2b5733f9e7f2a54afa69.apk 
I: Using Apktool 2.0.0 on 5c70988fc9751f283b2f2b5733f9e7f2a54afa69.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000002
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```
Here would be the malicious apk: https://drive.google.com/file/d/0B7mw1J0o156uMS1nNFNiSnY5LUU/view?usp=sharing
PW: infected

Thanks in advance.

**Comment by iBotPeaches** [comment] 2015-06-03 12:00
I duplicate. Must be some good trickery to break apktool that early in the decode.

**Comment by gizmaniac** [comment] 2015-06-16 19:48
This also breaks with the latest version of K-9 Mail in the Play Store (5.006), which one would hope is not malicious.

**Comment by minsko** [comment] 2015-06-19 15:01
The same issue occurs when attempting to decode any apk created with SDK Build Tools  v23.0.0-rc2. Here is a simple "Hello World" created with 22.0.1 and 23.0.0rc2. https://drive.google.com/file/d/0B5BNATXQ2jdIbWJGWjNRYVZMR28/view?usp=sharing

**Comment by iBotPeaches** [comment] 2015-06-22 12:21
Thanks. I duplicate with the simplest of applications using the new Build Tools. I will build the exact same application using different build tools and figure out what is changing and why.

**Comment by minsko** [comment] 2015-06-22 12:31
FYI, RC4 does not have this issue with apk's created by the new tools.

**Comment by iBotPeaches** [comment] 2015-07-01 13:30
Hmmm.

I tried

```
    buildToolsVersion "23.0.0-rc2"
and
    buildToolsVersion "22.0.1"
```

The built apks could be decompiled without error. Now the original APK still breaks, but not having much luck building a test apk to duplicate this issue.

**Comment by minsko** [comment] 2015-07-01 14:28
I just built from source (commit d5f3b3fd5aad4c54f5e3e74d349f509176a87cbd) and could NOT reproduce the issue (regarding the build tools) anymore.  I had previously reproduced it with the 2.0.0 release and had assumed it was related to the original issue listed concerning the Malware.apk (which still fails with this latest build.) Sorry for any confusion.  Thanks.

**Comment by iBotPeaches** [comment] 2015-12-15 12:44
I believe this is fixed now as of - https://github.com/iBotPeaches/Apktool/commit/eabb7d819b9a13f256153a174b8dd05e21c619f1

It had the same problem as #1031 if anyone is curious of the cause.

**Closed by iBotPeaches** 2015-12-15 12:44 UTC
Labels: Accepted, bug
