### ISSUE TITLE
org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method LX/1p3;->B(Landroid/content/Context;Ljava/lang/String;)Landroid/content/Intent;

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [iBotPeaches/Apktool#1834] opened 2018-07-03 05:38 UTC
### Information
1. **Apktool Version (`apktool -version`)** -  2.3.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
I: Using Apktool 2.3.3
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method LX/1p3;->B(Landroid/content/Context;Ljava/lang/String;)Landroid/content/Intent;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:825)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:268)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:417)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:363)
	at brut.androlib.Androlib.build(Androlib.java:301)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 88144
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1120)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:821)
```

### Steps to Reproduce
1. ` apktool d Facebook_v178.apk`
2. ` apktool b Facebook_v178.apk`

### APK
[Facebook_v178.apk.zip](https://github.com/iBotPeaches/Apktool/files/2157754/Facebook_v178.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment] 2018-07-06 11:38
Duplicate of #1718

**Closed by iBotPeaches** 2018-07-06 11:38 UTC

**Comment by happyfire** [comment] 2019-11-28 08:13
@iBotPeaches It seems not the same to #1718, it happens when apktool b. I hava a similar crash:
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/support/v4/util/LongSparseArray;->clone()Landroid/support/v4/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418)
	at brut.androlib.Androlib.buildSources(Androlib.java:349)
	at brut.androlib.Androlib.build(Androlib.java:301)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:251)
	at brut.apktool.Main.main(Main.java:79)
Please hava a look at that. 
Thanks!
