### ISSUE TITLE
[BUG] dexlib2 out of range

### ISSUE THREAD

**Issue by commonuserlol** [iBotPeaches/Apktool#3539] opened 2024-03-14 21:53 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - openjdk 21.0.2 2024-01-16

### Stacktrace/Logcat

```
Exception in thread "main" com.android.tools.smali.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/annotation/InspectableProperty$ValueType;->values()[Landroidx/annotation/InspectableProperty$ValueType;
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1119)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:415)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:56)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
	at brut.androlib.ApkBuilder.buildSourcesSmali(ApkBuilder.java:211)
	at brut.androlib.ApkBuilder.buildSources(ApkBuilder.java:145)
	at brut.androlib.ApkBuilder.build(ApkBuilder.java:99)
	at brut.apktool.Main.cmdBuild(Main.java:296)
	at brut.apktool.Main.main(Main.java:95)
Caused by: com.android.tools.smali.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1392)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1115)
	... 9 more
Caused by: com.android.tools.smali.util.ExceptionWithContext: Unsigned short value out of range: 65536
	at com.android.tools.smali.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:115)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:397)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1352)
	... 10 more
```

### Steps to Reproduce
1. `apktool d target.apk`
2. `cat patch.txt > target/smali/by/saygames/SayKitActivity.smali` (file attached below)
3. `apktool b target/`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

**AOSP based rom**

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkcombo.com/race-master-3d-car-racing/com.easygames.race/download/phone-4.2.0-apk

### Patch for smali (payload generated by objection tool)
[patch.txt](https://github.com/iBotPeaches/Apktool/files/14608261/patch.txt)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, no error
2. If you are trying to install a modified apk, did you resign it? Cannot build it
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2024-03-15 11:05
As this error says

> Caused by: com.android.tools.smali.util.ExceptionWithContext: Unsigned short value out of range: 65536

You've exceeded the amount of methods allowed per dex (unsigned short) - so since I cannot replicate with a disassemble/assemble without the patch - that patch is the cause.

So I'm closing.

```
➜  3539 apktool b 3539
I: Using Apktool v2.9.2-27-5422bd70-SNAPSHOT with 8 thread(s).
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: 3539/dist/3539.apk
➜  3539 
```

**Closed by iBotPeaches** 2024-03-15 11:05 UTC
