### ISSUE TITLE
Getting exception while compiling on Airtel App

### ISSUE THREAD

**Issue by kuldeepkalassts** [iBotPeaches/Apktool#1743] opened 2018-03-09 12:21 UTC
### Information
1. **Apktool Version (`apktool -version`)** -  2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - APKPure.com

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file:  ?.xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:172)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:72)
        at Main.main(Main.java:75)
        ... 5 more
Caused by: brut.directory.DirectoryException: Error copying file:  ?.xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
        ... 9 more
Caused by: java.io.FileNotFoundException: 1520597505284sample\unknown\ ?.xml (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 11 more
```

### Steps to Reproduce
1. `apktool d -r sample.apk`
2.Getting these in logs
I: Using Apktool 2.3.1 on 1520597505284sample.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...

And after this getting exception

### APK
[My Airtel Online Recharge Pay Bill Wallet UPI_v4.2.7.10_apkpure.com.zip](https://github.com/iBotPeaches/Apktool/files/1796829/My.Airtel.Online.Recharge.Pay.Bill.Wallet.UPI_v4.2.7.10_apkpure.com.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes
2. If you are trying to install a modified apk, did you resign it?
Getting exception before modifing.
3. Are you using the latest apktool version?
Yes.

**Comment by iBotPeaches** [comment] 2018-03-13 14:53
Unfortunately this is a duplicate of a long running bug - #1460 isolated to the Windows environment.

**Closed by iBotPeaches** 2018-03-13 14:53 UTC
Labels: Duplicate
