### ISSUE TITLE
ERROR: input directory 'resS' does not exist

### ISSUE THREAD

**Issue by a598799539** [iBotPeaches/Apktool#1137] opened 2016-01-15 02:32 UTC
I just use `apktool d some.apk` and use `apktool b some.apk` , but comes an exception:

```java
C:\Users\Administrator\Downloads>apktool.bat b damaoxian
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
ERROR: input directory 'resS' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\ADMINI
~1\AppData\Local\Temp\brut_util_Jar_5987179725107148105.tmp, p, --forced-package
-id, 127, --min-sdk-version, 8, --target-sdk-version, 15, --version-code, 1080,
--version-name, 2.2.3, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL869390760
3349216397.tmp, -0, arsc, -0, dat, -0, txt, -0, , -0, resS, -0, split28, -0, zip
, -0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S, C:\Users\Adm
inistrator\Downloads\damaoxian\res, -M, C:\Users\Administrator\Downloads\damaoxi
an\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_5987179725107
148105.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-vers
ion, 15, --version-code, 1080, --version-name, 2.2.3, -F, C:\Users\ADMINI~1\AppD
ata\Local\Temp\APKTOOL8693907603349216397.tmp, -0, arsc, -0, dat, -0, txt, -0, ,
 -0, resS, -0, split28, -0, zip, -0, arsc, -I, C:\Users\Administrator\apktool\fr
amework\1.apk, -S, C:\Users\Administrator\Downloads\damaoxian\res, -M, C:\Users\
Administrator\Downloads\damaoxian\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\ADMINI~1
\AppData\Local\Temp\brut_util_Jar_5987179725107148105.tmp, p, --forced-package-i
d, 127, --min-sdk-version, 8, --target-sdk-version, 15, --version-code, 1080, --
version-name, 2.2.3, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL86939076033
49216397.tmp, -0, arsc, -0, dat, -0, txt, -0, , -0, resS, -0, split28, -0, zip,
-0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S, C:\Users\Admin
istrator\Downloads\damaoxian\res, -M, C:\Users\Administrator\Downloads\damaoxian
\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        ... 6 more
```

Env:
os: windows 7 Sp1
jdk: "1.8.0_65"
apktool: 2.0.3

**Comment by a598799539** [comment] 2016-01-15 07:52
The following is my apktool.yml:
```xml
version: 2.0.3
apkFileName: damaoxian.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
sdkInfo:
  minSdkVersion: '8'
  targetSdkVersion: '15'
packageInfo:
  forced-package-id: '127'
versionInfo:
  versionCode: '1080'
  versionName: 2.2.3
sharedLibrary: false
doNotCompress:
- arsc
- dat
- txt
- ''
- resS
- split28
- zip
```

If I try the same operation in my macbook or the lower-level apktool jar in windows 7 , that's ok.

**Comment by BurgerZ** [comment] 2016-01-15 09:27
Try to build apktool from source. This bug was fixed in code, but apktool with this fix is not released yet.

**Comment by iBotPeaches** [comment] 2016-01-15 13:27
Yes, duplicate of #1122

You can remove the entry in `apktool.yml` that is

```
- ' '
```

As a fix in the meantime.

**Closed by iBotPeaches** 2016-01-15 13:27 UTC
