### ISSUE TITLE
[BUG] NullPointerException in serializeToResValuesXml

### ISSUE THREAD

**Issue by sriteja777** [iBotPeaches/Apktool#2709] opened 2021-11-29 20:33 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Unfortunately can't share the apk

### Stacktrace/Logcat

```
❯ apktool d  app.apk
I: Using Apktool 2.6.0 on app.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/sriteja/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResScalarValue.serializeToResValuesXml(ResScalarValue.java:107)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:740)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:111)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
```

### Steps to Reproduce
1. `apktool  d app.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? NA
2. If you are trying to install a modified apk, did you resign it? NA
3. Are you using the latest apktool version? Yes

Unfortunately I cannot share the apk, but I will try to tell any details that will help resolve this issue. I have done some debugging on this and noticed that.
- The exception occurs while decoding `colors.xml`
- The `body` variable in `serializeToResValuesXml` coming out as `null` which is leading to `NullPointerException`
- The app use Android R8 for obfuscation (if that is any useful)
- I looked at that color value in `resources.arsc` by using Apk Analyzer of Android Studio, and found out the below values. 

| ID      | Name | default | night | v26 | 
| ---- | ----- | ----- | -------- | ---- |
0x7f06013a | m1_urgent_task__message | null |   | | 

- I have added below code at [here](https://github.com/iBotPeaches/Apktool/blob/6cfe2987e58762397472f40d12863b1a03d5e24f/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResScalarValue.java#L107) to handle exception. With that the app recompiled and launched successfully, but I don't know if ignoring is a good thing to do or that is the right way solve this issue.
```
if (body != null && !body.isEmpty() ) {
    serializer.ignorableWhitespace(body);
}
```

Let me know if any more details are needed to debug this.

**Comment by sriteja777** [comment] 2021-12-03 06:25
@iBotPeaches Can you please look into this issue?

**Comment by iBotPeaches** [comment] 2022-01-17 12:44
@sriteja777 - Sorry for delay. I took a look, but `body` can never be null in my testing.

```
        String body = encodeAsResXmlValue();
```
A String on top of a contract that enforces a String return. So I'm not sure and without application the true root cause of this and don't want to blindly add more checks without the full picture.

I apologize, but unless you want to share application and I will privately agree to toss it and not share it. I don't know what I can do here. So closing.

**Closed by iBotPeaches** 2022-01-17 12:44 UTC

**Comment by ashwanthkumar** [comment] 2023-03-04 20:23
Sample App: https://www.apkmirror.com/apk/zomato/zomato-restaurant-finder-2/zomato-restaurant-finder-2-17-3-6-release/zomato-food-delivery-dining-17-3-6-android-apk-download/download that throws this error.
