### ISSUE TITLE
Can't recompile app with latest release, Proguard? Packer?

### ISSUE THREAD

**Issue by forkoz** [iBotPeaches/Apktool#1546] opened 2017-07-01 19:23 UTC
What's going on here? I read some other issues and this is packed? Or am I just wrong?

```

 Log For : com.wireless.macchanger.46.apk 

 Log Type : Recompiling 

 Log Recorded At : Sat 01-07-2017 13:57:00.26 

 Log Recorded By : Advanced ApkTool v4.1.0 By BDFreak 

------------------------------------------------------ 

W: A/        (  916): First type is not attr!
W: 
W: This application has requested the Runtime to terminate it in an unusual way.
W: Please contact the application's support team for more information.
W: res\drawable-v21\$avd_hide_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res\drawable-v21\$avd_hide_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res\drawable-v21\$avd_hide_password__2.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res\drawable-v21\$avd_show_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res\drawable-v21\$avd_show_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res\drawable-v21\$avd_show_password__2.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 3): [c:\temp\brut_util_Jar_4764410609085976155.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 46, --version-name, 3.32, --no-version-vectors, -F, c:\temp\APKTOOL3916453221211738253.tmp, -0, arsc, -0, arsc, -I, C:\Users\user\Downloads\app\build\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\user\Downloads\app\build\AdvancedApkTool\3-Out\com.wireless.macchanger.46.apk\res, -M, C:\Users\user\Downloads\app\build\AdvancedApkTool\3-Out\com.wireless.macchanger.46.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
	at brut.androlib.Androlib.buildResources(Androlib.java:427)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 3): [c:\temp\brut_util_Jar_4764410609085976155.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 46, --version-name, 3.32, --no-version-vectors, -F, c:\temp\APKTOOL3916453221211738253.tmp, -0, arsc, -0, arsc, -I, C:\Users\user\Downloads\app\build\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\user\Downloads\app\build\AdvancedApkTool\3-Out\com.wireless.macchanger.46.apk\res, -M, C:\Users\user\Downloads\app\build\AdvancedApkTool\3-Out\com.wireless.macchanger.46.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 3): [c:\temp\brut_util_Jar_4764410609085976155.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 46, --version-name, 3.32, --no-version-vectors, -F, c:\temp\APKTOOL3916453221211738253.tmp, -0, arsc, -0, arsc, -I, C:\Users\user\Downloads\app\build\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\user\Downloads\app\build\AdvancedApkTool\3-Out\com.wireless.macchanger.46.apk\res, -M, C:\Users\user\Downloads\app\build\AdvancedApkTool\3-Out\com.wireless.macchanger.46.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more

------------------------------------------------------ 

```

**Comment by iBotPeaches** [comment] 2017-07-02 13:26
Nope, just aapt2. Duplicate of #1520 which was a duplicate of #1540 which was a duplicate of #1532 :)

Follow this one for updates - #1520

**Closed by iBotPeaches** 2017-07-02 13:26 UTC
