### ISSUE TITLE
brut.common.BrutException: could not exec command

### ISSUE THREAD

**Issue by gilgamaze** [iBotPeaches/Apktool#1004] opened 2015-07-18 16:47 UTC
I'm using the latest version of apktool. I get the error message when I recompile my apk:
```
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
C:\Users\censored\Desktop\sendsecret\res\layout\abc_action_menu_layout.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_activity_chooser_view.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_list_menu_item_layout.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_popup_menu_item_layout.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_screen_content_include.xml:4: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout-v11\abc_screen_content_include.xml:4: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_screen_simple.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_screen_simple_overlay_action_mode.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout\abc_screen_toolbar.xml:5: error: Error parsing XML: not well-formed (invalid token)

C:\Users\censored\Desktop\sendsecret\res\layout-v21\abc_screen_toolbar.xml:5: error: Error parsing XML: not well-formed (invalid token)

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\censored\AppData\Local\Temp\brut_util_Jar_2573
390687842648843.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, -F, C:\Users\censored\AppData\Local\Temp\APKTOOL8095085151391
50950.tmp, -0, arsc, -I, C:\Users\censored\apktool\framework\1.apk, -S, C:\Users\censored\Desktop\sendsecret\res, -M, C:\Users\censored\Desktop\sendsecret\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\censored\AppData\Local\Temp\brut_util_Jar_2573390687842648843.tmp, p, --forced-package-id, 127,
 --min-sdk-version, 17, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, -F, C:\Users\censored\AppData\Local\Temp\APKTOOL809508515139150950.tmp, -0, arsc, -I, C:\Users\censored\apktoo
l\framework\1.apk, -S, C:\Users\censored\Desktop\sendsecret\res, -M, C:\Users\censored\Desktop\sendsecret\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\censored\AppData\Local\Temp\brut_util_Jar_2573390687842648843.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-
sdk-version, 21, --version-code, 1, --version-name, 1.0, -F, C:\Users\censored\AppData\Local\Temp\APKTOOL809508515139150950.tmp, -0, arsc, -I, C:\Users\censored\apktool\framework\1.apk, -S, C:\Users\W
anyoike\Desktop\sendsecret\res, -M, C:\Users\censored\Desktop\sendsecret\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
```
The apk can be found at: https://dl.dropboxusercontent.com/u/18007092/SENDSECRET.apk

**Comment by iBotPeaches** [comment] 2015-07-24 12:53
Obfuscation of resources is a duplicate of #885

**Closed by iBotPeaches** 2015-07-24 12:53 UTC
Labels: duplicate
