### ISSUE TITLE
Samsung TouchWiz 5.0.1 decompile but cannot recompile

### ISSUE THREAD

**Issue by seriousam** [iBotPeaches/Apktool#1080] opened 2015-11-07 08:44 UTC
As the title says, I'm trying to recompile SecMms_Candy.apk (messaging app) but can not. Even if I don't make any changes. I'm using unmodified framework,twframework and messaging app. I have tried to edit other files like settings and framework and work fine. I only have issues with this app.
Using apktool 2.0.2, windows 7 x64
You can see all logs and files here https://mega.nz/#F!WJo1AL4A!a11SR8UdOklmy9d3tLz_vg

**Comment by iBotPeaches** [comment] 2015-11-09 02:03
```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1080$ apktool if framework-res.apk -t 1080
I: Framework installed to: /home/ibotpeaches/apktool/framework/1-1080.apk
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1080$ apktool if twframework-res.apk -t 1080
I: Framework installed to: /home/ibotpeaches/apktool/framework/2-1080.apk
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1080$ apktool d SecMms_Candy.apk -t 1080
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT on SecMms_Candy.apk
I: Loading resource table...
I: Decoding Shared Library (touchwiz), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1-1080.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/2-1080.apk
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
apktooI: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1080$ apktool b SecMms_Candy
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
E/ResourceType(15111): Failed resolving ResTable_map name at 1824 with ident 0x0204000e
warning: Package not found for resource #0201002c
W/ResourceType(15111): Attempt to retrieve bag 0x0201002c which is invalid or in a cycle.
warning: Package not found for resource #0201002c
I: Building apk file...
I: Copying unknown files/dir...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1080$ 
```

No error, based on your stacetrace. This was already fixed (5e4bae05264e9f1ea1c969971d81d824558cd12f) which will be in the public 2.0.3 release.

Duplicate of #1053

**Closed by iBotPeaches** 2015-11-09 02:03 UTC
Labels: duplicate
