### ISSUE TITLE
[BUG] INSTALL_FAILED_INVALID_APK

### ISSUE THREAD

**Issue by 89z** [iBotPeaches/Apktool#2681] opened 2021-10-17 15:32 UTC
### Information

1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Windows

### Steps to Reproduce

https://stackoverflow.com/a/52951354

### APK

https://apkpure.com/vimeo/com.vimeo.android.videoapp

### Questions to ask before submission

2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

When I try to install patched APK to Android Studio, I get this result:

~~~
APK Installer
---------------------------
The APK failed to install.<br/> Error: INSTALL_FAILED_INVALID_APK: Failed to
extract native libraries, res=-2
~~~

**Comment by iBotPeaches** [comment] 2021-10-17 15:42
There is a workaround in #1626, but probably a duplicate of https://github.com/iBotPeaches/Apktool/issues/2609

Closing.

**Closed by iBotPeaches** 2021-10-17 15:42 UTC
