### ISSUE TITLE
Error in resource k_APKTOOL_DUPLICATENAME_0x7f0f0044

### ISSUE THREAD

**Issue by maxben14** [iBotPeaches/Apktool#1480] opened 2017-04-18 19:37 UTC
I try decompiled apk resource but after decompilation all names in resources as k_APKTOOL_DUPLICATENAME_0x7f0f0001 names. Why so work apktool ? How fixed ?

If you need my apk i can upload apk your for research mistakes in apktool.

http://rgho.st/68gldNwQV
My apk.

My issue https://github.com/iBotPeaches/Apktool/issues/1474#issuecomment-292926115
Do you think about this bug in apktool ?

**Comment by iBotPeaches** [comment] 2017-04-18 19:40
Duplicate of #1474 

Please don't open duplicate reports.

**Closed by iBotPeaches** 2017-04-18 19:40 UTC
Labels: Duplicate

**Comment by maxben14** [comment] 2017-04-18 20:23
Okay, but do you remember my problem? You can answer the reason for the error in the  apktool, I upload the apk file.

**Comment by iBotPeaches** [comment] 2017-04-18 20:25
I remember your previous bug. I have 74 others :)

Remember, this is just me. Working unpaid on a hobby project in my spare time. Things take me awhile. I haven't even triage`d your ticket yet.
