### ISSUE TITLE
build fails on First type is not attr

### ISSUE THREAD

**Issue by gilhartman** [iBotPeaches/Apktool#1540] opened 2017-06-26 09:45 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.3
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: A/        (65890): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/brut_util_Jar_821956130558135074.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 8, --version-name, 1.0, --no-version-vectors, -F, /var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/APKTOOL1112946391103945943.tmp, -0, arsc, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/Desktop/app/res, -M, /Users/user/Desktop/app/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
	at brut.androlib.Androlib.buildResources(Androlib.java:427)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/brut_util_Jar_821956130558135074.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 8, --version-name, 1.0, --no-version-vectors, -F, /var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/APKTOOL1112946391103945943.tmp, -0, arsc, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/Desktop/app/res, -M, /Users/user/Desktop/app/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/brut_util_Jar_821956130558135074.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 8, --version-name, 1.0, --no-version-vectors, -F, /var/folders/r_/lfrzsqgn4cxb416ysxq75sqh0000gn/T/APKTOOL1112946391103945943.tmp, -0, arsc, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/Desktop/app/res, -M, /Users/user/Desktop/app/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```

### Steps to Reproduce
1. `apktool d app.apk`
2. `apktool b app.apk -o app2.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
None
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

Unfortunately, I can't share the app itself but I added the verbose log of apktool. If there is anything I can do to speed up the inquiry, please tell me

[log.txt](https://github.com/iBotPeaches/Apktool/files/1101680/log.txt)

**Comment by iBotPeaches** [comment] 2017-06-26 16:10
Thanks for the report, however this is a duplicate of #1520 which was also recently found in #1532 with another error. 

Closing as duplicate of #1520

**Closed by iBotPeaches** 2017-06-26 16:10 UTC
