### ISSUE TITLE
Increase in apk size after recompiling and signing

### ISSUE THREAD

**Issue by StanleySd** [iBotPeaches/Apktool#1620] opened 2017-09-23 16:10 UTC
### Information
1. **Apktool Version 2.3.0 also latest advanced apktool
2. **Operating System ( Windows7)** -
3. **APK From? (Other)** -YES

```### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
A: Im using it through advanced apktool
2. If you are trying to install a modified apk, did you resign it?
A:Yes i did!
3. Are you using the latest apktool version?
A: Using latest one

**Comment by iBotPeaches** [comment] 2017-09-28 12:34
This is unforunately a problem when there are file extensions in an apk that are stored and deflated, instead of being all deflated or all stored. This is a duplicate of #1572

**Closed by iBotPeaches** 2017-09-28 12:34 UTC
