### ISSUE TITLE
APK force close with missing Google APP_ID

### ISSUE THREAD

**Issue by JustDragon** [iBotPeaches/Apktool#1058] opened 2015-10-14 11:47 UTC
Here is the APK to test: http://www82.zippyshare.com/v/EczyQVOY/file.html
What steps will reproduce this problem? Just decompile and recompile, no touch anything. Then run it and it will force close. It run fine with original apk
What is the expected output? I checked logcat and I found this:
W/Bundle  (23946): Key com.google.android.gms.games.APP_ID expected String but value was a java.lang.Integer.  The default value <null> was returned.
So I think the problem is it can't get google app_id somehow.
What version of the tool are you using? On what Operating System?I'm using 2.0.2 and on Kitkat 4.4

**Comment by iBotPeaches** [comment] 2015-10-14 12:46
Duplicate of #767

**Closed by iBotPeaches** 2015-10-14 12:46 UTC
Labels: duplicate

**Comment by JustDragon** [comment] 2015-10-16 02:07
Hi Connor,

I have used this apktool build for a long time but I don't have this
problem like your apktool. Can you look into this and find out what's fix?
Thanks!
http://www71.zippyshare.com/v/TaE6DsZo/file.html
