### ISSUE TITLE
java.io.IOException: Cannot run program...error=7, Argument list too long

### ISSUE THREAD

**Issue by wuzhou** [iBotPeaches/Apktool#1660] opened 2017-11-13 12:12 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.3.0
2. **Operating System (Mac, Linux, Windows)** -Mac
3. **APK From? (Playstore, ROM, Other)** -Application build by my self.

### Stacktrace/Logcat

```
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/var/folders/9x/jcx5zk113vj79h21txt56yfw0000gn/T/brut_util_Jar_414495445637280235.tmp": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

### Steps to Reproduce
1. `apktool  d mytest.apk`
2. Modify the `AndroidManifest.xml` file.
3. `apktool b mytest.apk`

### APK
I'm sorry. I can't share the apk. However, this apk contains about 7000 files. I think this large number of files to build may cause this issue.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? I can't rebuild it.
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2017-11-13 14:44
This is a duplicate of #1272 

I am working on an enhancement that splits the process into chunks as to not hit any command size limit.

**Closed by iBotPeaches** 2017-11-13 14:44 UTC
