### ISSUE TITLE
cannot decode and build wechat (version 6.5.10) from playstore

### ISSUE THREAD

**Issue by dillrich** [iBotPeaches/Apktool#1566] opened 2017-07-21 15:36 UTC
[apktool_bug_report.txt](https://github.com/iBotPeaches/Apktool/files/1166016/apktool_bug_report.txt)
### Information
1. **Apktool Version (`apktool -version`)** -2.2.3
2. **Operating System (Mac, Linux, Windows)** -Linux 
3. **APK From? (Playstore, ROM, Other)** -Playstore

### Stacktrace/Logcat
- see attached
```
Include stacktrace here
### Steps to Reproduce
1. `apktool  d wechat`
2. cd wechat && apktool b

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
--file is too big to attach.  Please get it from the playstore.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? --  that is exactly what I did and received the crazy error output.
2. If you are trying to install a modified apk, did you resign it?  APK was not modified
3. Are you using the latest apktool version? yes

**Comment by dillrich** [comment] 2017-07-21 15:52
output was too large for body .... so it is pasted into apktool_bug_report.txt, which is attached.

**Comment by iBotPeaches** [comment] 2017-07-21 18:53
Duplicate of #1423

**Closed by iBotPeaches** 2017-07-21 18:53 UTC

**Comment by ZAZA316** [comment] 2017-12-20 14:43
Why don't you use ApkEasyTool for decode?
