### ISSUE TITLE
AAPT Issues (?) with Samsung framework-res

### ISSUE THREAD

**Issue by Jertlok** [iBotPeaches/Apktool#1258] opened 2016-05-27 05:12 UTC
Hello there, i'm trying to theme my Samsung Framework-res.apk, but one _magical_ glitch stopped me and led me dig for it. I'll attach the error that apktool gives me, it seems to be an AAPT issue on some PNGs but this is not the main issue since it can be manually fixed changing their name - (no more errors are thrown after those manual renaming). Basically, changing the windowBackground color to black, made me noticing that somehow a red glitch on WiFi texts was magically appearing.
[Album@Imgur](http://imgur.com/a/EaSxP) - _in order to keep this bug report clean and small_.
My first move, in order to try fixing the issue,  has been to set EVERYTHING from SecSettings.apk and framework-res.apk into transparent (#00000000) using regular expressions to match every colors and item lines (found in all their XML files) placing _(at)android:color/transparent_, but yet some wifi labels were still there. 
**AAPT issues perhaps?**

Thanks in advance, cheers.
### Information
1. **Apktool Version (`2.1.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (ROM)** -
### Stacktrace/Logcat

**Decompilation:**

```
I: Using Apktool 2.1.1 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

**Compilation**

```
I: Using Apktool 2.1.1
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Jertlok\Desktop\apkbench\framework-res\res\drawable-sw360dp-xxxhdpi-v13\ic_knox_badge.PNG: error: File is case-insensitive equivalent to: C:\Users\Jertlok\Desktop\apkbench\framework-res\res\drawable-hdpi-v4\ic_knox_badge.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Jertlok\AppData\Local\Temp\brut_util_Jar_1442071662568735255.tmp, p, --forced-package-id, 1, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 23, --version-name, 6.0.1, -F, C:\Users\Jertlok\AppData\Local\Temp\APKTOOL2743732649485842444.tmp, -x, -0, arsc, -0, PNG, -0, arsc, -S, C:\Users\Jertlok\Desktop\apkbench\framework-res\res, -M, C:\Users\Jertlok\Desktop\apkbench\framework-res\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Jertlok\AppData\Local\Temp\brut_util_Jar_1442071662568735255.tmp, p, --forced-package-id, 1, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 23, --version-name, 6.0.1, -F, C:\Users\Jertlok\AppData\Local\Temp\APKTOOL2743732649485842444.tmp, -x, -0, arsc, -0, PNG, -0, arsc, -S, C:\Users\Jertlok\Desktop\apkbench\framework-res\res, -M, C:\Users\Jertlok\Desktop\apkbench\framework-res\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Jertlok\AppData\Local\Temp\brut_util_Jar_1442071662568735255.tmp, p, --forced-package-id, 1, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 23, --version-name, 6.0.1, -F, C:\Users\Jertlok\AppData\Local\Temp\APKTOOL2743732649485842444.tmp, -x, -0, arsc, -0, PNG, -0, arsc, -S, C:\Users\Jertlok\Desktop\apkbench\framework-res\res, -M, C:\Users\Jertlok\Desktop\apkbench\framework-res\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
        ... 6 more
```
### Steps to Reproduce
1. `apktool  d framework-res.apk`
2. `apktool b framework-res.apk`
### Frameworks

framework-res.apk from Samsung Galaxy Note 4 MM Stock ROM
[framework-res.zip@GDrive](https://drive.google.com/file/d/0B2osSqW4Jxl8ZVhTeWxjUkttNWM/view?usp=sharing) - _uploaded on Google Drive due to its size_
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
   _Yes, and it gives me some errors related to PNGs during the re-compilation._
2. If you are trying to install a modified apk, did you resign it?
   _I'm not installing the application via a normal installation procedure because it's a framework-res.apk (System)._
3. Are you using the latest apktool version?
   _Yes, i'm using the version downloadable from here [ApkTool Download Link](https://github.com/iBotPeaches/Apktool/releases/download/2.1.1/apktool_2.1.1.jar)._

**Comment by Jertlok** [comment] 2016-05-27 06:36
Similar to https://github.com/iBotPeaches/Apktool/issues/1026
But let's see what you think about the second issue ;)

**Comment by iBotPeaches** [comment] 2016-05-31 11:36
Fixed the PNG issue. Still not sure what I should be looking at in terms of where the problem may be at. Might need to refresh my aapt knowledge especially in regards to how it handles colors.

**Comment by Jertlok** [comment] 2016-06-01 10:11
I've seen your new commit, pretty simple workaround!
Thank you very much!
Maybe the situation will change with the hypotetical new AAPT.

**Comment by micky387** [comment] 2016-06-02 20:06
Hello.
No need to fix anything. Just rename your xxx.PNG to xxx.png.

regards

**Comment by Jertlok** [comment] 2016-06-04 12:56
Yeah mate, thanks for your reply but i stated it too inside my bug report.
Though iBotPeaches came with a simple workaround ;)

**Comment by micky387** [comment] 2016-06-04 20:54
ok sorry,i dont saw it.

**Comment by iBotPeaches** [comment] 2016-08-09 12:05
Sorry for delay. 2.2.0 introduces this commit - https://github.com/iBotPeaches/Apktool/commit/a684bae43ae51859a3bd933dc0d52c3186eb8abf which properly handles `@empty` references. I believe this was the cause to the above errors if you could give it another shot.

**Comment by Jertlok** [comment] 2016-08-09 12:40
Hello, iBotPeaches, unfortunately i switched to a Nexus 6P some days ago but i'm still inside plenty of Note 4 communities, i'll ask them to test this for you.

**Comment by rakeshraimca** [comment] 2016-09-07 23:57
Hello, iBotPeaches,  Sorry to say but this issue still appears while recompiling my framework-res file . i am using latest framework.jar file patched by you..but still i am getting same issue

"

framework-res\res\drawable-sw360dp-xxxhdpi-v13\ic_knox_badge.PNG: error: File is case-insensitive equivalent to:"

here is my framework-res file:  https://drive.google.com/open?id=0B5yEFQJPxvK6ZGMtNUdRXzVhOEE

any workaround for this?

**Comment by iBotPeaches** [comment] 2016-09-07 23:58
@rakeshraimca Did you decode it with 2.2.0 as well? That warning you posted goes against patches that directly went into 2.2.0.

**Comment by rakeshraimca** [comment] 2016-09-08 00:01
I am using 2.1.1 version apktool..i decoded with that version

**Comment by iBotPeaches** [comment] 2016-09-08 00:04
@rakeshraimca That is old, use 2.2.0 - https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.0.jar

**Comment by rakeshraimca** [comment] 2016-09-08 00:04
let me try with latest 2.2 ...will update here shortly

**Comment by rakeshraimca** [comment] 2016-09-08 01:28
Yes its working now..sorry my bad..

**Comment by iBotPeaches** [comment] 2016-12-24 12:55
Okay, so I am under belief this has since been fixed. Original OP couldn't test, but someone with similar issue after using the 2.2.0 binary confirmed the problem was resolved.

This should have been in 2.2.0 patch notes, but I forgot to add changelog entry for this. Closing this now. If this appears to be broken, just leave another comment.

**Closed by iBotPeaches** 2016-12-24 12:55 UTC
Labels: Waiting for issuer

**Comment by sutan99** [comment] 2020-11-23 23:58
same problem in apktool 2.4.1

`I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: D:\Black Box\BackUP\DS\Android Image Kitchen\New folder\Advanced+ApkTool+-+Supports+Oreo\3-Out\AsusSettings.apk\res\drawable-hdpi\asus_navigationbar_pic_1_zenuI_five.png: error: File is case-insensitive equivalent to: D:\Black Box\BackUP\DS\Android Image Kitchen\New folder\Advanced+ApkTool+-+Supports+Oreo\3-Out\AsusSettings.apk\res\drawable-mdpi\asus_navigationbar_pic_1_zenui_five.png
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SUTANK~1\AppData\Local\Temp\brut_util_Jar_3043174590468067550.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\SUTANK~1\AppData\Local\Temp\APKTOOL2330504736862354369.tmp, -e, C:\Users\SUTANK~1\AppData\Local\Temp\APKTOOL8521152726330176485.tmp, -0, arsc, -I, C:\Users\Sutan Karim\AppData\Local\apktool\framework\1.apk, -S, D:\Black Box\BackUP\DS\Android Image Kitchen\New folder\Advanced+ApkTool+-+Supports+Oreo\3-Out\AsusSettings.apk\res, -M, D:\Black Box\BackUP\DS\Android Image Kitchen\New folder\Advanced+ApkTool+-+Supports+Oreo\3-Out\AsusSettings.apk\AndroidManifest.xml]`
