### ISSUE TITLE
Problems with resources when rebuilding a few apps

### ISSUE THREAD

**Issue by pvertenten** [iBotPeaches/Apktool#986] opened 2015-07-02 14:56 UTC
I am using the latest code from master, but I get the same issues with the 2.0 release.

Also for this purpose I am just doing an a decompile and build. I have the latest framework installed.

apktool d app.apk
apktool b app.apk

Periscope 1.0.2 (1900062)
http://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=15898

Bunch of resource errors like:
No resource identifier found for attribute 'font' in package 'android'

Amazon 5.6.1.200
http://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=15936
Bunch of resource errors like:
Tag <action> attribute name has invalid character '-'.

**Comment by iBotPeaches** [comment] 2015-07-09 11:58
Duplicate of #983 but yes I duplicate.

**Closed by iBotPeaches** 2015-07-09 11:58 UTC
Labels: duplicate
