### ISSUE TITLE
skipping file '.test.t' due to ANDROID_AAPT_IGNORE pattern '.*'

### ISSUE THREAD

**Issue by blstbbcxz** [iBotPeaches/Apktool#1184] opened 2016-03-07 09:25 UTC
Hi,i use apktool 2.0.0-RC3 version to rebuild my apk but problem occured.
```
C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\bin\developTools\jdk1.6.0\bin>cmd.exe /c java.exe -jar C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\bin\developTools\apktool.jar b -o
 C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\laohu_OneSDK_Demo-test.apk C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\OneSDK_Demo-test.apk.dir
I: Using Apktool 2.0.0-RC3 on OneSDK_Demo-test.apk.dir
I: Checking whether resources has changed...
I: Building apk file...
    (skipping file '.test.t' due to ANDROID_AAPT_IGNORE pattern '.*')

skipping file '.test.t' due to ANDROID_AAPT_IGNORE pattern '.*'
```
can I modify the pattern to include all the files?
if it can be, where should i modify, modify aapt.exe or apktool.jar? and how to modify it

Thanks!

**Comment by iBotPeaches** [comment] 2016-03-07 12:08
This shouldn't be a problem. Files that are outside of the common folders (`resources`, `libs`, `etc`) are automatically included as unknown files. The only reason the `ANDROID_AAPT_IGNORE` pattern would kick in would be for files hidden among the resource directories, in which they would be ignored.

I can't be certain, because there is no apk.

You don't need to modify aapt to change the ignore pattern, but there is no easy way without recompiling apktool. There is a parameter `--ignore-assets` in aapt. Passing a blank parameter might override to ignore nothing, therefore include your files.

You can modify the Apktool Resource builder for this. Need APK to move forward.

**Comment by iBotPeaches** [comment] 2016-04-18 12:36
This warning was caused by aapt and never received any more details in a month. Closing this.

**Closed by iBotPeaches** 2016-04-18 12:36 UTC
Labels: Waiting for issuer
