### ISSUE TITLE
apktool d my.apk error

### ISSUE THREAD

**Issue by matianhe** [iBotPeaches/Apktool#1964] opened 2018-12-25 14:15 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.3.4
2. **Operating System (Mac, Linux, Windows)** -Mac 10.14
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool ` apktool d test.apk

<img width="1086" alt="screen shot 2018-12-25 at 22 14 43" src="https://user-images.githubusercontent.com/24929062/50423594-85876080-0892-11e9-9b7e-5f8c3c2f74ed.png">

**Comment by iBotPeaches** [comment] 2018-12-27 15:35
Duplicate of #1874 , thanks for the report!

In the future, screenshots of errors are difficult to triage due to unable to copy/paste.

**Closed by iBotPeaches** 2018-12-27 15:35 UTC
