### ISSUE TITLE
[INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2] after Compile

### ISSUE THREAD

**Issue by Deltafox79** [iBotPeaches/Apktool#1626] opened 2017-09-26 11:47 UTC
### Information
1. **Apktool Version (`apktool -version`)** -
**2.3.0**
2. **Operating System (Mac, Linux, Windows)** -
**Windows**
3. **APK From? (Playstore, ROM, Other)** -
**PlayStore**
### Stacktrace/Logcat

```
Include stacktrace here
```
After recompile apk and signed I have this issue when install recompiled apk...
> `Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

### Steps to Reproduce
1. `apktool `
**apktool.bat r ..apk**

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

**http://www17.zippyshare.com/v/cE36EDY0/file.html**

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
yes
3. Are you using the latest apktool version?
yes

**Comment by iBotPeaches** [comment] 2017-10-04 21:18
Sorry delayed on this. Was going to look into it, but forgot my dev phone today. Just letting you know I read this and have the application locally and will look into it hopefully tomorrow.

**Comment by Deltafox79** [comment] 2017-11-02 10:53
Hi I have update download link any info on this issue? Regards

**Comment by danhawkes** [comment] 2017-11-21 15:27
Think this is triggered by setting`extractNativeLibs` to false in the manifest. Have reverted a change to set it and the recompiled APK installs successfully.
<https://developer.android.com/guide/topics/manifest/application-element.html>

**Comment by iBotPeaches** [comment] 2017-11-21 15:32
Interesting. Apktool should not change values of the Manifest though. I'll run some tests with that info.

```
 E: application (line=34)
      A: android:label(0x01010001)=@0x7f0d0032
      A: android:icon(0x01010002)=@0x7f0b0000
      A: android:name(0x01010003)="com.bittorrent.client.BTApp" (Raw: "com.bittorrent.client.BTApp")
      A: android:allowBackup(0x01010280)=(type 0x12)0x0
      A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
      A: android:supportsRtl(0x010103af)=(type 0x12)0x0
      A: android:extractNativeLibs(0x010104ea)=(type 0x12)0x0
      A: android:resizeableActivity(0x010104f6)=(type 0x12)0xffffffff
      A: android:roundIcon(0x0101052c)=@0x7f0b0000
```

AAPT already has it set to `0x0` or `false`.

**Comment by Deltafox79** [comment] 2017-11-23 11:10
Yes if I put tru the extractNativeLibs apk compiled works.. strange if whit -r option apk have same problems..

Regards

**Comment by iBotPeaches** [comment] 2017-12-01 20:53
Looked into this some more. If going by the words of @danhawkes & @Deltafox79 that manually changing this `extractNativeLibs` property to true resolves the booting issue doesn't make much sense.

I confirmed that the property was false in the original application, the decoded original application and the rebuilt (dirty) application. Apktool should not be in the market of random changing properties in the Manifest.

There was some research online that an application needs to be "zipaligned" to resolve this issue. I read that here: https://github.com/scala-android/sbt-android/issues/252

Might be worth testing. Resign, then zipalign and try with the property set to false.

**Comment by peret** [comment] 2018-11-23 17:20
I can also confirm that this is still an issue in 2.3.4. zipaligning the apk did unfortunately not fix it.
The [Documentation](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) says: "If set to false, then your native libraries must be page aligned and stored uncompressed in the APK."

Could the issue be related to apktool compressing the native libs for some reason? From what I can see, .so-files are actually on the doNotCompress list though...

**Comment by Deltafox79** [comment] 2019-07-22 11:50
Hi Any news on this issue? also whit latest **apktool-2.4.1-c20659-SNAPSHOT-small.jar** this bug is present..

Just use d for decompile apk and manifest change android:extractNativeLibs="false" why false?

Download apk for test :

[debug.apk](https://mega.nz/#!ObhTTA4Q!P1uTuy1ouKnK4oKa6iaX69b9SuGYsGW71d6CbhppPUM)

Regards

**Comment by rosasurfer** [comment] 2019-11-08 10:22
With the latest version of the Android build environment the manifest attribute "android:extractNativeLibs" is always set to "false". This means the libraries in the APK are page aligned by the build environment (not to confuse with zipaligning the whole APK) and the loader loads them directly from the APK (presumably performance considerations). When the ApkTool (newest version) recompiles such an APK it doesn't change the manifest settings but the resulting library file layout in the APK is not page aligned anymore. That's why the loader fails and the error occures. Removing the attribute or explicitely setting it to "true" (the default value) should prevent the bug to happen.

**Comment by timjosten** [comment] 2020-08-09 07:43
@iBotPeaches When extractNativeLibs="false", then .so files should not be ZIP compressed. The system will load .so files directly from APK binary file. It won't work if .so files are compressed.

**Comment by iBotPeaches** [comment] 2020-08-09 11:08
> @iBotPeaches If extractNativeLibs="false", then .so files should not be ZIP compressed. The system will load .so files directly from APK binary file. It won't work if .so files are compressed.
> 
> For a dirty fix, you should always change this attribute to true.
> For a proper fix, you should implement new code to not compress .so files if this attribute is set to false, but compress everything else.

Thanks for the research. I see. So the property extraction is required if true, if false is just uses random access to stream file.

**Comment by giacomoferretti** [comment] 2020-08-28 12:06
Seems to work with 2.4.2-d3f9d5-SNAPSHOT.

After rebuilding, `zipalign` it using this command: `zipalign -p -f 4 input.apk output.apk`
Then sign it with `apksigner` and should work now.

**Comment by bletham** [comment] 2020-10-10 22:39
I was running into this issue (in apktool 2.4.1, and using zipalign after jarsigner) and @giacomoferretti's approach worked for me.

**Comment by iBotPeaches** [comment] 2020-11-29 13:11
This should be handled now with proper handling of compression. Zipaligning may be required to align to 4byte boundries.

Closing.

**Closed by iBotPeaches** 2020-11-29 13:11 UTC

**Comment by scottkennedy** [comment] 2021-09-03 12:19
I'm having this issue on 2.6.0.  Removing the property from the manifest allows it to work.

**Comment by 89z** [comment] 2021-10-17 15:45
In my case, just removing the attribute fixed the problem:

~~~
android:extractNativeLibs="false"
~~~

no need to set it to true or false, just delete it.

**Comment by 89z** [comment] 2021-10-17 15:47
https://github.com/iBotPeaches/Apktool/issues/2609

**Comment by cbrevik** [comment] 2021-12-15 20:23
> Seems to work with 2.4.2-d3f9d5-SNAPSHOT.
> 
> After rebuilding, `zipalign` it using this command: `zipalign -p -f 4 input.apk output.apk` Then sign it with `apksigner` and should work now.

Chiming in to say that the important part for me was that I had to add the `-p` flag to do alignment of .so files in the apk

**Comment by baptx** [comment] 2022-12-22 21:13
I still got this error even with the latest version 2.7. The workaround with `zipalign -p` did not work for me and I cannot set `extractNativeLibs="true"` or remove this option from AndroidManifest.xml because of another issue that requires `apktool -r` to not decompile resources (https://stackoverflow.com/questions/23317208/apktool-build-apk-fails/23719727#23719727).
But I have another workaround to share, you just remove the lib folder from the APK file with an archive manager like file-roller, then install the APK (after having aligned and signed the file), make sure the app is stopped in Android settings, fill the lib folder with the subfolder from an original installation in `/data/data/YOUR_APP_ID/lib`, change permissions with `chown -R system:system` on the folder added if needed, start the app.
If it is not working, it is also possible to replace the APK file from the `/data/app/YOUR_APP_ID` folder with the one customized. You may also need to execute the commands `chown system:system base.apk` and `chmod 644 base.apk`.
If there are several APK files, you need to install them all with `adb install-multiple apk1 apk2` (https://www.reddit.com/r/AndroidQuestions/comments/wqllmv/how_to_install_splitconfig_apk_files/).

To sign the app, I used these commands (from https://blog.securityevaluators.com/bypassing-okhttp3-certificate-pinning-c68a872ca9c8):
```
keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore <patched.apk> alias_name
```
Note that according to https://developer.android.com/studio/command-line/zipalign, if we use jarsigner, we have to align the APK after, not before (as we can see on https://medium.com/@felipecsl/bypassing-certificate-pinning-on-android-for-fun-and-profit-1b0d14beab2b).

**Comment by gelldur** [comment] 2023-08-26 21:59
When you add extra .so file maybe you try inject `libfrida-gadget.so` then:
1. Add libfrida-gadget.so to apktool.yml file (check section `doNotCompress:`) and add there your file
2. `apktool b target`
3. `zipalign -p -f 4 target.apk aligned.apk`
4. `java -jar uber-apk-signer-1.3.0.jar --skipZipAlign --apks app/dist` 

In my case it worked. No changes to manifest and I decompiled with `apktool d -rs`

**Comment by Starmania** [comment] 2023-08-29 13:23
adding frida in the `doNotCompress` list in apktool.yml also solve my problem

**Comment by ego-lay-atman-bay** [comment] 2024-01-05 23:42
I am also having this issue in 2.9.1, although I haven't tried any of the fixes in this thread yet.

**Comment by HackJJ** [comment] 2024-01-24 21:52
The fix to change `extractNativeLibs` to `true` works but seems a bodge.

**Comment by firdiar-mita** [comment] 2024-05-09 18:14
> When you add extra .so file maybe you try inject `libfrida-gadget.so` then:
> 
> 1. Add libfrida-gadget.so to apktool.yml file (check section `doNotCompress:`) and add there your file
> 2. `apktool b target`
> 3. `zipalign -p -f 4 target.apk aligned.apk`
> 4. `java -jar uber-apk-signer-1.3.0.jar --skipZipAlign --apks app/dist`
> 
> In my case it worked. No changes to manifest and I decompiled with `apktool d -rs`

i decompile using apktool d -r
following those 3 steps allowing the app to be installed, but when i open it it crash immidiately
despite im not changing anything n source

**Comment by DanBrown47** [comment] 2025-03-13 12:38
The latest version of Android studio is packed with an Apk Signer, using the apk signer helped to installation, look into logcat log and it will tell you what have gone wrong
