### ISSUE TITLE
decode adds `-v4` to res\drawable-*dpi folders

### ISSUE THREAD

**Issue by zxcat** [iBotPeaches/Apktool#1253] opened 2016-05-22 20:29 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.1.1
2. **Operating System (Mac, Linux, Windows)** - Windows 7
3. **APK From? (Playstore, ROM, Other)** - any

### Steps to Reproduce
1. Open original apk (as zip), which have dirs `res\drawable-hdpi`, `res\drawable-mdpi`, etc.
2. `apktool  d PackageInstaller.apk`.
3. Open decoded `res` folder, it will contain `drawable-hdpi-v4`, `drawable-mdpi-v4`, etc. There were no `-v4` in original `res`

### APK
Any. Checked on standard android like `PackageInstaller`, APKs from playstore or self created.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Yes**
2. If you are trying to install a modified apk, did you resign it? **Do not installing**
3. Are you using the latest apktool version? **Yes**

**Comment by iBotPeaches** [comment] 2016-05-22 20:32
Duplicate of #1212

**Closed by iBotPeaches** 2016-05-22 20:32 UTC
