### ISSUE TITLE
apk decompiling not working on Android O developer preview

### ISSUE THREAD

**Issue by Jassun16** [iBotPeaches/Apktool#1457] opened 2017-03-25 09:47 UTC
### Information
1. **Apktool Version (`2.2.2`)** -
2. **Operating System (Windows)** -
3. **APK From? (android O developer preview)** -

### Stacktrace/Logcat
F:\>java -jar apktool_2.2.2.jar d framework-res.apk
I: Using Apktool 2.2.2 on framework-res.apk
I: Loading resource table...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 111
        at java.lang.String.substring(Unknown Source)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:162)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:315)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:241)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:559)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:67)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
Framework file from Nexus 6P Android O Developer Preview 1 
https://drive.google.com/open?id=0B67SfczIpYMvMnMyQW1Va0R2bE0

**Comment by iBotPeaches** [comment] 2017-03-25 11:26
Duplicate of #1453

**Closed by iBotPeaches** 2017-03-25 11:26 UTC
