### ISSUE TITLE
Asset named in CP936 encoding build failure.

### ISSUE THREAD

**Issue by wdworks** [iBotPeaches/Apktool#1650] opened 2017-11-01 14:10 UTC
Hello!
I'm trying to repackage apk that contains asset with name in simplified Chinese.

`java -jar apktool_2.3.0.jar b build_dir`

This runs perfectly fine on linux because on linux java uses UTF8 encoding for zip entry.
However on windows this asset is not being added at all with default locale.
If windows system locale is changed to simplified Chinese (CP936) i get following error

`    java.lang.IllegalArgumentException: MALFORMED[1]
        at java.util.zip.ZipCoder.toString(ZipCoder.java:65)
        at java.util.zip.ZipFile.getZipEntry(ZipFile.java:566)
        at java.util.zip.ZipFile.access$900(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:524)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
        at brut.androlib.Androlib.copyExistingFiles(Androlib.java:625)
`

I've also tried with the github version.
This error also can be reproduced at build testing stage if changed.
`ZipFile inputFile = new ZipFile(tempFile,Charset.forName("CP936"));` in buildUnknownFiles routine. I assume similar stuff happens if system locale is changed.
Example of asset name: 拟专网.txt
Also interesting detail it it is being added correctly by aapt add on windows when CP936 in use.
JRE 8 in use.

**Comment by iBotPeaches** [comment] 2017-11-01 14:15
Might be duplicate of #1460 . In the short term stick with unix until I figure out a proper solution of encoding/locales on Windows

**Comment by wdworks** [comment] 2017-11-01 14:19
@iBotPeaches thanks for great work you doing!
Also worth mentioning that unpacking on windows goes without any issues no matter what locale in use.

**Closed** 2017-11-01 14:21 UTC
