### ISSUE TITLE
[BUG] compile issues this type error are show pl z helps me.

### ISSUE THREAD

**Issue by tejasnikumbh1432** [iBotPeaches/Apktool#3698] opened 2024-09-19 16:37 UTC
### Information
1. **Apktool Version (`apktool -version 2.9.3`)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -
**
```
I: Using Apktool 2.9.3
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes10 folder into classes10.dex...
I: Smaling smali_classes11 folder into classes11.dex...
I: Smaling smali_classes12 folder into classes12.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Smaling smali_classes6 folder into classes6.dex...
I: Smaling smali_classes7 folder into classes7.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Smaling smali_classes9 folder into classes9.dex...
I: Building resources...
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-h640dp\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-h640dp\layouts.xml: error: file failed to compile.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-land\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-land\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-land\layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-land\layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-land\layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-land\layouts.xml: error: file failed to compile.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-sw600dp\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-sw600dp\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values-sw600dp\layouts.xml: error: file failed to compile.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:4: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:5: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:6: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:7: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:8: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:9: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:10: error: invalid value for type 'layout'. Expected a reference.
W: C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res\values\layouts.xml:11: error: invalid value for type 'layout'. Expected a reference.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Vaibhav\AppData\Local\Temp\brut_util_Jar_70226531727345531718059468123696520281.tmp, compile, --dir, C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\res, --legacy, -o, C:\Users\Vaibhav\Documents\APK Easy Tool\1-Decompiled APKs\com.instagram.android_349.0.0.39.104-374912646_minAPI28(arm64-v8a)(nodpi)_apkmirror.com\build\resources.zip]
```

**Comment by iBotPeaches** [comment] 2024-09-19 16:56
This looks like a duplicate of https://github.com/iBotPeaches/Apktool/issues/2618 - closing.

**Closed by iBotPeaches** 2024-09-19 16:56 UTC

**Comment by tejasnikumbh1432** [comment] 2024-09-20 14:15
i want solution plz sir

**Comment by tejasnikumbh1432** [comment] 2024-09-20 14:15
i want solution

**Comment by iBotPeaches** [comment] 2024-09-20 14:16
Please don't spam the repository.
