### ISSUE TITLE
apktool crash when processing arsc file

### ISSUE THREAD

**Issue by nil1666** [iBotPeaches/Apktool#1081] opened 2015-11-07 15:30 UTC
The apk can be downloaded from:
http://qd.alibaba.com/d/android

bug track:
```
Exception in thread "main" brut.androlib.AndrolibException: Could not decode ars
c file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:544)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.jav
a:63)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.jav
a:55)
        at brut.androlib.Androlib.getResTable(Androlib.java:65)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:197)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:73)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 8 more
```
Thank you

**Comment by iBotPeaches** [comment] 2015-11-09 01:58
Same early crash as #964 Some good trickey going on here. Duplicate of existing report, but additional apk helps for investigation.

Thanks!

**Closed by iBotPeaches** 2015-11-09 01:58 UTC
Labels: duplicate
