### ISSUE TITLE
Apktool  any version not let me to decompile any odex file

### ISSUE THREAD

**Issue by Androdiver** [iBotPeaches/Apktool#1246] opened 2016-05-16 08:16 UTC
### Information
1. **Apktool Version 4.3/4.1/etc any of these version i tried cant decompile my odex or apk file even framework is not impoting why
2. **Operating System (Android lollipop)** -
3. Odex from my system framework

My framework

**Comment by iBotPeaches** [comment] 2016-05-16 15:12
Closing as duplicate of #1247

**Closed by iBotPeaches** 2016-05-16 15:12 UTC
Labels: Duplicate
