### ISSUE TITLE
Error decompiling APK: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.

### ISSUE THREAD

**Issue by RobertRBT** [iBotPeaches/Apktool#2017] opened 2019-02-25 12:52 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.3.4
2. **Operating System (Mac, Linux, Windows)** -Windows 10
3. **APK From? (Playstore, ROM, Other)** -other

### Stacktrace/Logcat.
```
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/virtual_preload.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/virtual_preload.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/virtual_preload.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/virtual_preload_folder.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/virtual_preload_folder.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/colorpicker_btn_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxxhdpi-v4/preset_radio_button_bg_checked.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
...
```

### Steps to Reproduce
1. `apktool d nova_6.0-beta14-59915.apk`
2. `apktool b nova_6.0-beta14-59915`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/teslacoil-software/nova-launcher/nova-launcher-6-0-beta14-release/nova-launcher-6-0-beta14-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes

**Comment by ibuprophen1** [comment] 2019-02-25 17:22
This looks allot like a duplicate of the https://github.com/iBotPeaches/Apktool/issues/2019 issue to me... 


~Ibuprophen

**Comment by Amirphony** [comment] 2019-02-26 07:09
> 
> 
> This looks allot like a duplicate of the #2019 issue to me...
> 
> ~Ibuprophen

That issue is closed for some reason. Here I the stacktrace is from an official release.

**Comment by Amirphony** [comment] 2019-09-22 08:08
> This looks allot like a duplicate of the #2019 issue to me...
> 
> ~Ibuprophen

Don't you think #2019 is allot like a duplicate of this issue?

**Comment by Amirphony** [comment] 2019-09-22 08:18
This issue still exist on `2.4.0`.

**Comment by farouk327** [comment] 2020-01-31 01:01
I have the same problem so i will try to rename  all file to *.png (removing.9) like the software  said and tell ya if it work

**Comment by MEJIOMAH17** [comment] 2020-09-13 13:39
Still actual

**Comment by iBotPeaches** [comment] 2020-11-29 03:14
None of these are valid 9patches. I'm looking at them now, so they will continue to throw warnings. Nothing we can do. They say they are 9patches, but aren't. 

There is no bug here.

**Closed by iBotPeaches** 2020-11-29 03:14 UTC

**Comment by Luiz-Monad** [comment] 2022-12-27 17:43
Is that because they are ".9"  for stupid version 9 of old compatibility tool ? then renaming to anything else will fix. Because it does break the Android Studio Tools gradle build.

**Comment by Luiz-Monad** [comment] 2022-12-27 17:51
> Is that because they are ".9" for stupid version 9 of old compatibility tool ? then renaming to anything else will fix. Because it does break the Android Studio Tools gradle build.

Never mind, I copied a working file from this, its probably not important either way, I only want the thing to recompile.
https://chromium.googlesource.com/android_tools/+/b3b75e0951a2fcb8380d5f74144ec34a654ce6b2/sdk/platforms/android-19/data/res

**Comment by GirlFurCat** [comment] 2024-10-15 08:55
How to solve it? I also encountered this problem;
W: Cant find 9patch chunk in file: "bbx.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "Ttf.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "pYC.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "be9.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "j1Q.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "LbA.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "jYV.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "o_p.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "csO.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "qCK.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "MaR.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "G96.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "oR7.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "8hc.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "Eni.9.png". Renaming it to *.png.
