### ISSUE TITLE
Apktool windows10 smali problem

### ISSUE THREAD

**Issue by ClassiCTR** [iBotPeaches/Apktool#2042] opened 2019-03-13 19:29 UTC
Apktool 2.3.1, 2.3.4, 2.4.0 Batchapktool and jbart pro
Miui10 "Settings.apk" and "Miuihome.apk" decompile. I am getting an error when doing any editing in Smali. But there's no problem doing the same thing in Linux. other apk files also have no problem.
I just write a character and delete it back. This is happening. I do not add any mode.
Please help me. Thanks

MiuiHome  error
![aa](https://user-images.githubusercontent.com/44117173/54308129-628d6280-45de-11e9-96f2-204e2a0f99c3.jpg)

Settings.apk error

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/settingslib/bluetooth/I;
 at com.android.settingslib.bluetooth.q.<init>(Unknown Source:14)
 at com.android.settingslib.bluetooth.q.ctF(Unknown Source:22)
 at com.android.settings.bluetooth.Utils.aNs(Unknown Source:2)
 at com.android.settings.bluetooth.BluetoothStatusController.<init>(Unknown Source:11)
 at com.android.settings.by.<init>(Unknown Source:74)
 at com.android.settings.SettingsFragment.boS(Unknown Source:20)
 at com.android.settings.BasePreferenceFragment.onViewCreated(Unknown Source:1)
 at com.android.settings.SettingsFragment.onViewCreated(Unknown Source:0)
 at android.app.FragmentManagerImpl.moveToState(Unknown Source:701)
 at android.app.FragmentManagerImpl.addAddedFragments(Unknown Source:43)
 at android.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:161)
 at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:110)
 at android.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
 at android.app.FragmentManagerImpl.dispatchMoveToState(Unknown Source:8)
 at android.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source:4)
 at android.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
 at android.app.Activity.performCreateCommon(Unknown Source:19)
 at android.app.Activity.performCreate(Unknown Source:11)
 at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
 at android.app.ActivityThread.performLaunchActivity(Unknown Source:466)
 at android.app.ActivityThread.handleLaunchActivity(Unknown Source:30)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(Unknown Source:80)
 at android.os.Handler.dispatchMessage(Unknown Source:21)
 at android.os.Looper.loop(Unknown Source:152)
 at android.app.ActivityThread.main(Unknown Source:68)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:203)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.settingslib.bluetooth.I" on path: DexPathList[[zip file "/system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk", zip file "/system/framework/protobuf.jar", zip file "/system/framework/gson.jar", zip file "/system/framework/zxing.jar", zip file "/system/framework/security-device-credential-sdk.jar", zip file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/system/priv-app/Settings/lib/arm64, /system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 ... 29 more

**Comment by ClassiCTR** [comment] 2019-03-16 13:14
Apk. when i do decompile i.smali and I.smali need to be. But windows i.smali is wiping
![photo5789690355837415740](https://user-images.githubusercontent.com/44117173/54475774-8206d400-4806-11e9-843b-6ccec3ad11a8.jpg)

**Comment by iBotPeaches** [comment] 2020-11-28 23:17
https://superuser.com/questions/165975/are-all-versions-of-windows-case-insensitive

Windows isn't case sensitive, so that points back to a duplicate of https://github.com/iBotPeaches/Apktool/issues/1460

**Closed by iBotPeaches** 2020-11-28 23:17 UTC
