### ISSUE TITLE
Resource identifier error "srcCompat" and "navigationContentDescription" on build without changes to APK

### ISSUE THREAD

**Issue by FawenYo** [iBotPeaches/Apktool#1883] opened 2018-08-23 13:54 UTC
### Information
1. **Apktool Version (`apktool -version`)** - v2.3.3
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a4.xml:5: error: No resource identif
ier found for attribute 'cardCornerRadius' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a4.xml:5: error: No resource identif
ier found for attribute 'cardElevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a4.xml:5: error: No resource identif
ier found for attribute 'cardUseCompatPadding' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:4: error: No resource identif
ier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:9: error: No resource identif
ier found for attribute 'tlcFooterBackground' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:9: error: No resource identif
ier found for attribute 'tlcGraphBackground' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:9: error: No resource identif
ier found for attribute 'tlcGraphMode' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:9: error: No resource identif
ier found for attribute 'tlcShowFooter' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:11: error: No resource identi
fier found for attribute 'adSize' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a5.xml:11: error: No resource identi
fier found for attribute 'adUnitId' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:4: error: No resource ide
ntifier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:9: error: No resource ide
ntifier found for attribute 'tlcFooterBackground' in package 'com.evozi.network'

W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:9: error: No resource ide
ntifier found for attribute 'tlcGraphBackground' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:9: error: No resource ide
ntifier found for attribute 'tlcGraphMode' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:9: error: No resource ide
ntifier found for attribute 'tlcShowFooter' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:11: error: No resource id
entifier found for attribute 'adSize' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a5.xml:11: error: No resource id
entifier found for attribute 'adUnitId' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a6.xml:10: error: No resource identi
fier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\a6.xml:10: error: No resource id
entifier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a7.xml:5: error: No resource identif
ier found for attribute 'headerLayout' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a7.xml:5: error: No resource identif
ier found for attribute 'menu' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a8.xml:4: error: No resource identif
ier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a8.xml:8: error: No resource identif
ier found for attribute 'layout_behavior' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a8.xml:9: error: No resource identif
ier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a8.xml:9: error: No resource identif
ier found for attribute 'layout_anchor' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a8.xml:9: error: No resource identif
ier found for attribute 'layout_anchorGravity' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a8.xml:9: error: No resource identif
ier found for attribute 'menu' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\a9.xml:4: error: No resource identif
ier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ab.xml:4: error: No resource identif
ier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ad.xml:4: error: No resource identif
ier found for attribute 'cardBackgroundColor' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ad.xml:4: error: No resource identif
ier found for attribute 'cardCornerRadius' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ad.xml:4: error: No resource identif
ier found for attribute 'cardElevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ad.xml:4: error: No resource identif
ier found for attribute 'cardUseCompatPadding' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\ad.xml:4: error: No resource ide
ntifier found for attribute 'cardBackgroundColor' in package 'com.evozi.network'

W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\ad.xml:4: error: No resource ide
ntifier found for attribute 'cardCornerRadius' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\ad.xml:4: error: No resource ide
ntifier found for attribute 'cardElevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\ad.xml:4: error: No resource ide
ntifier found for attribute 'cardUseCompatPadding' in package 'com.evozi.network
'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ae.xml:4: error: No resource identif
ier found for attribute 'elevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ae.xml:5: error: No resource identif
ier found for attribute 'popupTheme' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\af.xml:4: error: No resource identif
ier found for attribute 'cardBackgroundColor' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\af.xml:4: error: No resource identif
ier found for attribute 'cardCornerRadius' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\af.xml:4: error: No resource identif
ier found for attribute 'cardElevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\af.xml:4: error: No resource identif
ier found for attribute 'cardUseCompatPadding' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:2: error: No resource identif
ier found for attribute 'layout_behavior' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:6: error: No resource identif
ier found for attribute 'above_wave_color' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:6: error: No resource identif
ier found for attribute 'wave_height' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:6: error: No resource identif
ier found for attribute 'wave_hz' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:6: error: No resource identif
ier found for attribute 'wave_length' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:21: error: No resource identi
fier found for attribute 'adSize' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ah.xml:21: error: No resource identi
fier found for attribute 'adUnitId' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ai.xml:4: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\aj.xml:4: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ak.xml:8: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ak.xml:10: error: No resource identi
fier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\am.xml:2: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\an.xml:2: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ao.xml:2: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ap.xml:2: error: No resource identif
ier found for attribute 'cpv_colorShape' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\as.xml:6: error: No resource identif
ier found for attribute 'layout_behavior' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v16\as.xml:6: error: No resource ide
ntifier found for attribute 'layout_behavior' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\ba.xml:4: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bb.xml:4: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bd.xml:4: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bg.xml:52: error: No resource identi
fier found for attribute 'cardCornerRadius' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bg.xml:52: error: No resource identi
fier found for attribute 'cardElevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bg.xml:52: error: No resource identi
fier found for attribute 'cardUseCompatPadding' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\bg.xml:52: error: No resource id
entifier found for attribute 'cardCornerRadius' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\bg.xml:52: error: No resource id
entifier found for attribute 'cardElevation' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\bg.xml:52: error: No resource id
entifier found for attribute 'cardUseCompatPadding' in package 'com.evozi.networ
k'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bh.xml:6: error: No resource identif
ier found for attribute 'shimmer_demo_child_count' in package 'com.evozi.network
'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bh.xml:6: error: No resource identif
ier found for attribute 'shimmer_demo_layout' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bi.xml:7: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bi.xml:8: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bi.xml:9: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bl.xml:15: error: No resource identi
fier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\bl.xml:15: error: No resource id
entifier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bn.xml:5: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\bn.xml:5: error: No resource ide
ntifier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v21\bn.xml:5: error: No resource ide
ntifier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\bp.xml:4: error: No resource identif
ier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\cu.xml:2: error: No resource identif
ier found for attribute 'popupTheme' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\d.xml:2: error: No resource identifi
er found for attribute 'divider' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\d.xml:2: error: No resource identifi
er found for attribute 'dividerPadding' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\f.xml:2: error: No resource identifi
er found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v17\f.xml:2: error: No resource iden
tifier found for attribute 'srcCompat' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout\x.xml:6: error: No resource identifi
er found for attribute 'navigationContentDescription' in package 'com.evozi.netw
ork'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v21\x.xml:6: error: No resource iden
tifier found for attribute 'navigationContentDescription' in package 'com.evozi.
network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\layout-v26\x.xml:6: error: No resource iden
tifier found for attribute 'navigationContentDescription' in package 'com.evozi.
network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\animator-v21\j.xml:4: error: No resource id
entifier found for attribute 'state_liftable' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\animator-v21\j.xml:4: error: No resource id
entifier found for attribute 'state_lifted' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\xml\a.xml:14: error: No resource identifier
 found for attribute 'cpv_colorPresets' in package 'com.evozi.network'
W:
W: C:\Users\user\Desktop\nsm\nsm\res\xml\a.xml:14: error: No resource identifier
 found for attribute 'cpv_showAlphaSlider' in package 'com.evozi.network'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit
 code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_434580028892888812.t
mp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 28
, --version-code, 33, --version-name, 1.1.3, --no-version-vectors, -F, C:\Users\
user\AppData\Local\Temp\APKTOOL2052244667765593993.tmp, -0, assets/classes.dex.d
at, -0, assets/dp.arm-v7.so.dat, -0, assets/dp.arm-v8.so.dat, -0, assets/dp.arm.
so.dat, -0, assets/dp.x86.so.dat, -0, assets/dp.x86_64.so.dat, -0, arsc, -I, C:\
Users\user\AppData\Local\Temp\1.apk, -S, C:\Users\user\Desktop\nsm\nsm\res, -M,
C:\Users\user\Desktop\nsm\nsm\AndroidManifest.xml]
W: C:\Users\user\Desktop\nsm\nsm\res\xml\a.xml:14: error: No resource identifier
 found for attribute 'cpv_showColorShades' in package 'com.evozi.network'
```
(too much that I can only show these)

### Steps to Reproduce
1. `apktool d nsm.apk `
2. `apktool b nsm`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

No.

### APK
If this APK can be freely shared, please upload/attach a link to it.

From APKPure : https://apkpure.com/network-speed-monitoring-speed-meter/com.evozi.network

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2018-08-23 20:48
Thanks for the report. This is unfortunately a duplicate of an existing ticket. A form of Obfuscation paired with a malformed decoder in my 2second investigation.

#1744 is the duplicate ticket. Closing.

**Closed by iBotPeaches** 2018-08-23 20:48 UTC
