### ISSUE TITLE
[BUG] apktool 2.6.1 unsupported res type name for bags. Found: style2

### ISSUE THREAD

**Issue by ajinabraham** [iBotPeaches/Apktool#2842] opened 2022-06-29 16:17 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - macOS 12.4
3. **APK From? (Playstore, ROM, Other)** - [APKPure](https://m.apkpure.com/de/facebook/com.facebook.katana)

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
	at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:115)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:356)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:70)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)

```

```
java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
```

### Steps to Reproduce

```bash
java -jar /tmp/apktool_2.6.1.jar --match-original --frame-path /var/folders/l3/d2gvmj691zbdjzjjgx59ghdw0000gp/T -f -s d /tmp/com.facebook.katana.apk -o /tmp/apktool_out
```

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://m.apkpure.com/de/facebook/com.facebook.katana

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - This is the command that MobSF runs on all APKs
2. If you are trying to install a modified apk, did you resign it? - Not a modified APK
3. Are you using the latest apktool version? - Yes, as of today

**Comment by UwUeeb** [comment] 2022-06-29 22:26
similar to #1719

**Comment by iBotPeaches** [comment] 2022-07-03 10:43
As mentioned above - an existing issue for this. It seems to be an interesting technique of duplicating res types in a sparse packed arsc.

Marking as duplicate of #1719

**Closed by iBotPeaches** 2022-07-03 10:43 UTC
