### ISSUE TITLE
apktool build fails at compiling resource files

### ISSUE THREAD

**Issue by nderkach** [iBotPeaches/Apktool#983] opened 2015-06-30 05:03 UTC
I'm trying to decompile and compile the following APK with debug symbols: https://dl.dropboxusercontent.com/u/5017232/Ticketmaster_1.6.4.1_30-orig.apk

    ./apktool d -d -f Ticketmaster_1.6.4.1_30-orig.apk -o out
    ./apktool b -d out -o Ticketmaster_1.6.4.1_30-new.apk

I'm using the latest apktool 2.0.0 with JDK 8. I'm running with the following issues when trying to build the apt back:

    I: Using Apktool 2.0.0
	I: Checking whether sources has changed...
	I: Smaling smali folder into classes.dex...
	I: Checking whether sources has changed...
	I: Smaling smali_classes10 folder into classes10.dex...
	I: Checking whether sources has changed...
	I: Smaling smali_classes2 folder into classes2.dex...
	I: Checking whether sources has changed...
	I: Smaling smali_classes5 folder into classes5.dex...
	I: Checking whether sources has changed...
	I: Smaling smali_classes8 folder into classes8.dex...
	I: Checking whether sources has changed...
	I: Smaling smali_classes9 folder into classes9.dex...
	I: Checking whether resources has changed...
	I: Building resources...
	/Users/nderkach/Desktop/ticketmaster/out/res/layout/activity_bootscreen.xml:9: error: No resource identifier found for attribute 'insetForeground' in package 'android'

	/Users/nderkach/Desktop/ticketmaster/out/res/layout-v21/activity_bootscreen.xml:9: error: No resource identifier found for attribute 'insetForeground' in package 'android'

	/Users/nderkach/Desktop/ticketmaster/out/res/layout/adu_walkthrough_activity.xml:6: error: No resource identifier found for attribute 'pageColor' in package 'android'

	/Users/nderkach/Desktop/ticketmaster/out/res/layout/edp_combined_activity.xml:7: error: No resource identifier found for attribute 'pstsIndicatorColor' in package 'android'

	/Users/nderkach/Desktop/ticketmaster/out/res/layout/horizontal_ticket_recto.xml:6: error: No resource identifier found for attribute 'labelStyle' in package 'android'

	/Users/nderkach/Desktop/ticketmaster/out/res/layout/horizontal_ticket_recto.xml:6: error: No resource identifier found for attribute 'valueStyle' in package 'android'

	/Users/nderkach/Desktop/ticketmaster/out/res/layout/tm_activity_integrated_listings.xml:34: error: Error: Integer types not allowed (at 'orientation' with value '1').

	Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/nc/9y2gpgzs1gz4wg9mp3spyfnm0000gn/T/brut_util_Jar_6348033727496735282.tmp, p, --debug-mode, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 30, --version-name, 1.6.4.1, -F, /var/folders/nc/9y2gpgzs1gz4wg9mp3spyfnm0000gn/T/APKTOOL6979768093236566769.tmp, -0, arsc, -I, /Users/nderkach/Library/apktool/framework/1.apk, -S, /Users/nderkach/Desktop/ticketmaster/out/res, -M, /Users/nderkach/Desktop/ticketmaster/out/AndroidManifest.xml]
		at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
		at brut.androlib.Androlib.buildResources(Androlib.java:396)
		at brut.androlib.Androlib.build(Androlib.java:285)
		at brut.androlib.Androlib.build(Androlib.java:256)
		at brut.apktool.Main.cmdBuild(Main.java:225)
		at brut.apktool.Main.main(Main.java:84)
	Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/nc/9y2gpgzs1gz4wg9mp3spyfnm0000gn/T/brut_util_Jar_6348033727496735282.tmp, p, --debug-mode, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 30, --version-name, 1.6.4.1, -F, /var/folders/nc/9y2gpgzs1gz4wg9mp3spyfnm0000gn/T/APKTOOL6979768093236566769.tmp, -0, arsc, -I, /Users/nderkach/Library/apktool/framework/1.apk, -S, /Users/nderkach/Desktop/ticketmaster/out/res, -M, /Users/nderkach/Desktop/ticketmaster/out/AndroidManifest.xml]
		at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
		at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
		... 5 more
	Caused by: brut.common.BrutException: could not exec command: [/var/folders/nc/9y2gpgzs1gz4wg9mp3spyfnm0000gn/T/brut_util_Jar_6348033727496735282.tmp, p, --debug-mode, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 30, --version-name, 1.6.4.1, -F, /var/folders/nc/9y2gpgzs1gz4wg9mp3spyfnm0000gn/T/APKTOOL6979768093236566769.tmp, -0, arsc, -I, /Users/nderkach/Library/apktool/framework/1.apk, -S, /Users/nderkach/Desktop/ticketmaster/out/res, -M, /Users/nderkach/Desktop/ticketmaster/out/AndroidManifest.xml]
		at brut.util.OS.exec(OS.java:89)
		at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
		... 6 more

I've tried to do the same without compiling and decompiling resource files, but then I run into an issue with ```[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog```

**Comment by iBotPeaches** [comment] 2015-07-09 12:01
It appears custom attributes (or rather attributes from a library), in this case `com.android.support:design:22.2.0` are having troubles being decoded.

**Comment by bootstraponline** [comment] 2015-07-27 21:30
> [Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog

I'm running into this as well. Why is AndroidManifest.xml even parsed if `--no-res` is set?

**Comment by IgorGanapolsky** [comment] 2015-08-10 21:47
I have the same issue.  Is there a solution?

**Comment by paericksen** [comment] 2015-10-19 17:16
I am running into this issue as well.

**Comment by ltoad** [comment] 2015-10-27 08:48
i have same issue 

dex file compile success but ....  Building resources...  step error


I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
W: Unknown file type, ignoring: kat/smali/.DS_Store
W: Unknown file type, ignoring: kat/smali/android/.DS_Store
W: Unknown file type, ignoring: kat/smali/android/opengl/.DS_Store
I: Checking whether resources has changed...
I: Building resources...
warning: string 'body_for_snapshot_friends_email' has no default translation.
warning: string 'cover_date_format' has no default translation.
warning: string 'desc_for_emoticon_download' has no default translation.


.
. 
.


/Users/toto/Desktop/mobile/kat_1/res/layout-ldrtl-v17/vox_voice_activity.xml:76: error: No resource identifier found for attribute 'bg_type' in package 'android'

/Users/toto/Desktop/mobile/kat_1/res/layout-ldrtl-v17/vox_voice_activity.xml:84: error: No resource identifier found for attribute 'bg_type' in package 'android'

/Users/toto/Desktop/mobile/kat_1/res/layout-ldrtl-v17/vox_voice_activity.xml:92: error: No resource identifier found for attribute 'bg_type' in package 'android'

/Users/toto/Desktop/mobile/kat_1/res/layout/walkietalkie_layout.xml:5: error: No resource identifier found for attribute 'thm_background' in package 'android'

/Users/toto/Desktop/mobile/kat_1/res/layout/walkietalkie_layout.xml:9: error: No resource identifier found for attribute 'thm_textColor' in package 'android'

/Users/toto/Desktop/mobile/kat_1/res/layout-ldrtl-v17/walkietalkie_layout.xml:5: error: No resource identifier found for attribute 'thm_background' in package 'android'

/Users/toto/Desktop/mobile/kat_1/res/layout-ldrtl-v17/walkietalkie_layout.xml:9: error: No resource identifier found for attribute 'thm_textColor' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/pq/1z00kxtn2yv3x6tf5t7_84y40000gn/T/brut_util_Jar_3636030068287513085.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 1400205, --version-name, 5.1.4, -F, /var/folders/pq/1z00kxtn2yv3x6tf5t7_84y40000gn/T/APKTOOL1705594288349679015.tmp, -0, resources.arsc, -0, assets/katEffects-Android.zip, -0, arsc, -I, /Users/toto/Library/apktool/framework/1.apk, -S, /Users/toto/Desktop/mobile/kat_1/res, -M, /Users/toto/Desktop/mobile/kat_1/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
	at brut.androlib.Androlib.buildResources(Androlib.java:403)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could Not

**Comment by jiaoyigui** [comment] 2015-12-17 03:41
i have same issue
dex file compile success but .... Building resources... step error

```
jiaoyigui-2:Downloads jiaoyigui$ apktool b hello
I: Using Apktool 2.0.3-831765-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
/Users/jiaoyigui/Downloads/hello/res/values-v23/styles.xml:5: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/AlertDialog'.

/Users/jiaoyigui/Downloads/hello/res/values-v23/styles.xml:6: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/DialogWindowTitle'.

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/f1/kw9g28fn2dsb2_kwsj4y19nr0000gn/T/brut_util_Jar_686373888929815871.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 22, --version-code, 450825, --version-name, 2.12.374, -F, /var/folders/f1/kw9g28fn2dsb2_kwsj4y19nr0000gn/T/APKTOOL8887438693574401727.tmp, -0, arsc, -0, arsc, -I, /Users/jiaoyigui/Library/apktool/framework/1.apk, -S, /Users/jiaoyigui/Downloads/hello/res, -M, /Users/jiaoyigui/Downloads/hello/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
	at brut.androlib.Androlib.buildResources(Androlib.java:410)
	at brut.androlib.Androlib.build(Androlib.java:298)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/f1/kw9g28fn2dsb2_kwsj4y19nr0000gn/T/brut_util_Jar_686373888929815871.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 22, --version-code, 450825, --version-name, 2.12.374, -F, /var/folders/f1/kw9g28fn2dsb2_kwsj4y19nr0000gn/T/APKTOOL8887438693574401727.tmp, -0, arsc, -0, arsc, -I, /Users/jiaoyigui/Library/apktool/framework/1.apk, -S, /Users/jiaoyigui/Downloads/hello/res, -M, /Users/jiaoyigui/Downloads/hello/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/var/folders/f1/kw9g28fn2dsb2_kwsj4y19nr0000gn/T/brut_util_Jar_686373888929815871.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 22, --version-code, 450825, --version-name, 2.12.374, -F, /var/folders/f1/kw9g28fn2dsb2_kwsj4y19nr0000gn/T/APKTOOL8887438693574401727.tmp, -0, arsc, -0, arsc, -I, /Users/jiaoyigui/Library/apktool/framework/1.apk, -S, /Users/jiaoyigui/Downloads/hello/res, -M, /Users/jiaoyigui/Downloads/hello/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
```

and my resources is changed. How can I recompile it?

**Comment by iBotPeaches** [comment] 2016-02-04 01:34
Closing in favour of #1157

**Closed by iBotPeaches** 2016-02-04 01:34 UTC
Labels: bug

**Comment by catenatedgoose** [comment] 2019-04-21 05:19
i wrote an auotmated bash script to fix this issue 

https://github.com/catenatedgoose?tab=repositories

https://www.youtube.com/watch?v=kB6s10Uwpcs
