### ISSUE TITLE
Newline character in Strings.xml is removed in decompiled resource file

### ISSUE THREAD

**Issue by vkslabs** [iBotPeaches/Apktool#1749] opened 2018-03-19 15:54 UTC
### Information
1. Apktool Version (apktool -version) - **2.3.1** 
2. Operating System (Mac, Linux, Windows) - **Mac** 
3. **Any APK** 

### Steps to Reproduce
1. `apktool d apkname.apk`

### Questions to ask before submission
If my application has strings.xml with strings containing \n, after decompiling the strings.xml is missing \n and hence the UI is kind of messed up.

**Comment by ibuprophen1** [comment] 2018-06-26 18:08
@vkslabs, Has this issue been resolved using either of the more recent releases of the Apktool since this was happening using v2.3.1?

If it's been resolved, you can close this issue... 

If not, please try to provide the additional information needed (like the Logs and such) using the most recent release of the Apktool. 

Thank you very much! :-) 


~Ibuprophen

**Comment by iBotPeaches** [comment] 2020-11-29 14:55
Marking as duplicate of https://github.com/iBotPeaches/Apktool/issues/1168

**Closed by iBotPeaches** 2020-11-29 14:55 UTC
