### ISSUE TITLE
[EXCEPTION] Error installing framework-res.apk

### ISSUE THREAD

**Issue by quadraticfunction** [iBotPeaches/Apktool#2951] opened 2022-11-22 21:06 UTC
Sorry I forgot the template, will update in a sec

Hi, I've tried to decompile Samsung's system apps from Android 13 using both apktool 2.6.1 and 2.5.0 but it throws this exception when installing the framework-res:

```
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000206
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:549)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:90)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:42)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:879)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:861)
	at brut.androlib.Androlib.installFramework(Androlib.java:741)
	at brut.apktool.Main.cmdInstallFramework(Main.java:273)
	at brut.apktool.Main.main(Main.java:85)
```

What can I do against this?

**Comment by iBotPeaches** [comment] 2022-11-22 21:12
Wait for 2.6.2. I believe it resolves the unknown chunk type, which is overlays.

Duplicate of https://github.com/iBotPeaches/Apktool/issues/2740

**Closed by iBotPeaches** 2022-11-22 21:12 UTC
