### ISSUE TITLE
ApkTool Building error

### ISSUE THREAD

**Issue by TheGeekdu74** [iBotPeaches/Apktool#1092] opened 2015-11-27 18:57 UTC
When I try to recompile the apk, I have this issue (File name or extension too long) : 

http://pastebin.com/eX7Uxhgx

'out' is the name of the folder where are the files of the APK
PS : I'm french, so it's a french CMD...

EDIT : my gradlew.bat doesn't work properly, I have an error : 

http://pastebin.com/6TeT5kwR

**Comment by osamaalboss** [comment] 2015-11-28 00:30
I can decompile apps but for stock rom I can't recompile coz I cant find sources or classes.dex

**Comment by iBotPeaches** [comment] 2015-11-28 04:09
First issue is a duplicate of #1053 which was fixed already for the upcoming 2.0.3 version. The second issue is also a duplicate of #1076

**Closed by iBotPeaches** 2015-11-28 04:09 UTC
Labels: duplicate
