### ISSUE TITLE
'Could not decode attr value' - Google Maps v.9.60+

### ISSUE THREAD

**Issue by PerLycke** [iBotPeaches/Apktool#1646] opened 2017-10-21 17:46 UTC
### Information
1. 2.3.1-3ec4f3-SNAPSHOT
2. Mac
3. Play Store

### Stacktrace/Logcat

```
I: Using Apktool 2.3.1-3ec4f3-SNAPSHOT on maps_new.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/per/Library/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120147
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=roundIcon, value=0x7f030024
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f090007
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f090000
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f090005
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03000b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f02070c
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f020492
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0201e6
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120215
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014e
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f120147
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014c
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f090001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120117
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120117
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120141
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12011a
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12011a
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120141
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120116
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120116
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12011b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12011b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12013e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12013e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12013f
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12013f
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120143
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12001b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f120288
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f0f000b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03000f
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f12014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f03000d
I: Renamed manifest package found! Replacing com.google.android.apps.maps with FFFFFFFFFFFFFFFFFFFFFF
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

### Steps to Reproduce
1. `apktool d Maps.apk`

**Comment by feinstein** [comment] 2017-10-25 03:45
I have the same issue, would love to know how to fix this as well.

**Comment by iBotPeaches** [comment] 2017-11-01 20:11
Duplicate of #1471 , I apologize I am still digging into the solution/patch for this issue.

**Closed by iBotPeaches** 2017-11-01 20:11 UTC
