### ISSUE TITLE
 FATAL EXCEPTION: RxCachedThreadScheduler-1 when running rebuild apk

### ISSUE THREAD

**Issue by RobertRBT** [iBotPeaches/Apktool#2191] opened 2019-10-05 10:29 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Apk4Fun

### Stacktrace/Logcat

```
2019-10-05 12:21:49.091 31863-31930/io.faceapp E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: io.faceapp, PID: 31863
    CMa: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | eRa: null cannot be cast to non-null type java.lang.String
        at EQa.b(RxJavaPlugins.java:8)
        at cQa.run(ScheduledRunnable.java:3)
        at cQa.call(ScheduledRunnable.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: eRa: null cannot be cast to non-null type java.lang.String
```

### Steps to Reproduce
1. `apktool  d io.faceapp-3.4.12.2@APK4Fun.com.apk`
2. `apktool b io.faceapp-3.4.12.2@APK4Fun.com`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by bphown** [comment] 2019-10-05 13:11
Also there is a different error when testing on android 8:

```
2019-10-05 14:53:45.400 24492-24492/? W/ChimeraUtils: Non Chimera context
2019-10-05 14:53:45.400 24492-24492/? W/ChimeraUtils: Non Chimera context
2019-10-05 14:53:45.426 1154-1166/? D/Debug: !@DumpState : SHIP
2019-10-05 14:53:45.426 1154-1166/? D/Debug: !@DumpState : debug level:0x4f4c
2019-10-05 14:53:45.426 1154-1166/? D/Debug: !@Dumpstate : Finally, system will skip dumpstate
2019-10-05 14:53:45.427 1154-1166/? W/ActivityManager: crash : io.faceapp,0
2019-10-05 14:53:45.429 1154-1166/? W/ActivityManager:   Force finishing activity io.faceapp/.MainActivity
2019-10-05 14:53:45.433 1154-1166/? I/ActivityManager: KPU : put [com.instagram.android:videoplayer] : 21802 K
2019-10-05 14:53:45.433 1154-1166/? I/ActivityManager: Killing 6144:com.instagram.android:videoplayer/u0a193 (adj 906): DHA:empty #33
2019-10-05 14:53:45.438 1154-1327/? W/Choreographer: Frame time is 17.389784 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2019-10-05 14:53:45.448 1154-1207/? I/ActivityManager: Showing crash dialog for package io.faceapp u0
2019-10-05 14:53:45.452 6770-6770/? D/ViewRootImpl@6b39fc9[MainActivity]: dispatchDetachedFromWindow
2019-10-05 14:53:45.453 6770-6770/? D/InputEventReceiver: channel '1c1c5d4 io.faceapp/io.faceapp.MainActivity (client)' ~ Disposing input event receiver.
2019-10-05 14:53:45.453 6770-6770/? D/InputEventReceiver: channel '1c1c5d4 io.faceapp/io.faceapp.MainActivity (client)' ~NativeInputEventReceiver.
2019-10-05 14:53:45.454 1175-1175/? I/DMT-SMReceiver: Received : com.samsung.android.sm.ACTION_ERROR
2019-10-05 14:53:45.459 1175-1175/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1545 android.content.ContextWrapper.startService:669 android.content.ContextWrapper.startService:669 com.samsung.android.sm.common.SmartManagerReceiver.a:237 com.samsung.android.sm.common.SmartManagerReceiver.onReceive:116 
2019-10-05 14:53:45.460 1154-4607/? D/InputTransport: Input channel destroyed: fd=474
2019-10-05 14:53:45.462 6770-6770/? D/InputTransport: Input channel destroyed: fd=130
2019-10-05 14:53:45.466 24492-24506/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-10-05 14:53:45.466 24492-24506/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
```

**Comment by iBotPeaches** [comment] 2019-10-06 09:26
So it sounds like you are saying Apktool changed something that ended up forcing a variable to be null, when it should be not-null.

This could be a multitude of things, which may just be anti-tamper protections.

**Comment by bphown** [comment] 2019-10-08 10:51
@iBotPeaches The error on android 8 is completely different, i've no idea if the cause is the same.

**Comment by iBotPeaches** [comment] 2020-11-28 22:08
Going to chuck this up to magic applications, anti-tamper, etc. 

Apktool isn't doing anything knowingly here and a year later with this ticket I don't have an application to triage. Closing.

**Closed by iBotPeaches** 2020-11-28 22:08 UTC
