### ISSUE TITLE
No resource found that matches the given name [xxxxxxxxxxx]

### ISSUE THREAD

**Issue by Zane96** [iBotPeaches/Apktool#1686] opened 2017-12-12 08:37 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
 ✘ Zane@Hello-World  ~/programming/reverse  java -jar apktool.jar d /Users/Zane/programming/reverse/kcp/kc-raw.apk
I: Using Apktool 2.3.0 on kc-raw.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/Zane/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
 Zane@Hello-World  ~/programming/reverse  java -jar apktool.jar b /Users/Zane/programming/reverse/kc-raw
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
W: Unknown file type, ignoring: /Users/Zane/programming/reverse/kc-raw/smali_classes2/.DS_Store
W: Unknown file type, ignoring: /Users/Zane/programming/reverse/kc-raw/smali_classes2/com/.DS_Store
W: Unknown file type, ignoring: /Users/Zane/programming/reverse/kc-raw/smali_classes2/com/xuanke/.DS_Store
W: Unknown file type, ignoring: /Users/Zane/programming/reverse/kc-raw/smali_classes2/com/xuanke/kaochong/.DS_Store
W: Unknown file type, ignoring: /Users/Zane/programming/reverse/kc-raw/smali_classes2/com/xuanke/kaochong/lesson/.DS_Store
W: Unknown file type, ignoring: /Users/Zane/programming/reverse/kc-raw/smali_classes2/com/xuanke/kaochong/lesson/download/.DS_Store
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/Zane/programming/reverse/kc-raw/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: /Users/Zane/programming/reverse/kc-raw/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/n4/0d_pjdqd0lg1zd9jfjz98hj00000gn/T/brut_util_Jar_896544294338367806.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1950, --version-name, 1.9.5, --no-version-vectors, -F, /var/folders/n4/0d_pjdqd0lg1zd9jfjz98hj00000gn/T/APKTOOL6669464971872187696.tmp, -0, arsc, -0, arsc, -I, /Users/Zane/Library/apktool/framework/1.apk, -S, /Users/Zane/programming/reverse/kc-raw/res, -M, /Users/Zane/programming/reverse/kc-raw/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/n4/0d_pjdqd0lg1zd9jfjz98hj00000gn/T/brut_util_Jar_896544294338367806.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1950, --version-name, 1.9.5, --no-version-vectors, -F, /var/folders/n4/0d_pjdqd0lg1zd9jfjz98hj00000gn/T/APKTOOL6669464971872187696.tmp, -0, arsc, -0, arsc, -I, /Users/Zane/Library/apktool/framework/1.apk, -S, /Users/Zane/programming/reverse/kc-raw/res, -M, /Users/Zane/programming/reverse/kc-raw/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/n4/0d_pjdqd0lg1zd9jfjz98hj00000gn/T/brut_util_Jar_896544294338367806.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1950, --version-name, 1.9.5, --no-version-vectors, -F, /var/folders/n4/0d_pjdqd0lg1zd9jfjz98hj00000gn/T/APKTOOL6669464971872187696.tmp, -0, arsc, -0, arsc, -I, /Users/Zane/Library/apktool/framework/1.apk, -S, /Users/Zane/programming/reverse/kc-raw/res, -M, /Users/Zane/programming/reverse/kc-raw/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
no

### APK
https://www.kaochong.com/app.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  yes
2. If you are trying to install a modified apk, did you resign it?  no
3. Are you using the latest apktool version? yes

**Comment by Zane96** [comment] 2017-12-12 08:39
It seems 
W: /Users/Zane/programming/reverse/kc-raw/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: /Users/Zane/programming/reverse/kc-raw/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
is the reason to failed

**Comment by devbazilio** [comment] 2017-12-16 15:48
I got same error for this apk (used apktool 2.3.0) - https://apk-dl.com/com.ftband.mono

```
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:10: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:11: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:12: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:13: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:14: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:15: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:16: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:17: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:18: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:19: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: D:\tools\android\com.ftband.mono\res\drawable-anydpi-v21\logo_bank.xml:21: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\usr\AppData\Local\Temp\brut_util_Jar_36121318912
49966424.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 27, --version-code, 257, --version-name, 1.9.3-mono, --no-version-vectors, -F, C:\Users\usr\AppData\Local\Temp\APKTOOL9016
836727812789424.tmp, -0, arsc, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/
raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_et
c_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_g
mtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/jo
da_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, C:\Users\usr\AppD
ata\Local\apktool\framework\1.apk, -S, D:\tools\android\com.ftband.mono\res, -M, D:\tools\android\com.ftband.mono\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
        at brut.androlib.Androlib.buildResources(Androlib.java:419)
        at brut.androlib.Androlib.build(Androlib.java:318)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\usr\AppData\Local\Temp\brut_util_Jar_3612131891249966424.tmp, p, --forced-package-id, 127, --min-
sdk-version, 19, --target-sdk-version, 27, --version-code, 257, --version-name, 1.9.3-mono, --no-version-vectors, -F, C:\Users\usr\AppData\Local\Temp\APKTOOL9016836727812789424.tmp, -0, arsc, -0, res/raw/joda_a
tlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13,
 -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/
joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/
raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -
0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, C:\Users\usr\AppData\Local\apktool\framework\1.apk, -S, D:\usr\Cra
cking\tools\android\com.ftband.mono\res, -M, D:\tools\android\com.ftband.mono\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\usr\AppData\Local\Temp\brut_util_Jar_3612131891249966424.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-ver
sion, 27, --version-code, 257, --version-name, 1.9.3-mono, --no-version-vectors, -F, C:\Users\usr\AppData\Local\Temp\APKTOOL9016836727812789424.tmp, -0, arsc, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/jo
da_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0,
 res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_
etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/ra
w/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/
raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, C:\Users\usr\AppData\Local\apktool\framework\1.apk, -S, D:\tools\android\com.ftband.mo
no\res, -M, D:\tools\android\com.ftband.mono\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
        ... 6 more
```

**Comment by ftyszyx** [comment] 2017-12-20 10:16
same issue

**Comment by renkchina** [comment] 2018-01-09 08:38
error: No resource identifier found for attribute 'layout_heightPercent' in package 'com.xxx'
error: No resource identifier found for attribute 'layout_marginTopPercent' in package 'com.xxx'
error: No resource identifier found for attribute 'sl_cornerRadius' in package 'com.xxx'
error: No resource identifier found for attribute 'showAsAction' in package 'com.xxx'

The compilation cannot find the resource id.

**Comment by jarkeet** [comment] 2018-01-17 14:07
same issue in macos Sierra 10.13.2
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/res/values-v24/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/res/values-v24/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/7k/992nczpn553bb9tvzbz6nkw00000gn/T/brut_util_Jar_6882967188385146246.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 1, --version-name, 2.5.1, --no-version-vectors, -F, /var/folders/7k/992nczpn553bb9tvzbz6nkw00000gn/T/APKTOOL7916495108515266448.tmp, -0, arsc, -0, arsc, -I, /Users/jeff/Library/apktool/framework/1.apk, -S, /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/res, -M, /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/7k/992nczpn553bb9tvzbz6nkw00000gn/T/brut_util_Jar_6882967188385146246.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 1, --version-name, 2.5.1, --no-version-vectors, -F, /var/folders/7k/992nczpn553bb9tvzbz6nkw00000gn/T/APKTOOL7916495108515266448.tmp, -0, arsc, -0, arsc, -I, /Users/jeff/Library/apktool/framework/1.apk, -S, /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/res, -M, /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/7k/992nczpn553bb9tvzbz6nkw00000gn/T/brut_util_Jar_6882967188385146246.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 1, --version-name, 2.5.1, --no-version-vectors, -F, /var/folders/7k/992nczpn553bb9tvzbz6nkw00000gn/T/APKTOOL7916495108515266448.tmp, -0, arsc, -0, arsc, -I, /Users/jeff/Library/apktool/framework/1.apk, -S, /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/res, -M, /Users/jeff/Desktop/rebuild/anhuiDebug-2.5.1_2018-01-17/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more

**Comment by action7777** [comment] 2018-02-15 17:47
same issue with Apktool 2.3.1 on mac os 10.9.5

**Comment by BiteFoo** [comment] 2018-03-13 06:59
same issue with apktool 2.3.0 and apktool 2.3.1  on windows 10

\java\.\11\res\menu\g.xml:5: error: No resource identifier found for attribute 'showAsAction' in package 'com.financial.quantgroup'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\John.Lu\AppData\Local\Temp\brut_util_Jar_4198053875533240000.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 6365, --version-name, 6.3.65, --no-version-vectors, -F, C:\Users\John.Lu\AppData\Local\Temp\APKTOOL1127730790915739308.tmp, -0, assets/meta-channel-inf/meta_info, -0, zip, -0, arsc, -I, C:\Users\John.Lu\AppData\Local\apktool\framework\1.apk, -S, D:\PythonWork\autosmaliwork\java\.\11\res, -M, D:\PythonWork\autosmaliwork\java\.\11\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\John.Lu\AppData\Local\Temp\brut_util_Jar_4198053875533240000.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 6365, --version-name, 6.3.65, --no-version-vectors, -F, C:\Users\John.Lu\AppData\Local\Temp\APKTOOL1127730790915739308.tmp, -0, assets/meta-channel-inf/meta_info, -0, zip, -0, arsc, -I, C:\Users\John.Lu\AppData\Local\apktool\framework\1.apk, -S, D:\PythonWork\autosmaliwork\java\.\11\res, -M, D:\PythonWork\autosmaliwork\java\.\11\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\John.Lu\AppData\Local\Temp\brut_util_Jar_4198053875533240000.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 6365, --version-name, 6.3.65, --no-version-vectors, -F, C:\Users\John.Lu\AppData\Local\Temp\APKTOOL1127730790915739308.tmp, -0, assets/meta-channel-inf/meta_info, -0, zip, -0, arsc, -I, C:\Users\John.Lu\AppData\Local\apktool\framework\1.apk, -S, D:\PythonWork\autosmaliwork\java\.\11\res, -M, D:\PythonWork\autosmaliwork\java\.\11\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more

**Comment by nottoobad** [comment] 2019-03-27 08:40
Any updates?

**Comment by iBotPeaches** [comment] 2020-11-29 15:03
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/1955

**Closed by iBotPeaches** 2020-11-29 15:03 UTC
