### ISSUE TITLE
Could not decode file, replacing by FALSE value

### ISSUE THREAD

**Issue by VirtualPointer** [iBotPeaches/Apktool#1771] opened 2018-04-13 10:59 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.2
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Other (Facebook Messenger v161 from en.uptodown.com)

### Stacktrace/Logcat

```
C:\apktool>apktool d -s "Messenger v161.1.0.22.97.apk"
I: Using Apktool 2.3.2 on Messenger v161.1.0.22.97.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\---\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: e5f.png
S: Could not decode file, replacing by FALSE value: d5_.png
S: Could not decode file, replacing by FALSE value: eqe.png
S: Could not decode file, replacing by FALSE value: hu6.png
S: Could not decode file, replacing by FALSE value: c43.png
................
................
S: Could not decode file, replacing by FALSE value: dl8.png
S: Could not decode file, replacing by FALSE value: vt.png
S: Could not decode file, replacing by FALSE value: eb7.m4a
.................................
```

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment] 2018-04-13 12:44
Yep, newest suite of Facebook apps use a modified/custom version of AndResGuard. Duplicate of #1719

**Closed by iBotPeaches** 2018-04-13 12:44 UTC

**Comment by VirtualPointer** [comment] 2018-04-13 15:15
so, there is no way to decode it?

**Comment by iBotPeaches** [comment] 2018-04-13 15:18
I didn't say anything about decoding. I simply closed this ticket as a duplicate. You'll find more information in the linked issue.

**Comment by VirtualPointer** [comment] 2018-04-13 16:05
I have read everything from the Issue #1719. my question is, is there any way to decode & rebuild it properly in current version of apktool? if not, will it be possible in future version?

**Comment by iBotPeaches** [comment] 2018-04-13 16:08
>  is there any way to decode & rebuild it properly in current version of apktool?

No

> If not, will it be possible in future version?

I don't know, you may follow some work in #1724 or contribute any fixes you discover yourself.
