### ISSUE TITLE
webview.apk: Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by rickmacgillis** [iBotPeaches/Apktool#2233] opened 2019-11-19 19:20 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1-661f92-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Kali Linux and Linux Mint
3. **APK From? (Playstore, ROM, Other)** - See below.

### Originally I posted this to issue #2117 as it's similar, but it didn't get addressed.

Unfortunately that fix didn't completely fix the issue. I'm working on setting up a dev toolchain for pentesting Android apps, and this is what I get when I use the Facebook APK for the test subject since it gets updated frequently.

```
root@kali:~/Downloads/APK# apktool -f d Facebook.apk
I: Using Apktool 2.4.1-661f92-SNAPSHOT on Facebook.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
	at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:119)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:750)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
```
If this topic seems more like a new issue, please let me know and I'll create a new ticket.

BTW, I compiled the latest source from the master repo just minutes ago.

EDIT: Updating the [latest version of WebView](https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-79-0-3945-36-release/android-system-webview-79-0-3945-36-2-android-apk-download/) results in the following issue.

```
root@kali:~/Downloads/APK# apktool d webview.apk
I: Using Apktool 2.4.1-661f92-SNAPSHOT on webview.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Writer.write(Writer.java:249)
	at org.xmlpull.renamed.MXSerializer.attribute(MXSerializer.java:631)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:84)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:121)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
```

**Comment by iBotPeaches** [comment] 2019-11-20 12:36
The first crash is a dupe of #2193, the 2nd I haven't seen before.

**Comment by iBotPeaches** [comment] 2020-11-28 22:01
The 2nd crash is because of first crash. System can't seem to handle these new types of resource types (duplicate of known types)

Will merge into #2193 and triage both there.

**Closed by iBotPeaches** 2020-11-28 22:01 UTC

**Comment by Lerie82** [comment] 2020-12-15 05:19
(running Ubuntu 16.04.7 LTS...)

When I got this error, I ran it like this...
`sudo java -jar apktool d -f file_name.apk`

and it ran just fine.
