### ISSUE TITLE
Unable to build framework-res in v2.3.3 and later

### ISSUE THREAD

**Issue by Magendanz** [iBotPeaches/Apktool#1935] opened 2018-11-11 09:27 UTC
### Information
1. **Apktool Version (`apktool -version`)** - v2.3.3 and later
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Amlogic SDK 7.1.2

### Stacktrace/Logcat
[apktool-2.3.3.log](https://github.com/iBotPeaches/Apktool/files/2569203/apktool-2.3.3.log)

```
Include stacktrace here
```

### Steps to Reproduce
1. apktool d -s .\framework-res.apk
2. apktool b .\framework-res\

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/2569205/framework-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? tried both v2.3.3 and v2.3.4 (v2.3.2 works fine)

**Comment by iBotPeaches** [comment] 2018-11-19 15:52
This is a known issue with no planned fix. It was attempted at one point and backfired. A limitation of Windows sadly.

What happens is the executed command exceeds the length allowed for Windows. Lots of details and explanations, if curious are here - https://github.com/iBotPeaches/Apktool/issues/1272

Marking as duplicate of #1272

**Closed by iBotPeaches** 2018-11-19 15:52 UTC

**Comment by Magendanz** [comment] 2018-11-19 20:03
I was actually running apktool from PowerShell.  Would that have the same 8K limitation as cmd.exe?

**Comment by Magendanz** [comment] 2018-12-19 04:36
So, if this is a limitation of Windows, why is Apktool 2.3.2 still working fine?

**Comment by Magendanz** [comment] 2019-07-04 19:29
If this is due to a command line limit for Windows, I'm surprised that I'm seeing the same issue now in Ubuntu.  Up until now, I've just been sticking with 2.3.2 to work around the problem, but with Pie I simply can't do that anymore.

Has anyone come up with a workaround?

**Comment by Magendanz** [comment] 2019-07-04 19:41
@iBotPeaches, are you sure this is a dupe of #1272?  Isn't the command line limit in Linux 2,097,152?  (At least, that's what I get from 'getconf ARG_MAX'.)  And #1272 seems to predate changes introduced in v2.3.3.

**Comment by Magendanz** [comment] 2019-07-04 19:51
Here's a log from 2.4.0 running on framework-res.apk from the latest AOSP 9.0.  Looks very similar, right?

[apktool-2.4.0-Linux.log](https://github.com/iBotPeaches/Apktool/files/3360364/apktool-2.4.0-Linux.log)
