### ISSUE TITLE
No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android' 

### ISSUE THREAD

**Issue by PNPL** [iBotPeaches/Apktool#1951] opened 2018-12-01 09:41 UTC
### Information
1. **Apktool Version (`apktool -2.3.4`)** -
2. **Operating System (Linux)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

$ apktool b /root/original
```
I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /root/original/AndroidManifest.xml:2: error: No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_12295376079311074178.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 28, --version-code, 121, --version-name, 1.0.3, --no-version-vectors, -F, /tmp/APKTOOL2601075435284485134.tmp, -0, arsc, -0, resource, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/original/res, -M, /root/original/AndroidManifest.xml]
Include stacktrace here
```
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes I've tried apktool d and then when i tried apktool b then the above problem appears

2. If you are trying to install a modified apk, did you resign it?
I haven't resigned it because of the error when repackaging the apk.

3. Are you using the latest apktool version?
Yes, i am using apktool version 2.3.4.

**Comment by MostafaAnter** [comment] 2018-12-05 18:38
`apktool empty-framework-dir --force`

**Comment by iBotPeaches** [comment] 2018-12-27 16:19
Duplicate of - https://github.com/iBotPeaches/Apktool/issues/1842#issuecomment-407102329, which can be solved with latest release and new framework files as described above.

```
apktool empty-framework-dir 
```

**Closed by iBotPeaches** 2018-12-27 16:19 UTC

**Comment by alimp5** [comment] 2020-07-23 08:55
delete /Users/XXXX/Library/apktool/framework/1.apk

in KALI LINUX:
rm -rf /root/.local/share/apktool/framework/1.apk
