### ISSUE TITLE
Error ResBoolValue cannot be cast to brut.androlib.res.data.value.ResAttr

### ISSUE THREAD

**Issue by Rosssssss7** [iBotPeaches/Apktool#1100] opened 2015-12-09 00:04 UTC
Tell me, I can not unpack the file.
error...
Filles https://yadi.sk/d/7J2bQglam6EdA

I: Using Apktool 2.0.3-5f5f50-SNAPSHOT on flyme-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Flyme\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResBoolValue cannot be cast to brut.androlib.res.data.value.ResAttr
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:65)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment] 2015-12-09 01:15
Duplicate of #1065

**Closed by iBotPeaches** 2015-12-09 01:15 UTC
Labels: duplicate

**Comment by Rosssssss7** [comment] 2015-12-09 11:40
How to solve this problem?
I do not know how to make a patch. Help make. 
Thank you!

**Comment by iBotPeaches** [comment] 2015-12-09 12:29
There is no patch yet, its a work in progress. It was marked as duplicate, since this exact stacktrace is already a confirmed bug.

**Comment by Rosssssss7** [comment] 2015-12-09 15:04
Ok. 
Thank you!
