### ISSUE TITLE
[BUG] [ARSC]

### ISSUE THREAD

**Issue by Jinghao1209** [iBotPeaches/Apktool#2719] opened 2021-12-19 08:05 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Output
```
I: Using Apktool 2.6.0 on unit-1.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:55)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:69)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x4b545353
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:72)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:50)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	... 8 more
```

I'm using lastest version, but still can't work it! Hope fix it.....

### Java Version
```
$ java -version
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

Is it my java version to high?

**Comment by iBotPeaches** [comment] 2021-12-19 14:53
This appears to be a newly built `resources.arsc` so I believe its a dupe of https://github.com/iBotPeaches/Apktool/issues/2714

No application to confirm for sure.

**Closed by iBotPeaches** 2021-12-19 14:53 UTC
