### ISSUE TITLE
warning null when compile,  then cannot recompile

### ISSUE THREAD

**Issue by chr0247** [iBotPeaches/Apktool#1666] opened 2017-11-17 15:10 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.3.1-f7a872-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** -windows
3. **APK From? (Playstore, ROM, Other)** -stock rom from HTC U11 anroid 8.0

### Stacktrace/Logcat
apktool.bat d SystemUI.apk
I: Using Apktool 2.3.1-f7a872-SNAPSHOT on SystemUI.apk
I: Loading resource table...
W: null
W: null
W: null
W: null
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\CHR\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
framework apk1: https://mega.nz/#!TJklRQRb!z6iI1BpnR1qP9vQEtmX3JrfxsEaK-bwrZPTcXH_72GQ
framework apk2: https://mega.nz/#!Tc1nyJgD!F-f9C7gnxxNvqxcH2umOJAhznotOe8itqoZqK4P7RZg
apk needs modified: https://mega.nz/#!qUNw0TYT!JLcF8M4MiS8y3caP0vz5izQ47fKwoXVK6TRtb9sGzwA
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it?Haven't tried to install
3. Are you using the latest apktool version?YES

**Comment by chr0247** [comment] 2017-11-27 07:32
D:\adb>apktool.bat d  SystemUI.apk -o S
I: Using Apktool 2.3.1-f7a872-SNAPSHOT on SystemUI.apk
I: Loading resource table...
W: null
W: null
W: null
W: null
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\CHR\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\adb>apktool.bat b S
I: Using Apktool 2.3.1-f7a872-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: 9-patch image S\res\drawable-mdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image S\res\drawable-mdpi\pip_dismiss_scrim.9.png
W: ERROR: 9-patch image S\res\drawable-hdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image S\res\drawable-hdpi\pip_dismiss_scrim.9.png
W: ERROR: 9-patch image S\res\drawable-xhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image S\res\drawable-xhdpi\pip_dismiss_scrim.9.png
W: ERROR: 9-patch image S\res\drawable-xxhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image S\res\drawable-xxhdpi\pip_dismiss_scrim.9.png
W: ERROR: 9-patch image S\res\drawable-xxxhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image S\res\drawable-xxxhdpi\pip_dismiss_scrim.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\CHR\AppData\Local\Temp\brut_util_Jar_110379691726271222.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\CHR\AppData\Local\Temp\APKTOOL8376928404290776226.tmp, -0, arsc, -0, webp, -0, arsc, -I, C:\Users\CHR\AppData\Local\apktool\framework\1.apk, -S, S\res, -M, S\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
        at brut.androlib.Androlib.buildResources(Androlib.java:419)
        at brut.androlib.Androlib.build(Androlib.java:318)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\CHR\AppData\Local\Temp\brut_util_Jar_110379691726271222.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\CHR\AppData\Local\Temp\APKTOOL8376928404290776226.tmp, -0, arsc, -0, webp, -0, arsc, -I, C:\Users\CHR\AppData\Local\apktool\framework\1.apk, -S, S\res, -M, S\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\CHR\AppData\Local\Temp\brut_util_Jar_110379691726271222.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\CHR\AppData\Local\Temp\APKTOOL8376928404290776226.tmp, -0, arsc, -0, webp, -0, arsc, -I, C:\Users\CHR\AppData\Local\apktool\framework\1.apk, -S, S\res, -M, S\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
        ... 6 more

**Comment by chr0247** [comment] 2017-11-27 07:33
Any ideals to solve this?

**Comment by ale8530** [comment] 2017-11-27 12:22
same problem [here](https://github.com/iBotPeaches/Apktool/issues/1672)

**Comment by iBotPeaches** [comment] 2017-11-29 13:31
Closing as duplicate of #1668

See this comment in that ticket for some more details - https://github.com/iBotPeaches/Apktool/issues/1668#issuecomment-347859910

**Closed by iBotPeaches** 2017-11-29 13:31 UTC
