### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nuttolum** [iBotPeaches/Apktool#2768] opened 2022-03-01 18:39 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\nut\Desktop\bbstuff\decompile\w\com.bestbuy.android\res\xml\locales_config.xml:3: error: unbound prefix.
W: C:\Users\nut\Desktop\bbstuff\decompile\w\com.bestbuy.android\res\xml\locales_config.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\nut\AppData\Local\Temp\brut_util_Jar_15325550289147760896724761214212810432.tmp, compile, --dir, C:\Users\nut\Desktop\bbstuff\decompile\w\com.bestbuy.android\res, --legacy, -o, C:\Users\nut\Desktop\bbstuff\decompile\w\com.bestbuy.android\build\resources.zip]

```

### Steps to Reproduce
1. `apktool d com.bestbuy.android-base.apk`
2. `apktool b com.bestbuy.android-base -o modified.apk --use-aapt2`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

best buy apk from play store, can be downloaded here: https://apk.support/apk-downloader package name is com.bestbuy.android

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes

4. Are you using the latest apktool version?
yes

### additional notes

i have tried merging the apks manually, and the problem persisted.

**Comment by iBotPeaches** [comment] 2022-03-01 19:57
Duplicate of #2756

**Closed by iBotPeaches** 2022-03-01 19:57 UTC
