### ISSUE TITLE
apktool will fail and can be bypassed with weird utf8 string; Suggestion and solution included

### ISSUE THREAD

**Issue by ericsia** [iBotPeaches/Apktool#2195] opened 2019-10-12 15:52 UTC
### Information
1. **Apktool Version (`2.4`)** -
2. **Operating System (Linux and Windows)** -
3. **APK From? (Playstore,)** -

apktool will fail and can be bypassed with weird utf8 string; 

### Suggestion/idea
hey coder, if I were as smart and as capable as you, I would first detect if there's unicode in the name, 
public int canDisplayUpTo​(String str)
then I replace the unicode in the name with a marker like /com/android/%mark1%/etc

Then I put a log file (ex: rename.log) in same folder, inside the log file, if 0 then no unicode, if 1 then u convert them to unicode. You can use json library to store the name.
if no unicode text:
```
0
```
proceed to recompile without the need of renaming after reading the rename.log value as 0, else
```
1
com{
 android {
                    %mark1% = \uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD9
           }
}

```
then you rename it back (/com/android/%mark1%/etc), covert unicode escape back then only compile. 

### Stacktrace/Logcat

```
command substitution: line 3: `B�F	1~(X�����K�W�%�h4���2�[Ȳ���&Ϲ������{O�����^��d�2�2��%<�A�4�8��
                                                                  f���lF�4�9w�QqK*4�����pOE
                �d�\ۯ48�jz��82���t������
                                         xMorx��okm/����'�u���a9ɦ��ݾ�!b^��e�~%�j�c�����m�d��^�a�rį�d�nǰ��g����1�al�S��.�8D��W+{�ٰ�����x��Ţ�fe�U�Q!�ya�7��̕m
      cBHI�v*8y��n�G���Ѣ;��
                              ;0��
                                   ��_Z�������<�A�lzduf��K1�@�k䭐eC@��
                                                                            �W�8<"�^���y,����J\L}��DƏ\�?��:d�9���s�
                                         9��Rjm���c�%*Gґ'
/home/NNN/Desktop/apktool_2.4.0.jar: line 3: $'\360\357\f~\317\340\367\r\376\300\340\017\r\376\330': command not found
Desktop/apktool_2.4.0.jar: line 3: !brut/apktool/Main.class�Smo�P~JK[���ӱu�k�С: No such file or directory
```

### Steps to Reproduce
1. `Yes this problem exist in linux environment when decompiling, no joke. 
https://wap.pp.cn/app/dl/fs08/2019/11/07/11/106_039ea82f26db61aa480f9000620c78f1.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
- not applicable
3. Are you using the latest apktool version?
yes

**Comment by ericsia** [comment] 2019-10-28 14:09
update apk sample http://download.zhushou.sogou.com/open/files/year_2019/day_20190329/3945a0bbcfad7bb39eae1871e23d2dd6.apk?dn=%E8%A1%97%E6%9C%BA%E8%BE%BE%E4%BA%BA%E6%8D%95%E9%B1%BC1.1.4.1.apk

**Comment by jpstotz** [comment] 2019-11-02 17:27
I think you would gain more attention if the original post would not be that confusing. 

I would first describe what the actual problem is, not starting with somethings that reads like a new feature description. Describe it precise - what commands trigger the problem and describe what problem occurs.

**Comment by ericsia** [comment] 2019-11-02 18:54
> I think you would gain more attention if the original post would not be that confusing.
> 
> I would first describe what the actual problem is, not starting with something that reads like a new feature description. Describe it precise - what commands trigger the problem and describe what problem occurs.

I thought the title already describe it? "apktool will fail and can be bypassed with weird utf8 string;"
If the apk string contain chinese character for example it will failed to recompile. Some may even failed to decompile in the beginning.
The basic command to decompile trigger it:
`apktool input.apk`
The problem it it can't recompile. It may even failed to decompile if the unicode string is long.

Do tell me if you need further clarification

**Comment by jpstotz** [comment] 2019-11-03 13:22
Well, first the title is IMHO the place where you can summarize something. Placing important details in the title only is a bad idea. Second you use the term "bypassed" but forgot to mention what can be bypassed and where. 
Third a good bug report should include the name of one of the classes that are causing this problem. Therefore it would be good if you could exactly name the package and class names (or at least one) causing this issue. That makes it easier to identify the root cause.

**Comment by ericsia** [comment] 2019-11-04 15:38
> Well, first the title is IMHO the place where you can summarize something. Placing important details in the title only is a bad idea. Second you use the term "bypassed" but forgot to mention what can be bypassed and where.
> Third a good bug report should include the name of one of the classes that are causing this problem. Therefore it would be good if you could exactly name the package and class names (or at least one) causing this issue. That makes it easier to identify the root cause.

bypassed as fail to even decompile as a decompiler function of this tool.
That is the error shown in console, it can't even display the class name so I can't show any.
I already provided the sample apk, I don't know if how is that still unclear.

**Comment by jpstotz** [comment] 2019-11-04 16:04
I decompiled the linked APK yesterday on a Ubuntu VM and did not encounter problems on decompiling.
Recompiling failed not because of file-names but a image-resource that should be of PNG file format but contained some other data. 

Therefore I would assume that the main problem is not apktool but your Linux installation. Make sure your system is capable of handling UTF-8 file name (selecting an UTF-8 locale?) and I would suggest using a recent Java version (v11 is IMHO the recommended version at the moment).

**Comment by ericsia** [comment] 2019-11-06 15:40
> Recompiling failed not because of file-names but a image-resource that should be of PNG file format but contained some other data.

"Recompiling failed not because of file-names but a image-resource that should be of PNG file format but contained some other data." so what did you do about it? also do try if it can be installed after compiling

**Comment by jpstotz** [comment] 2019-11-06 19:21
> so what did you do about it?

Nothing because this is not the error you have described. If I disable resource decoding (`apktool_2.4.0.jar d -r`) upon decompiling the recompiling works without any problem. If the APK works or not is unknown, I don't install APKs I don't know on any of my devices. 

As I wrote from my perspective your problem is not apktool, but your operating system. I recommend to close this issue.

**Comment by ericsia** [comment] 2019-11-07 13:09
> > so what did you do about it?
> 
> Nothing because this is not the error you have described. If I disable resource decoding (`apktool_2.4.0.jar d -r`) upon decompiling the recompiling works without any problem. If the APK works or not is unknown, I don't install APKs I don't know on any of my devices.
> 
> As I wrote from my perspective your problem is not apktool, but your operating system. I recommend to close this issue.

then try this another chinese apk: https://wap.pp.cn/app/dl/fs08/2019/11/07/11/106_039ea82f26db61aa480f9000620c78f1.apk

**Comment by ericsia** [comment] 2019-11-07 18:14
> > then try this another chinese apk, this one will fail in decompilation:
> 
> I am sorry, but I won't test this and any further APK files you post unless you have tested it yourself for verifying that it actually triggers a bug in apktool. In such a case post the APK files and include a detailed bug report.

I can't test it yet, I am not in my hometown, I'll be back on 21st
But I can tell you I am 99% positive this one you will fail to decompile for you because for mine I tried v8.1 of the apk it did failed on both windows and linux

**Comment by iBotPeaches** [comment] 2019-11-15 13:41
> Gosh we really need a Java coder to update this apktool to support unicode and rebrand as BetterApkTool

https://stackoverflow.com/questions/58666141/is-it-me-or-apktool-keep-failing-to-recompile-chinese-apk

:) - You are welcome to work on the open source project :)

**Comment by ericsia** [comment] 2019-11-18 09:52
> > Gosh we really need a Java coder to update this apktool to support unicode and rebrand as BetterApkTool
> 
> https://stackoverflow.com/questions/58666141/is-it-me-or-apktool-keep-failing-to-recompile-chinese-apk
> 
> :) - You are welcome to work on the open source project :)

I wish I can help, I'm not familiar with java unfortunately, I see, she took my post.  This one is more problematic: https://wap.pp.cn/app/dl/fs08/2019/11/07/11/106_039ea82f26db61aa480f9000620c78f1.apk

**Comment by iBotPeaches** [comment] 2020-11-28 22:07
Not sure what is being reported here.

Application seems to decode fine.

```
➜  2195 apktool d "街机达人捕鱼1.1.4.1.apk" 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on 街机达人捕鱼1.1.4.1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2195 
```

Feel free to open a report if you know what you expect vs see. I can't follow this existing thread. Closing.

**Closed by iBotPeaches** 2020-11-28 22:07 UTC
