### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alexcohn** [iBotPeaches/Apktool#2620] opened 2021-07-22 19:52 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.astropaycard.android

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? ✅
2. If you are trying to install a modified apk, did you resign it? ✅
3. Are you using the latest apktool version? ✅

### The problem:
After decoding, lots of XMLs have dropped the attribute namespace. E.g., **AndroidManifest.xml** almost does not have `android:` for attributes like `name`, `value`, or `grantUriPermissions`; the layout xmls have lost both `android:` and `app:` namespaces.

After having fixed these attributes manually, the apk can be installed and runs.

**Comment by iBotPeaches** [comment] 2021-07-31 22:02
Duplicate of https://github.com/iBotPeaches/Apktool/issues/2420

Closing.

**Closed by iBotPeaches** 2021-07-31 22:02 UTC
