### ISSUE TITLE
apktool decompile with error

### ISSUE THREAD

**Issue by Cathy0218** [iBotPeaches/Apktool#1536] opened 2017-06-21 02:16 UTC
### Information
1. Apktool Version: Tried both apktool 2.2.3 and apk 2.2.2
2. Operating System: Linux
3. APK: Google Player Service (http://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-10-5-48-release/google-play-services-10-5-48-448-150087156-android-apk-download/download/)

### Stacktrace/Logcat
```
Decompiling with warning:
I: Using Apktool 2.2.2 on com.google.android.gms_10.5.48_(448-150087156)-10548448_minAPI23(arm64-v8a,armeabi-v7a)(480dpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file:~/.local/share/apktool/framework/1-res.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0200b4
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0200f3
W: Could not decode attr value, using undecoded value instead: ns=android, name=manageSpaceActivity, value=0x7f120369
.......
I: Renamed manifest package found! Replacing com.google.android.gms with FFFFFFFFFFFFFFFFFFFFFF
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Compiling with error:
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: ~/tool/com.google.android.gms_10.5.48_(448-150087156)-10548448_minAPI23(arm64-v8a,armeabi-v7a)(480dpi)_apkmirror.com/AndroidManifest.xml:177: error: Error: No resource type specified (at 'icon' with value '@2130837684').
W: ~/tool/com.google.android.gms_10.5.48_(448-150087156)-10548448_minAPI23(arm64-v8a,armeabi-v7a)(480dpi)_apkmirror.com/AndroidManifest.xml:217: error: Error: No resource type specified (at 'icon' with value '@2130837747').
W: ~/tool/com.google.android.gms_10.5.48_(448-150087156)-10548448_minAPI23(arm64-v8a,armeabi-v7a)(480dpi)_apkmirror.com/AndroidManifest.xml:217: error: Error: No resource type specified (at 'manageSpaceActivity' with value '@2131886953').
W: ~/tool/com.google.android.gms_10.5.48_(448-150087156)-10548448_minAPI23(arm64-v8a,armeabi-v7a)(480dpi)_apkmirror.com/AndroidManifest.xml:221: error: Error: No resource type specified (at 'value' with value '@2131755035').
W: ~/tool/com.google.android.gms_10.5.48_(448-150087156)-10548448_minAPI23(arm64-v8a,armeabi-v7a)(480dpi)_apkmirror.com/AndroidManifest.xml:222: error: Error: No resource type specified (at 'resource' with value '@2131230756').
```
and existed

### Steps to Reproduce
1. Download Linux wrapper script
2. Download apktool-2.2.2 
3. Rename downloaded jar to apktool.jar
4. Move both files (apktool.jar & apktool) to /usr/local/bin 
5. chmod +x apktool apktool.jar
6. apktool d ***.apk
7. apktool b ***
### Frameworks
No

### APK
http://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-10-5-48-release/google-play-services-10-5-48-448-150087156-android-apk-download/download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes
2. If you are trying to install a modified apk, did you resign it?
NO
3. Are you using the latest apktool version?
Yes

**Comment by iBotPeaches** [comment] 2017-06-21 12:54
Duplicate of #1471, thanks for the report. Still digging into this one.

**Closed by iBotPeaches** 2017-06-21 12:54 UTC

**Comment by Cathy0218** [comment] 2017-06-22 01:02
Thank you very much for your attention !

**Comment by Nishant8146** [comment] 2021-05-22 12:18
┌──(root💀nishant)-[~]
└─# apktool d /root/Desktop/sticker.apk                                                                                                                 1 ⨯
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.4.1 on sticker.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:315)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:313)
        ... 3 more
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1581)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1476)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1483)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 6 more
                                                                   
                                                                   
                                                                   
           please help unable to decompile apk
