### ISSUE TITLE
java.io.IOException: error=7, Argument list too long

### ISSUE THREAD

**Issue by kizzyang** [iBotPeaches/Apktool#1612] opened 2017-09-11 15:46 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - debian Linux
3. **APK From? (Playstore, ROM, Other)** - From https://bitbucket.org/iBotPeaches/apktool/downloads/

### Stacktrace/Logcat

when I exec >./apktool.sh b myapp
the log is:

```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
.............
at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 5 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_8465357062502397082.tmp": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 6 more
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more

```

### Steps to Reproduce
1.>./apktool.sh d myapp.apk
2. >./apktool.sh b myapp

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? NO
2. If you are trying to install a modified apk, did you resign it? NO
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment] 2017-09-11 21:24
Duplicate of #1272

**Closed by iBotPeaches** 2017-09-11 21:24 UTC
