### ISSUE TITLE
the new bug

### ISSUE THREAD

**Issue by SSOOnline** [iBotPeaches/Apktool#1138] opened 2016-01-15 02:47 UTC
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\DEVELO~1\AppData\Local\Temp\brut_util_Jar_4938846032654294102.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 410010000, --version-name, 10.0.0, -F, C:\Users\DEVELO~1\AppData\Local\Temp\APKTOOL5139113566359301023.tmp, -0, arsc, -0, sql, -0, zip, -0, txt, -0, , -0, webp, -0, arsc, -I, C:\Users\Developer\apktool\framework\1.apk, -S, D:\\app-release\res, -M, D:\\app-release\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\DEVELO~1\AppData\Local\Temp\brut_util_Jar_4938846032654294102.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 410010000, --version-name, 10.0.0, -F, C:\Users\DEVELO~1\AppData\Local\Temp\APKTOOL5139113566359301023.tmp, -0, arsc, -0, sql, -0, zip, -0, txt, -0, , -0, webp, -0, arsc, -I, C:\Users\Developer\apktool\framework\1.apk, -S, D:\\app-release\res, -M, D:\\app-release\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\DEVELO~1\AppData\Local\Temp\brut_util_Jar_4938846032654294102.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 410010000, --version-name, 10.0.0, -F, C:\Users\DEVELO~1\AppData\Local\Temp\APKTOOL5139113566359301023.tmp, -0, arsc, -0, sql, -0, zip, -0, txt, -0, , -0, webp, -0, arsc, -I, C:\Users\Developer\apktool\framework\1.apk, -S, D:\\app-release\res, -M, D:\\app-release\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more

**Comment by iBotPeaches** [comment] 2016-01-15 04:36
Duplicate of #1122

**Closed by iBotPeaches** 2016-01-15 04:36 UTC
