### ISSUE TITLE
SDK version gets dumped as application version

### ISSUE THREAD

**Issue by aveao** [iBotPeaches/Apktool#2046] opened 2019-03-21 19:58 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 8.4.0, but bisected all the way from cc194daf8366b850d6b0888343269dde1b9d837c to 896569a822ea7f74bcbf91cde6e6361a028d636c (as I thought 896569a822ea7f74bcbf91cde6e6361a028d636c worked fine-- it doesn't).
2. **Operating System (Mac, Linux, Windows)** - Linux (Arch, x86_64)
3. **APK From? (Play Store, ROM, Other)** - Play Store

### Steps to Reproduce
1. `apktool d com.discord-861.apk`
2. `cat com.discord-861/AndroidManifest.xml | head -n 1`

Observe that `platformBuildVersionCode` matches `android:compileSdkVersion`, and that `platformBuildVersionName` incorrectly matches `android:compileSdkVersionCodename`.

### APK
https://transfer.sh/NYgFd/com.discord-861.apk

Issue is present on any Discord Android version starting from v8.5.8 to v8.6.1 (latest, linked above).

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Irrelevant to this issue.
2. If you are trying to install a modified apk, did you resign it? Irrelevant to this issue.
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment] 2019-04-24 21:55
Sorry for the delay. Not sure I understand this report. Are you saying the values (when built) between `platformBuildVersionName` and `android:compileSdkVersionCodename` were the same? Then after Apktool decoded the application that was no longer the case?

I believe we patched out all the aapt changes that were responsible for those changes, but if you use your own aapt this could be working as intended.

There are also some parts of Apktool that follow `@string` references and injects those values directly. This is a limitation and requirement of Apktool, because we can't reference public attributes in certain fields of the `AndroidManifest.xml` and since our only solution currently to maintain consistent resource ids is to make them public, this is a nature of the beast per-se.

**Comment by aveao** [comment] 2019-04-25 07:52
`platformBuildVersionName` and `android:compileSdkVersionCodename` are the same when decoded in AndroidManifest.xml, and that is not correct.

![](https://btw.i-use-ar.ch/i/jqz9tpse.png)

![](https://btw.i-use-ar.ch/i/9sphafln.png)

apktool.yml contains right version information:

![](https://btw.i-use-ar.ch/i/0zjktops.png)

**Comment by iBotPeaches** [comment] 2020-11-28 23:14
Not following this still. The yml file keeps version information (code/name) for injection as parameters to aapt2/aapt. The first screenshot is compile version which Apktool is deciding to no longer change as that affects applications so that is intentional.

Closing as can't understand bug being reported.

**Closed by iBotPeaches** 2020-11-28 23:14 UTC
Labels: Waiting for issuer
