### ISSUE TITLE
cant compile system ui from samsung oreo

### ISSUE THREAD

**Issue by Jdelavega36** [iBotPeaches/Apktool#1681] opened 2017-12-08 00:31 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -Rom

### Stacktrace/Logcat
```
jose@jose-X556UB:~/Desktop/modded apk$ apktool b --no-src --frame-path ~/Desktop/ SystemUI
I: Using Apktool 2.3.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: 9-patch image /home/jose/Desktop/modded apk/SystemUI/res/drawable-xxxhdpi/pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image /home/jose/Desktop/modded apk/SystemUI/res/drawable-xxxhdpi/pip_dismiss_scrim.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_969256524786460335.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 20171030, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL1319015161355722924.tmp, -0, arsc, -0, webp, -0, qmg, -0, png_opti, -0, arsc, -I, /home/jose/Desktop/1.apk, -S, /home/jose/Desktop/modded apk/SystemUI/res, -M, /home/jose/Desktop/modded apk/SystemUI/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_969256524786460335.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 20171030, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL1319015161355722924.tmp, -0, arsc, -0, webp, -0, qmg, -0, png_opti, -0, arsc, -I, /home/jose/Desktop/1.apk, -S, /home/jose/Desktop/modded apk/SystemUI/res, -M, /home/jose/Desktop/modded apk/SystemUI/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_969256524786460335.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 20171030, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL1319015161355722924.tmp, -0, arsc, -0, webp, -0, qmg, -0, png_opti, -0, arsc, -I, /home/jose/Desktop/1.apk, -S, /home/jose/Desktop/modded apk/SystemUI/res, -M, /home/jose/Desktop/modded apk/SystemUI/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
```

[

](url)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://drive.google.com/open?id=1kY8TAG7oCUwheH9xgmKhhrgUNzjMb8E1

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no modified apk
3. Are you using the latest apktool version? yes

**Comment by syrm** [comment] 2017-12-08 14:17
Can't too compile SystemUIGoogle from Google Pixel 2 XL : 

apktool b SystemUIGoogle --no-src                                                       ⏎
I: Using Apktool 2.3.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: 9-patch image /home/srm/Téléchargements/bidouille/SystemUIGoogle/res/drawable-xxxhdpi/pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image /home/srm/Téléchargements/bidouille/SystemUIGoogle/res/drawable-xxxhdpi/pip_dismiss_scrim.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2621683013314748442.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 27, --version-name, 8.1.0, --no-version-vectors, -F, /tmp/APKTOOL700553454809318707.tmp, -0, arsc, -0, arsc, -I, /home/srm/.local/share/apktool/framework/1.apk, -S, /home/srm/Téléchargements/bidouille/SystemUIGoogle/res, -M, /home/srm/Téléchargements/bidouille/SystemUIGoogle/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2621683013314748442.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 27, --version-name, 8.1.0, --no-version-vectors, -F, /tmp/APKTOOL700553454809318707.tmp, -0, arsc, -0, arsc, -I, /home/srm/.local/share/apktool/framework/1.apk, -S, /home/srm/Téléchargements/bidouille/SystemUIGoogle/res, -M, /home/srm/Téléchargements/bidouille/SystemUIGoogle/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2621683013314748442.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 27, --version-name, 8.1.0, --no-version-vectors, -F, /tmp/APKTOOL700553454809318707.tmp, -0, arsc, -0, arsc, -I, /home/srm/.local/share/apktool/framework/1.apk, -S, /home/srm/Téléchargements/bidouille/SystemUIGoogle/res, -M, /home/srm/Téléchargements/bidouille/SystemUIGoogle/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more

**Comment by iBotPeaches** [comment] 2017-12-08 14:41
Malformed 9patch image. Nothing apktool can do.

See https://github.com/iBotPeaches/Apktool/issues/1608#issuecomment-348606421

Duplicate of #1522

**Closed by iBotPeaches** 2017-12-08 14:41 UTC

**Comment by gsmmazhar007** [comment] 2018-07-17 12:04
yes i also faced this problem during oreo recompile any apk

**Comment by gsmmazhar007** [comment] 2018-08-14 11:25
brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [C:\Users\PIYAJE~1\AppData\Local\Temp\brut_util_Jar_4119612751798393913.tmp, p, --forced-package-id, 1, --min-sdk-version, 26, --target-sdk-version, 26, --version-c

**Comment by gsmmazhar007** [comment] 2018-08-14 11:25
apktool 2.3.3 cant repack any samsung apk
