### ISSUE TITLE
Failed to rebuild builtin packages from android N 

### ISSUE THREAD

**Issue by ohadcn** [iBotPeaches/Apktool#1289] opened 2016-07-21 14:53 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0-475178-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - linux (ubuntu 15.4)
3. **APK From? (Playstore, ROM, Other)** - ROM (android NPD56N)

### Stacktrace/Logcat

```
$ apktool b yt -o yt.apk
I: Using Apktool 2.2.0-475178-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/yt/AndroidManifest.xml:6: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:7: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:8: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:9: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:80: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:88: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:95: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:96: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:97: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:110: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:111: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:112: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:118: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:119: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:162: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:168: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:169: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:170: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:171: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:191: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: /tmp/yt/AndroidManifest.xml:211: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2680796169606961806.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 111963644, --version-name, 11.19.63, -F, /tmp/APKTOOL2179736692689113304.tmp, -0, arsc, -0, so, -0, webp, -0, arsc, -I, /home/ohad/.local/share/apktool/framework/1.apk, -S, /tmp/yt/res, -M, /tmp/yt/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2680796169606961806.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 111963644, --version-name, 11.19.63, -F, /tmp/APKTOOL2179736692689113304.tmp, -0, arsc, -0, so, -0, webp, -0, arsc, -I, /home/ohad/.local/share/apktool/framework/1.apk, -S, /tmp/yt/res, -M, /tmp/yt/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2680796169606961806.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 111963644, --version-name, 11.19.63, -F, /tmp/APKTOOL2179736692689113304.tmp, -0, arsc, -0, so, -0, webp, -0, arsc, -I, /home/ohad/.local/share/apktool/framework/1.apk, -S, /tmp/yt/res, -M, /tmp/yt/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more

```

### Steps to Reproduce
0. pull youtube.apk from the device (or download from the link below)
1. `apktool d youtube.apk -o yt`
2. `apktool b yt -o yt.apk`

### Frameworks
https://drive.google.com/file/d/0B9ih8FQpx4K7aUlLWHVjem5Fcnc/view?usp=sharing

### APK
https://drive.google.com/file/d/0B9ih8FQpx4K7bTJWOFBlM1pIYW8/view?usp=sharing
https://drive.google.com/file/d/0B9ih8FQpx4K7bE9rWmZaNzlDc1U/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? can't built, so can't install.
3. Are you using the latest apktool version? see version details above.
4. I could install another APK's decoded and rebuilt by apktool.
5. Similar errors came when rebuilding Chrome browser - this time with errors for the resource 'externalService' (haven't tried another packages)

**Comment by iBotPeaches** [comment] 2016-07-22 04:13
Closing as duplicate of #1223 

Android N issues will be triaged in that report and handled once the source drops officially.

**Closed by iBotPeaches** 2016-07-22 04:13 UTC
