### ISSUE TITLE
ERROR: 9-patch image

### ISSUE THREAD

**Issue by linyia01** [iBotPeaches/Apktool#1925] opened 2018-10-24 05:38 UTC
### Information
1. **Apktool Version (`apktool -version`)** - Apktool v2.3.4 Released
2. **Operating System (Mac, Linux, Windows)** - centos java 1.8.0
3. **APK From? (Playstore, ROM, Other)** -东方财富apk7.7.1

### Stacktrace/Logcat
S: WARNING: Could not write to (/root/.local/share/apktool/framework), using /tmp instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: ERROR: 9-patch image /root/tools/apk/dfcf7/res/drawable-xhdpi/bg_fund_ad_single_with_button_buy.9.png malformed.
W:        No marked region found along edge.
W:        Found along top edge.
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
java -jar apktool_2.3.4.jar d dfcf7.apk 

java -jar apktool_2.3.4.jar b dfcf7

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by ibuprophen1** [comment] 2018-10-24 15:58
@linyia01, This is a duplicate of the https://github.com/iBotPeaches/Apktool/issues/1522 issue that was confirmed by @iBotPeaches. 


~Ibuprophen

**Comment by iBotPeaches** [comment] 2018-11-01 20:54
Unfortunately there is no APK here to determine if the bug is the same one apparent in #1522. The output/error is, but not sure if the underlying cause is the same.

It seems due to the increasing amount of tickets for this, we might need to explore padding pixels to images in order to '9patch' them.

Closing as duplicate of #1522

**Closed by iBotPeaches** 2018-11-01 20:54 UTC
