### ISSUE TITLE
Instagram can't find some drawables after being rebuilt with apktool

### ISSUE THREAD

**Issue by grishka** [iBotPeaches/Apktool#2074] opened 2019-05-09 14:13 UTC
### Information
1. **Apktool Version (`apktool -version`)** 2.4.0
2. **Operating System (Mac, Linux, Windows)** Mac
3. **APK From? (Playstore, ROM, Other)** Playstore

### Stacktrace/Logcat

```
    --------- beginning of crash
2019-05-09 16:37:00.985 7418-7418/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.instagram.android, PID: 7418
    android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class com.instagram.share.facebook.widget.FindPeopleButton
    Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class com.instagram.share.facebook.widget.FindPeopleButton
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at X.4oI.II(:430522)
        at X.0fF.ac(:73764)
        at X.1h0.C(:185119)
        at X.1fZ.getView(:182935)
        at android.widget.AbsListView.obtainView(AbsListView.java:3219)
        at android.widget.ListView.makeAndAddView(ListView.java:2219)
        at android.widget.ListView.fillDown(ListView.java:827)
        at android.widget.ListView.fillFromTop(ListView.java:888)
        at android.widget.ListView.layoutChildren(ListView.java:1958)
        at android.widget.AbsListView.onLayout(AbsListView.java:2991)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at androidx.viewpager.widget.ViewPager.onLayout(:690784)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.instagram.ui.swipenavigation.SwipeNavigationContainer.onLayout(:89481)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
2019-05-09 16:37:00.985 7418-7418/? E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3340)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2804)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.instagram.android:drawable/fb_connect with resource ID #0x7f0801e0
     Caused by: android.content.res.Resources$NotFoundException: File R|GFr2ZgPv0HBOCTMBAAAAAADRz-J5bnsvAAAD|AQAJ8q2IfPBI|288|288|480 from drawable resource ID #0x7f0801e0
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:898)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
        at android.content.res.Resources.loadDrawable(Resources.java:912)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
        at com.instagram.share.facebook.widget.FindPeopleButton.B(:290044)
        at com.instagram.share.facebook.widget.FindPeopleButton.<init>(:290033)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at X.4oI.II(:430522)
        at X.0fF.ac(:73764)
        at X.1h0.C(:185119)
        at X.1fZ.getView(:182935)
        at android.widget.AbsListView.obtainView(AbsListView.java:3219)
        at android.widget.ListView.makeAndAddView(ListView.java:2219)
        at android.widget.ListView.fillDown(ListView.java:827)
        at android.widget.ListView.fillFromTop(ListView.java:888)
        at android.widget.ListView.layoutChildren(ListView.java:1958)
        at android.widget.AbsListView.onLayout(AbsListView.java:2991)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
2019-05-09 16:37:00.986 7418-7418/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at androidx.viewpager.widget.ViewPager.onLayout(:690784)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.instagram.ui.swipenavigation.SwipeNavigationContainer.onLayout(:89481)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
        at android.view.View.layout(View.java:22399)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3340)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2804)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.io.FileNotFoundException: R|GFr2ZgPv0HBOCTMBAAAAAADRz-J5bnsvAAAD|AQAJ8q2IfPBI|288|288|480
        at android.content.res.AssetManager.nativeOpenNonAsset(Native Method)
        at android.content.res.AssetManager.openNonAsset(AssetManager.java:909)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:882)
        	... 92 more
```

### Steps to Reproduce
1. `apktool d instagram.apk`
2. `apktool b instagram`
3. Sign
4. Install
5. Log in
6. Open your profile
7. Open followers list

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

Not applicable, this is not a system app.

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=676634

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes. I didn't touch any of the resources anyway.
2. If you are trying to install a modified apk, did you resign it?
Of course.
3. Are you using the latest apktool version?
2.4.0 is latest at the time of writing.

### Additional info
Instagram uses a weird custom way of storing its resources, presumably to reduce the apk size, that apktool doesn't preserve. If you unzip the original apk directly, you get an "r" folder with this mess inside:
![Снимок экрана 2019-05-09 в 17 01 14](https://user-images.githubusercontent.com/1478258/57459525-1415e080-727c-11e9-9290-abfaf6f35a42.png)
Basically, all the resources piled together into one folder. I didn't even know this is a valid thing to do, but it apparently is as far as Android is concerned.

Apktool tries decoding resources.arsc and giving these files meaningful names, but somewhat fails. Both the directory that results from `apktool d` and the rebuilt apk have the Android's usual resource structure with res folder and different resource types and their configuration variants in their own subfolders. The problem might be that there are two or more different resource ids that refer to the same file, which is impossible if you built your app using the usual SDK tools, but I can't know for sure.

If that matters, I use the following bash script to rebuild, sign and install the apk:
```bash
#!/bin/bash

apktool b instagram91 || exit 1
jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore instagram91/dist/instagram91.apk -storepass android -keypass android androiddebugkey || exit 1
adb install -r instagram91/dist/instagram91.apk || exit 1
```

**Comment by nicknitewolf** [comment] 2019-05-10 04:16
The NPE was patched in #2063 but we still have to find out how the resources can be decompiled correctly

**Comment by jtrollkarl** [comment] 2019-05-10 07:08
I have the same issue with another popular app

**Comment by iBotPeaches** [comment] 2019-06-02 21:55
This looks like a duplicate of an existing Dexguard/AndroResGuard ticket, but can't find it right now. So will hold this open.

**Comment by iBotPeaches** [comment] 2019-06-02 23:15
Found it - #2054 - yeah something is going on with this resource obfuscation that we don't have right.

**Closed by iBotPeaches** 2019-06-02 23:15 UTC
