### ISSUE TITLE
Error copying file: assets

### ISSUE THREAD

**Issue by LGLTeam** [iBotPeaches/Apktool#2307] opened 2020-03-05 16:28 UTC
### Information
1. **Apktool Version (`apktool -version`)** 2.4.1
2. **Operating System (Mac, Linux, Windows)** Windows 10
3. **APK From? (Playstore, ROM, Other)** Other

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1 on xlua-app.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\lgl\AppData\Local\apktool\framework\1.apk
I: Renamed manifest package found! Replacing Lorazalora.Modz with com.AndLua.LY
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable/welcome.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:158)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:179)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file: assets
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:145)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: Mod/so/libil/unity/cheating/*pokeh
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
	... 5 more
Caused by: java.io.IOException: Invalid argument
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(Unknown Source)
	at java.io.File.getCanonicalPath(Unknown Source)
	at brut.util.BrutIO.sanitizeUnknownFile(BrutIO.java:90)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 8 more

```

### Steps to Reproduce
1. `apktool d`

### Frameworks
N/A

### APK
If this APK can be freely shared, please upload/attach a link to it.

[xlua-app.zip](https://github.com/iBotPeaches/Apktool/files/4293999/xlua-app.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2020-04-11 11:18
```
➜  2307 apktool d xlua-app.apk 
I: Using Apktool 2.4.1 on xlua-app.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Renamed manifest package found! Replacing Lorazalora.Modz with com.AndLua.LY
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable/welcome.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2307 
```

It works on linux, but my guess it is fails on windows due to reserved characters and that issue is a large one stuck in our backlog for years :/

Sorry, but closing as duplicate of #1460. In the meantime you may use linux.

**Closed by iBotPeaches** 2020-04-11 11:18 UTC
