### ISSUE TITLE
Cannot compile APK, problem during building.

### ISSUE THREAD

**Issue by Daniel41550** [iBotPeaches/Apktool#1922] opened 2018-10-21 22:15 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ApkMirror

### Stacktrace/Logcat

```
`I: Using Apktool 2.3.4
I: Checking whether resources has changed...
I: Building resources...
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:54: error: Public symbol array/defaultActions declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:55: error: Public symbol array/defaultActionsValues declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:56: error: Public symbol array/fontValues declared here is not defined.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Daniel\AppData\Local\Temp\brut_util_Jar_2978718851619109034.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 371, --version-name, 9.0.72, --no-version-vectors, -F, C:\Users\Daniel\AppData\Local\Temp\APKTOOL6063945892517520887.tmp, -0, arsc, -0, META-INF/android.support.design_material.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.arch.core_core-runtime.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.browser_browser.version, -0, META-INF/androidx.cardview_cardview.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.legacy_legacy-support-v4.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata-core.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata.version, -0, META-INF/androidx.lifecycle_lifecycle-runtime.version, -0, META-INF/androidx.lifecycle_lifecycle-viewmodel.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.media_media.version, -0, META-INF/androidx.palette_palette.version, -0, META-INF/androidx.percentlayout_percentlayout.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.transition_transition.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, META-INF/com.google.android.material_material.version, -0, properties, -0, png, -0, res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-hdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-hdpi-v4/ic_story_hide.9.png, -0, res/drawable-hdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-hdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-hdpi-v4/notification_bg_normal.9.png, -0, res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-hdpi-v4/quickcontact_drop_shadow.9.png, -0, res/drawable-hdpi-v4/toast_frame.9.png, -0, res/drawable-hdpi-v4/tooltip_bottom_frame.9.png, -0, res/drawable-hdpi-v4/tooltip_top_frame.9.png, -0, res/drawable-ldpi-v4/toast_frame.9.png, -0, res/drawable-ldrtl-hdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-mdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-xhdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-xxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-xxxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-mdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-mdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-mdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-mdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-mdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-mdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-mdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-mdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-mdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-mdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-mdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-mdpi-v4/ic_story_hide.9.png, -0, res/drawable-mdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-mdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-mdpi-v4/notification_bg_normal.9.png, -0, res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-mdpi-v4/toast_frame.9.png, -0, res/drawable-nodpi-v4/abs_dialog_full_holo_dark.9.png, -0, res/drawable-nodpi-v4/abs_dialog_full_holo_light.9.png, -0, res/drawable-nodpi-v4/background_card_dark.9.png, -0, res/drawable-nodpi-v4/bg_divider_black.9.png, -0, res/drawable-nodpi-v4/bg_divider_blue_50_dark.9.png, -0, res/drawable-nodpi-v4/bg_divider_blue_50_light.9.png, -0, res/drawable-nodpi-v4/bg_divider_blue_dark.9.png, -0, res/drawable-nodpi-v4/bg_divider_blue_light.9.png, -0, res/drawable-nodpi-v4/bg_divider_dark_blue.9.png, -0, res/drawable-nodpi-v4/bg_divider_grey.9.png, -0, res/drawable-nodpi-v4/bg_divider_highlight_dark.9.png, -0, res/drawable-nodpi-v4/bg_divider_highlight_light.9.png, -0, res/drawable-nodpi-v4/bg_divider_viewed_dark.9.png, -0, res/drawable-nodpi-v4/bg_divider_viewed_light.9.png, -0, res/drawable-nodpi-v4/bg_divider_white.9.png, -0, res/drawable-nodpi-v4/bottom_shadow.9.png, -0, res/drawable-nodpi-v4/card_bg_dark.9.png, -0, res/drawable-nodpi-v4/card_bg_highlight_dark.9.png, -0, res/drawable-nodpi-v4/card_bg_highlight_light.9.png, -0, res/drawable-nodpi-v4/card_bg_light.9.png, -0, res/drawable-nodpi-v4/card_bg_read_dark.9.png, -0, res/drawable-nodpi-v4/card_bg_read_light.9.png, -0, res/drawable-nodpi-v4/dark_header.9.png, -0, res/drawable-nodpi-v4/divider_dark.9.png, -0, res/drawable-nodpi-v4/divider_light.9.png, -0, res/drawable-nodpi-v4/holo_black_dark_card.9.png, -0, res/drawable-nodpi-v4/holo_black_viewed_dark_card.9.png, -0, res/drawable-nodpi-v4/holo_blue_dark_card.9.png, -0, res/drawable-nodpi-v4/holo_blue_dark_card_50.9.png, -0, res/drawable-nodpi-v4/holo_blue_dark_highlight_card.9.png, -0, res/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-xhdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-xhdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-xhdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-xhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-xhdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-xhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/button_focused.9.png, -0, res/drawable-xhdpi-v4/button_pressed.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-xhdpi-v4/ic_story_hide.9.png, -0, res/drawable-xhdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-xhdpi-v4/notification_bg_normal.9.png, -0, res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-xhdpi-v4/toast_frame.9.png, -0, res/drawable-xxhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xxhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-xxhdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-xxhdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-xxhdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-xxhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-xxhdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-xxhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-xxhdpi-v4/left_shadow.9.png, -0, res/drawable-xxhdpi-v4/right_shadow.9.png, -0, res/drawable-xxhdpi-v4/toast_frame.9.png, -0, res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xxxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xxxhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xxxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, arsc, -I, C:\Users\Daniel\AppData\Local\apktool\framework\1.apk, -S, T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res, -M, T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\AndroidManifest.xml]
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:57: error: Public symbol array/fonts declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:58: error: Public symbol array/mailNames declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:59: error: Public symbol array/mailValues declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:60: error: Public symbol array/prefetchNames declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:61: error: Public symbol array/prefetchValues declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:62: error: Public symbol array/textSizes declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:63: error: Public symbol array/textValues declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:64: error: Public symbol array/themeValues declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:65: error: Public symbol array/themes declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:66: error: Public symbol array/viewValues declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:67: error: Public symbol array/viewValuesBeta declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:68: error: Public symbol array/views declared here is not defined.
W: T:\Libraries\Programming\Decompiled\ApkTool\Relay\9.0.72\Original\Source\res\values\public.xml:69: error: Public symbol array/viewsBeta declared here is not defined.`
```

### Steps to Reproduce
1. Download .apk and decompile it
2. Attempt to recompile source

### Frameworks
Not an APK from an OEM ROM.

### APK
https://www.apkmirror.com/apk/dbrady/relay-for-reddit-2/relay-for-reddit-2-9-0-72-release/relay-for-reddit-9-0-72-2-android-apk-download/download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? Build Error.
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment] 2018-11-01 20:57
Confirmed in both aapt1/aapt2.

```
I: Building resources...
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:54: error: no definition for declared symbol 'free.reddit.news:array/defaultActions'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:55: error: no definition for declared symbol 'free.reddit.news:array/defaultActionsValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:56: error: no definition for declared symbol 'free.reddit.news:array/fontValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:57: error: no definition for declared symbol 'free.reddit.news:array/fonts'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:58: error: no definition for declared symbol 'free.reddit.news:array/mailNames'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:59: error: no definition for declared symbol 'free.reddit.news:array/mailValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:60: error: no definition for declared symbol 'free.reddit.news:array/prefetchNames'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:61: error: no definition for declared symbol 'free.reddit.news:array/prefetchValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:62: error: no definition for declared symbol 'free.reddit.news:array/textSizes'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:63: error: no definition for declared symbol 'free.reddit.news:array/textValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:64: error: no definition for declared symbol 'free.reddit.news:array/themeValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:65: error: no definition for declared symbol 'free.reddit.news:array/themes'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:66: error: no definition for declared symbol 'free.reddit.news:array/viewValues'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:67: error: no definition for declared symbol 'free.reddit.news:array/viewValuesBeta'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:68: error: no definition for declared symbol 'free.reddit.news:array/views'.
W: /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1922/reddit.news/res/values/public.xml:69: error: no definition for declared symbol 'free.reddit.news:array/viewsBeta'.
W: error: failed linking references.
```

**Comment by jeanbmar** [comment] 2019-01-16 17:25
I had the same issues with this APK: https://www.apkmirror.com/apk/supercell/brawl-stars/brawl-stars-14-118-release/brawl-stars-14-118-android-apk-download/

I've noticed resources in res/values/arrays.xml where using the style tag instead of the array tag.
Fixing it manually and rebuilding solved the issue.

**Comment by geek1011** [comment] 2019-01-30 22:25
Same issue with the Termius APK, @jeanbmar's fix works.

**Comment by micmar** [comment] 2019-02-11 16:54
> I've noticed resources in res/values/arrays.xml where using the style tag instead of the array tag.
> Fixing tags manually and rebuilding solved the issue.

Can you please elaborate what you mean by "style tag" instead of "array tag"?
I have the same problem showing up with fonts (but I don't have a res/values/arrays.xml)

**Comment by andreimarcut** [comment] 2019-02-21 10:51
I am in the same boat with @micmar - it doesn't work when using the public released version 2.3.4 but it works with a locally built version 2.4.0-53fdd9-SNAPSHOT

**Comment by micmar** [comment] 2019-02-21 13:15
I think at this point the issue has been fixed. It is just a matter of knowing when it will be released.
Is there any release date planned for 2.4.0? Thanks.

**Comment by iBotPeaches** [comment] 2019-02-21 13:37
Apologies, it seems this was a duplicate of #1994 which has since been fixed. It will be in the upcoming v2.4.0 release.

**Closed by iBotPeaches** 2019-02-21 13:37 UTC
Labels: Bug

**Comment by ChaseRocks360** [comment] 2023-02-18 06:14
So I've been working on a menu for Roblox and when I get ready to build it, it says Public symbol array/roblox_channels declared here is not defined I've gone through it and it seems that nothing is wrong with it but I don't know why it won't let me build it.
