### ISSUE TITLE
Cant build for some reason~

### ISSUE THREAD

**Issue by kiiromitsuki** [iBotPeaches/Apktool#2423] opened 2020-11-03 03:20 UTC
### Information
1. **Apktool Version (`2.4.1`)** -
2. **Operating System (Windows 10)** -
3. **APK From? (My Project)** -

### Stacktrace/Logcat

```
-c/--copy-original has been deprecated. Removal planned for v2.5.0 (#2129)
I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [C:\Users\user\AppData\Local\Temp\brut_util_Jar_196511341337974616.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL2914511454443315299.tmp, -e, C:\Users\user\AppData\Local\Temp\APKTOOL3972489429532014902.tmp, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, D:\OneDrive\Desktop\apktool\app3\res, -M, D:\OneDrive\Desktop\apktool\app3\AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool.bat b app3 -c -f -o patched_app3.apk`

### APK
https://salam.inche-ali.com/JUN~2020/apk/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? 
3. Are you using the latest apktool version?yes

**Comment by iBotPeaches** [comment] 2020-11-27 14:52
Can't seem to download that file and you could running in verbose mode for more output `-v`.

Closing for now as not able to reproduce.

**Closed by iBotPeaches** 2020-11-27 14:52 UTC
