### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thkui12121233** [iBotPeaches/Apktool#3068] opened 2023-05-17 06:41 UTC
Information
1. Apktool Version 2.7.0 -
2. Operating System Windows 11
3. APK From www.whatsapp.com/android
4. Java Version 1.8.0_371

Stacktrace/Logcat

Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:43)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:876)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:858)
        at brut.androlib.Androlib.installFramework(Androlib.java:766)
        at brut.apktool.Main.cmdInstallFramework(Main.java:281)
        at brut.apktool.Main.main(Main.java:85)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000005
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:53)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:399)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:324)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:309)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:224)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:133)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:85)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:51)
        ... 6 more

I tried "apktool if whatsapp.apk" and got this

I didn't change anything 

THANKS

APK
 www.whatsapp.com/android.

**Comment by iBotPeaches** [comment] 2023-05-18 13:12
Thanks for report. Duplicate of: https://github.com/iBotPeaches/Apktool/issues/3036

**Closed by iBotPeaches** 2023-05-18 13:12 UTC
