### ISSUE TITLE
 match_parent  changed to fill_parent  

### ISSUE THREAD

**Issue by nematiprog** [iBotPeaches/Apktool#1274] opened 2016-06-16 22:43 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.11
2. **Operating System (Mac, Linux, Windows)** -windows 10
3. **APK From? (Playstore, ROM, Other)** - all

Hi

why all  match_parent  changed to fill_parent  in layouts? is it bug ?or i have to use Framework? thanks a lot

**Comment by iBotPeaches** [comment] 2016-06-16 22:45
Can you create an example file? I can then add it to our unit-tests and see if this is indeed a problem or not. - https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/layout

If not, I might have time this weekend to look into a few bugs and this.

**Comment by nemati456** [comment] 2016-06-16 22:57
i created main and main_de

**Comment by nemati456** [comment] 2016-06-16 23:02
is it bug?

**Comment by nemati456** [comment] 2016-06-16 23:11
and apk file 
https://mega.nz/#!ftIzRTYB!YtzDS5O7z_vPiCOnsRFNy6-ZEQX5XWSpONmHd6ZpWpA

**Comment by iBotPeaches** [comment] 2016-06-17 12:22
```
brut.androlib.BuildAndDecodeTest > xmlFillParentBecomesMatchTest FAILED
    java.lang.AssertionError: res/layout/issue1274.xml: [Expected attribute value 'match_parent' but was 'fill_parent' - comparing <LinearLayout android:layout_width="match_parent"...> at /LinearLayout[1]/@layout_width to <LinearLayout android:layout_width="fill_parent"...> at /LinearLayout[1]/@layout_width, Expected presence of child nodes to be 'true' but was 'false' - comparing <LinearLayout...> at /LinearLayout[1] to <LinearLayout...> at /LinearLayout[1]]
        at org.junit.Assert.fail(Assert.java:93)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at brut.androlib.BuildAndDecodeTest.compareXmlFiles(BuildAndDecodeTest.java:464)
        at brut.androlib.BuildAndDecodeTest.compareXmlFiles(BuildAndDecodeTest.java:440)
        at brut.androlib.BuildAndDecodeTest.xmlFillParentBecomesMatchTest(BuildAndDecodeTest.java:197)

70 tests completed, 1 failed
```

**Comment by iBotPeaches** [comment] 2016-06-18 17:10
`match_parent` and `fill_parent`.

```
➜  BRUT925320871113552706.tmp aapt d xmltree testapp.apk res/layout/issue1274.xml
N: android=http://schemas.android.com/apk/res/android
  E: LinearLayout (line=2)
    A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
    A: android:layout_height(0x010100f5)=(type 0x10)0xffffffff
```

`match_parent` and `match_parent`

```
➜  BRUT2609634117341352147.tmp aapt d xmltree testapp.apk res/layout/issue1274.xml
N: android=http://schemas.android.com/apk/res/android
  E: LinearLayout (line=2)
    A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
    A: android:layout_height(0x010100f5)=(type 0x10)0xffffffff
```

So the problem is occurring during build?

**Comment by iBotPeaches** [comment] 2016-08-03 00:13
https://developer.android.com/reference/android/view/ViewGroup.LayoutParams.html

> FILL_PARENT (renamed MATCH_PARENT in API Level 8 and higher), which means that the view wants to be as big as its parent (minus padding)

This is intentional. Both enums `MATCH_PARENT` and `FILL_PARENT` resolve to `-1`. Since they do, Apktool can't determine what the original value was as both programmatically map to the same value.

`FILL_PARENT` was the original one which is why Apktool selects it. That enum is technically deprecated, but still works. For this reason, I'm closing this.

**Closed by iBotPeaches** 2016-08-03 00:13 UTC
Labels: Accepted, Not a Bug
