### ISSUE TITLE
Tencentmobileassistant version 5.1 tencentmobileassistant.apk can decompile.

### ISSUE THREAD

**Issue by siten** [iBotPeaches/Apktool#1002] opened 2015-07-17 08:41 UTC
C:\Users\*****\Desktop>java -jar apktool_2.0.1.jar d -d tencentmobileassistant.apk -o out
I: Using Apktool 2.0.1 on tencentmobileassistant.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple res specs:attr/0
        at brut.androlib.res.data.ResType.addResSpec(ResType.java:62)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:219)

        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
        at brut.androlib.Androlib.getResTable(Androlib.java:64)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment] 2015-08-05 11:49
Duplicate of #894

**Closed by iBotPeaches** 2015-08-05 11:49 UTC
Labels: duplicate
