### ISSUE TITLE
5.0.2 Tab S/S2, Tab 4, Touchwiz SystemUI  Pulldown layout bug

### ISSUE THREAD

**Issue by DUHAsianSKILLZ** [iBotPeaches/Apktool#1034] opened 2015-09-06 19:12 UTC
I found a bug in which when I decompile and recompile SystemUI apk (stock touchwiz 5.0.2) without any edits, when I flash it to my device.. the Pulldown is shifted to the left. Heres the picture of what is looks like: https://www.dropbox.com/s/39f7fl3o2bkcbxt/download_20150906_123540.jpeg?dl=0
I am using the latest apktool and have also tryed previous versions with the same result.

Its supposed to be in the middle and not on the left. All of the notifications and Pulldown are shifted to the left including when rotating to verticle and horizontal. It is also shifted on the lockscreen. So far i have found this issue to happen on the Tab S, Tab S2, Tab 4, and maybe more tablets running 5.0.2 Touchwiz. This issue seems to be only on samsung tablets on lollipop as i could not reproduce this issue on my friends galaxy s5.

After lots of digging around, i pinpointed the issue to be in the layout folder and  status_bar_expanded xml and status_bar_expanded_header and finally super_status_bar xml. I have found the issue to be in those three xmls as the only soultion is to copy back the 3 xmls from the original apk to the recompiled apk with winrar. I have also tried to fix the issue by changing some layout_gravity text in those 3 xmls. So far i just fixed the status_bar_expanded_header by changing the layout_gravity to layout_gravity="top|center_horizontal". That made the date part Pulldown go back to the center but not the rest. I could not fix the rest as i had no sucess so far. I really do need to add mods to those xmls but this bug is holding me back to do so. Thanks!

**Comment by iBotPeaches** [comment] 2015-09-06 22:04
Duplicate of #1023

**Closed by iBotPeaches** 2015-09-06 22:04 UTC
