### ISSUE TITLE
Apktool Failing to recompile obfuscated apk(using apktool 2.0.3)

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1134] opened 2016-01-13 11:19 UTC
Apktool is failing to recompile obfuscated apk. Error showed is, "illegal characters in manifest. There are some uniocode characters in manifest file due to obfuscation. Can we expect a solution for this anytime soon?

**Comment by iBotPeaches** [comment] 2016-01-13 14:07
Duplicate of #885

**Closed by iBotPeaches** 2016-01-13 14:07 UTC

**Comment by jack16099** [comment] 2016-01-13 14:55
so any fix coming?

**Comment by iBotPeaches** [comment] 2016-01-13 15:01
if//when I figure it out. Yes
