### ISSUE TITLE
"Invalid resource directory name" and Exception while repacking Facebook resources (and warnings when unpacking)

### ISSUE THREAD

**Issue by evilwombat** [iBotPeaches/Apktool#1738] opened 2018-03-02 23:54 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1, and top-of-tree as of 34a2d03
2. **Operating System (Mac, Linux, Windows)** - Linux x86_64 (Ubuntu 14.04)
3. **APK From? (Playstore, ROM, Other)** - Play store

A workaround is to pass -r to apktool, but this partially defeats the purpose because I would like to modify resources as well as code.

### Steps to Reproduce
0. Grab https://www.apkmirror.com/apk/facebook-2/facebook/facebook-161-0-0-35-93-release/facebook-161-0-0-35-93-2-android-apk-download/ (and rename to fb.apk to help with personal sanity)

1. `apktool d fb.apk -s -o test`
Lots of warnings are produced, all in the form of:
S: Could not decode file, replacing by FALSE value: f0i.png
S: Could not decode file, replacing by FALSE value: dmi.png
S: Could not decode file, replacing by FALSE value: euu.g.png
S: Could not decode file, replacing by FALSE value: dk2.g.png
S: Could not decode file, replacing by FALSE value: ea3.g.png
<snip>

2. `apktool b test -o repacked.apk`
Exceptions are produced:
apktool b test -o repacked.apk 
I: Using Apktool 2.3.2-34a2d0-SNAPSHOT
I: Copying test classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /home/steve/debullshification/repo/test/res drawable3
W: invalid resource directory name: /home/steve/debullshification/repo/test/res layout3
W: invalid resource directory name: /home/steve/debullshification/repo/test/res raw2
W: invalid resource directory name: /home/steve/debullshification/repo/test/res drawable4
W: invalid resource directory name: /home/steve/debullshification/repo/test/res drawable2
W: invalid resource directory name: /home/steve/debullshification/repo/test/res layout2
W: invalid resource directory name: /home/steve/debullshification/repo/test/res drawable3-xhdpi
W: invalid resource directory name: /home/steve/debullshification/repo/test/res drawable4-xxhdpi
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6140894604968111965.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 94117312, --version-name, 161.0.0.35.93, --no-version-vectors, -F, /tmp/APKTOOL8592479291632135486.tmp, -0, arsc, -0, assets/Bundle-fb4a.js.bytecode.sha256, -0, assets/Fb4aBundle.js.bytecode.sha256, -0, assets/Fb4aBundle.js.bytecode.xz, -0, assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui.dex.jar.xzs, -0, assets/java.com.facebook.base.activity.activitylike.fragment/java.com.facebook.base.activity.activitylike.fragment-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.base.activity.activitylike.fragment/java.com.facebook.base.activity.activitylike.fragment.dex.jar.xzs, -0, assets/java.com.facebook.fbliteinfb4a/java.com.facebook.fbliteinfb4a.dex.jar.xzs, -0, assets/java.com.facebook.fbliteinfb4a/libs.xzs, -0, assets/java.com.facebook.katana.internsettingsactivity/java.com.facebook.katana.internsettingsactivity.dex.jar.xzs, -0, assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser.dex.jar.xzs, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, frsc, -0, assets/thirdparty.mapbox.mapboxglnative/libs.xzs, -0, assets/xplat.rtc.librtc/libs.xzs, -0, fbfx, -0, json, -0, webp, -0, key, -0, FBSIG, -0, arsc, -I, /home/steve/.local/share/apktool/framework/1.apk, -S, /home/steve/debullshification/repo/test/res, -M, /home/steve/debullshification/repo/test/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:498)
	at brut.androlib.Androlib.buildResources(Androlib.java:424)
	at brut.androlib.Androlib.build(Androlib.java:304)
	at brut.androlib.Androlib.build(Androlib.java:269)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6140894604968111965.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 94117312, --version-name, 161.0.0.35.93, --no-version-vectors, -F, /tmp/APKTOOL8592479291632135486.tmp, -0, arsc, -0, assets/Bundle-fb4a.js.bytecode.sha256, -0, assets/Fb4aBundle.js.bytecode.sha256, -0, assets/Fb4aBundle.js.bytecode.xz, -0, assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui.dex.jar.xzs, -0, assets/java.com.facebook.base.activity.activitylike.fragment/java.com.facebook.base.activity.activitylike.fragment-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.base.activity.activitylike.fragment/java.com.facebook.base.activity.activitylike.fragment.dex.jar.xzs, -0, assets/java.com.facebook.fbliteinfb4a/java.com.facebook.fbliteinfb4a.dex.jar.xzs, -0, assets/java.com.facebook.fbliteinfb4a/libs.xzs, -0, assets/java.com.facebook.katana.internsettingsactivity/java.com.facebook.katana.internsettingsactivity.dex.jar.xzs, -0, assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser.dex.jar.xzs, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, frsc, -0, assets/thirdparty.mapbox.mapboxglnative/libs.xzs, -0, assets/xplat.rtc.librtc/libs.xzs, -0, fbfx, -0, json, -0, webp, -0, key, -0, FBSIG, -0, arsc, -I, /home/steve/.local/share/apktool/framework/1.apk, -S, /home/steve/debullshification/repo/test/res, -M, /home/steve/debullshification/repo/test/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:476)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6140894604968111965.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 94117312, --version-name, 161.0.0.35.93, --no-version-vectors, -F, /tmp/APKTOOL8592479291632135486.tmp, -0, arsc, -0, assets/Bundle-fb4a.js.bytecode.sha256, -0, assets/Fb4aBundle.js.bytecode.sha256, -0, assets/Fb4aBundle.js.bytecode.xz, -0, assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui.dex.jar.xzs, -0, assets/java.com.facebook.base.activity.activitylike.fragment/java.com.facebook.base.activity.activitylike.fragment-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.base.activity.activitylike.fragment/java.com.facebook.base.activity.activitylike.fragment.dex.jar.xzs, -0, assets/java.com.facebook.fbliteinfb4a/java.com.facebook.fbliteinfb4a.dex.jar.xzs, -0, assets/java.com.facebook.fbliteinfb4a/libs.xzs, -0, assets/java.com.facebook.katana.internsettingsactivity/java.com.facebook.katana.internsettingsactivity.dex.jar.xzs, -0, assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser-1.dex.jar.xzs.tmp~.meta, -0, assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser.dex.jar.xzs, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, frsc, -0, assets/thirdparty.mapbox.mapboxglnative/libs.xzs, -0, assets/xplat.rtc.librtc/libs.xzs, -0, fbfx, -0, json, -0, webp, -0, key, -0, FBSIG, -0, arsc, -I, /home/steve/.local/share/apktool/framework/1.apk, -S, /home/steve/debullshification/repo/test/res, -M, /home/steve/debullshification/repo/test/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

### APK
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-161-0-0-35-93-release/facebook-161-0-0-35-93-2-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes.
2. If you are trying to install a modified apk, did you resign it?
N/A
3. Are you using the latest apktool version?
Yes. Used v2.3.1 and also tried top-of-tree as of 34a2d03 with same results.

**Comment by evilwombat** [comment] 2018-03-03 09:05
After reading other issues some more, this looks to be related to part 2 of https://github.com/iBotPeaches/Apktool/issues/1719. Sorry about the churn.

**Comment by iBotPeaches** [comment] 2018-03-06 14:57
Correct. This is the result of the new custom AndroResGuard that Facebook is using. Still working out the type issues which is what is causing those drawable2 etc types. Moving into the other ticket to keep things organized.

Duplicate of #1719

**Closed by iBotPeaches** 2018-03-06 14:57 UTC
Labels: Duplicate
