### ISSUE TITLE
error while recompiling

### ISSUE THREAD

**Issue by golditaradipa** [iBotPeaches/Apktool#1148] opened 2016-01-28 08:51 UTC
C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\res\layout-v21\abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'touchscreenBlocksFocus' in package 'android'

C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\res\drawable-v21\abc_cab_background_top_material.xml:2: error: No resource identifier found for attribute 'paddingMode' in package 'android'
```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\GOLDIV~1\AppData\Local\Temp\brut_util_Jar_5320501368477827346.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 75, --version-name, 1.0.83, -F, C:\Users\GOLDIV~1\AppData\Local\Temp\APKTOOL2709538103983845096.tmp, -0, arsc, -0, Processor, -0, arsc, -I, C:\Users\goldivansyah\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\res, -M, C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
	at brut.androlib.Androlib.buildResources(Androlib.java:410)
	at brut.androlib.Androlib.build(Androlib.java:298)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\GOLDIV~1\AppData\Local\Temp\brut_util_Jar_5320501368477827346.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 75, --version-name, 1.0.83, -F, C:\Users\GOLDIV~1\AppData\Local\Temp\APKTOOL2709538103983845096.tmp, -0, arsc, -0, Processor, -0, arsc, -I, C:\Users\goldivansyah\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\res, -M, C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\GOLDIV~1\AppData\Local\Temp\brut_util_Jar_5320501368477827346.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 75, --version-name, 1.0.83, -F, C:\Users\GOLDIV~1\AppData\Local\Temp\APKTOOL2709538103983845096.tmp, -0, arsc, -0, Processor, -0, arsc, -I, C:\Users\goldivansyah\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\res, -M, C:\Users\goldivansyah\Desktop\AdvancedApkTool\3-Out\nice.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
```

pls help

**Comment by iBotPeaches** [comment] 2016-01-28 12:08
Duplicate of #1033 (touchscreenBlocksFocus) & #1019 (undefined resource identifier)

**Closed by iBotPeaches** 2016-01-28 12:08 UTC
Labels: duplicate
