### ISSUE TITLE
com.facebook.katana cannot decode value

### ISSUE THREAD

**Issue by MarcMil** [iBotPeaches/Apktool#940] opened 2015-05-05 17:31 UTC
I have made sure that I removed any old framework file, but I cannot decode the resources of com.facebook.katana:
http://apps.evozi.com/apk-downloader/?id=com.facebook.katana

	java -jar ./brut.apktool/apktool-cli/build/libs/apktool-cli.jar d  com.facebook.katana.apk

	I: Using Apktool 2.0.0-dirty on com.facebook.katana.apk
	I: Loading resource table...
	I: Decoding AndroidManifest.xml with resources...
	I: Loading resource table from file: /home/marc/apktool/framework/1.apk
	I: Regular manifest package...
	I: Decoding file-resources...
	W: Could not decode attr value, using undecoded value instead: ns=internal, name=layout_maxHeight, value=0x00004001
	W: Could not decode attr value, using undecoded value instead: ns=internal, name=layout_minHeight, value=0x00004001
	I: Decoding values */* XMLs...
	Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101055c
		at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
		at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
		at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
		at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:37)
		at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
		at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
		at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
		at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
		at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
		at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
		at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
		at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
		at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
		at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
		at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
		at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
		at brut.apktool.Main.cmdDecode(Main.java:165)
		at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment] 2015-05-05 17:37
Duplicate of #913

**Closed by iBotPeaches** 2015-05-05 17:37 UTC
Labels: duplicate

**Comment by MarcMil** [comment] 2015-05-05 17:38
Oh, ok, haven't seen this one, sorry.
