### ISSUE TITLE
brut.directory.DirUtil.copyToDir() throws (The filename, directory name, or volume label syntax is incorrect) for obfuscated resource

### ISSUE THREAD

**Issue by sergey-wowwow** [iBotPeaches/Apktool#1644] opened 2017-10-18 13:41 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore https://play.google.com/store/apps/details?id=ru.mw

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ??   .xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:165)
        at brut.apktool.Main.cmdDecode(Main.java:160)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: Error copying file: ??    .xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
        ... 3 more
Caused by: java.io.FileNotFoundException: QIWI_3.9.0_apk-dl.com\unknown\??      .xml (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more

```

### Steps to Reproduce
1. Run `apktool.bat d QIWI_3.9.0_apk-dl.com.apk`

### APK
http://dl.apk-cloud.com/root/apk/2017/9/29/ru.mw_30449.apk?f=QIWI_3.9.0_apk-dl.com.apk&id=ru.mw&dl=2

Is that behavior designed? Shouldn't you try to rename it? Or if a filename is too long or contains illegal characters, just assign random ones and write them to a table, and when building the app back, just assign correct ones?

**Comment by iBotPeaches** [comment] 2017-10-19 10:51
Duplicate of #1460

**Closed by iBotPeaches** 2017-10-19 10:51 UTC
