### ISSUE TITLE
ZipFile invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by CrazyLeoJay** [iBotPeaches/Apktool#2287] opened 2020-01-28 03:13 UTC
### Information
1. **Apktool Version (`2.4.1`)** -
2. **Operating System (Mac)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
$ java -jar apktool_2.4.1.jar d /Users/leojay/Desktop/work20200127/Mother.apk -o /Users/leojay/Desktop/work20200127/out
I: Using Apktool 2.4.1 on Mother.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/leojay/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:148)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.androlib.AndrolibException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:103)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:39)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:96)
	... 3 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:938)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:948)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:245)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:285)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:344)
	at com.google.common.io.ByteStreams.read(ByteStreams.java:910)
	at com.google.common.io.ByteStreams.readFully(ByteStreams.java:787)
	at com.google.common.io.ByteStreams.readFully(ByteStreams.java:770)
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:66)
	at org.jf.dexlib2.dexbacked.ZipDexContainer.isDex(ZipDexContainer.java:144)
	at org.jf.dexlib2.dexbacked.ZipDexContainer.getDexEntryNames(ZipDexContainer.java:87)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:78)
	... 5 more
```

### Steps to Reproduce
1. only  ` java -jar apktool_2.4.1.jar d /Users/leojay/Desktop/work20200127/Mother.apk -o /Users/leojay/Desktop/work20200127/out`

### Frameworks
no frameworks

### APK
I can`t provide

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
 > no change
2. If you are trying to install a modified apk, did you resign it?
> in windows no problem，this error in mac
3. Are you using the latest apktool version?
> all version ,i try  2.4.1 , 2.1.2 , 2.4.0

**Comment by Ticklefish** [comment] 2020-02-15 13:38
Are you saying that you don't get this issue in Windows, only on a Mac? If so, that's probably not going to be an issue with apktool - it'll be something to do with the way that MacOS processes ZIP files.

**Comment by zatol** [comment] 2020-03-24 10:57
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: java.util.zip.ZipException: invalid LOC header (bad signature)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:148)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
Caused by: brut.androlib.AndrolibException: java.util.zip.ZipException: invalid
LOC header (bad signature)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:103)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:39)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:96)
        ... 3 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method)
        at java.util.zip.ZipFile.access$1400(Unknown Source)
        at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)

        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at com.google.common.io.ByteStreams.read(ByteStreams.java:910)
        at com.google.common.io.ByteStreams.readFully(ByteStreams.java:787)
        at com.google.common.io.ByteStreams.readFully(ByteStreams.java:770)
        at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:66)
        at org.jf.dexlib2.dexbacked.ZipDexContainer.isDex(ZipDexContainer.java:1
44)
        at org.jf.dexlib2.dexbacked.ZipDexContainer.getDexEntryNames(ZipDexConta
iner.java:87)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:78)
        ... 5 more|
原因
apk包不完整导致的

**Comment by iBotPeaches** [comment] 2020-04-12 10:25
Sorry for the delay.

When dealing with low level unzip issues, we normally need the apk to begin any investigation. Or at least a reproducible small test file.

Since neither were provided. I am going to close this. We can revisit if those are provided. Thanks again and sorry for delay.

**Closed by iBotPeaches** 2020-04-12 10:25 UTC
