### ISSUE TITLE
Throws error when trying to open apk

### ISSUE THREAD

**Issue by Rayn322** [iBotPeaches/Apktool#2289] opened 2020-01-29 23:34 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1 on Audica.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/ryan/Library/Preferences/apk-editor-studio/frameworks/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:158)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:179)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file: assets
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:145)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: bin/Data/level3.split9
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
	... 5 more
Caused by: java.util.zip.ZipException: invalid stored block lengths
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at brut.util.BrutIO.copyAndClose(BrutIO.java:38)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
	... 8 more
```

### Steps to Reproduce
1. Try to open an apk on my computer?

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by jackwpa** [comment] 2020-01-30 21:58
Can you share an APK?

**Comment by Rayn322** [comment] 2020-01-30 23:59
I didn't rename the apk after getting it onto my computer and it worked.

**Comment by jackwpa** [comment] 2020-01-31 17:27
What had you renamed it to? That explication does not make much sense.

**Comment by Rayn322** [comment] 2020-02-01 17:28
I agree that doesn't make any sense. I renamed it from something similar to "2020-01-31T03-34-54.942Z_1.0.2.1.apk" to "Audica.apk".

**Comment by Ticklefish** [comment] 2020-02-15 13:35
This could be a duplicate of issue 1460: [https://github.com/iBotPeaches/Apktool/issues/1460](url)

In that issue, there are characters in the APK that can't be read by a Windows system.

**Comment by iBotPeaches** [comment] 2020-04-12 10:23
Sorry for the delay.

There are so many known and unknown crashes in that zip handler in your stacktrace I don't know what to do with this without an application. The last error makes it look like the stream is reading passed the data. The first few are usually encoding related.

Unfortunately without an application there is no feasible method for fixing this. So I'm going to close.

**Closed by iBotPeaches** 2020-04-12 10:23 UTC
