### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by Octolus** [iBotPeaches/Apktool#1654] opened 2017-11-03 18:47 UTC
I've been trying to find a solution for this for a very long time, is there any?

Caused by: java.io.IOException: CreateProcess error=206, Filnavnet eller filtypen er for lang
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 9 more

**Comment by ibuprophen1** [comment] 2017-11-03 19:24
I think that I've encountered this before but, it was a while ago... 

If I'm remembering correctly, I believe thattThis happens when the number of characters exceeds 255 characters. This is a NTFS filesystem limit.

I think that I had solved this issue by simply reducing the number of characters in the file. 

If I'm wrong, then it would be great for someone (like @iBotPeaches) could provide a correction to this because I'm just going by memory.

**Comment by CunningLogic** [comment] 2017-11-03 19:50
If you can post the apk, I can probably provide a solution

**Comment by Octolus** [comment] 2017-11-05 19:46
@CunningLogic https://octolus.net/example.rar

**Comment by iBotPeaches** [comment] 2017-11-23 11:13
Correct. This is a duplicate of #1272 

I am working on a solution to stage "groups" of changes to the application. So we do not exceed system limits of maximum command length.

**Closed by iBotPeaches** 2017-11-23 11:13 UTC
