### ISSUE TITLE
Implicit qualifiers removed during decode

### ISSUE THREAD

**Issue by mentalmuso** [iBotPeaches/Apktool#1761] opened 2018-04-03 14:25 UTC
### Information
1. Apktool 2.3.1 and 2.3.2 snapshot
2. Linux
3. SystemUI.apk and framework-res.apk from note 8 Oreo firmware

The resource folder layout changes from the original apk, for instance in the original SystemUI.apk there is an animator-v21 folder but the disappears when decompiled and files move to a simple animator folder.
```

### Steps to Reproduce
1. `apktool d SystemUI.apk
2. apktool b SystemUI -c
3. Flash new apk, results in SystemUI crash

### Frameworks

**Comment by mentalmuso** [comment] 2018-04-03 14:27
framework-res - https://drive.google.com/open?id=1NvP6XVG2YGrqKHB5fww95n8BVr56KPfR

SystemUI - https://drive.google.com/open?id=1zrpD3tHIg9XWwAyGQkV9XNU0flJjvFFS

**Comment by folgore95** [comment] 2018-04-03 17:58
Issues already know. Same thing for S8/S8+ on Oreo.

**Comment by mentalmuso** [comment] 2018-04-03 18:31
Great, thanks mate

**Comment by folgore95** [comment] 2018-04-03 21:02
Also there are some problems when decompiling system apps of Samsung Oreo ( missing correct layout folder name ) . @djdarkknight96 already reported .

**Comment by iBotPeaches** [comment] 2018-04-06 16:43
Are you positive the removal of version qualifiers is the cause of these crashes? Without the stacktrace of error, I don't know.

This probably cannot be resolved as this breaks way more applications when fixing. Nothing in the qualifiers say the "animator-v21" has an SDK version of 21. That value is actually completely null.

This means it was an implicit version added, which is a the directory level, not qualifier. You can confirm this by running `aapt d configurations SystemUI.apk`. You won't see a single version qualifier. They are all implicit. 

This means to properly determine implicit qualifiers, you have to look into the resources to determine if an attribute used is from a newer API. This requires hardcoded list of properties and the API version they were added at, which aapt1 and aapt2 do - https://github.com/aosp-mirror/platform_frameworks_base/blob/06169ed6b34b10fd49ab2633ac32e1eb095f22a1/tools/aapt2/SdkConstants.cpp#L73 not to mention the code able to read attributes at the resource level, which Apktool is far from being able to do. This even if added would slow down Apktool 100x, because we don't have a linked list C++ data struct, we'd need to crawl the XML with some pull-parser.

However, we disable that because of other bugs. Applications built before that version of aapt where implicit SDK version was done, will now be implicitly versioned. That breaks things.

We cannot win this battle.

 - We enable implicit SDK versioning, and applications break that don't have SDK versions that can't handle resources/etc moving under version qualifiers.
 - We disable implicit SDK versioning and this report suggests applications break, because the application was coded to locate resources without the version qualifier.

Unrelated to all this, this ticket is now a hard-block before weekend release. I introduced a regression when building an application. I record the resource directory name for assets and not the qualifier produced directory name, which as explained above might be `drawable-v21 vs drawable`. This will produce a hard failure.

```
I: Copying unknown files/dir...
java.io.FileNotFoundException: SystemUI/res/drawable-ldrtl-xxhdpi-v4/ic_sysbar_back_carmode.webp (No such file or directory)
```

**Comment by char101** [comment] 2018-08-21 10:07
In my case when modifying framework-res.apk from OP6, using either the original res/ (with version modifier) or the res/ (without version modifier) from apktool does not work (SystemUI crashed). What worked was combining both the old and new res/ (i.e. with and without version modifier).

**Comment by iBotPeaches** [comment] 2020-11-30 02:38
Going to close this for roadmap - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#implicit-qualifiers-cleanup

This is a much larger problem that requires more planning then this ticket.

**Closed by iBotPeaches** 2020-11-30 02:38 UTC
Labels: Bug
