### ISSUE TITLE
Cannot decompile/recompile settings.apk

### ISSUE THREAD

**Issue by uday4all** [iBotPeaches/Apktool#1183] opened 2016-03-06 03:18 UTC
hi,i have 2 framework apks  (framework-res.apk and mediatek-res.apk) and installed them.
apktool can succesfully decompile and recompile SystemUI.apk
but it fails on Settings.apk

files i working on(extensions renamed):
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/160150/framework-res.zip)
[mediatek-res.zip](https://github.com/iBotPeaches/Apktool/files/160151/mediatek-res.zip)
[Settings.zip](https://github.com/iBotPeaches/Apktool/files/160152/Settings.zip)
[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/160153/SystemUI.zip)

the decompile log

```
C:\Users\Uday\apktool>apktool d Settings.apk
I: Using Apktool 2.0.3 on Settings.apk
I: Loading resource table...
W: Skipping "android" package group
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Uday\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\Uday\apktool> 
```

the recompile log 
to keep the looking simple,providing txt file [recompile log](https://github.com/iBotPeaches/Apktool/files/160139/recompile.txt)
'[recompile.txt](https://github.com/iBotPeaches/Apktool/files/160139/recompile.txt)
`

for SystemUI.apk,decompiling and recompiling is successful [SystemUI operations](https://github.com/iBotPeaches/Apktool/files/160141/systemui.txt)
`
[systemui.txt](https://github.com/iBotPeaches/Apktool/files/160141/systemui.txt)
`

Additional details :
API Level 19 Kitkat 4.4.2

**Comment by iBotPeaches** [comment] 2016-03-06 17:35
Duplicate of #1157

**Closed by iBotPeaches** 2016-03-06 17:35 UTC
