### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec

### ISSUE THREAD

**Issue by etmatrix** [iBotPeaches/Apktool#1376] opened 2016-12-08 18:05 UTC
### Information
1. Version: 2.2.1
2. OS: Linux
3. APK From: Playstore

### Stacktrace/Logcat
W: /tmp/base/AndroidManifest.xml:34: Tag \<application> attribute name has invalid character ''.
W: /tmp/base/AndroidManifest.xml:42: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:43: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:44: Tag \<activity> attribute name has invalid character ';'.
W: /tmp/base/AndroidManifest.xml:45: Tag \<activity> attribute name has invalid character ''.
W: /tmp/base/AndroidManifest.xml:46: Tag \<activity> attribute name has invalid character '('.
W: /tmp/base/AndroidManifest.xml:57: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:58: Tag \<activity> attribute name has invalid character '9'.
W: /tmp/base/AndroidManifest.xml:59: Tag \<activity> attribute name has invalid character ''.
W: /tmp/base/AndroidManifest.xml:61: Tag \<activity> attribute name has invalid character '0'.
W: /tmp/base/AndroidManifest.xml:62: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:63: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:64: Tag \<activity> attribute name has invalid character '='.
W: /tmp/base/AndroidManifest.xml:65: Tag \<activity> attribute name has invalid character 'u'.
W: /tmp/base/AndroidManifest.xml:66: Tag \<activity> attribute name has invalid character '{'.
W: /tmp/base/AndroidManifest.xml:67: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:118: Tag \<activity> attribute name has invalid character 'v'.
W: /tmp/base/AndroidManifest.xml:119: Tag \<activity> attribute name has invalid character '�'.
W: /tmp/base/AndroidManifest.xml:158: Tag \<service> attribute name has invalid character 'x'.

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2378830923611381623.tmp, p, --forced-package-id, 127, --min-sdk-version, 3, --target-sdk-version, 21, --version-code, 388, --version-name, 7.6.0, -F, /tmp/APKTOOL5145675347682530280.tmp, -0, R, -0, arsc, -0, apk, -0, arsc, -I, /home/enzo/.local/share/apktool/framework/1.apk, -S, /tmp/base/res, -M, /tmp/base/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2378830923611381623.tmp, p, --forced-package-id, 127, --min-sdk-version, 3, --target-sdk-version, 21, --version-code, 388, --version-name, 7.6.0, -F, /tmp/APKTOOL5145675347682530280.tmp, -0, R, -0, arsc, -0, apk, -0, arsc, -I, /home/user/.local/share/apktool/framework/1.apk, -S, /tmp/base/res, -M, /tmp/base/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2378830923611381623.tmp, p, --forced-package-id, 127, --min-sdk-version, 3, --target-sdk-version, 21, --version-code, 388, --version-name, 7.6.0, -F, /tmp/APKTOOL5145675347682530280.tmp, -0, R, -0, arsc, -0, apk, -0, arsc, -I, /home/enzo/.local/share/apktool/framework/1.apk, -S, /tmp/base/res, -M, /tmp/base/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more

### Steps to Reproduce
1. ./apktool d base.apk
2. ./apktool b base

### APK
https://play.google.com/store/apps/details?id=com.keramidas.TitaniumBackup&hl=it

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

**Comment by etmatrix** [comment] 2016-12-09 12:41
I have the same issue with lastest version from github (164c64cec239431224ac8fecee0424fd0b4c22dd)

**Comment by iBotPeaches** [comment] 2016-12-09 13:07
Yes, known bug. #885 

Closing as duplicate.

**Closed by iBotPeaches** 2016-12-09 13:07 UTC
Labels: Duplicate

**Comment by DaveOak** [comment] 2017-01-27 16:54
Simply using _apktool d_ and _apktool b_ I get the following errors. I am not modifying the unpacked apk and this previously worked on earlier versions of the source apk.

I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/res/values-v21/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/SegmentedButton'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/d9/2dqlhlcd6hq6v6x7cj9pfq3m0000gn/T/brut_util_Jar_2868060030181813312.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 19, --version-code, 2008000, --version-name, 2.8.0, --no-version-vectors, -F, /var/folders/d9/2dqlhlcd6hq6v6x7cj9pfq3m0000gn/T/APKTOOL8172964557381333528.tmp, -0, assets/META-INF/AIR/extensions/com.oak.amazondevicemessaging/library.swf, -0, assets/META-INF/AIR/extensions/com.oak.amazondevicemessaging/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/pl.mateuszmackowiak.nativeANE.properties.SystemProperties/library.swf, -0, assets/META-INF/AIR/extensions/pl.mateuszmackowiak.nativeANE.properties.SystemProperties/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.milkmangames.extensions.GoogleServices/library.swf, -0, assets/META-INF/AIR/extensions/com.milkmangames.extensions.GoogleServices/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.freshplanet.AirAlert/library.swf, -0, assets/META-INF/AIR/extensions/com.freshplanet.AirAlert/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.amazon.device.iap.cpt.AmazonIapV2Extension/library.swf, -0, assets/META-INF/AIR/extensions/com.amazon.device.iap.cpt.AmazonIapV2Extension/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.jirbo.airadc.AirAdColony/library.swf, -0, assets/META-INF/AIR/extensions/com.jirbo.airadc.AirAdColony/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.illuzor.extensions.SharingExtension/library.swf, -0, assets/META-INF/AIR/extensions/com.illuzor.extensions.SharingExtension/META-INF/ANE/Android-ARM/library.swf, -0, res/raw/rgba8888, -0, res/raw/debuginfo, -0, arsc, -I, /Users/dave/Library/apktool/framework/1.apk, -S, /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/res, -M, /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/d9/2dqlhlcd6hq6v6x7cj9pfq3m0000gn/T/brut_util_Jar_2868060030181813312.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 19, --version-code, 2008000, --version-name, 2.8.0, --no-version-vectors, -F, /var/folders/d9/2dqlhlcd6hq6v6x7cj9pfq3m0000gn/T/APKTOOL8172964557381333528.tmp, -0, assets/META-INF/AIR/extensions/com.oak.amazondevicemessaging/library.swf, -0, assets/META-INF/AIR/extensions/com.oak.amazondevicemessaging/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/pl.mateuszmackowiak.nativeANE.properties.SystemProperties/library.swf, -0, assets/META-INF/AIR/extensions/pl.mateuszmackowiak.nativeANE.properties.SystemProperties/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.milkmangames.extensions.GoogleServices/library.swf, -0, assets/META-INF/AIR/extensions/com.milkmangames.extensions.GoogleServices/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.freshplanet.AirAlert/library.swf, -0, assets/META-INF/AIR/extensions/com.freshplanet.AirAlert/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.amazon.device.iap.cpt.AmazonIapV2Extension/library.swf, -0, assets/META-INF/AIR/extensions/com.amazon.device.iap.cpt.AmazonIapV2Extension/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.jirbo.airadc.AirAdColony/library.swf, -0, assets/META-INF/AIR/extensions/com.jirbo.airadc.AirAdColony/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.illuzor.extensions.SharingExtension/library.swf, -0, assets/META-INF/AIR/extensions/com.illuzor.extensions.SharingExtension/META-INF/ANE/Android-ARM/library.swf, -0, res/raw/rgba8888, -0, res/raw/debuginfo, -0, arsc, -I, /Users/dave/Library/apktool/framework/1.apk, -S, /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/res, -M, /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/d9/2dqlhlcd6hq6v6x7cj9pfq3m0000gn/T/brut_util_Jar_2868060030181813312.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 19, --version-code, 2008000, --version-name, 2.8.0, --no-version-vectors, -F, /var/folders/d9/2dqlhlcd6hq6v6x7cj9pfq3m0000gn/T/APKTOOL8172964557381333528.tmp, -0, assets/META-INF/AIR/extensions/com.oak.amazondevicemessaging/library.swf, -0, assets/META-INF/AIR/extensions/com.oak.amazondevicemessaging/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/pl.mateuszmackowiak.nativeANE.properties.SystemProperties/library.swf, -0, assets/META-INF/AIR/extensions/pl.mateuszmackowiak.nativeANE.properties.SystemProperties/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.milkmangames.extensions.GoogleServices/library.swf, -0, assets/META-INF/AIR/extensions/com.milkmangames.extensions.GoogleServices/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.freshplanet.AirAlert/library.swf, -0, assets/META-INF/AIR/extensions/com.freshplanet.AirAlert/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.amazon.device.iap.cpt.AmazonIapV2Extension/library.swf, -0, assets/META-INF/AIR/extensions/com.amazon.device.iap.cpt.AmazonIapV2Extension/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.jirbo.airadc.AirAdColony/library.swf, -0, assets/META-INF/AIR/extensions/com.jirbo.airadc.AirAdColony/META-INF/ANE/Android-ARM/library.swf, -0, assets/META-INF/AIR/extensions/com.illuzor.extensions.SharingExtension/library.swf, -0, assets/META-INF/AIR/extensions/com.illuzor.extensions.SharingExtension/META-INF/ANE/Android-ARM/library.swf, -0, res/raw/rgba8888, -0, res/raw/debuginfo, -0, arsc, -I, /Users/dave/Library/apktool/framework/1.apk, -S, /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/res, -M, /Users/dave/git/OddSocks/FDT/OddSocksAmazon/build/temp/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more

**Comment by DaveOak** [comment] 2017-01-27 16:57
Further info - the source APK is created by FDT as an Adobe AIR application for Android. It is not obfuscated, but various components (including AIR) have been updated since the last successful build of the APK.

**Comment by coolpixs4** [comment] 2017-02-06 02:31
help me please,

C:\apktool_miui7>apktool if framework-res.apk
I: Framework installed to: C:\Users\Admin\AppData\Local\apktool\framework\1.apk

C:\apktool_miui7>apktool if framework-ext-res.apk
I: Framework installed to: C:\Users\Admin\AppData\Local\apktool\framework\17.apk


C:\apktool_miui7>java -jar ./apktool.jar b facebook
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.err.Ca
ntFindFrameworkResException
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.err.CantFindFrameworkResException
        at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources
.java:592)
        at brut.androlib.Androlib.parseUsesFramework(Androlib.java:718)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        ... 5 more

**Comment by Ahmed7fathi** [comment] 2017-12-09 15:23
same issue here

**Comment by fighter-lee** [comment] 2017-12-15 02:27
apktool 2.3.0 support version should below 26, example: implementation "com.android.support:appcompat-v7:25.+"

**Comment by Ben1981** [comment] 2017-12-24 11:31
this issue is about missing resources, look for missing resources, might be a missing resource for external library.

**Comment by ouihamdaoui** [comment] 2018-01-12 01:46
Help me please to correct, I'm on Android M 6.0.1+ framework
Same error during recomplie apk...

Thank you !
 Log For : app.apk 

 Log Type : Recompiling 

 Log Recorded At : 12 2018-01- 2:22:58,11 

 Log Recorded By : Advanced ApkTool v4.2.0 By BDFreak 

------------------------------------------------------ 

W: C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml:16: error: No resource identifier found for attribute 'roundIcon' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_1479779000625798190.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, --no-version-vectors, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL5360200212280990529.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_1479779000625798190.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, --no-version-vectors, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL5360200212280990529.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_1479779000625798190.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, --no-version-vectors, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL5360200212280990529.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)

**Comment by DevGracyy** [comment] 2018-03-28 11:24
same issue please help us :D

**Comment by blue0527** [comment] 2018-06-26 15:39
add param -r, apktool -r d xxx.apk

**Comment by blue0527** [comment] 2018-06-26 15:41
apktool -r d xxx.apk -o test
apktool b test

use -r parameter

**Comment by rogan528** [comment] 2019-08-12 02:38
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit  code = -1073741515)
how to resolve it ?

**Comment by rtmweiyi** [comment] 2019-08-12 03:39
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515)
> how to resolve it ?

Hi,I facing the same issue as you, are you using the version 2.4.0?
After I used version 2.3.4,the issue was resolved.

**Comment by rogan528** [comment] 2019-08-12 06:42
> > brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515)
> > how to resolve it ?
> 
> Hi,I facing the same issue as you, are you using the version 2.4.0?
> After I used version 2.3.4,the issue was resolved.

not resolve. 
java -jar apktool_2.3.4.jar b XX  
\res\values\public.xml:170:error: Public symbol array/a declared here is not defined
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit  code = 1)
res\values\public.xml:174:error: Public symbol array/c declared here is not defined

**Comment by pandusetiawan** [comment] 2019-09-20 16:14
No solution for this issue yet?

**Comment by Sadykov70** [comment] 2019-10-16 17:21
> I resolved the issue with this step :
> 
> 1. fix JAVA_HOME and JRE_HOME environment variable
> 2. Add apktool path to system PATH
> 3. Open apktool 2.4.0 version using winrar, delete apt.exe and apt2.exe
> 4. Download apktool 2.3.4, open it using winrar, copy apt.exe and apt2.exe to apktool 2.4.0
> 
> Hope this can help.

Thanks for this info. After downgrading to 2.3.4 (by replacing apktool_2.4.0.jar with the old  2.3.4)  helped me.

**Comment by yashrs** [comment] 2019-11-24 10:53
@pandusetiawan Thanks!! It worked like a charm
