### ISSUE TITLE
Brut could not exec error in recompiling

### ISSUE THREAD

**Issue by UltraWelfare** [iBotPeaches/Apktool#1383] opened 2016-12-17 15:13 UTC
### Information
1. 2.2.2-164c64-SNAPSHOT (Same issue for 2.2.1) 
2. Windows 10 64 bit 
3. Mirror APK 

### Stacktrace/Logcat
http://pastebin.com/DPVpPjWu
Scroll down to 177 line

### Steps to Reproduce
1.Download latest messenger apk 101.0.0.0.100 beta
2. apktool d messenger.apk
3. apktool b messenger -o test.apk

### Frameworks
None

### APK
[APK from MirrorAPK](http://www.apkmirror.com/wp-content/uploads/uploaded/58535508301a2/com.facebook.orca_101.0.0.0.100-46056930_minAPI21(armeabi-v7a)(280,360,400,420,480,560,640dpi)_apkmirror.com.apk)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? : Yeah
2. If you are trying to install a modified apk, did you resign it? : It doesn't build so I cant resign it
3. Are you using the latest apktool version? I tried both 2.2.1 and building the git repository but its the same error

**Comment by UltraWelfare** [comment] 2016-12-17 17:02
I pulled the apk straight out of my phone and it did recompile..I don't know what went wrong there

**Comment by iBotPeaches** [comment] 2016-12-18 13:56
Duplicate of #1360

**Closed by iBotPeaches** 2016-12-18 13:56 UTC
Labels: Duplicate
