### ISSUE TITLE
BUG：MOTO360 5.0.2 ClockworkHomeGoogle.apk  decompile error

### ISSUE THREAD

**Issue by mapleshadow** [iBotPeaches/Apktool#944] opened 2015-05-12 15:44 UTC
1、The folder name changes, and lost RAW folder, See the picture。
![apktool-1](https://cloud.githubusercontent.com/assets/525478/7591312/bea0740c-f8ff-11e4-8957-f84d9055b7ec.JPG)
2、Compiled files can not be used, it would lead to moto360 not boot properly.
Attach the framework-res and files, for testing.
http://pan.baidu.com/s/1eQvolY6

**Comment by iBotPeaches** [comment] 2015-05-13 12:19
None of the files in `res/raw` have an extension, which makes this a duplicate of #921.

**Closed by iBotPeaches** 2015-05-13 12:19 UTC

**Comment by mapleshadow** [comment] 2015-05-13 13:22
When I put all the manual after anti compiler is not consistent with the original directory of APK plus -v4, is a directory with the original APK directory, again compiled APK can work.
This should be a BUG, please fix.

**Comment by iBotPeaches** [comment] 2015-05-13 13:43
No, it is a duplicate of a bug. Trust me, I know my bug tracker.

`v4` - #928 
`res/raw` - #921

**Comment by mapleshadow** [comment] 2015-05-18 00:47
Thank you for your work, this is indeed a problem, expecting to solve :)
