### ISSUE TITLE
File Not Found. Error: Unable to access jarfile C:\Windows\apktool_0.jar

### ISSUE THREAD

**Issue by Eldonz0** [iBotPeaches/Apktool#2803] opened 2022-04-27 07:46 UTC
CMD : 

C:\Windows>apktool
File Not Found
Error: Unable to access jarfile C:\Windows\apktool_0.jar

Can anyone please help me with this I already walked through the process exactly as it should be, what am I missing?

**Comment by auermich93** [comment] 2022-04-28 12:22
Did you follow these instructions: https://ibotpeaches.github.io/Apktool/install/?

To quote from there:

> Rename downloaded jar to apktool.jar

It seems you didn't rename it.

> If you do not have access to C://Windows, you may place the two files anywhere then add that directory to your Environment Variables System PATH variable.

Try out a different location, e.g. ~/Downloads, where you place both files.

**Comment by iBotPeaches** [comment] 2022-05-07 11:55
This looks like a support issue and not a bug. Help looks like it was posted anyway, so closing.

**Closed by iBotPeaches** 2022-05-07 11:55 UTC
