### ISSUE TITLE
apktool.bat b xx.apk failed

### ISSUE THREAD

**Issue by genius-ye** [iBotPeaches/Apktool#2080] opened 2019-05-25 08:35 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Playstore

### Stacktrace/Logcat

![image](https://user-images.githubusercontent.com/5753805/58366839-b4216a00-7f0a-11e9-8722-e76d2a2bb87d.png)

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment] 2019-06-02 21:53
In the future, please don't use images. The stacktrace cannot be searched and its difficult to read images vs text. This is a duplicate of #1427

**Closed by iBotPeaches** 2019-06-02 21:53 UTC
