### ISSUE TITLE
First type is not attr!

### ISSUE THREAD

**Issue by askary94** [iBotPeaches/Apktool#2375] opened 2020-07-10 13:08 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** - https://play.google.com/store/apps/details?id=com.instagram.android

### Stacktrace/Logcat

```
[aapt] invalid resource directory name: /home/xxx/APK/instagram/res/values-watch-v20
[aapt] invalid resource directory name: /home/xxx/APK/instagram/res/drawable-anydpi-v21
[aapt] invalid resource directory name: /home/xxx/APK/instagram/res/mipmap-anydpi-v26
[aapt] invalid resource directory name: /home/xxx/APK/instagram/res/layout-watch-v20
[aapt] invalid resource directory name: /home/xxx/APK/instagram/res/drawable-watch-v20
[aapt] invalid resource directory name: /home/xxx/APK/instagram/res/values-watch-v21
```

### Steps to Reproduce
I use `apktool ` to analyze applications. Thus
1- I decompile these applications with `apktool `.
2- By putting these files together and setting the project in the form of `ant ` project
3-I command `sudo ant clean debug ` in the terminal.
Which gives this error during debugging

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? 2.4.0

**Comment by Ticklefish** [comment] 2020-07-11 16:52
This doesn't sound like an apktool issue but..

The error you got from aapt says that you have an invalid resource directory name. Since "values-watch-v20" is a perfectly valid directory name in Android the problem must come from something else. 
Try changing "My Earthquake Alerts2" to something like "My_Earthquake_Alerts2" without the whitespace. I'm not sure what that's got to do with Instagram, or first types not being attr, but that looks like a good possibility to me.

**Comment by askary94** [comment] 2020-07-11 18:18
Hello. Thank you very much for your reply.
I've tested it on different programs and it gives each of them the same error. 
I didn't notice that I putting the ```Instagram``` app.
Yes, maybe you are right. Apparently it's not related to ```apktool```, but I also created the simplest project with the ```gradle structure```, but ```apktool``` generates folders in resources that are not in the main program (for example, ```values-b+sr+Latn```) . These folders give me an error during debugging, and when we delete such folders, it leads to ```aapt``` error.

**Comment by iBotPeaches** [comment] 2020-11-27 15:58
I can't really follow this report. Generally that error I've seen in the past when trying to recompile an application with aapt1, that was built with aapt2. 

Hope that helps. Closing as this appears to be support and not a bug in the tool.

**Closed by iBotPeaches** 2020-11-27 15:58 UTC
