### ISSUE TITLE
Cannot decode reference values for Google Chrome apk.

### ISSUE THREAD

**Issue by heyitsdross** [iBotPeaches/Apktool#1752] opened 2018-03-23 12:17 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - MacOS 10.13.3
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/google-chrome-fast-secure/com.android.chrome

### Stacktrace/Logcat

```
I: Using Apktool 2.3.1 on Google Chrome Fast Secure_v65.0.3325.109_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/username/Library/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f12011a
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f080141
W: Could not decode attr value, using undecoded value instead: ns=android, name=manageSpaceActivity, value=0x7f120345
W: Could not decode attr value, using undecoded value instead: ns=android, name=networkSecurityConfig, value=0x7f160016
W: Could not decode attr value, using undecoded value instead: ns=android, name=roundIcon, value=0x7f080142
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160004
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300f4
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160013
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16001b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300f3
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0003
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=enableVrMode, value=0x7f1202d5
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301d8
W: Could not decode attr value, using undecoded value instead: ns=android, name=enableVrMode, value=0x7f1202d5
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13015e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13015e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13015e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f130156
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300e3
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13015d
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301d7
W: Could not decode attr value, using undecoded value instead: ns=android, name=enableVrMode, value=0x7f1202d5
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f130138
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f130138
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300e9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300e9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300e9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1301eb
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0f0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f080268
W: Could not decode attr value, using undecoded value instead: ns=android, name=enableVrMode, value=0x7f1202d5
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f080265
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000f
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f120171
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160008
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1204ca
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16001a
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13014e
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160011
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300e2
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f0b000e
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300ee
I: Renamed manifest package found! Replacing com.android.chrome with FFFFFFFFFFFFFFFFFFFFFF
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

### Steps to Reproduce
1. `apktool d Google\ Chrome\ Fast\ Secure_v65.0.3325.109_apkpure.com.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/google-chrome-fast-secure/com.android.chrome

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Cannot complete apktool d.
2. If you are trying to install a modified apk, did you resign it? No modifications.
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment] 2018-04-06 18:28
Yeah another weird package of `FFFFFFFFFFFFFFFFFFFFFF`. This is a duplicate of #1471 , thanks for the report. Another application that experiences that issue may help identify this issue.

**Closed by iBotPeaches** 2018-04-06 18:28 UTC

**Comment by ChristophHeilmann** [comment] 2018-04-08 16:35
How can I edit the .pak files in assets?
