### ISSUE TITLE
Can't decode apk

### ISSUE THREAD

**Issue by evco1** [iBotPeaches/Apktool#1101] opened 2015-12-10 13:25 UTC
Hi, I'm trying to decode the settings apk of my stock rom but it throws an exception:
```
D:\>apktool d -o Settings.apk_output Settings.apk
I: Using Apktool 2.0.3-0649d5-SNAPSHOT on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\ε∙⌠τ· δΣ∩\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=summary, value=0x010406bb
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResBoolValue cannot be cast to brut.androlib.res.data.value.ResAttr
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:65)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
```
Please fix it.
Thanks!

**Comment by iBotPeaches** [comment] 2015-12-10 13:37
```
W: Could not decode attr value, using undecoded value instead: ns=android, name=summary, value=0x010406bb
```

Looks like you need a different framework with packageId `1`. Which is normally `framework-res.apk`.

2nd issue is duplicate of #1065

**Closed by iBotPeaches** 2015-12-10 13:37 UTC
Labels: duplicate
