### ISSUE TITLE
Linux use apktool problem

### ISSUE THREAD

**Issue by sheep0704** [iBotPeaches/Apktool#1778] opened 2018-04-25 12:04 UTC
### Information
1. **Apktool Version (`apktool -version`)** -V2.2.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** - eclipse apk

  
### Questions to ask before submission
1.  The use of tools can generate compiling,  but the size of packets will increase by tens of megabytes.
2.  Some APK sizes will increase by tens of megabytes, and some APK will not. Linux environment
3.  Windows is Normal system。Bug linuxs the use of tools can generate compiling,  but the size of packets will increase by tens of megabytes.

why.?

**Comment by sheep0704** [comment] 2018-04-25 13:37
GET.解决

**Comment by sheep0704** [comment] 2018-04-25 13:38
2.1.3

**Comment by iBotPeaches** [comment] 2018-04-26 16:48
Duplicate of https://github.com/iBotPeaches/Apktool/issues/1769

Fixed in v2.3.3

**Closed by iBotPeaches** 2018-04-26 16:48 UTC
