### ISSUE TITLE
unable to decode apk

### ISSUE THREAD

**Issue by NimaAliNejad** [iBotPeaches/Apktool#2012] opened 2019-02-13 06:30 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Downloaded from market websites
```
C:\Users\Zanis\Desktop\apktool 2>apktool d App.apk
I: Using Apktool 2.3.4 on App.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Zanis\AppData\Local\apktool\framework\1.apk
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3593
        at brut.androlib.res.decoder.StringBlock.getUtf8(StringBlock.java:317)
        at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:102)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:388)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:155)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:136)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
        at brut.apktool.Main.cmdDecode(Main.java:164)
        at brut.apktool.Main.main(Main.java:73)
```
### APK
If this APK can be freely shared, please upload/attach a link to it.
[here](https://apkpure.com/eleq-live-trivia/com.trivia.eleq)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment] 2019-02-14 15:17
Duplicate of #1306. Thanks for the report!

**Closed by iBotPeaches** 2019-02-14 15:17 UTC
