### ISSUE TITLE
Hangouts v31.0 not decompiling [Q Compat]

### ISSUE THREAD

**Issue by nishithkhanna** [iBotPeaches/Apktool#2133] opened 2019-07-15 07:14 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1-5aa3cf-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Play Store

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:53)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:747)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000202
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:354)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        ... 8 more

```

### Steps to Reproduce
1. `apktool d Hangouts.apk `

### APK
https://www.apkmirror.com/apk/google-inc/hangouts/hangouts-31-0-246194187-release/

**Comment by iBotPeaches** [comment] 2019-07-20 16:05
Looks to be new qualifiers, I imagine Q related. I'll mark this ticket as Q compatibility.

 * https://github.com/aosp-mirror/platform_frameworks_base/commit/7ec28a888c7e59af02aeb0e0a9b078037d317e2e#diff-228741fbe06e061b59e5bd87df20cf28 - unicode qualifiers

**Comment by nishithkhanna** [comment] 2019-07-20 16:12
Hi, Sorry I noticed it after posting the issue here. This was reported before too
https://github.com/iBotPeaches/Apktool/issues/1874
And its from before Q. 
Hope this helps more.

**Comment by iBotPeaches** [comment] 2019-08-17 11:02
Thanks for updating! It does appear to be a duplicate of that issue. I moved the file(s) for this one into the directory locally for the other ticket for organization.

Closing as duplicate of #1874

**Closed by iBotPeaches** 2019-08-17 11:02 UTC
Labels: Bug
