### ISSUE TITLE
Correctly decompiled & recompiled APK crashes on start-up

### ISSUE THREAD

**Issue by LoopsGod** [iBotPeaches/Apktool#2381] opened 2020-07-25 15:51 UTC
### Information
1. **Apktool Version (`apktool -version`)** -
v2.4.1

2. **Operating System (Mac, Linux, Windows)** -
MacOS

3. **APK From? (Playstore, ROM, Other)** -
Playstore/Manufacturer

### Stacktrace/Logcat

```
2020-07-25 17:43:03.503 26542-26542/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.AppComponentFactory" on path: DexPathList[[zip file "/data/app/dji.go.v5-2ay_BUceLK5SA17Q8TVPcw==/base.apk"],nativeLibraryDirectories=[/data/app/dji.go.v5-2ay_BUceLK5SA17Q8TVPcw==/lib/arm64, /data/app/dji.go.v5-2ay_BUceLK5SA17Q8TVPcw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:855)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
        at android.app.LoadedApk.getResources(LoadedApk.java:1188)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2499)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2491)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6508)
        at android.app.ActivityThread.access$1600(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1974)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7707)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Steps to Reproduce
Download the APK here: https://www.dji.com/nl/downloads/djiapp/dji-fly (click on **Download for Android**)

1. Run `apktool d APKHERE`
2. Run `apktool b APKDIRECTORY`
3. Sign the APK
4. Install the APK, make sure you've got an `arm64-v8a` chipset.
5. Start the app, it'll first paint & crash.

Just run apktool, without changing anything, decode + recompile & it fails.

### Frameworks
None

### APK
**DJI Fly:** https://www.dji.com/nl/downloads/djiapp/dji-fly

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes

2. If you are trying to install a modified apk, did you resign it?
Resigned the APK. I've tried to use `--no-src`, etc etc.

3. Are you using the latest apktool version?
Yes, **v2.4.1**

**Comment by nm17** [comment] 2020-07-30 08:36
Can reproduce on a different apk, also missing classes even though I'm using `--no-src`. Please fix!

**Comment by iBotPeaches** [comment] 2020-09-13 17:29
There is just too much in this application for me to spend any time to investigate this. I'm sorry. I just have to be honest. I decoded/rebuilt and dumped out files in comparison to clean and the dirty file had nearly 200 more files, so there is too much to investigate.

Open for any PRs. Closing in meantime.

**Closed by iBotPeaches** 2020-09-13 17:29 UTC

**Comment by nm17** [comment] 2020-09-13 22:06
Well that sucks...

**Comment by giacomoferretti** [comment] 2020-09-13 23:10
> Can reproduce on a completely different apk (not a DJI app), also missing classes even though I'm using `--no-src`. Please fix! I'm using `2.4.0-dirty`.
> Also can reproduce on `2.3.3`.

Is this app smaller than the DJI's one?

**Comment by nm17** [comment] 2020-09-14 11:00
> Is this app smaller than the DJI's one?

It's 4.7 MB

**Comment by giacomoferretti** [comment] 2020-09-14 11:28
> > Is this app smaller than the DJI's one?
> 
> It's 4.7 MB

Can you share it with us? Maybe it's easier to identify the problem with a smaller app.

**Comment by nm17** [comment] 2020-09-14 14:40
[FUAV_com.shenyaocn.android.fuav.zip](https://github.com/iBotPeaches/Apktool/files/5219149/FUAV_com.shenyaocn.android.fuav.zip)

**Comment by nm17** [comment] 2020-09-17 13:27
@giacomoferretti @iBotPeaches Any news?

**Comment by giacomoferretti** [comment] 2020-09-17 13:36
Sorry, not yet. I will look at it in the weekend.

**Comment by giacomoferretti** [comment] 2020-09-19 22:55
@nm17 I don't think your APK it's related to the issue. Your APK doesn't crash on startup, but simply exits because it checks the signature.

**Comment by nm17** [comment] 2020-09-19 22:57
> @nm17 I don't think your APK it's related to the issue. Your APK doesn't crash on startup, but simply exits because it checks the signature.

No it doesn't, I literally made a tool to automatically sign all the apks for me and I later checked that it actually signs them and not just doing nothing. I definitely was running them signed.

**Comment by nm17** [comment] 2020-09-19 22:59
> @nm17 I don't think your APK it's related to the issue. Your APK doesn't crash on startup, but simply exits because it checks the signature.

So you're saying you can repack the apk, without it crashing on startup?

**Comment by giacomoferretti** [comment] 2020-09-19 23:02
The app doesn't crash, it simply calls `finish()` because the signature is different.

**Comment by nm17** [comment] 2020-09-19 23:49
> The app doesn't crash, it simply calls `finish()` because the signature is different.

So what should I do to avoid that? What is `finish()`?

**Comment by giacomoferretti** [comment] 2020-09-20 08:35
`finish()` closes the Activity. You need to modify the app to not check the signature, but I'm not here to tell you how.

**Comment by hunterxxx** [comment] 2020-12-05 13:30
I have similar situation where I resigned the apk before using apktool, installed it without problem.
But when I apktool d, apktool b, it crashes.

**Comment by shipsywor** [comment] 2021-03-06 12:59
@giacomoferretti Can you atleast link to the relevant guides to modify the app so we can search further?
