### ISSUE TITLE
Apktool 2.0.3;ERROR: input directory 'js' does not exist

### ISSUE THREAD

**Issue by blstbbcxz** [iBotPeaches/Apktool#1140] opened 2016-01-18 09:51 UTC
I used apktool 2.0.0version to decompile and recompile my app before,now i change it to apktool 2.0.3version but occur error.

This is the error log:

C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\bin\developTools\jdk1.6.0\bin>cmd.exe /c java.exe -jar C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\bin\developTools\apktool.jar b C:
\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\ProjectZ.apk.dir -o C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\vivo_ProjectZ.apk
I: Using Apktool 2.0.3
I: Checking whether resources has changed...
I: Building resources...
ERROR: input directory 'js' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\pbaichen\AppData\Local\Temp\brut_util_Jar_4353
151712812605047.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0.1, -F, C:\Users\pbaichen\AppData\Local\Temp\APKTOOL626760866300
6663572.tmp, -0, arsc, -0, config, -0, jar, -0, , -0, js, -0, bundle, -0, ui, -0, zip, -0, arsc, -I, C:\Users\pbaichen\apktool\framework\1.apk, -S, C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56
210\cache\temp\ProjectZ.apk.dir\res, -M, C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\ProjectZ.apk.dir\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\pbaichen\AppData\Local\Temp\brut_util_Jar_4353151712812605047.tmp, p, --forced-package-id, 127,
 --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0.1, -F, C:\Users\pbaichen\AppData\Local\Temp\APKTOOL6267608663006663572.tmp, -0, arsc, -0, config, -0, jar, -0, ,
 -0, js, -0, bundle, -0, ui, -0, zip, -0, arsc, -I, C:\Users\pbaichen\apktool\framework\1.apk, -S, C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\ProjectZ.apk.dir\res, -M, C:\Users
\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\ProjectZ.apk.dir\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\pbaichen\AppData\Local\Temp\brut_util_Jar_4353151712812605047.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-s
dk-version, 21, --version-code, 1, --version-name, 1.0.1, -F, C:\Users\pbaichen\AppData\Local\Temp\APKTOOL6267608663006663572.tmp, -0, arsc, -0, config, -0, jar, -0, , -0, js, -0, bundle, -0, ui, -0,
zip, -0, arsc, -I, C:\Users\pbaichen\apktool\framework\1.apk, -S, C:\Users\pbaichen\Desktop\OneSDK_android_windows_r56210\cache\temp\ProjectZ.apk.dir\res, -M, C:\Users\pbaichen\Desktop\OneSDK_android_
windows_r56210\cache\temp\ProjectZ.apk.dir\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more

The key seems to be "js folder", but i don't have a js folder and how can i fix it?

**Comment by iBotPeaches** [comment] 2016-01-18 12:35
Duplicate of #1122 

Fix will be in 2.1.0, check bug for fix in meantime.

**Closed by iBotPeaches** 2016-01-18 12:35 UTC
