### ISSUE TITLE
Build does not work on Linux, permission denied

### ISSUE THREAD

**Issue by PLockhart** [iBotPeaches/Apktool#1238] opened 2016-05-02 12:49 UTC
### Information
1. **Apktool Version** -  (`2.1.0`)
2. **Operating System** -  (Linux) 64bit CENTOS 6.7 x86_64 xenpv – server2
3. **APK From?** - Personal APK from a Unity3d build

### Stacktrace/Logcat
```
[/usr/local/bin]# java -jar apktool.jar b petertests/template.out
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_5268995908417715492.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 2, --version-name, 1.0, -F, /tmp/APKTOOL9033472733835290131.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, split3, -0, split4, -0, split5, -0, split6, -0, split7, -0, resource, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /usr/local/bin/petertests/template.out/res, -M, /usr/local/bin/petertests/template.out/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_5268995908417715492.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 2, --version-name, 1.0, -F, /tmp/APKTOOL9033472733835290131.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, split3, -0, split4, -0, split5, -0, split6, -0, split7, -0, resource, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /usr/local/bin/petertests/template.out/res, -M, /usr/local/bin/petertests/template.out/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_5268995908417715492.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 2, --version-name, 1.0, -F, /tmp/APKTOOL9033472733835290131.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, split3, -0, split4, -0, split5, -0, split6, -0, split7, -0, resource, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /usr/local/bin/petertests/template.out/res, -M, /usr/local/bin/petertests/template.out/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_5268995908417715492.tmp": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

### Steps to Reproduce
(On linux server, in usr/local/bin folder)
1. java -jar apktool.jar d tests/template -o tests/template.out
2. java -jar apktool.jar b /home/tests/template.out
3. Build will fail

### Frameworks
N/A

### APK
Left in work, can update this issue when back in office

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment] 2016-05-02 13:00
This is because you don't have write permission on the default directory of `/tmp` for executing binaries. That is where the internal aapt binary is copied and executed. You have two options. 

1. Fix the permissions on executing binaries from `/tmp`. Potentially dangerous depending on the environment used.

2. Grab the internal aapt you need from here - https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/main/resources/prebuilt/aapt and place it on your filesystem in a readable directory, then use `-a / --aapt` to point to that location.

Adding support for `-a / --aapt` to designate the location of the internal aapt binary is already an open issue - https://github.com/iBotPeaches/Apktool/issues/1017

So closing this.

**Closed by iBotPeaches** 2016-05-02 13:00 UTC
Labels: Not a Bug

**Comment by PLockhart** [comment] 2016-05-02 13:07
Ok will try I double check tomorrow, thanks. I thought I was sure I had set the permissions correctly in the temp directory. What about [the duplicate apk delete command above it?](https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java#L417)

**Comment by iBotPeaches** [comment] 2016-05-02 14:47
The entire function needs a cleanup. Just looks messy. Thanks for the tip, but that line is a duplicate and there seems to be some room for improvement in that function to cut down on all the `new File()` calls.

**Comment by designzoo-peter** [comment] 2016-05-03 07:20
Thanks for the speedy replies. I have double checked I have the correct permissions in the tmp directory

> root@server2 [/]# ls -ld tmp
drwxrwxrwt 10 root root 81920 May  3 08:18 tmp/

Considering the code successfully passes the 1st delete call but not the 2nd, I'm inclined to think it is a bug. Maybe we run different java versions that handle things differently?

**Comment by designzoo-peter** [comment] 2016-05-03 08:09
I went to use the 2nd option, using the aapt file for Linux, but I think there is something wrong with the file. I get the following output:

> root@server2 [/usr/local/bin]# ./apktool b petertests/template.out -a petertests/aapt
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
**W: petertests/aapt: line 5: syntax error near unexpected token `newline'
W: petertests/aapt: line 5: `<!DOCTYPE html>'**
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [petertests/aapt, p, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 2, --version-name, 1.0, -F, /tmp/APKTOOL189751636752577159.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, split3, -0, split4, -0, split5, -0, split6, -0, split7, -0, resource, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /usr/local/bin/petertests/template.out/res, -M, /usr/local/bin/petertests/template.out/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [petertests/aapt, p, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 2, --version-name, 1.0, -F, /tmp/APKTOOL189751636752577159.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, split3, -0, split4, -0, split5, -0, split6, -0, split7, -0, resource, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /usr/local/bin/petertests/template.out/res, -M, /usr/local/bin/petertests/template.out/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 2): [petertests/aapt, p, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 2, --version-name, 1.0, -F, /tmp/APKTOOL189751636752577159.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, split3, -0, split4, -0, split5, -0, split6, -0, split7, -0, resource, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /usr/local/bin/petertests/template.out/res, -M, /usr/local/bin/petertests/template.out/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
	... 6 more
root@server2 [/usr/local/bin]# 

When I try to run the aapt file by itself I don't get the normal dump of command lists etc, just another sytax error.

Is there an extra step I have to do for the Linux aapt file? Sorry if these are all dumb questions, I'm completely new to this!

**Comment by BurgerZ** [comment] 2016-05-03 08:36
you can try to run this command `file aapt` to see that your aapt is not binary file, you saved an html file instead.

**Comment by designzoo-peter** [comment] 2016-05-03 08:43
Well that's embarrassing, I used wget to transfer the file but I guess that's what I deserve for using commands without fully understanding them! Guess who's new to Linux

**Comment by designzoo-peter** [comment] 2016-05-03 08:59
Thanks for the patient replies guys. After several package dependencies later I've got it up and running using option 2. Awesome work on the tool, it's amazing.
