### ISSUE TITLE
No resource identifier found for attribute 'qihoo' in package 'android'

### ISSUE THREAD

**Issue by abdodriowya** [iBotPeaches/Apktool#1424] opened 2017-02-07 18:28 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64 
3. **APK From? (Playstore, ROM, Other)** - Playstore apkpure

### Stacktrace/Logcat
```
**apktool d Cadillacs.apk**

C:\Users\Th3CracKed>apktool d Cadillacs.apk
I: Using Apktool 2.2.2 on Cadillacs.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Th3CracKed\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
---------------------------------------------------------------------------------------------------
**apktool b Cadillacs**
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Th3CracKed\Cadillacs\AndroidManifest.xml:4: error: No resource identifier found for attribute 'qihoo' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\TH3CRA~1\AppData\Local\Temp\brut_util_Jar_9112944107089398724.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 11, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\TH3CRA~1\AppData\Local\Temp\APKTOOL8679457475346164241.tmp, -0, arsc, -0, appkey, -0, so, -0, txt, -0, zip, -0, arsc, -I, C:\Users\Th3CracKed\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Th3CracKed\Cadillacs\res, -M, C:\Users\Th3CracKed\Cadillacs\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\TH3CRA~1\AppData\Local\Temp\brut_util_Jar_9112944107089398724.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 11, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\TH3CRA~1\AppData\Local\Temp\APKTOOL8679457475346164241.tmp, -0, arsc, -0, appkey, -0, so, -0, txt, -0, zip, -0, arsc, -I, C:\Users\Th3CracKed\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Th3CracKed\Cadillacs\res, -M, C:\Users\Th3CracKed\Cadillacs\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\TH3CRA~1\AppData\Local\Temp\brut_util_Jar_9112944107089398724.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 11, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\TH3CRA~1\AppData\Local\Temp\APKTOOL8679457475346164241.tmp, -0, arsc, -0, appkey, -0, so, -0, txt, -0, zip, -0, arsc, -I, C:\Users\Th3CracKed\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Th3CracKed\Cadillacs\res, -M, C:\Users\Th3CracKed\Cadillacs\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
```

### APK
If this APK can be freely shared, please upload/attach a link to it:
[https://apkpure.com/guide-for-cadillacs/com.partner.gativ.dino2](url)
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Yes decompile are okey but recompile won't work**
2. If you are trying to install a modified apk, did you resign it? **Not yet, recompiling failed.**
3. Are you using the latest apktool version? **YES**
i tried to remove qihoo but doesn't work any solution please?

**Comment by iBotPeaches** [comment] 2017-02-07 21:24
Duplicate of #1323

**Closed by iBotPeaches** 2017-02-07 21:24 UTC
Labels: Duplicate
