### ISSUE TITLE
ArrayIndexOutOfBoundsException when decode LocusPro

### ISSUE THREAD

**Issue by eriklu** [iBotPeaches/Apktool#1051] opened 2015-10-09 03:37 UTC
```
java -jar apktool_2.0.1.jar d -advance -r -f LocusPro\ v3.10.3.apk
I: Using Apktool 2.0.1 on LocusPro v3.10.3.apk
I: Loading resource table...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment] 2015-10-12 11:54
Duplicate of #1031 . Seems this error is occurring more frequently.

**Closed by iBotPeaches** 2015-10-12 11:54 UTC
Labels: duplicate
