### ISSUE TITLE
[BUG] When decompiling yandex, the static variables in the interface are not public and final, causing runtime dex check errors. 

### ISSUE THREAD

**Issue by yescpu** [iBotPeaches/Apktool#3431] opened 2023-11-17 17:01 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - java11

### Problem description
use `com.yandex.android:mobileads:5.7.0`, `com/yandex/mobile/ads/impl/bt` is an interface, but the variables in the interface cannot be decompiled into public and final, resulting in runtime verification dex errors.
#### smali code
`.field static synthetic $desugar$clinit:I`

<img width="400" alt="image" src="https://github.com/iBotPeaches/Apktool/assets/962421/c7144d17-0964-4a9a-9a16-7beb52d963af">

#### Correct smali example
`.field public static synthetic final $desugar$clinit:I`

### Stacktrace/Logcat
I: Using Apktool 2.9.0 on app-release-unsigned.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /Users/XX/Library/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...

#### .....runtime log
Failure to verify dex file '/data/app/~~fGJ6c7yDYxFsDthpRG5keQ==/com.XX.XX-Se31Qf-EF24W6hXPpIfjhA==/base.apk!classes5.dex': Interface field is not public final static, Lcom/yandex/mobile/ads/impl/bt;.$desugar$clinit: 1008(static 

### Steps to Reproduce
1. `apktool d app-release-unsigned.apk`
2. `apktool b app-release-unsigned.apk` 
3. `adb install app-release-signed.apk`

**Comment by iBotPeaches** [comment] 2023-11-20 11:01
Unless this is caused by a configuration we (Apktool) are using against (smali), I believe this might be upstream and out of our control.

You may try directly with smali/baksmali here and report if replicating on the source tool - https://github.com/google/smali/issues

**Comment by iBotPeaches** [comment] 2023-12-02 12:38
As mentioned above - this is intended for another repo. Apktool just leverages smali, so to keep this bug tracker clean. I'm closing this.

I urge you to attempt replication on smali/baksmali and report upstream.

**Closed by iBotPeaches** 2023-12-02 12:38 UTC
Labels: 3rd-party, Waiting for issuer
