### ISSUE TITLE
[BUG] 'java' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by SardanDev** [iBotPeaches/Apktool#3321] opened 2023-09-06 13:21 UTC
### Information
1. **Apktool Version (`apktool -version`)** - v1.2
2. **Operating System (Mac, Linux, Windows)** - Window
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - Idk

### Stacktrace/Logcat

```
[15:10:04] Decompiling FMSC1.40F_By_FouadMODS.apk...
[15:10:04] 'java' n'est pas reconnu en tant que commande interne  ou externe, un programme ex‚cutable ou un fichier de commandes.  
```

### Steps to Reproduce
1. `apktool decomplied`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
3. If you are trying to install a modified apk, did you resign it?
4. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2023-09-06 13:32
I don't recognize that output. So this must not be a direct invocation of Apktool and if you were directly invoking it you'd need Java.

So I'm closing this as not a bug.

**Closed as not planned by iBotPeaches** 2023-09-06 13:32 UTC

**Comment by SardanDev** [comment] 2023-09-06 14:30
Hi, problem solved. I thinked i have installed Java but i don't... Sorry for the mistake
