### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: No implementation found

### ISSUE THREAD

**Issue by binarycounter** [iBotPeaches/Apktool#1079] opened 2015-11-07 04:38 UTC
This app http://music.163.com/api/android/download/latest2

```
java -jar apktool.jar d -s original.apk
java -jar apktool.jar b -c original
```

works great, even if resources get modified.

```
java -jar apktool.jar d original.apk
java -jar apktool.jar b -c original
```

force-closes/crashes on launch (app background gets displayed for a split--second)

logcat:

```
11-07 05:15:20.037: I/MultiDex(32158): VM with version 2.1.0 has multidex support
11-07 05:15:20.037: I/MultiDex(32158): install
11-07 05:15:20.037: I/MultiDex(32158): VM has multidex support, MultiDex support library is disabled.
11-07 05:15:20.075: I/art(7176): Background sticky concurrent mark sweep GC freed 158240(7MB) AllocSpace objects, 1(16KB) LOS objects, 13% free, 50MB/57MB, paused 1.922ms total 128.410ms
11-07 05:15:20.617: D/bugrpt(32158): sendReportsToServer begin
11-07 05:15:20.617: D/bugrpt(32158): ctx is null
11-07 05:15:20.617: E/art(32158): No implementation found for void com.netease.cloudmusic.utils.NeteaseMusicUtils.nativeInit(android.content.Context) (tried Java_com_netease_cloudmusic_utils_NeteaseMusicUtils_nativeInit and Java_com_netease_cloudmusic_utils_NeteaseMusicUtils_nativeInit__Landroid_content_Context_2)
11-07 05:15:20.618: D/AndroidRuntime(32158): Shutting down VM
11-07 05:15:20.618: E/AndroidRuntime(32158): FATAL EXCEPTION: main
11-07 05:15:20.618: E/AndroidRuntime(32158): Process: com.netease.cloudmusic, PID: 32158
11-07 05:15:20.618: E/AndroidRuntime(32158): java.lang.UnsatisfiedLinkError: No implementation found for void com.netease.cloudmusic.utils.NeteaseMusicUtils.nativeInit(android.content.Context) (tried Java_com_netease_cloudmusic_utils_NeteaseMusicUtils_nativeInit and Java_com_netease_cloudmusic_utils_NeteaseMusicUtils_nativeInit__Landroid_content_Context_2)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.netease.cloudmusic.utils.NeteaseMusicUtils.nativeInit(Native Method)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.netease.cloudmusic.utils.NeteaseMusicUtils.<clinit>(ProGuard:190)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.netease.cloudmusic.utils.q.a(ProGuard:264)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.netease.cloudmusic.NeteaseMusicApplication.onCreate(ProGuard:170)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.netease.nis.wrapper.MyApplication.onCreate(MyApplication.java:12)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.app.ActivityThread.access$1600(ActivityThread.java:147)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.os.Handler.dispatchMessage(Handler.java:102)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.os.Looper.loop(Looper.java:135)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at android.app.ActivityThread.main(ActivityThread.java:5256)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at java.lang.reflect.Method.invoke(Native Method)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at java.lang.reflect.Method.invoke(Method.java:372)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
11-07 05:15:20.618: E/AndroidRuntime(32158):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
11-07 05:15:20.620: W/ActivityManager(7176):   Force finishing activity com.netease.cloudmusic/.activity.LoadingActivity

```

**Comment by felix3008** [comment] 2015-11-09 16:55
I just build Apktool v2.0.3-5f5f50-SNAPSHOT from source and the issue is still happening, therefor has not been fixed since the last release.

**Comment by iBotPeaches** [comment] 2015-11-09 16:56
Yeah all the `lib` files have the same compression before/after, so that throws that idea out. I'm not sure why this is happening.

**Comment by felix3008** [comment] 2015-11-09 17:50
Since you mentioned compression, putting the lib files in doNotCompress made the apk larger but did not fix the issue.

**Comment by DamienOReilly** [comment] 2015-11-10 14:02
Could this be some sort of tamper mechanism ? It seems like the .lib wasn't loaded by the VM.

**Comment by felix3008** [comment] 2015-11-10 18:30
The app seems to use Proguard, but that should not be an issue, right?
Also, is it maybe possible to just reassemble a single smali file so that the mayority of the code is unchanged and just the thing i want to edit is modified? I don't need to change the file that includes nativeInit.

**Comment by iBotPeaches** [comment] 2020-11-29 12:17
```
11-29 07:16:11.633  3873  3873 D ItemClickHandler: onClick app, tag = AppInfo(id=-1 type=APP container=-1 screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=My Application hidden=false dirty = false newInstallTag=com.xone.android.myapplication#0#1606652156630 componentName=ComponentInfo{com.xone.android.myapplication/com.xone.android.myapplication.MainActivity} searchResult=null suggestionApp=null)
11-29 07:16:11.635  3873  3873 D Launcher: onPause# hashcode: 198870316
11-29 07:16:11.636  1365  8257 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{86619ed com.xone.android.myapplication} is now in focus and seems to be in full-screen mode
11-29 07:16:11.636  1365  8257 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.xone.android.myapplication/com.xone.android.myapplication.MainActivity/1
11-29 07:16:11.637  1365  1480 D RestartProcessManager: Update Total Launch Times :com.xone.android.myapplication
11-29 07:16:11.637  1365  1480 D RestartProcessManager: updateSelf :  com.xone.android.myapplication, size : 30
11-29 07:16:11.637  1365  1480 D RestartProcessManager: Increase Total Launch Time : com.xone.android.myapplication, times : 1, index : 29
11-29 07:16:11.637  1365  1480 D RestartProcessManager: Last Running Package : com.xone.android.myapplication , start time 1606652171637
11-29 07:16:11.639  3873  3873 D AppTagModel: onTagChangedUpdate#
11-29 07:16:11.639  3873  3873 D AppTagModel: onTagChangedUpdate# apply default ranks
11-29 07:16:11.639  3873  3873 D AppTagPresenter: dumpCategories# 
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Social: rank=0, count=15
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Music & Video: rank=1, count=6
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Travel: rank=2, count=3
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Tools: rank=3, count=21
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Financial: rank=4, count=3
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Lifestyle: rank=5, count=5
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Photo: rank=6, count=2
11-29 07:16:11.639  3873  3873 D AppTagPresenter: Reading: rank=7, count=1
11-29 07:16:11.655  1365  1482 I ActivityManager: Start proc 20292:com.xone.android.myapplication/u0a158 for activity com.xone.android.myapplication/.MainActivity
11-29 07:16:11.657 20292 20292 I d.myapplicatio: Late-enabling -Xcheck:jni
11-29 07:16:11.698   797   797 D AudioPolicyService: setRecordSilenced() uid 10158 on silenced 0
```

```
➜  2128 apktool d app-debug.apk 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2128 apktool b app-debug --use-aapt2
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2128 cd app-debug/dist 
➜  dist signapk app-debug.apk 
```

Could not replicate with file in original report. Closing as not reproducible. Sorry for 5+ year delay.

**Closed by iBotPeaches** 2020-11-29 12:17 UTC
