### ISSUE TITLE
[BUG] App can't be compiled after decompiling

### ISSUE THREAD

**Issue by mbj222** [iBotPeaches/Apktool#2660] opened 2021-09-17 07:26 UTC
### Information
1. **Apktool Version (`2.6.0`)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
[Fatal Error] :2:91: Attribute "android:" was already specified for element "manifest".
I: Checking whether resources has changed...
I: Building resources...
W: /home/pisanim/Argenta/Argenta/AndroidManifest.xml:2: error: Error parsing XML: not well-formed (invalid token)
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_46056059891695539653880217336772652422.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 30, --version-code, 72, --version-name, 3.1.0, --no-version-vectors, -F, /tmp/APKTOOL16202201262417655169.tmp, -e, /tmp/APKTOOL223301538113756630.tmp, -0, arsc, -I, /home/pisanim/.local/share/apktool/framework/1.apk, -S, /home/pisanim/Argenta/Argenta/res, -M, /home/pisanim/Argenta/Argenta/AndroidManifest.xml]
W:
```

### Steps to Reproduce
1. `apktool d Argenta.apk `
2. `apktool b Argenta `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.sitael.vending

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment] 2021-09-17 10:24
Thanks for the report. I'm going to mark this as a duplicate of an existing known ticket - https://github.com/iBotPeaches/Apktool/issues/1407

**Closed by iBotPeaches** 2021-09-17 10:24 UTC
