### ISSUE TITLE
Not modified decompiled and rebuilt apk don't working

### ISSUE THREAD

**Issue by donmezburak** [iBotPeaches/Apktool#2380] opened 2020-07-18 10:34 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - mac
3. **APK From? (Playstore, ROM, Other)** - apkcombo.com

### Stacktrace/Logcat

```
2020-07-18 13:10:35.320 25270-25270/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.dji.industry.pilot.pilot" on path: DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dji.industry.pilot-s7E2o_RIRIv2FNnCRpwDCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dji.industry.pilot-s7E2o_RIRIv2FNnCRpwDCw==/lib/arm64, /data/app/com.dji.industry.pilot-s7E2o_RIRIv2FNnCRpwDCw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:257)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:805)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:884)
        at android.app.LoadedApk.getResources(LoadedApk.java:1135)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2623)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

### Steps to Reproduce
1. `apktool d -c dji-pilot_v1.8.0.apk  `
2.  `apktool b dji-pilot_v1.8.0 -o ndji.apk   `

### Frameworks
nope

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://apkcombo.com/tr-tr/apk-downloader/?device=&arch=&android=&q=com.dji.industry.pilot

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? not modified
3. Are you using the latest apktool version? yes

**Comment by LoopsGod** [comment] 2020-07-28 08:55
I think this is a problem with how DJI builds their apps, check my issue #2381 @donmezburak .

For some reason, dependencies / native libs drop with recompilation of DJI apps.

**Comment by iBotPeaches** [comment] 2020-11-27 15:57
Closing as duplicate of #2381. It appears there is some anti-tamper mechanisms going on with that app.

**Closed by iBotPeaches** 2020-11-27 15:57 UTC
