### ISSUE TITLE
Error recompiling APK after adding a method to a certain class

### ISSUE THREAD

**Issue by RonKab** [iBotPeaches/Apktool#2041] opened 2019-03-13 17:45 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows10
3. **APK From? (Playstore, ROM, Other)** - APKmirror

### Stacktrace/Logcat

```
C:\Users\Ron Kabas\AppData\Local\Android\Sdk\platform-tools>apktool b -f -o twitter.apk twitter
I: Using Apktool 2.4.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/twitter/metrics/ForegroundMetricTracker$BackgroundBehavior;->values()[Lcom/twitter/metrics/ForegroundMetricTracker$BackgroundBehavior;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
        at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:365)
        at brut.androlib.Androlib.build(Androlib.java:303)
        at brut.androlib.Androlib.build(Androlib.java:269)
        at brut.apktool.Main.cmdBuild(Main.java:247)
        at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
        ... 11 more
```

### Steps to Reproduce
1. apktool d twitter.apk
2. Add any method (even an empty one) to an object in samli_classes2
3. apktool b -f -o twitter.apk twitter

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-7-64-0-release-1060-release/twitter-7-64-0-release-1060-3-android-apk-download/

**Comment by ibuprophen1** [comment] 2019-03-13 20:25
@RonKab, does this occur using a previous version of Apktool (v2.3.1 or v2.3.2)? 

Just curious to see if it's tied to the AAPT/AAPT2... 


~Ibuprophen

**Comment by iBotPeaches** [comment] 2020-11-28 23:25
You went pass the limit of methods. See https://github.com/JesusFreke/smali/issues/469

Marking as duplicate of https://github.com/iBotPeaches/Apktool/issues/2177

**Closed by iBotPeaches** 2020-11-28 23:25 UTC
