### ISSUE TITLE
[BUG] Aapt2 breaks compatibility on Android 7 and below

### ISSUE THREAD

**Issue by AndnixSH** [iBotPeaches/Apktool#3247] opened 2023-08-01 13:21 UTC
### Information
1. **Apktool Version (`apktool -version`)** 2.8.1 (Tried 2.8.0 as well)
2. **Operating System (Mac, Linux, Windows)** Windows 11 2h22
3. **APK From? (Playstore, ROM, Other)** Playstore
4. **Java Version (`java --version`)** java version "20.0.1" 2023-04-18

### Description
When using Aapt2 on Apktool 2.8.0 and above, resources breaks on Android 7 and below, causing the icon and app name to not display correctly, and it crashes immediately due to missing resource ID. It works fine on Android 9 and above (Only tested on Android 9 and 11). I have been using Aapt2 since 2.5.0 and never encountered this issue until now. The last working version is 2.7.0

![image](https://github.com/iBotPeaches/Apktool/assets/40742924/ffd3fe66-6997-4b19-a84c-c90bf39b0564)

![image](https://github.com/iBotPeaches/Apktool/assets/40742924/b47faefb-f9df-45b9-adab-dc859bf9ce51)

When comparing, only differences is the apktool.yml. I'm attaching the yml files to be compared
[apktool yml.zip](https://github.com/iBotPeaches/Apktool/files/12229583/apktool.yml.zip)

### Stacktrace/Logcat

```
08-01 15:07:04.984 E/AndroidRuntime(3953): FATAL EXCEPTION: main
08-01 15:07:04.984 E/AndroidRuntime(3953): Process: com.finalwire.aida64, PID: 3953
08-01 15:07:04.984 E/AndroidRuntime(3953): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.finalwire.aida64/com.finalwire.aida64.HHMainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x11200a0
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.os.Looper.loop(Looper.java:154)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at java.lang.reflect.Method.invoke(Native Method)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-01 15:07:04.984 E/AndroidRuntime(3953): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x11200a0
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.content.res.Resources.getBoolean(Resources.java:1029)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.view.Window.getDefaultFeatures(Window.java:1624)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.view.Window.<init>(Window.java:664)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:298)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:306)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.Activity.attach(Activity.java:6700)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2600)
08-01 15:07:04.984 E/AndroidRuntime(3953): 	... 9 more
```

### Steps to Reproduce
1. `apktool d (apk path --use-aapt2`
2. `apktool b (apk path --use-aapt2`
3. Zipalign and sign APK

### Frameworks
N/A

### APK
It happens with any apps but you can try a small app called Aida64: https://apkcombo.com/aida64/com.finalwire.aida64/download/apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2023-08-01 13:26
As your research suggests - if you don't see a difference in the files - it must be from the recently updated aapt2/aapt binaries from this commit - https://github.com/iBotPeaches/Apktool/commit/86340503acd4f81d8b3decc1f60f35b30faa8d72

To save me some time. Anyway you can email/attach the signed built apk and the original? I can compare those much easier and determine if aapt2 was at fault or apktool.

**Comment by AndnixSH** [comment] 2023-08-01 13:31
Here is the file: [AIDA64_1.94_2.8.1.zip](https://github.com/iBotPeaches/Apktool/files/12229700/AIDA64_1.94_2.8.1.zip)

**Comment by iBotPeaches** [comment] 2023-08-05 01:06
Sorry I have no idea. I decoded/assembled the application with aapt1/aapt2 and then re-decoded them both and compared. The only changes were some compression on assets. Everything else was the same.

So then I tried a different approach. I dumped the chunks between original/aapt1/aapt2. Nothing helped since the behavior of string pools or res table isn't consistent.

I'll leave this open till I update the aapts again for the upcoming Android 14 release. If that doesn't help - I'll just close it. Apktool isn't doing anything wrong from what I can see in an investigation.

**Comment by AndnixSH** [comment] 2023-08-05 14:36
I found out that `sparseResources: true` in the `apktool.yml` caused issues. On apktool 2.7.0 `sparseResources` was `false` by default. After changing it to `false`, the APK works again for Android 7 and below. Tested on 7.1.2, 5.1.1 and 4.4.4

**Comment by iBotPeaches** [comment] 2023-08-05 15:38
Ah nice find. Sorry I didn't notice that. We patched that regression here: https://github.com/iBotPeaches/Apktool/issues/3199 and added a test so it wouldn't happen again.

**Comment by iBotPeaches** [comment] 2023-08-05 16:23
Closing as I believe we discovered the issue. The upcoming 2.8.2 will resolve this.

**Closed by iBotPeaches** 2023-08-05 16:23 UTC
