### ISSUE TITLE
AndroidManifest.xml:17: error: No resource identifier found for attribute 'isSplitRequired' in package 'android'

### ISSUE THREAD

**Issue by ifengchao** [iBotPeaches/Apktool#2139] opened 2019-07-23 06:25 UTC
### Information
1. **Apktool Version (`apktool -version`)** -
ver 2.4.0
2. **Operating System (Mac, Linux, Windows)** -
Win10
3. **APK From? (Playstore, ROM, Other)** -
Playstore
### Stacktrace/Logcat
None
```
Include stacktrace here
```
None
### Steps to Reproduce
1. `apktool `

`apktool d` will be success, but `apktool `b will show the problem, easy to reproduce.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

None

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://www.lanzous.com/i54do4f

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
`apktool b` not successful.

3. Are you using the latest apktool version?
Not tried 2.4.1 yet.

**Comment by iBotPeaches** [comment] 2019-07-30 22:56
Already fixed here: https://github.com/iBotPeaches/Apktool/commit/c2065995ed5d4e1b69b701c27a0f02f49e528d7b

Will be in 2.4.1

**Closed by iBotPeaches** 2019-07-30 22:56 UTC

**Comment by ifengchao** [comment] 2019-07-31 03:10
Nice work, expecting 2.4.1

**Comment by denysvitali** [comment] 2019-09-01 06:30
I can confirm that the issue was fixed with c206599.
Attached you can find a build using the latest commit till now (683fef3) if you can't wait for a release.
[apktool-cli.tar.gz](https://github.com/iBotPeaches/Apktool/files/3563157/apktool-cli.tar.gz)


@iBotPeaches Travis CI doesn't store any artifacts for this project: is it possible to change that? It will be nice to have the latest build available on Travis (which could be in turn used for [android-apktool](https://aur.archlinux.org/packages/android-apktool/) or [android-apktool-git](https://aur.archlinux.org/packages/android-apktool-git))

**Comment by gameFace22** [comment] 2019-09-27 11:27
Hey @denysvitali and @iBotPeaches 

I used the jar file you had included in the above comment because of the isSplitRequired error while recompiling the APK. 

Unfortunately, I am getting the same error. Can you please let me know what to do?

![Screenshot 2019-09-27 at 4 55 55 PM](https://user-images.githubusercontent.com/7415260/65766131-b6f5cb00-e147-11e9-8482-c4cf8245cb43.png)

@ifengchao did 2.4.1 work for you?

**Comment by denysvitali** [comment] 2019-09-30 20:29
@gameFace22 Can you delete the framework file and try again?  

```
rm /Users/nshaanth/Library/apktool/framework/1.apk
```

**Comment by mbouzian42** [comment] 2019-09-30 21:40
Hello, i'm getting the same error..

**Comment by Gopinath001** [comment] 2019-10-03 20:48
Facing the same issue,
 * the build provided by @denysvitali did not work, 
 * tried deleting the framework file too.

**Comment by zlrab** [comment] 2019-10-08 10:26
> Facing the same issue,
> 
> * the build provided by @denysvitali did not work,
> * tried deleting the framework file too.
> 
> edit:1
> attached error,
> ![rebuild Error](https://user-images.githubusercontent.com/18617846/66163229-72899400-e64d-11e9-8910-f004381e9fc8.png)
> 
> edit:2
> **FIX:**
> remove all instance of "split" from androidManifest, then try building with 2.4.0.
> 
> (or)
> 
> go to this commit id [c206599](https://github.com/iBotPeaches/Apktool/commit/c2065995ed5d4e1b69b701c27a0f02f49e528d7b) download the android-framework.jar file & then do
> 
> ` apktool_2.4.0.jar if android-framework.jar`

Your two solutions can make apktool2.4.0 build successfully,
```
remove isSplitRequired attr

apktool_2.4.0.jar if android-framework.jar
```
but the generated apk can't be installed on your phone.error:`Failure [INSTALL_FAILED_INVALID_APK]`

**Comment by HussainR-coder** [comment] 2019-10-29 17:32
Tried Both method, ie ; installing new framework and editing AndroidManifest.xml as mentioned by @zlrab , it helps in compiling the apk file and installing it in the phone properly. But the app Forecloses without any error, I'm working on Freecharge Application Downloaded from Playstore directly. 
Ps : Files are untouched from apk and nothing other than AndroidManifest.xml is been modified.

**Comment by AGSPhoenix** [comment] 2019-11-03 16:33
When can we expect 2.4.1 to be released?

**Comment by Decikingship** [comment] 2019-12-02 08:29
> > Facing the same issue,
> > 
> > * the build provided by @denysvitali did not work,
> > * tried deleting the framework file too.
> > 
> > edit:1
> > attached error,
> > ![rebuild Error](https://user-images.githubusercontent.com/18617846/66163229-72899400-e64d-11e9-8910-f004381e9fc8.png)
> > edit:2
> > **FIX:**
> > remove all instance of "split" from androidManifest, then try building with 2.4.0.
> > (or)
> > go to this commit id [c206599](https://github.com/iBotPeaches/Apktool/commit/c2065995ed5d4e1b69b701c27a0f02f49e528d7b) download the android-framework.jar file & then do
> > ` apktool_2.4.0.jar if android-framework.jar`
> 
> Your two solutions can make apktool2.4.0 build successfully,
> 
> ```
> remove isSplitRequired attr
> 
> apktool_2.4.0.jar if android-framework.jar
> ```
> 
> but the generated apk can't be installed on your phone.error:`Failure [INSTALL_FAILED_INVALID_APK]`
> 
> @Gopinath001 The problem is solved,Detailed plan:
> Edit AndroidManifest.xml
> 
> 1. delete the following node properties on the Application:
> 
> ```
> android:isSplitRequired="true"
> android:extractNativeLibs="false" 
> //Optional
> android:networkSecurityConfig="@xml/network_security_config"
> ```
> 
> 1. Edit as follows,ture modified to base
>    old:
> 
> ```
> <meta-data android:name="com.android.vending.splits.required" android:value="true"/>
> ```
> 
> new:
> 
> ```
> <meta-data android:name="com.android.vending.splits.required" android:value="base"/>
> ```
> 
> 1. Use apktool2.4.0 to build the project and install it successfully

Thanks, you solved my problem!
I use apktool 2.4.1 but are still faced with this problem, and I tried you method, it worked!
