### ISSUE TITLE
invalid resource directory name: ...\res navigation

### ISSUE THREAD

**Issue by tahsin1373** [iBotPeaches/Apktool#2219] opened 2019-11-06 18:35 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

Building resources...
W: invalid resource directory name: C:\Users\TS\AppData\Local\Temp\apk-editor-studio\apk {cbd48689-8b7a-4a53-a9e9-c03f6bf00409}\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\TS\AppData\Local\Temp\brut_util_Jar_5779047406839396973.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 28, --version-code, 13021, --version-name, 6.49.0.1, --no-version-vectors, -F, C:\Users\TS\AppData\Local\Temp\APKTOOL3129153657309499600.tmp, -0, arsc, -0, res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-hdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, webp, -0, res/drawable-hdpi-v4/bac_active_call.9.png, -0, res/drawable-hdpi-v4/bac_general_notice.9.png, -0, res/drawable-hdpi-v4/bac_notification.9.png, -0, res/drawable-hdpi-v4/bac_notification_green.9.png, -0, res/drawable-hdpi-v4/btn_conversation_native_default.9.png, -0, res/drawable-hdpi-v4/btn_conversation_native_focus.9.png, -0, res/drawable-hdpi-v4/btn_conversation_native_pressed.9.png, -0, res/drawable-hdpi-v4/btn_conversation_sms_default.9.png, -0, res/drawable-hdpi-v4/btn_conversation_sms_focus.9.png, -0, res/drawable-hdpi-v4/btn_conversation_sms_pressed.9.png, -0, res/drawable-hdpi-v4/btn_facebook.9.png, -0, jpg, -0, res/drawable-hdpi-v4/com_facebook_tooltip_black_background.9.png, -0, res/drawable-hdpi-v4/com_facebook_tooltip_blue_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-hdpi-v4/con_system_dark.9.png, -0, res/drawable-hdpi-v4/con_system_light.9.png, -0, res/drawable-hdpi-v4/drawer_shadow.9.png, -0, res/drawable-hdpi-v4/dropdown_arrow.9.png, -0, res/drawable-hdpi-v4/list_focused_holo.9.png, -0, res/drawable-hdpi-v4/list_pressed_holo_dark.9.png, -0, res/drawable-hdpi-v4/msc_widget_seperator.9.png, -0, res/drawable-hdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-hdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-hdpi-v4/notification_bg_normal.9.png, -0, res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-ldrtl-hdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-mdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-xhdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-xxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-ldrtl-xxxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-mdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-mdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-mdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-mdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-mdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-mdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-mdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-mdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-mdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-mdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-mdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-mdpi-v4/bac_active_call.9.png, -0, res/drawable-mdpi-v4/bac_general_notice.9.png, -0, res/drawable-mdpi-v4/bac_notification.9.png, -0, res/drawable-mdpi-v4/bac_notification_green.9.png, -0, res/drawable-mdpi-v4/bac_tablet_current.9.png, -0, res/drawable-mdpi-v4/bac_tablet_selected.9.png, -0, res/drawable-mdpi-v4/btn_conversation_native_default.9.png, -0, res/drawable-mdpi-v4/btn_conversation_native_focus.9.png, -0, res/drawable-mdpi-v4/btn_conversation_native_pressed.9.png, -0, res/drawable-mdpi-v4/btn_conversation_sms_default.9.png, -0, res/drawable-mdpi-v4/btn_conversation_sms_focus.9.png, -0, res/drawable-mdpi-v4/btn_conversation_sms_pressed.9.png, -0, res/drawable-mdpi-v4/btn_facebook.9.png, -0, res/drawable-mdpi-v4/com_facebook_tooltip_black_background.9.png, -0, res/drawable-mdpi-v4/com_facebook_tooltip_blue_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-mdpi-v4/con_system_dark.9.png, -0, res/drawable-mdpi-v4/con_system_light.9.png, -0, res/drawable-mdpi-v4/drawer_shadow.9.png, -0, res/drawable-mdpi-v4/list_focused_holo.9.png, -0, res/drawable-mdpi-v4/list_focused_holo_dark.9.png, -0, res/drawable-mdpi-v4/list_pressed_holo_dark.9.png, -0, res/drawable-mdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-mdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-mdpi-v4/notification_bg_normal.9.png, -0, res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-xhdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-xhdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-xhdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-xhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-xhdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-xhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-xhdpi-v4/bac_active_call.9.png, -0, res/drawable-xhdpi-v4/bac_general_notice.9.png, -0, res/drawable-xhdpi-v4/bac_notification.9.png, -0, res/drawable-xhdpi-v4/bac_notification_green.9.png, -0, res/drawable-xhdpi-v4/btn_conversation_native_default.9.png, -0, res/drawable-xhdpi-v4/btn_conversation_native_focus.9.png, -0, res/drawable-xhdpi-v4/btn_conversation_native_pressed.9.png, -0, res/drawable-xhdpi-v4/btn_conversation_sms_default.9.png, -0, res/drawable-xhdpi-v4/btn_conversation_sms_focus.9.png, -0, res/drawable-xhdpi-v4/btn_conversation_sms_pressed.9.png, -0, res/drawable-xhdpi-v4/btn_facebook.9.png, -0, res/drawable-xhdpi-v4/com_facebook_tooltip_black_background.9.png, -0, res/drawable-xhdpi-v4/com_facebook_tooltip_blue_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-xhdpi-v4/con_system_dark.9.png, -0, res/drawable-xhdpi-v4/con_system_light.9.png, -0, res/drawable-xhdpi-v4/drawer_shadow.9.png, -0, res/drawable-xhdpi-v4/list_focused_holo.9.png, -0, res/drawable-xhdpi-v4/list_pressed_holo_dark.9.png, -0, res/drawable-xhdpi-v4/msc_widget_seperator.9.png, -0, res/drawable-xhdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-xhdpi-v4/notification_bg_normal.9.png, -0, res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-xxhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xxhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-xxhdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-xxhdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-xxhdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-xxhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-xxhdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-xxhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/btn_facebook.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png, -0, res/drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png, -0, res/drawable-xxhdpi-v4/incall_overlay.9.png, -0, res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xxxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xxxhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xxxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-xxxhdpi-v4/btn_facebook.9.png, -0, res/drawable-xxxhdpi-v4/btn_material.9.png, -0, res/drawable-xxxhdpi-v4/btn_material_pressed.9.png, -0, gif, -0, res/drawable/shadow7.9.png, -0, apk, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, mp3, -0, ogg, -0, arsc, -I, C:\Users\TS\AppData\Local\apk-editor-studio\frameworks\1.apk, -S, C:\Users\TS\AppData\Local\Temp\apk-editor-studio\apk\{cbd48689-8b7a-4a53-a9e9-c03f6bf00409}\res, -M, C:\Users\TS\AppData\Local\Temp\apk-editor-studio\apk\{cbd48689-8b7a-4a53-a9e9-c03f6bf00409}\AndroidManifest.xml]

### Steps to Reproduce
1. apktool d tn.apk
2. apktool b tn

If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.enflick.android.TextNow

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version?yes

**Comment by tahsin1373** [comment] 2019-11-06 19:04
8888

**Comment by tahsin1373** [comment] 2019-11-08 14:37
@iBotPeaches 
Please help me find the problem

**Comment by realityJie** [comment] 2019-11-10 13:20
you can see [#2192](https://github.com/iBotPeaches/Apktool/pull/2192) and [2187](https://github.com/iBotPeaches/Apktool/pull/2187)

**Comment by iBotPeaches** [comment] 2019-11-10 19:57
This is a duplicate of quite a few issues here. There are also links to the fix above. Closing as duplicate.

**Closed by iBotPeaches** 2019-11-10 19:57 UTC

**Comment by tahsin1373** [comment] 2019-11-11 14:12
> you can see [#2192](https://github.com/iBotPeaches/Apktool/pull/2192) and [#2187](https://github.com/iBotPeaches/Apktool/pull/2187)

> This is a duplicate of quite a few issues here. There are also links to the fix above. Closing as duplicate.

thanks for your help
I solved the problem using #1811 .
I used aapt2 to compile.
1. apktool d tn.apk
2. apktool b tn/ --use-aapt2

**Comment by tahsin1373** [comment] 2019-11-11 16:51
> you can see [#2192](https://github.com/iBotPeaches/Apktool/pull/2192) and [#2187](https://github.com/iBotPeaches/Apktool/pull/2187)

> This is a duplicate of quite a few issues here. There are also links to the fix above. Closing as duplicate.

thanks for your help
I solved the problem using #1811 .
I used aapt2 to compile.
1. apktool d tn.apk
2. apktool b tn/ --use-aapt2 

But now i am getting a new error :
W: C:\Windows\aa\tn\res\values\public.xml:2805: error: resource 'drawable/$avd_
hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid charac
ter '$avd_hide_password__0'.
.
.
.

**Comment by tahsin1373** [comment] 2019-11-11 16:56
> you can see [#2192](https://github.com/iBotPeaches/Apktool/pull/2192) and [#2187](https://github.com/iBotPeaches/Apktool/pull/2187)

> This is a duplicate of quite a few issues here. There are also links to the fix above. Closing as duplicate.

thanks for your help
I solved the problem using #1811 .
I used aapt2 to compile.
1. apktool d tn.apk
2. apktool b tn/ --use-aapt2 

But now i am getting a new error :
W: C:\Windows\aa\tn\res\values\public.xml:2805: error: resource 'drawable/$avd_
hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid charac
ter '$avd_hide_password__0'.
.
.
.

I removed $ but got an error again.

**Comment by shin-illua** [comment] 2020-09-02 10:06
@iBotPeaches Any updates on this? I did the same as OP, used `--use-appt2` too, and got the same new errors as OP, what more I tried is: 
 * Modify the xml files, For example, if it shows an error like this: ```W: C:\Windows\aa\tn\res\values\public.xml:2805: error: resource 'drawable/$avd_
hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid charac
ter '$avd_hide_password__0'.```
   I would comment `C:\Windows\aa\tn\res\values\public.xml:2805` and the error referencing to that would be gone, and I tried to remove all errors like this, but it just gave me a new type of errors again, which would make me think that commenting out these code is not really the solution, rather another problem itself.

**Comment by didia** [comment] 2020-09-18 00:56
These invalid characters for me are coming from the library https://github.com/aws-amplify/amplify-android so it would be really cool if I could fix this issue without editing the library
