### ISSUE TITLE
Fail to rebuild

### ISSUE THREAD

**Issue by ProsAnon** [iBotPeaches/Apktool#1710] opened 2018-01-13 12:07 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.2.2
2. **Operating System (Mac, Linux, Windows)** - Kali
3. **APK From? (Playstore, ROM, Other)** - google

### Stacktrace/Logcat

~/Desktop/apktool# apktool b /root/Desktop/apktool/as
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Desktop/apktool/as/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2756462982314022824.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452100, --version-name, 2.17.427, --no-version-vectors, -F, /tmp/APKTOOL816634177047142614.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/apktool/as/res, -M, /root/Desktop/apktool/as/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2756462982314022824.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452100, --version-name, 2.17.427, --no-version-vectors, -F, /tmp/APKTOOL816634177047142614.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/apktool/as/res, -M, /root/Desktop/apktool/as/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2756462982314022824.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452100, --version-name, 2.17.427, --no-version-vectors, -F, /tmp/APKTOOL816634177047142614.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/apktool/as/res, -M, /root/Desktop/apktool/as/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
root@kali:~/Desktop/apktool#
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

1. Yes
2. No
3. Not really,i don't know how to update,last time i tried something it crashed all.

EDIT: Freshly new installed OS

**Comment by ProsAnon** [comment] 2018-01-13 17:02
I fixed this.

**Comment by MineEric64** [comment] 2018-01-18 17:42
How to fix it?

**Comment by ProsAnon** [comment] 2018-01-18 17:45
Git clone it then run The gradle file from The folder

**Comment by iBotPeaches** [comment] 2018-01-18 17:45
This issue had nothing to do with that. It was a duplicate of this #1709 which was the 4th ticket about this issue.

**Closed by iBotPeaches** 2018-01-18 17:45 UTC

**Comment by maurikkio** [comment] 2019-02-12 14:29
where can I clone which git repositoty ?
