### ISSUE TITLE
failed to recompile the instrumented code

### ISSUE THREAD

**Issue by xlpei** [iBotPeaches/Apktool#1898] opened 2018-09-11 03:07 UTC
### Information
1. **Apktool Version (2.3.3)** -
2. **Operating System ( Windows)** -
3. **APK From? ( Other)** -

### Stacktrace/Logcat
    error infor:
   
```
[error_info.txt](https://github.com/iBotPeaches/Apktool/files/2369193/error_info.txt)

System.Exception: Failed to recompile the instrumented code. See details for more information: S: WARNING: Could not write to (D:\My Documents\AppData\Local\apktool\framework), using C:\Users\ADMINI~1\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: C:\Users\Administrator\AppData\Local\RanorexStudio8\RxEnv\Android\temp\decomp\res\layout\a.xml:2: error: Error: No resource found that matches the given name (at 'style' with value '@style/RtlOverlay.Widget.AppCompat.ActionBar.TitleItem').
W: 
W: C:\Users\Administrator\AppData\Local\RanorexStudio8\RxEnv\Android\temp\decomp\res\layout\a0.xml:2: error: No resource identifier found for attribute 'paddingBottomNoButtons' in package 'com.tencent.qqlive'
W: 
W: C:\Users\Administrator\AppData\Local\RanorexStudio8\RxEnv\Android\temp\decomp\res\layout\a0.xml:2: error: No resource identifier found for attribute 'paddingTopNoTitle' in package 'com.tencent.qqlive'
W: 
W: C:\Users\Administrator\AppData\Local\RanorexStudio8\RxEnv\Android\temp\decomp\res\layout\a0.xml:2: error: Error: No resource found that matches the given name (at 'style' with value '@style/Widget.AppCompat.ListView').
W: 
W: C:\Users\Administrator\AppData\Local\RanorexStudio8\RxEnv\Android\temp\decomp\res\layout-v17\a0.xml:2: error: No resource identifier found for attribute 'paddingBottomNoButtons' in package 'com.tencent.qqlive'
W: 
W: C:\Users\Administrator\AppData\Local\RanorexStudio8\RxEnv\Android\temp\decomp\res\layout-v17\a0.xml:2: error: No resource identifier found for attribute 'paddingTopNoTitle' in package 'com.tencent.qqlive'
W: .......


### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please uplo
  the APK is too bigger than 10M,cannot upload. 
the name of apk is com.tencent.qqlive_17138.apk

ad/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by ibuprophen1** [comment] 2018-09-11 17:21
@xlpei, did you try Apktool v2.3.4? 

Also, the following is just a suggestion that worked for some (not all of course)... 

Some individuals do try a bit of the older versions of Apktool like v2.2... just to see if the ability to decompile/recompile was previously there that isn't able to now. 

That's more of a "ruling out the possibilities" thing and is only a suggestion. 

Good Luck! 


~Ibuprophen

**Comment by xlpei** [comment] 2018-09-12 02:09
Where can I get Apktool v2.3.4 ，v2.2.. ?



xlpei@fiberhome.com
 
From: Ibuprophen
Date: 2018-09-12 01:21
To: iBotPeaches/Apktool
CC: 裴晓利; Mention
Subject: Re: [iBotPeaches/Apktool] failed to recompile the instrumented code (#1898)
@xlpei, did you try Apktool v2.3.4?
Also, the following is just a suggestion that worked for some (not all of course)...
Some individuals do try a bit of the older versions of Apktool like v2.2... just to see if the ability to decompile/recompile was previously there that isn't able to now.
That's more of a "ruling out the possibilities" thing and is only a suggestion.
Good Luck!
~Ibuprophen

**Comment by ibuprophen1** [comment] 2018-09-12 13:53
@xlpei, you can obtain all the releases via one of the following links:

https://github.com/iBotPeaches/Apktool/releases

https://ibotpeaches.github.io/Apktool


~Ibuprophen

**Comment by xlpei** [comment] 2018-09-17 01:57
I have tried 7 versions of apktool to insturmented apk，include v2.2.3、v2.2.4、v2.3.0、v2.3.1、v2.3.2、v2.3.3、v2.3.4，all  failed。

xlpei@fiberhome.com
 
From: Ibuprophen
Date: 2018-09-12 21:53
To: iBotPeaches/Apktool
CC: 裴晓利; Mention
Subject: Re: [iBotPeaches/Apktool] failed to recompile the instrumented code (#1898)
@xlpei, you can obtain all the releases via one of the following links:
https://github.com/iBotPeaches/Apktool/releases
https://ibotpeaches.github.io/Apktool
~Ibuprophen

**Comment by iBotPeaches** [comment] 2018-09-18 17:46
Duplicate of #1423, thanks for the report.

**Closed by iBotPeaches** 2018-09-18 17:46 UTC
