### ISSUE TITLE
[BUG] Unable to decode resources

### ISSUE THREAD

**Issue by 0x454d505459** [iBotPeaches/Apktool#2753] opened 2022-02-05 14:52 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Extracted from the device

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0 on com.adups.fota_v215.apk
I: Loading resource table...
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [color:#4c4c4c] is not a valid entry
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
        at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
        at brut.androlib.res.decoder.StringBlock$Tag.toString(StringBlock.java:167)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at brut.androlib.res.decoder.StringBlock.processStyledString(StringBlock.java:260)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:288)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
        at brut.androlib.Androlib.getResTable(Androlib.java:69)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:78)

```

### Steps to Reproduce
1. `apktool d -s app.apk `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, fails too
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Lastest from my repos

**Comment by pashamcr** [comment] 2022-02-07 14:34
Does it make sense to decode it and use it?
> FOTA, in fact, has a built-in backdoor that constantly keeps in touch with the servers of the Chinese company. Having received the appropriate command from the server, FOTA can:
> ●     send all SMS messages from the device to the Adups server every 72 hours;
> ●     every 72 hours send the contents of the call log to the Adups server;
> ●     collect personal data that can identify the user and send it to the Adups server every 24 hours;
> ●     collect information about IMSI and IMEI, geolocation data and a list of installed applications;
> ●     remove or update applications;
> ●     download and install new applications without the knowledge of the user;
> ●     update the firmware of the device;
> ●     remotely execute arbitrary commands and elevate your privileges on the device.
> According to Kryptowire, all malicious functionality is concentrated inside two system applications, which the user simply cannot disable or remove: com.adups.fota.sysoper and com.adups.fota.

**Comment by 0x454d505459** [comment] 2022-02-16 12:16
Well, the thing is, the package comes from an android device exclusively available in France and some other countries but not in China. I need to be able to decode it as I would like to see how the app works and where is downloads the OTA.

I didn't knew that updating apps did that

**Comment by iBotPeaches** [comment] 2022-02-27 13:32
This looks like a duplicate of #2675. Will take a look soon.

**Closed by iBotPeaches** 2022-02-27 13:32 UTC
