### ISSUE TITLE
apktool not wokring properly on some apk decompilation

### ISSUE THREAD

**Issue by effortlessdevsec** [iBotPeaches/Apktool#2044] opened 2019-03-15 05:12 UTC
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, OI: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file:              ?.
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:223)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:172)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file:       ?.
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:216)
        ... 3 more
Caused by: java.io.FileNotFoundException: package\unknown\      ?. (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more

E:\ANDROID>ther)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by ravkr** [comment] 2019-04-08 15:04
Similar problem with this app:
https://play.google.com/store/apps/details?id=wit.android.bcpBankingApp.millenniumPL

Tested on Windows 10
```
E:\apk\>apktool d "Millennium  4.32.7.apk" -f -r -s
I: Using Apktool 2.4.0 on Millennium  4.32.7.apk
I: Copying raw resources...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file:
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:223)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:172)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file:
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:216)
        ... 3 more
Caused by: java.io.FileNotFoundException: Millennium  4.32.7\unknown\   (Odmowa dostępu)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more
```

Opening apk file with 7-zip doesn't look good either...
![obraz](https://user-images.githubusercontent.com/3875202/55734707-54d1ce00-5a20-11e9-818a-7be0df9f9879.png)

**Comment by iBotPeaches** [comment] 2020-11-28 23:16
I would try linux with these. We don't have a good system in place on Windows with all the charset differences to handle some of these surrogate/weird characters.

Either way, duplicate of https://github.com/iBotPeaches/Apktool/issues/1460

**Closed by iBotPeaches** 2020-11-28 23:16 UTC
