### ISSUE TITLE
apktool failed to decompile some attributes in manifest file (protected by F-PROT packer)

### ISSUE THREAD

**Issue by nguyenvulong** [iBotPeaches/Apktool#1823] opened 2018-06-19 13:02 UTC
### Information
1. **Apktool Version (`apktool -version`)** - Apktool-2.3.3
2. **Operating System (Mac, Linux, Windows)** - Linux (Ubuntu)
3. **APK From? (Playstore, ROM, Other)** - Other

This APK runs fine on the device, but apktool cannot properly unpack the AndroidManifest.xml file

### Steps to Reproduce
1. `apktool `
running the command 
./apktool d 53165cae610f0e0f915bf838de241944.apk --output frot_packer_noName

### APK (please change the extension from .zip to .apk)
please see the attachment, _please note that this APK is a malware, which I use for learning purpose only_
[53165cae610f0e0f915bf838de241944.zip](https://github.com/iBotPeaches/Apktool/files/2115248/53165cae610f0e0f915bf838de241944.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? I did not modify the APK
3. Are you using the latest apktool version? YES

**Some attributes are missing after decompilation (for example: name=)**

![image](https://user-images.githubusercontent.com/1311412/41598736-0cb41394-740c-11e8-83f5-7513351b390b.png)

**Comment by iBotPeaches** [comment] 2018-06-22 21:01
Thanks for the report and information. I think this is a duplicate of #1526, but I need to confirm. Basically the packer is destroying the literal text value of the key, but retaining the resourceId for the type of value so the application can still work.

**Comment by iBotPeaches** [comment] 2018-06-22 21:21
Yep confirmed. Same issue as #1576

**Closed by iBotPeaches** 2018-06-22 21:21 UTC
