### ISSUE TITLE
Can't recompile AOSP Nougat SystemUI

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#1325] opened 2016-09-18 19:32 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.2.1
2. **Operating System (Mac, Linux, Windows)** -Windows 10 64-bit
3. **APK From? (Playstore, ROM, Other)** -AOSP Nougat ROM for SGS4

### Stacktrace/Logcat
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
A subdirectory or file modified-system-apk-files-here already exists.
W: Could not find sources
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2070: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2071: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2076: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2086: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_3733580573281903296.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 24, --version-name, 7.0, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8949540748492794871.tmp, -0, arsc, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_3733580573281903296.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 24, --version-name, 7.0, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8949540748492794871.tmp, -0, arsc, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_3733580573281903296.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 24, --version-name, 7.0, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8949540748492794871.tmp, -0, arsc, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
```
### Steps to Reproduce
1. `apktool `d
apktool b

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment] 2016-09-18 21:22
Duplicate of #1223

**Closed by iBotPeaches** 2016-09-18 21:22 UTC
Labels: Duplicate

**Comment by Phone-Guru** [comment] 2016-09-19 01:20
This issue is not fixed with the new commit.  I compiled apktool and still get the same error.
