### ISSUE TITLE
 No resource identifier found for attribute 'compileSdkVe rsion' in package 'android'

### ISSUE THREAD

**Issue by zhangyunx** [iBotPeaches/Apktool#2016] opened 2019-02-25 03:54 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.3.4
2. **Operating System (Mac, Linux, Windows)** -windows
3. **APK From? (Playstore, ROM, Other)** -other

### Stacktrace/Logcat
C:\Users\Administrator\Desktop\手游打包学习文件夹\工具\反编译工具\wzxx\Androi
dManifest.xml:2: error: No resource identifier found for attribute 'compileSdkVe
rsion' in package 'android'
```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no resign
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment] 2019-02-25 15:25
Duplicate of - #1852

**Closed by iBotPeaches** 2019-02-25 15:25 UTC
