### ISSUE TITLE
Decoding com.safaricom.mysafaricom versions > 1.5.0.0 gives NullPointerException in AXmlResourceParser.getNonDefaultNamespaceUri

### ISSUE THREAD

**Issue by alandixon** [iBotPeaches/Apktool#2308] opened 2020-03-06 14:34 UTC
### Information
1. **Apktool Version 2.4.1** 
2. **Windows 10 Pro 64 bit** 
3. **APK: com.safaricom.mysafaricom v1.5.0.5 from https://apkpure.com/**

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1 on mySafaricom_v1.5.0.5.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\alan\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.decoder.AXmlResourceParser.getNonDefaultNamespaceUri(AXmlResourceParser.java:312)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeNamespace(AXmlResourceParser.java:299)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeNamespace(XmlPullParserDelegate.java:176)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:84)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:121)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
1. Download com.safaricom.mysafaricom v1.5.0.5 from ApkPure. See 'APK' below
2. apktool.bat d  mySafaricom_v1.5.0.5.apk

### Frameworks
N/A

### APK
mySafaricom_v1.5.0.5_apkpure.com.apk from (https://apkpure.com/mysafaricom/com.selfcare.safaricom/download?from=versions)
Other versions here: (https://apkpure.com/mysafaricom/com.selfcare.safaricom/versions)
Note that v1.5.0.0 and earlier all play well with ApkTool

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Yes**
2. If you are trying to install a modified apk, did you resign it? **N/A**
3. Are you using the latest apktool version? **Yes 2.4.1**

**Comment by iBotPeaches** [comment] 2020-04-11 11:14
Thanks for the report, this looks like a duplicate of a ticket I recently triaged. You can subscribe to this ticket for updates - https://github.com/iBotPeaches/Apktool/issues/1859

Closing due to duplicate.

**Closed by iBotPeaches** 2020-04-11 11:14 UTC

**Comment by alandixon** [comment] 2020-04-11 13:05
You're right.
My apologies, I thought I'd checked for duplicates.
All the best and stay well!
