### ISSUE TITLE
Main thread

### ISSUE THREAD

**Issue by techker** [iBotPeaches/Apktool#1800] opened 2018-05-18 10:37 UTC
### Information
1. **Apktool Version (`apktool -version`)** -150
2. **Operating System (Mac, Linux, Windows)** -w10
3. **APK From? (Playstore, ROM, Other)** -play store

i can't build anymore..
always get a main thread error. increased the heap to difference..
also re installed jdk

also get lots of warnings.but should stop it from building?
```
I: Using Apktool 2.3.3
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/arch/lifecycle/Lifecycle$Event;->values()[Landroid/arch/lifecycle/Lifecycle$Event;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:825)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:268)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:417)
	at brut.androlib.Androlib.buildSources(Androlib.java:348)
	at brut.androlib.Androlib.build(Androlib.java:300)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1098)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:821)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65617
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:348)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1058)
	... 11 more
```

**Comment by iBotPeaches** [comment] 2018-05-23 16:37
Duplicate of #1718

**Closed by iBotPeaches** 2018-05-23 16:37 UTC

**Comment by neobenedict** [comment] 2020-09-21 22:33
See https://github.com/iBotPeaches/Apktool/issues/2106#issuecomment-696414088 if you are trying to add new files to your smali folder and this error pops up.
