### ISSUE TITLE
Apk build fails if use aapt2 option is ON.

### ISSUE THREAD

**Issue by diksha3** [iBotPeaches/Apktool#1816] opened 2018-06-12 13:39 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other (Sample App)

### Stacktrace/Logcat

Using the latest version of apktools, it still gives the same error for aapt2.

I: Using Apktool 2.3.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
S: WARNING: Could not write to (/Users/dikshapandey/Library/apktool/framework), using /var/folders/wg/_hyzh4rn2rj5z9csw3bpprtw0000gn/T/ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: /usr/local/bin/app-integration-release/res/values/public.xml:964: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
W: /usr/local/bin/app-integration-release/res/values/public.xml:965: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1'. Invalid character '$avd_hide_password__1'.
W: /usr/local/bin/app-integration-release/res/values/public.xml:966: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2'. Invalid character '$avd_hide_password__2'.
W: /usr/local/bin/app-integration-release/res/values/public.xml:967: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0'. Invalid character '$avd_show_password__0'.
W: /usr/local/bin/app-integration-release/res/values/public.xml:968: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1'. Invalid character '$avd_show_password__1'.
W: /usr/local/bin/app-integration-release/res/values/public.xml:969: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2'. Invalid character '$avd_show_password__2'.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/wg/_hyzh4rn2rj5z9csw3bpprtw0000gn/T/brut_util_Jar_6626944185893826816.tmp, compile, --dir, /usr/local/bin/app-integration-release/res, --legacy, -o, /usr/local/bin/app-integration-release/build/resources.zip]

### Steps to Reproduce
1. Build apk using latest apktool version (2.3.3)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2018-06-12 13:43
Duplicate of #1776

**Closed by iBotPeaches** 2018-06-12 13:43 UTC
