### ISSUE TITLE
[BUG]Chunk [$(did)&amp] is not a valid entry

### ISSUE THREAD

**Issue by Dhanraj6zoho** [iBotPeaches/Apktool#2765] opened 2022-02-25 05:29 UTC
### Information
1. **Apktool Version 2.6.0** -
2. **Operating System Linux** -
3. **APK From? other)** -

### Stacktrace/Logcat
```
I: Using Apktool 2.6.0 on a.apk
I: Loading resource table...
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [$(did)&amp] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
	at brut.androlib.res.decoder.StringBlock$Tag.toString(StringBlock.java:167)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at brut.androlib.res.decoder.StringBlock.processStyledString(StringBlock.java:260)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:288)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:69)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
```

getting the above issue while extracting the apk. how to fix this?

**Comment by iBotPeaches** [comment] 2022-02-27 13:29
Thanks for the report. I've identified this as an existing duplicate of #2675 - closing.

**Closed by iBotPeaches** 2022-02-27 13:29 UTC
