### ISSUE TITLE
Unable to decompile Settings.apk HTC Android 5.1  /6.0

### ISSUE THREAD

**Issue by ineedone** [iBotPeaches/Apktool#1072] opened 2015-10-21 23:49 UTC
I'm not able to decompile Settings.apk with any version of apktool. This is for 5.1 and just released 6.0 android version of HTC A9. Both apks give the same error. Here is a link to latest settings.apk if needed: https://drive.google.com/file/d/0Bw2v2JVflPziOGZ0Y1VPdGZESVE/view?usp=sharing

```
2:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: I: Using Apktool 2.0.1-037041-SNAPSHOT on C79B78.apk'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: I: Loading resource table...'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: Exception in thread "main" brut.androlib.AndrolibException:  *Multiple resources: spec=0x7f110000 bool/config_allow_edit_carrier_enabled, config=[DEFAULT]'*
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:223)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.Androlib.getResTable(Androlib.java:64)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.apktool.Main.cmdDecode(Main.java:165)'
22:22:32.624: [Error] - ApkTool.DecompileApk: 'ApkTool: 	at brut.apktool.Main.main(Main.java:81)'
```

**Comment by iBotPeaches** [comment] 2015-10-22 15:51
This is a long running bug I haven't been able to track down yet. Duplicate of #644 

Different APKs, but same root cause. Something to do with an HTC qualifier or something.

**Comment by iBotPeaches** [comment] 2015-11-01 12:16
Different issue. Dumped the bad values.

```
      config (default):
        resource 0x7f110000 com.android.settings:bool/config_allow_edit_carrier_enabled: t=0x12 d=0x00000000 (s=0x0008 r=0x00)
      config mnc1:
        resource 0x7f110000 com.android.settings:bool/config_allow_edit_carrier_enabled: t=0x12 d=0xffffffff (s=0x0008 r=0x00)
          (color) #ffffffff
      config mnc10:
        resource 0x7f110000 com.android.settings:bool/config_allow_edit_carrier_enabled: t=0x12 d=0xffffffff (s=0x0008 r=0x00)
          (color) #ffffffff
      config mcc310-mnc28:
        resource 0x7f110000 com.android.settings:bool/config_allow_edit_carrier_enabled: t=0x12 d=0xffffffff (s=0x0008 r=0x00)
          (color) #ffffffff
      config mcc246-mnc81:
        resource 0x7f110000 com.android.settings:bool/config_allow_edit_carrier_enabled: t=0x12 d=0xffffffff (s=0x0008 r=0x00)
          (color) #ffffffff
      config mcc311-mnc390:
        resource 0x7f110000 com.android.settings:bool/config_allow_edit_carrier_enabled: t=0x12 d=0xffffffff (s=0x0008 r=0x00)
```

Basically `mnc1` isn't supported. Patch incoming.

**Closed** 2015-11-01 12:17 UTC
Labels: Accepted, bug

**Comment by ineedone** [comment] 2015-11-02 21:04
Thanks, happy you got it fixed, confirmed working. Great work
