### ISSUE TITLE
Cannot Re-Compile LGTeleServices(LP)

### ISSUE THREAD

**Issue by AzharKanorwala786** [iBotPeaches/Apktool#979] opened 2015-06-21 17:30 UTC
Recompiling "LGTeleService.apk" With Original Signature,
in work area "_WorkArea4", using "apktool_2.0.0rc4.jar" 
 
With Tickle My Android 10.4.1. 
(tinyurl.com\ticklemyandroid) 

 ----------------
```
I: Using Apktool 2.0.0-RC4
I: Smaling smali folder into classes.dex...
I: Building resources...
W/ResourceType( 3708): Entry identifier 0x9 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x6 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x7 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x4 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x5 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Entry identifier 0x3 is larger than entry count 0x2
W/ResourceType( 3708): Type identifier 0x11 does not exist.
C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/txt_selected').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:4: error: Error: No resource found that matches the given name (at 'text' with value '@string/selected_info').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@style/checkbox_multi_selection_extra_size').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:5: error: Error: No resource found that matches the given name (at 'id' with value '@id/check_selectArea').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:5: error: Error: No resource found that matches the given name (at 'layout_toStartOf' with value '@id/txt_selected').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/chkbox_selectAll').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:7: error: Error: No resource found that matches the given name (at 'id' with value '@id/chkbox_selectText').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:7: error: Error: No resource found that matches the given name (at 'text' with value '@string/sp_SelectAll2_NORMAL').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\action_bar_select_all.xml:7: error: Error: No resource found that matches the given name (at 'style' with value '@style/checkbox_multi_selection_size').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\actionbar_custom.xml:2: error: Error: No resource found that matches the given name (at 'background' with value '@color/setupwizard_theme_sub_color').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\actionbar_custom.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/costum_title').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\actionbar_custom.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@style/startup_wizard_header').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_disclaimer.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/iv_disclaimer_image').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_disclaimer.xml:4: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/smart_forward').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_disclaimer.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/help_description').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_disclaimer.xml:6: error: Error: No resource found that matches the given name (at 'text' with value '@string/sp_sf_disclaimer_text_NORMAL').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_disclaimer.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/call_setting_help_list').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_disclaimer.xml:8: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/cancel_ok_button').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout-land\activity_xdiv_disclaimer.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/iv_disclaimer_image').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout-land\activity_xdiv_disclaimer.xml:6: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/smart_forward_land').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout-land\activity_xdiv_disclaimer.xml:10: error: Error: No resource found that matches the given name (at 'id' with value '@id/help_description').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout-land\activity_xdiv_disclaimer.xml:10: error: Error: No resource found that matches the given name (at 'text' with value '@string/sp_sf_disclaimer_text_NORMAL').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout-land\activity_xdiv_disclaimer.xml:10: error: Error: No resource found that matches the given name (at 'style' with value '@style/call_setting_help_list').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout-land\activity_xdiv_disclaimer.xml:14: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/cancel_ok_button').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:2: error: Error: No resource found that matches the given name (at 'id' with value '@id/rl_main_layout').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/ScrollView01').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:5: error: Error: No resource found that matches the given name (at 'id' with value '@id/rl_smart_forward').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/rl_with_check_box_status').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:7: error: Error: No resource found that matches the given name (at 'id' with value '@id/tv_sub_title').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:7: error: Error: No resource found that matches the given name (at 'text' with value '@string/sp_sf_title_NORMAL').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:8: error: Error: No resource found that matches the given name (at 'id' with value '@id/cb_sf_enable_dissable').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:8: error: Error: No resource found that matches the given name (at 'layout_alignTop' with value '@id/tv_sub_title').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:10: error: Error: No resource found that matches the given name (at 'id' with value '@id/firstDivider').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:10: error: Error: No resource found that matches the given name (at 'background' with value '@drawable/list_line').

C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\layout\activity_xdiv_number.xml:10: error: Error: No resource found that matches the given name (at 'layout_below' with value '@id/rl_with_check_box_status').



C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res\menu\respond_via_message_settings_menu.xml:4: error: Error: No resource found that matches the given name (at 'title' with value '@string/respond_via_sms_menu_reset_default_activity').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Developer Account\AppData\Local\Temp\brut_util_Jar_5948311022911722379.tmp, p, --forced-package-id, 2, --min-sdk-version, 21, --target-sdk-version, 21, --rename-manifest-package, com.android.phone, --version-code, 44002700, --version-name, 4.40.27, -F, C:\Users\Developer Account\AppData\Local\Temp\APKTOOL7052285139911701584.tmp, -0, arsc, -I, C:\Users\Developer Account\apktool\framework\1.apk, -I, C:\Users\Developer Account\apktool\framework\2.apk, -S, C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res, -M, C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:442)
        at brut.androlib.Androlib.buildResources(Androlib.java:379)
        at brut.androlib.Androlib.build(Androlib.java:282)
        at brut.androlib.Androlib.build(Androlib.java:255)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Developer Account\AppData\Local\Temp\brut_util_Jar_5948311022911722379.tmp, p, --forced-package-id, 2, --min-sdk-version, 21, --target-sdk-version, 21, --rename-manifest-package, com.android.phone, --version-code, 44002700, --version-name, 4.40.27, -F, C:\Users\Developer Account\AppData\Local\Temp\APKTOOL7052285139911701584.tmp, -0, arsc, -I, C:\Users\Developer Account\apktool\framework\1.apk, -I, C:\Users\Developer Account\apktool\framework\2.apk, -S, C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res, -M, C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:504)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:428)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Developer Account\AppData\Local\Temp\brut_util_Jar_5948311022911722379.tmp, p, --forced-package-id, 2, --min-sdk-version, 21, --target-sdk-version, 21, --rename-manifest-package, com.android.phone, --version-code, 44002700, --version-name, 4.40.27, -F, C:\Users\Developer Account\AppData\Local\Temp\APKTOOL7052285139911701584.tmp, -0, arsc, -I, C:\Users\Developer Account\apktool\framework\1.apk, -I, C:\Users\Developer Account\apktool\framework\2.apk, -S, C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\res, -M, C:\TickleMyAndroid\_WorkArea4\_working\LGTeleService.apk\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:498)
        ... 6 more
```
 ----------------

Recompile Not Successful!

**Comment by iBotPeaches** [comment] 2015-06-22 12:05
Duplicate of #857 

While I know one is HTC & the other is LG. aapt failing badly is the commonality in both of these.

**Closed by iBotPeaches** 2015-06-22 12:05 UTC
Labels: duplicate
