### ISSUE TITLE
 error: No resource identifier found for attribute 'tabIndicatorColor' in package

### ISSUE THREAD

**Issue by Bright-W** [iBotPeaches/Apktool#1588] opened 2017-08-14 12:16 UTC
Information

Apktool Version (apktool -version) - 2.2.4
Operating System (Mac, Linux, Windows) - Windows
APK From? (Playstore, ROM, Other) - Playstore
Stacktrace/Logcat
```
C:\Users\coolup\Desktop\apktool>apktool.bat b AirFrozen AirFrozen2.apk
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\a0.xml:2: error: No resource identifier found for attribute 'tabIndicatorColor' in package 'me.yourbay.airfrozen'
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\a0.xml:2: error: No resource identifier found for attribute 'tabMode' in package 'me.yourbay.airfrozen'
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\e.xml:2: error: No resource identifier found for attribute 'lilSquare' in package 'me.yourbay.airfrozen'
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\h.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/layout_loading').
Exception in thread "main" W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\k.xml:5: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/layout_guide_feature').
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\coolup\AppData\Local\Temp\brut_util_Jar_5161099286399731244.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 106, --version-name, 1.4.1.2, --no-version-vectors, -F, C:\Users\coolup\AppData\Local\Temp\APKTOOL3358781960356888336.tmp, -0, svg, -0, arsc, -I, C:\Users\coolup\AppData\Local\apktool\framework\1.apk, -S, C:\Users\coolup\Desktop\apktool\AirFrozen\res, -M, C:\Users\coolup\Desktop\apktool\AirFrozen\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
        at brut.androlib.Androlib.buildResources(Androlib.java:430)
        at brut.androlib.Androlib.build(Androlib.java:329)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:230)
        at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\coolup\AppData\Local\Temp\brut_util_Jar_5161099286399731244.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 106, --version-name, 1.4.1.2, --no-version-vectors, -F, C:\Users\coolup\AppData\Local\Temp\APKTOOL3358781960356888336.tmp, -0, svg, -0, arsc, -I, C:\Users\coolup\AppData\Local\apktool\framework\1.apk, -S, C:\Users\coolup\Desktop\apktool\AirFrozen\res, -M, C:\Users\coolup\Desktop\apktool\AirFrozen\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\coolup\AppData\Local\Temp\brut_util_Jar_5161099286399731244.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 106, --version-name, 1.4.1.2, --no-version-vectors, -F, C:\Users\coolup\AppData\Local\Temp\APKTOOL3358781960356888336.tmp, -0, svg, -0, arsc, -I, C:\Users\coolup\AppData\Local\apktool\framework\1.apk, -S, C:\Users\coolup\Desktop\apktool\AirFrozen\res, -M, C:\Users\coolup\Desktop\apktool\AirFrozen\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\k.xml:6: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/layout_guide_grant').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\l.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/layout_loading').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\m.xml:6: error: No resource identifier found for attribute 'pl_regularColor' in package 'me.yourbay.airfrozen'
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\m.xml:6: error: No resource identifier found for attribute 'pl_errorColor' in package 'me.yourbay.airfrozen'
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\m.xml:6: error: No resource identifier found for attribute 'pl_successColor' in package 'me.yourbay.airfrozen'
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\p.xml:12: error: Error: No resource found that matches the given name (at 'style' with value '@style/View.BaseButton.Button').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout-v21\p.xml:12: error: Error: No resource found that matches the given name (at 'style' with value '@style/View.BaseButton.Button').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\u.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Title').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\u.xml:5: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\u.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\u.xml:7: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\u.xml:8: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\u.xml:10: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\v.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Title').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\v.xml:5: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\v.xml:7: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\w.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\w.xml:5: error: Error: No resource found that matches the given name (at 'style' with value '@style/Guide.Item.Summary').
W:
W: C:\Users\coolup\Desktop\apktool\AirFrozen\res\layout\y.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/View.BaseButton.Button').
W:
```
Steps to Reproduce

apktool d AirFrozen.apk
apktool b AirFrozen AirFrozen2.apk

Frameworks
NA

APK

https://play.google.com/store/apps/details?id=me.yourbay.airfrozen&hl=en

Questions to ask before submission

Have you tried apktool d, apktool b without changing anything? Yes
If you are trying to install a modified apk, did you resign it? Not relevant
Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2017-08-15 19:29
Duplicate of #1361 - no known fix yet.

**Closed by iBotPeaches** 2017-08-15 19:29 UTC
