### ISSUE TITLE
[BUG] app-debug-androidTest.apk not fully rebuildable

### ISSUE THREAD

**Issue by auermich93** [iBotPeaches/Apktool#2738] opened 2022-01-13 10:19 UTC
### Information
1. **Apktool Version (`apktool -version`)** - Latest.
2. **Operating System (Mac, Linux, Windows)** - Windows.
3. **APK From? (Playstore, ROM, Other)** - Custom.

### Steps to Reproduce

0. Take an arbitrary app containing some instrumented tests, e.g. espresso tests. Let Android Studio build the APKs. 

1. Decode the test APK.
```
$ apktool d app-debug-androidTest.apk -f
I: Using Apktool 2.6.0 on app-debug-androidTest.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Michael\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
2. Rebuild the test APK.
```
$ apktool b
I: Using Apktool 2.6.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: Error copying file: resources.arsc
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```
3. Decode the rebuilt test APK again.
```
$ apktool d app-debug-androidTest.apk
I: Using Apktool 2.6.0 on app-debug-androidTest.apk
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

4. Show the content of it.
```
$ ls app-debug-androidTest
apktool.yml  original  smali  smali_classes2  smali_classes3  smali_classes4  unknown
```
In step 2, a warning is produced that the `resources.arsc `couldn't be copied succesfully and this seems to be actual problem.
As you can observe in the final output, the `AndroidManifest.xml` is missing among other things. If you look inside the `res` folder of the original APK, you will notice that only an empty `public.xml` file is present. I suppose that Android Studio is generating this test APK in an optimized way, which may not allow further modifications to the resources, e.g. the manifest. If you don't decode the resources (`apktool d -r`) and rebuild it that way, it works. So I am curious, is this actually a bug of `apktool` or does Android Studio assume that the test APK shouldn't be modified at all? Moreover, should `apktool` may throw an error instead of the warning when the resources can't be copied/encoded properly?

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[app-debug-androidTest.zip](https://github.com/iBotPeaches/Apktool/files/7861867/app-debug-androidTest.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? YES
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment] 2022-01-17 12:14
I took a look at this and the root issue I see is this packed `resources.arsc` finally just has next to no contents.

```
➜  2738 aapt d --values resources app-debug-androidTest.apk
Package Groups (1)
Package Group 0 id=0x7f packageCount=1 name=com.example.abcquiz.test
➜  2738 
```
Like the file is entirely empty, so there are no resources for Apktool to attempt to disassemble. So I'm going to close this as I don't believe there is anything Apktool can do here given the source application.

```
➜  2738 xxd resources.arsc 
00000000: 0200 0c00 8001 0000 0100 0000 0100 1c00  ................
00000010: 1c00 0000 0000 0000 0000 0000 0001 0000  ................
00000020: 1c00 0000 0000 0000 0002 2001 5801 0000  .......... .X...
00000030: 7f00 0000 6300 6f00 6d00 2e00 6500 7800  ....c.o.m...e.x.
00000040: 6100 6d00 7000 6c00 6500 2e00 6100 6200  a.m.p.l.e...a.b.
00000050: 6300 7100 7500 6900 7a00 2e00 7400 6500  c.q.u.i.z...t.e.
00000060: 7300 7400 0000 0000 0000 0000 0000 0000  s.t.............
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000100: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000110: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000130: 0000 0000 2001 0000 0000 0000 3c01 0000  .... .......<...
00000140: 0000 0000 0000 0000 0100 1c00 1c00 0000  ................
00000150: 0000 0000 0000 0000 0000 0000 1c00 0000  ................
00000160: 0000 0000 0100 1c00 1c00 0000 0000 0000  ................
00000170: 0000 0000 0001 0000 1c00 0000 0000 0000  ................
```

So to close, I believe since Apktool is throwing a warning (not failing) given no resources. This is intended behavior.

**Closed by iBotPeaches** 2022-01-17 12:14 UTC

**Comment by iBotPeaches** [comment] 2022-01-21 22:53
@auermich93 - do you have the source project you did to generate this?

**Comment by auermich93** [comment] 2022-03-07 13:07
Sorry @iBotPeaches,  I didn't get that notification although you tagged me. I have attached the source code.
[ABCQuiz-master.zip](https://github.com/iBotPeaches/Apktool/files/8197888/ABCQuiz-master.zip)
