### ISSUE TITLE
error: No resource identifier found for attribute.

### ISSUE THREAD

**Issue by acsway878787** [iBotPeaches/Apktool#1459] opened 2017-03-26 05:55 UTC
### Information
1. **Apktool Version (`apktool -2.2.2`)** 
2. **Operating System (`Windows`)** 
3. **APK From? (`ROM`)** 
4. **ROM Info(`ASUS Padfone S 4.4..2 stock`)**

### Stacktrace/Logcat

`W:brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_1576552267211253615.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 10545440, --version-name,0.2.4-81-gb1e98ea, --no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL5181806592759903079.tmp, -0, arsc, -0, so, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, D:\Wayne\Programming\apktool\microg\res, -M,D:\Wayne\Programming\apktool\microg\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_15765
52267211253615.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-
sdk-version, 23, --version-code, 10545440, --version-name, 0.2.4-81-gb1e98ea, --
no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL518180659275
9903079.tmp, -0, arsc, -0, so, -0, arsc, -I, C:\Users\Administrator\AppData\Loca
l\apktool\framework\1.apk, -S, D:\Wayne\Programming\apktool\microg\res, -M, D:\W
ayne\Programming\apktool\microg\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
ADMINI~1\AppData\Local\Temp\brut_util_Jar_1576552267211253615.tmp, p, --forced-p
ackage-id, 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code,
10545440, --version-name, 0.2.4-81-gb1e98ea, --no-version-vectors, -F, C:\Users\
ADMINI~1\AppData\Local\Temp\APKTOOL5181806592759903079.tmp, -0, arsc, -0, so, -0
, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, D:\Wayne\Programming\apktool\microg\res, -M, D:\Wayne\Programming\apktool\microg\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\dots_horizontal.x
ml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\dots_horizontal.x
ml:4: error: No resource identifier found for attribute 'pathData' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\gcm_bell.xml:2: e
rror: No resource identifier found for attribute 'viewportWidth' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\gcm_bell.xml:2: e
rror: No resource identifier found for attribute 'viewportHeight' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\gcm_bell.xml:4: e
rror: No resource identifier found for attribute 'fillColor' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\gcm_bell.xml:4: error: No resource identifier found for attribute 'pathData' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_less.xm
l:2: error: No resource identifier found for attribute 'viewportWidth' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_less.xm
l:2: error: No resource identifier found for attribute 'viewportHeight' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_less.xm
l:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_less.xm
l:4: error: No resource identifier found for attribute 'pathData' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_more.xm
l:2: error: No resource identifier found for attribute 'viewportWidth' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_more.xm
l:2: error: No resource identifier found for attribute 'viewportHeight' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_more.xm
l:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\ic_expand_more.xm
l:4: error: No resource identifier found for attribute 'pathData' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\location_marker.x
ml:2: error: No resource identifier found for attribute 'viewportWidth' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\location_marker.x
ml:2: error: No resource identifier found for attribute 'viewportHeight' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\location_marker.x
ml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\location_marker.x
ml:4: error: No resource identifier found for attribute 'pathData' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\self_check.xml:2:
 error: No resource identifier found for attribute 'viewportWidth' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\self_check.xml:2:
 error: No resource identifier found for attribute 'viewportHeight' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\self_check.xml:4:
 error: No resource identifier found for attribute 'fillColor' in package 'android'
W: D:\Wayne\Programming\apktool\microg\res\drawable-anydpi-v21\self_check.xml:4:
 error: No resource identifier found for attribute 'pathData' in package 'android'`
### Steps to Reproduce
1. `apktool if framework-res.apk`
`apktool d microg.apk`
`apktool b microg.apk `

### Frameworks
[https://www.dropbox.com/s/q91od465qiy0jt2/framework-res.apk?dl=0](https://www.dropbox.com/s/q91od465qiy0jt2/framework-res.apk?dl=0)

### APK
[https://microg.org/fdroid/repo/com.google.android.gms-10545440.apk](https://microg.org/fdroid/repo/com.google.android.gms-10545440.apk)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? `Yes`
2. If you are trying to install a modified apk, did you resign it? `Not doing this.`
3. Are you using the latest apktool version?  `Yes.`

**Comment by acsway878787** [comment] 2017-03-27 17:35
Can someone tell me whether it's a bug or not?
It made my head ache for a long time...

**Comment by iBotPeaches** [comment] 2017-03-27 17:36
This report is only two days old. Give me some time :)

A pretty large project to maintain by myself.

**Comment by acsway878787** [comment] 2017-03-27 18:11
@iBotPeaches Got it. Sorry for bothering you...
Hope you can deal with them!

**Comment by Furniel** [comment] 2017-03-27 18:34
It's not a bug.
com.google.android.gms-10545440.apk target sdk version is 23 and your framework sdk is 19. Try to use apktool default framework for this apk(run java -jar apktool.jar empty-framework-dir --force or delete C:\Users\Administrator\AppData\Local\apktool\framework\1.apk manually and try again).
```
java -jar apktool.jar d com.google.android.gms-10545440.apk
I: Using Apktool 2.2.2 on com.google.android.gms-10545440.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\furniel\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

java -jar apktool.jar b com.google.android.gms-10545440
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
```

**Comment by acsway878787** [comment] 2017-03-28 12:12
@Furniel Thanks a lot!
You save me a day: )

**Comment by iBotPeaches** [comment] 2017-03-29 15:11
Thanks for the help. Looks like just an updated framework. Closing this.

**Closed by iBotPeaches** 2017-03-29 15:11 UTC
Labels: Can't Confirm

**Comment by kartikchauhan** [comment] 2018-05-11 19:50
Download [aapt.exe](http://www.mediafire.com/?e8ww8wbgcowbti4) and keep the file in the same directory in which your `apktool.jar` and `apktool.bat` files are.

Use commands `java -jar apktool.jar d -s your_apk_file.apk` for decompiling and `java -jar apktool.jar b folder_name` for compiling. Here `folder_name` is the name of the folder that generated after decompiling.
