### ISSUE TITLE
Not able to repack the apk

### ISSUE THREAD

**Issue by AshiqKony** [iBotPeaches/Apktool#1037] opened 2015-09-07 12:34 UTC
I have teamviewer apk which can be decoded using apktool but while packing (apktool b -f -s cmd)it gives me following error.

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.co
mmon.BrutException: could not exec command: [C:\Users\KH602\AppData\Local\Temp\brut_util_Jar_4296855
100725796123.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --ve
rsion-code, 3264, --version-name, 10.0.3264, -F, C:\Users\KH602\AppData\Local\Temp\APKTOOL6067401783
145464996.tmp, -0, arsc, -I, C:\Users\KH602\apktool\framework\1.apk, -S, C:\Users\KH602\Desktop\temp
\apktool\com.teamviewer.quicksupport.market\res, -M, C:\Users\KH602\Desktop\temp\apktool\com.teamvie
wer.quicksupport.market\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\U
sers\KH602\AppData\Local\Temp\brut_util_Jar_4296855100725796123.tmp, p, --forced-package-id, 127, --
min-sdk-version, 14, --target-sdk-version, 21, --version-code, 3264, --version-name, 10.0.3264, -F,
C:\Users\KH602\AppData\Local\Temp\APKTOOL6067401783145464996.tmp, -0, arsc, -I, C:\Users\KH602\apkto
ol\framework\1.apk, -S, C:\Users\KH602\Desktop\temp\apktool\com.teamviewer.quicksupport.market\res,
-M, C:\Users\KH602\Desktop\temp\apktool\com.teamviewer.quicksupport.market\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\KH602\AppData\Local\Temp\bru
t_util_Jar_4296855100725796123.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk
-version, 21, --version-code, 3264, --version-name, 10.0.3264, -F, C:\Users\KH602\AppData\Local\Temp
\APKTOOL6067401783145464996.tmp, -0, arsc, -I, C:\Users\KH602\apktool\framework\1.apk, -S, C:\Users\
KH602\Desktop\temp\apktool\com.teamviewer.quicksupport.market\res, -M, C:\Users\KH602\Desktop\temp\a
pktool\com.teamviewer.quicksupport.market\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
```

**Comment by iBotPeaches** [comment] 2015-09-12 04:45
```
/home/ibotpeaches/Downloads/Apktool/Bug1037/com.teamviewer.quicksupport.market/res/layout/fragment_instantsupport.xml:22: error: Error parsing XML: not well-formed (invalid token)

/home/ibotpeaches/Downloads/Apktool/Bug1037/com.teamviewer.quicksupport.market/res/layout/fragment_qs.xml:23: error: Error parsing XML: not well-formed (invalid token)
```

Duplicate of #885

**Closed by iBotPeaches** 2015-09-12 04:45 UTC
