### ISSUE TITLE
Samsung Galaxy Note 4 (N910F - 5.1.1) SystemUI issue

### ISSUE THREAD

**Issue by Jertlok** [iBotPeaches/Apktool#1029] opened 2015-08-30 16:52 UTC
Hello there, yesterday has been released the 5.1.1 for the Samsung Galaxy Note 4 (N910F).
Today i tried to decompile and then recompile without any changes the SystemUI and when i moved it into my phone i noticed an issue: http://i.imgur.com/MOB4pLv.jpg (Look at the bottom)

The decompilation / Compilation didn't show any errors at all, only two warnings related to missing translations.

What can we do?

Here is the Framework-res.apk & SystemUI.apk:
https://drive.google.com/file/d/0B2osSqW4Jxl8bzNxdFdxVkZ4RWM/view?usp=sharing

**Comment by iBotPeaches** [comment] 2015-08-30 16:56
I believe I fixed this here: https://github.com/iBotPeaches/Apktool/commit/421999747082b05e576cf3bdeba590fc1710cd31

Which will be in 2.0.2.

**Comment by Jertlok** [comment] 2015-08-30 16:57
Oh, i've compiled the latest ApkTool via gradlebuild (Windows) and i've got the ApkTool v 2.0.2 (dirty).

Also tried with this version but i had the same issue..

**Comment by iBotPeaches** [comment] 2015-08-30 17:18
Could be duplicate of #926 or #1023 , not sure. All of these related issues I'm sure are aapt's fault.

**Comment by Jertlok** [comment] 2015-08-30 17:59
I see...
I hope you find the aapt's issue!

**Comment by iBotPeaches** [comment] 2015-09-06 22:07
Closing as duplicate of #1023.

Appears to be aapt changing the order of attributes in various `/layouts` causing these troubles.

**Closed by iBotPeaches** 2015-09-06 22:07 UTC
