### ISSUE TITLE
NO_COMPRESS_PATTERN has bug

### ISSUE THREAD

**Issue by realityJie** [iBotPeaches/Apktool#1577] opened 2017-08-02 10:02 UTC
there is a bug in Androlib.java
in the line of 169
`if (isAPKFileNames(file) && !NO_COMPRESS_PATTERN.matcher(file).find())`
the logic want to get the list of NO_COMPRESS files, but in fact, it gets the list of COMPRESS files!

**Comment by iBotPeaches** [comment] 2017-08-30 18:59
Closing as duplicate of #1272. 

I created unit-test here - https://github.com/iBotPeaches/Apktool/commit/a1cb15d721f2a03a1ad03a5c5f0a46b1384dd031 and it was passing. Therefore this logic is okay.

**Closed by iBotPeaches** 2017-08-30 18:59 UTC
