### ISSUE TITLE
[BUG] in recompiling whatsapp mod <activity-alias>

### ISSUE THREAD

**Issue by thelordehsan** [iBotPeaches/Apktool#3024] opened 2023-03-08 08:12 UTC
How to fix this error? I found this error when i was trying to recompile whatsapp mod.

### Information
1. **Apktool Version (`apktool -2.6.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (WhatsApp MOD)** -

I: Using Apktool 2.6.1
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Building resources...
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:676: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:683: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:690: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:697: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:704: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:711: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:718: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:725: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:732: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:739: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:746: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:753: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:760: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:767: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:774: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:781: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:788: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:795: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:802: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml:809: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\MUHAMM~1\AppData\Local\Temp\brut_util_Jar_5432596059535777383941878568944917819.tmp, link, -o, C:\Users\MUHAMM~1\AppData\Local\Temp\APKTOOL513194651234751294.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 29, --version-code, 222377002, --version-name, 2.22.23.77, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\MUHAMM~1\AppData\Local\Temp\APKTOOL4842908326227438809.tmp, -0, arsc, -I, C:\Users\Muhammad Ehsan Kambo\AppData\Local\apktool\framework\1.apk, --manifest, E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\AndroidManifest.xml, E:\softwares\APK Easy Tool v1.60 Portable\1-Decompiled APKs\TA2WhatsApp_V28_By_Nooraldeen (1)\build\resources.zip]
Compile failed. Please read the log

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment] 2023-03-18 16:41
Closing as duplicate of https://github.com/iBotPeaches/Apktool/issues/2992#issuecomment-1454855538

**Closed by iBotPeaches** 2023-03-18 16:41 UTC
