### ISSUE TITLE
Size of the Rebuilt apk is bigger

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1401] opened 2017-01-02 07:59 UTC
Decompiled-Recompiled apk without any changes and the rebuilt apk is much bigger. Example apk: UC Browser. Size of the original apk is 19 MB but the rebuilt apk(without signing) is more than 30 MB in size. Tried with many apktool versions including Apktool 2.2.2-166bf5-SNAPSHOT. Result is the same.

Here's the apk link: http://gjxz.ucweb.com/files/UCBrowser/en-us/354/UCBrowser_V11.1.5.890_android_pf145_(Build161230145121).apk?auth_key=1483942265-0-0-cc39ea0e03c9cc69c8b21684f8a3ec70&vh=ffabf19b21dc1a59768434ed75f8fb74&SESSID=c8ffa9461a3509f40aa6f9b624acf3d2 or can be downloaded from http://wap.ucweb.com

**Comment by iBotPeaches** [comment] 2017-01-06 12:01
So this application has some files that are deflated and some that are stored, but they are the same extension so apktool encounters the first file and extracts the extension and claims it is stored.

This is a duplicate of #1335 , which will be patched in #1272

**Closed by iBotPeaches** 2017-01-06 12:01 UTC
Labels: Duplicate
