### ISSUE TITLE
ArrayIndexOutOfBoundsException in ARSCDecoder

### ISSUE THREAD

**Issue by MarcMil** [iBotPeaches/Apktool#1016] opened 2015-08-04 16:52 UTC
Hi there,
I have a problem on an apk; I used the current version from git.
The used apk file can be obtained at https://drive.google.com/file/d/0B7999XZhN6ySWTdhY25ZUHg2cDg/view
```
java -jar ./brut.apktool/apktool-cli/build/libs/apktool-cli.jar d /home/marc/Downloads/SIGNificant4Android_v2436_Beta_r2092_google_play.apk  -f
I: Using Apktool 2.0.2-099cc0-SNAPSHOT on SIGNificant4Android_v2436_Beta_r2092_google_play.apk
I: Loading resource table...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 17
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment] 2015-08-04 22:56
Duplicate of #1014.

I believe its the new Dexguard at fault.

**Closed by iBotPeaches** 2015-08-04 22:56 UTC
Labels: duplicate
