### ISSUE TITLE
How to override * .dex in the assets folder

### ISSUE THREAD

**Issue by sbe37** [iBotPeaches/Apktool#1892] opened 2018-09-04 05:15 UTC
Q. 
Hello,
I am having trouble with decompilation.
There is a file of "assets/****/****. dex" in the APK file.
When de-compiling via apktool, the corresponding dex file is released.
I have a question. 
Is there a way to disable dex files from being decomposed at "assets/****/****. dex"?
If you know, please help me.

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - OSX 10.13.6
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment] 2018-09-18 17:42
I don't think dex files are being decoded in `/assets`. This open bug report says they do not - https://github.com/iBotPeaches/Apktool/issues/1312

Duplicate of that.

**Closed by iBotPeaches** 2018-09-18 17:42 UTC
