### ISSUE TITLE
Can't build with resource use reference attribute

### ISSUE THREAD

**Issue by quyetpv** [iBotPeaches/Apktool#2144] opened 2019-08-01 09:21 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Playstore
I see in apk by change apk to .rar file and view on winrar it cotain "r" directory which contain all resource reference but when use apktool d I don't see this directory.
### Stacktrace/Logcat

```
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\layout\
w.xml:6: error: No resource identifier found for attribute 'navigationContentDes
cription' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\layout-
v21\w.xml:6: error: No resource identifier found for attribute 'navigationConten
tDescription' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\layout\
z.xml:2: error: No resource identifier found for attribute 'paddingBottomNoButto
ns' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\layout\
z.xml:2: error: No resource identifier found for attribute 'paddingTopNoTitle' i
n package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\layout-
v17\z.xml:2: error: No resource identifier found for attribute 'paddingBottomNoB
uttons' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\layout-
v17\z.xml:2: error: No resource identifier found for attribute 'paddingTopNoTitl
e' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\animato
r-v21\a.xml:4: error: No resource identifier found for attribute 'state_collapse
d' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\animato
r-v21\a.xml:4: error: No resource identifier found for attribute 'state_collapsi
ble' in package 'com.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\c
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\d
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\h
s.xml:4: error: No resource identifier found for attribute 'alpha' in package 'c
om.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\r
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\s
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\t
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\u
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\v
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\w
.xml:4: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\w
.xml:5: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
W: D:\Projects\SuperApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res\color\w
.xml:6: error: No resource identifier found for attribute 'alpha' in package 'co
m.videoslideshow.photomovie.videomaker'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit
 code = 1): [C:\Users\Laptop88\AppData\Local\Temp\brut_util_Jar_8123040856827648
644.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-versio
n, 26, --version-code, 223, --version-name, 2.2.3, --no-version-vectors, -F, C:\
Users\Laptop88\AppData\Local\Temp\APKTOOL7593469748466769583.tmp, -0, mp4, -0, o
gg, -0, arsc, -I, C:\Users\Laptop88\AppData\Local\Temp\1.apk, -S, D:\Projects\Su
perApkToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\res, -M, D:\Projects\SuperAp
kToolv2.1_ng\SuperApkToolv2.1\tools\videoslide\AndroidManifest.xml]
```
### Steps to Reproduce
1. `apktool  d`
2. apktool b
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.videoslideshow.photomovie.videomaker
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2019-08-17 10:57
This is a duplicate of a few tickets:
 - https://github.com/iBotPeaches/Apktool/issues/2141
 - https://github.com/iBotPeaches/Apktool/issues/1272
 - https://github.com/iBotPeaches/Apktool/issues/2151

It is a form of resource obfuscation which makes difficult.

**Closed by iBotPeaches** 2019-08-17 10:57 UTC
