### ISSUE TITLE
Could not decode arsc files

### ISSUE THREAD

**Issue by Uroc327** [iBotPeaches/Apktool#908] opened 2015-04-07 19:10 UTC
When trying to install `framework-res.apk`, `framework-res-htc.apk` and `com.htc.resources.apk` I'm getting AndrolibExceptions that the asrc file couldn't get parsed.

```
$ apktool --advanced if -p frameworks -t res framework-res.apk 
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
    at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:685)
    at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:667)
    at brut.androlib.Androlib.installFramework(Androlib.java:660)
    at brut.apktool.Main.cmdInstallFramework(Main.java:240)
    at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
    at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
    at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    ... 6 more
```
```
$ apktool if -p frameworks -t res-htc framework-res-htc.apk 
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
    at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:685)
    at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:667)
    at brut.androlib.Androlib.installFramework(Androlib.java:660)
    at brut.apktool.Main.cmdInstallFramework(Main.java:240)
    at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000201
    at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
    at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
    at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:231)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    ... 6 more
```
```
$ apktool if -p frameworks -t com.htc.resources com.htc.resources.apk 
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
    at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:685)
    at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:667)
    at brut.androlib.Androlib.installFramework(Androlib.java:660)
    at brut.apktool.Main.cmdInstallFramework(Main.java:240)
    at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
    at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
    at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    ... 6 more
```

The apks are all from a HTC stock rom.

**Comment by iBotPeaches** [comment] 2015-04-07 19:42
Yep duplicate of #644.

HTC APKs have 40 bytes of data in the `ResSpec` header, but 2 bytes of that are currently unknown.

**Closed by iBotPeaches** 2015-04-07 19:42 UTC

**Comment by Uroc327** [comment] 2015-04-07 21:49
Assumed it only counts for htc specific apps and not the general framework.. Sorry for spam :)

**Comment by iBotPeaches** [comment] 2015-04-07 21:55
Well I was assuming, since the 3 files you mentioned were all frameworks. I know at least one of them I confirmed with that error and since there weren't any attached I assumed the other two would show the same result.

So no problem.
