### ISSUE TITLE
[BUG] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by LordAlex2015** [iBotPeaches/Apktool#2810] opened 2022-05-04 16:11 UTC
I'm trying to recompile the tiktok apk, but it crashes

### Information
Version: `2.6.1`
OS: Linux

### Stacktrace/Logcat

```
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes13 folder into classes13.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes10 folder into classes10.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes11 folder into classes11.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes12 folder into classes12.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/big.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/big.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/bpy.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/bpy.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/bq0.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/bq0.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/bq1.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land-v22/bq1.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land/ar_.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land/ar_.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land/bfh.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land/bfh.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land/bi4.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land/bi4.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land/bi7.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land/bi7.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land/big.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land/big.xml: error: file failed to compile.
W: /home/arvix/Desktop/tiktok/res/layout-land/bjh.xml:2: error: duplicate attribute.
W: /home/arvix/Desktop/tiktok/res/layout-land/bjh.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_171189713801739020606207990889561766678.tmp, compile, --dir, /home/arvix/Desktop/tiktok/res, --legacy, -o, /home/arvix/Desktop/tiktok/build/resources.zip]

```

**Comment by rkmax** [comment] 2022-05-04 23:52
I got a similar result

```
$ apktool d -o out_dir -t device app.pk

I: Using Apktool 2.6.1 on app.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/rkmax/.local/share/apktool/framework/1-device.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory

$ apktool b  -o build.apk out_dir
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /home/rkmax/apktool/out_dir/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_74939273820707919344813005827756433867.tmp, p, --forced-package-id, 127, --version-code, 290, --version-name, 5.36.0, --no-version-vectors, -F, /tmp/APKTOOL2791337228592563714.tmp, -e, /tmp/APKTOOL5754287998738842960.tmp, -0, arsc, -I, /home/rkmax/.local/share/apktool/framework/1-device.apk, -S, /home/rkmax/apktool/out_dir/res, -M, /home/rkmax/apktool/out_dir/AndroidManifest.xml]
```

using the the flag `--use-aapt2`
```
$ apktool b  --use-aapt2 -o build.apk out_dir
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/rkmax/apktool/out_dir/res/animator/2130837504.xml:4: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/animator/2130837504.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/animator/2130837520.xml:4: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/animator/2130837520.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/color/2131100002.xml:5: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/color/2131100002.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/color/2131100003.xml:5: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/color/2131100003.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/drawable/2131232086.xml:14: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/drawable/2131232086.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/font/2131296257.xml:4: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/font/2131296257.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558461.xml:21: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558461.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558625.xml:5: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558625.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558794.xml:2: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558794.xml: error: file failed to compile.
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558897.xml:11: error: not well-formed (invalid token).
W: /home/rkmax/apktool/out_dir/res/layout-land/2131558897.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_48259045504909079481482194009030662023.tmp, compile, --dir, /home/rkmax/apktool/out_dir/res, --legacy, -o, /home/rkmax/apktool/out_dir/build/resources.zip]
```

**Comment by iBotPeaches** [comment] 2022-05-07 11:05
This is a duplicate of the Tiktok issue here - https://github.com/iBotPeaches/Apktool/issues/2674

Thanks for the report, but closing as duplicate.

**Closed by iBotPeaches** 2022-05-07 11:05 UTC

**Comment by Mubelotix** [comment] 2024-06-30 11:17
Both github issues are closed but the actual issue isn't fixed at all

**Comment by iBotPeaches** [comment] 2024-06-30 11:23
> Both github issues are closed but the actual issue isn't fixed at all

Did you read this comment? https://github.com/iBotPeaches/Apktool/issues/2674#issuecomment-1657234077
