### ISSUE TITLE
Samsung Apps Not Recompile Like framework-res.apk,systemui.apk,secsetting2.apk in android 8.0

### ISSUE THREAD

**Issue by gsmmazhar** [iBotPeaches/Apktool#1932] opened 2018-11-02 10:40 UTC
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

Error..
```
C:\Users\Piya Jee\Desktop\apktool2 work on oreo>apktool b framework-res
I: Using Apktool 2.3.4_0503
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Piya Jee\Desktop\apktool2 work on oreo\framework-res\res\values\styles.xml:2452: error: Resource entry Theme.DeviceDefault already has bag item dropdownListPreferredItemHeight.
W: C:\Users\Piya Jee\Desktop\apktool2 work on oreo\framework-res\res\values\styles.xml:2451: Originally defined here.
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PIYAJE1\AppData\Local\Temp\brut_util_Jar_96045326345974598.tmp, p, --forced-package-id, 1, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\PIYAJE1\AppData\Local\Temp\APKTOOL2390478510879530650.tmp, -x, -0, arsc, -0, qmg, -0, arsc, -S, C:\Users\Piya Jee\Desktop\apktool2 work on oreo\framework-res\res, -M, C:\Users\Piya Jee\Desktop\apktool2 work on oreo\framework-res\AndroidManifest.xml]
```
i post below framework-res.apk
you can test and tell me solution
https://drive.google.com/open?id=1Z3jgUkG3pNlnYi68XxqtQ-aKpWng8NqH

**Comment by gsmmazhar** [comment] 2018-11-05 12:33
why not reply me any one

**Comment by iBotPeaches** [comment] 2018-11-05 13:16
This is a duplicate of #1927, which you already responded with multiple times. There is no need to spam issues.

**Closed by iBotPeaches** 2018-11-05 13:16 UTC
