### ISSUE TITLE
On MAC getting exception while decompiling The Emirates apk

### ISSUE THREAD

**Issue by kuldeepkalassts** [iBotPeaches/Apktool#1768] opened 2018-04-10 11:30 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - MAC
3. **APK From? (Playstore, ROM, Other)** - apkpure.com

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: brut.androlib.AndrolibException: java.io.FileNotFoundException: /Users/kuldeep/Desktop/MobileHelper/Resources/1523358654243sample/unknown/   . (No such file or directory)
	at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:617)
	at brut.androlib.Androlib.build(Androlib.java:313)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
	at Main.main(Main.java:150)
	... 5 more
Caused by: java.io.FileNotFoundException: /Users/kuldeep/Desktop/MobileHelper/Resources/1523358654243sample/unknown/   . (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at brut.util.BrutIO.copy(BrutIO.java:102)
	at brut.androlib.Androlib.copyUnknownFiles(Androlib.java:670)
	at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:615)
	... 10 more

```

### Steps to Reproduce
1. `apktool d -r`
2. Getting exception this step

################ Building sample APK
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...

### APK

https://apkpure.com/the-emirates-app/com.emirates.ek.android

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
 No
2. If you are trying to install a modified apk, did you resign it? 
can't reach to that point

3. Are you using the latest apktool version?
Yes.

**Comment by kuldeepkalassts** [comment] 2018-04-10 11:32
@iBotPeaches 
you mentioned in https://github.com/iBotPeaches/Apktool/issues/1460 that it is issue of windows.

but I am using MAC and getting exception

**Comment by kuldeepkalassts** [comment] 2018-04-10 12:06
Tested on Linux , it is working fine there

**Comment by iBotPeaches** [comment] 2018-04-10 20:07
Thanks for the details. At the end of the day, it seems to be an issue with charsets and this is a combined duplicate of AndroResGuard (#1719) and characters #1460 

As you can tell, application developers are starting to leverage tools that are getting smarter and smarter in how they store/handle their compiled code.

**Closed by iBotPeaches** 2018-04-10 20:07 UTC

**Comment by kuldeepkalassts** [comment] 2018-04-11 07:26
I don't think this issue is same as facebook obfuscation  issue https://github.com/iBotPeaches/Apktool/issues/1719 . 

I tried Emirates on Linux and it works fine there.
