### ISSUE TITLE
Can't recompile Google Maps 9.20.1

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#1161] opened 2016-02-14 00:21 UTC
Windows 10, APKTool 2.0.3, Log attached

-------------------------------------------------------------------------- 
|14/02/2016 --  0:28:55.52| 
-------------------------------------------------------------------------- 
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
A subdirectory or file modified-system-apk-files-here already exists.
ERROR: input directory 'arsc' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_6254379247327783736.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 23, --version-code, 920100124, --version-name, 9.20.1, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL4868799044299139937.tmp, -0, arsc, -0, dat, -0, bin, -0, zip, -0, , -0, arsc, -I, C:\Users\Ilan\apktool\framework\1.apk, -S, C:\Users\Ilan\Downloads\APK-Multi-ToolALBE45\projects\Maps9201.apk\res, -M, C:\Users\Ilan\Downloads\APK-Multi-ToolALBE45\projects\Maps9201.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
	at brut.androlib.Androlib.buildResources(Androlib.java:410)
	at brut.androlib.Androlib.build(Androlib.java:298)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_6254379247327783736.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 23, --version-code, 920100124, --version-name, 9.20.1, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL4868799044299139937.tmp, -0, arsc, -0, dat, -0, bin, -0, zip, -0, , -0, arsc, -I, C:\Users\Ilan\apktool\framework\1.apk, -S, C:\Users\Ilan\Downloads\APK-Multi-ToolALBE45\projects\Maps9201.apk\res, -M, C:\Users\Ilan\Downloads\APK-Multi-ToolALBE45\projects\Maps9201.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_6254379247327783736.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 23, --version-code, 920100124, --version-name, 9.20.1, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL4868799044299139937.tmp, -0, arsc, -0, dat, -0, bin, -0, zip, -0, , -0, arsc, -I, C:\Users\Ilan\apktool\framework\1.apk, -S, C:\Users\Ilan\Downloads\APK-Multi-ToolALBE45\projects\Maps9201.apk\res, -M, C:\Users\Ilan\Downloads\APK-Multi-ToolALBE45\projects\Maps9201.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)

**Comment by iBotPeaches** [comment] 2016-02-14 00:28
Duplicate of #1122 

Fix in incoming 2.1.0 release.

**Closed by iBotPeaches** 2016-02-14 00:28 UTC
