### ISSUE TITLE
HELP!.. I can't recompile framework-res.apk (API:27)...

### ISSUE THREAD

**Issue by brckhan88** [iBotPeaches/Apktool#1938] opened 2018-11-18 15:45 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.3.4
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat
[apktool.log](https://github.com/iBotPeaches/Apktool/files/2592924/apktool.log)

```

### Steps to Reproduce
1. apktool if framework-res.apk
2. apktool if SystemUI.apk
3. apktool d framework-res.apk
4. apktool b framework-res

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/2592926/framework-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? 
No, I've already tried all other combinations like : java -jar apktool.jar b framework-res
but the result is same
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? None of worked after version 2.3.x

Also started a thread on XDA:https://forum.xda-developers.com/android/help/help-recompile-framework-res-apk-t3841824

**Comment by ibuprophen1** [comment] 2018-11-18 15:55
This looks like its the same/similar to a number of other 9.png/9-png issues that's been reported and is well known by @iBotPeaches. 

The following link will provide you with a search result with "Open" issues that has "9.png" and "framework" within the results. 

https://github.com/iBotPeaches/Apktool/issues?q=9.png+framework+is%3Aopen

I hope it helps out in some way... :-) 


~Ibuprophen

**Comment by iBotPeaches** [comment] 2018-11-19 15:54
This is a known issue with no planned fix. It was attempted at one point and backfired. A limitation of Windows sadly.

What happens is the executed command exceeds the length allowed for Windows. Lots of details and explanations, if curious are here - #1272

Marking as duplicate of #1272

**Closed by iBotPeaches** 2018-11-19 15:54 UTC
