### ISSUE TITLE
Could not decode attr value: apktool d com.bigfatgorillastudios.minebot.apk

### ISSUE THREAD

**Issue by dongeast** [iBotPeaches/Apktool#937] opened 2015-05-05 13:29 UTC
Apk can download from https://play.google.com/store/apps/details?id=com.bigfatgorillastudios.minebot

C:\apktool>apktool.bat d -f com.bigfatgorillastudios.minebot.apk
I: Using Apktool 2.0.0-2bd1e5-SNAPSHOT on com.bigfatgorillastudios.minebot.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Tao\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=
textAlignment, value=0x00000004
W: Could not decode attr value, using undecoded value instead: ns=android, name=
textAlignment, value=0x00000004
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x010103b1
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:57)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:53)
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:3
6)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlRe
sourceParser.java:369)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValu
e(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartT
ag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Stati
cXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamD
ecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDe
coder.java:141)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamD
ecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:1
14)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:9
9)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:339
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:133)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment] 2015-05-05 15:51
Duplicate of #913

**Closed by iBotPeaches** 2015-05-05 15:51 UTC
Labels: duplicate

**Comment by dongeast** [comment] 2015-05-05 16:00
I used apktool_2.0.0.jar, not 2.0.0rc4.
my other colleague used 2.0.0-b81aac-SNAPSHOT to decompile com.bigfatgorillastudios.minebot.apk very well, I replace the apktool_2.0.0.jar to apktool 2.0.0-b81aac-SNAPSHOT, But I got the error too.

apktool_2.0.0.jar do not well on my computer.

**Comment by iBotPeaches** [comment] 2015-05-05 16:02
Okay, regardless of the version used. The bug you are reporting has already been reported and confirmed.
