### ISSUE TITLE
ApkTool 2.2.2 can not to pack AsusSettings.apk but 2.0.3 work fine

### ISSUE THREAD

**Issue by BORETS24** [iBotPeaches/Apktool#1467] opened 2017-04-01 07:12 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 17.04/Windows, no difference
3. **APK From? (Playstore, ROM, Other)** -Stock ROM
### Stacktrace/Logcat

```
Include stacktrace here
```
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'activity_main_title' has no default translation.
W: warning: string 'android_version' has no default translation.
W: warning: string 'app_name' has no default translation.
W: warning: string 'asus_app2sd_blacklist_warning' has no default translation.
W: warning: string 'asus_app2sd_notif_title' has no default translation.
W: warning: string 'att_factory_reset_password_summary' has no default translation.
W: warning: string 'auto_brightness_settings' has no default translation.
W: warning: string 'camera_double_tap_power_gesture_desc' has no default translation.
W: warning: string 'camera_double_tap_power_gesture_title' has no default translation.
W: warning: string 'camera_gesture_desc' has no default translation.
W: warning: string 'camera_gesture_title' has no default translation.
W: warning: string 'clear_apps_data_summary' has no default translation.
W: warning: string 'crypt_keeper_confirm_encrypt' has no default translation.
W: warning: string 'cta_category_communicate' has no default translation.
W: warning: string 'cta_category_data' has no default translation.
W: warning: string 'dialog_message' has no default translation.
W: warning: string 'dialog_title' has no default translation.
W: warning: string 'keywords_color_mode' has no default translation.
W: warning: string 'media_format_button_text' has no default translation.
W: warning: string 'media_format_desc' has no default translation.
W: warning: string 'media_format_final_button_text' has no default translation.
W: warning: string 'media_format_final_desc' has no default translation.
W: warning: string 'media_format_gesture_explanation' has no default translation.
W: warning: string 'media_format_summary' has no default translation.
W: warning: string 'media_format_title' has no default translation.
W: warning: string 'monotype_dialog_title' has no default translation.
W: warning: string 'monotype_restart_dialog_button_2' has no default translation.
W: warning: string 'no_all_caps' has no default translation.
W: warning: string 'notificationpanel_settings_title' has no default translation.
W: warning: string 'picture_color_mode' has no default translation.
W: warning: string 'picture_color_mode_desc' has no default translation.
W: warning: string 'pmode_set_two_passwords' has no default translation.
W: warning: string 'quick_setting' has no default translation.
W: warning: string 'quick_setting_summary' has no default translation.
W: warning: string 'security_settings_fingerprint_preference_summary_none' has no default translation.
W: warning: string 'unlock_backup_info_summary' has no default translation.
W: warning: string 'yes_all_caps' has no default translation.
```

Stop in this place and not continue... If try APK Tool 2.0.3- pack successfully

```
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
warning: string 'activity_main_title' has no default translation.
warning: string 'android_version' has no default translation.
warning: string 'app_name' has no default translation.
warning: string 'asus_app2sd_blacklist_warning' has no default translation.
warning: string 'asus_app2sd_notif_title' has no default translation.
warning: string 'att_factory_reset_password_summary' has no default translation.
warning: string 'auto_brightness_settings' has no default translation.
warning: string 'camera_double_tap_power_gesture_desc' has no default translation.
warning: string 'camera_double_tap_power_gesture_title' has no default translation.
warning: string 'camera_gesture_desc' has no default translation.
warning: string 'camera_gesture_title' has no default translation.
warning: string 'clear_apps_data_summary' has no default translation.
warning: string 'crypt_keeper_confirm_encrypt' has no default translation.
warning: string 'cta_category_communicate' has no default translation.
warning: string 'cta_category_data' has no default translation.
warning: string 'dialog_message' has no default translation.
warning: string 'dialog_title' has no default translation.
warning: string 'keywords_color_mode' has no default translation.
warning: string 'media_format_button_text' has no default translation.
warning: string 'media_format_desc' has no default translation.
warning: string 'media_format_final_button_text' has no default translation.
warning: string 'media_format_final_desc' has no default translation.
warning: string 'media_format_gesture_explanation' has no default translation.
warning: string 'media_format_summary' has no default translation.
warning: string 'media_format_title' has no default translation.
warning: string 'monotype_dialog_title' has no default translation.
warning: string 'monotype_restart_dialog_button_2' has no default translation.
warning: string 'no_all_caps' has no default translation.
warning: string 'notificationpanel_settings_title' has no default translation.
warning: string 'picture_color_mode' has no default translation.
warning: string 'picture_color_mode_desc' has no default translation.
warning: string 'pmode_set_two_passwords' has no default translation.
warning: string 'quick_setting' has no default translation.
warning: string 'quick_setting_summary' has no default translation.
warning: string 'security_settings_fingerprint_preference_summary_none' has no default translation.
warning: string 'unlock_backup_info_summary' has no default translation.
warning: string 'yes_all_caps' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...

Нажмите Enter для продолжения
```
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/887425/framework-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[AsusSettings.zip](https://github.com/iBotPeaches/Apktool/files/887426/AsusSettings.zip)


### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?
yes

**Comment by BORETS24** [comment] 2017-04-01 15:11
UPD: if wait about 30-40 **minutes** 2.2.2 pack too.

**Comment by iBotPeaches** [comment] 2017-04-04 11:41
```
➜  Bug1467 apktool if framework-res.apk -t 1467
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-1467.apk
➜  Bug1467 apktool d AsusSettings.apk -t 1467
I: Using Apktool 2.2.3-74f76a-SNAPSHOT on AsusSettings.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-1467.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1467 apktool b AsusSettings
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'activity_main_title' has no default translation.
W: warning: string 'android_version' has no default translation.
W: warning: string 'app_name' has no default translation.
W: warning: string 'att_factory_reset_password_summary' has no default translation.
W: warning: string 'auto_brightness_settings' has no default translation.
W: warning: string 'camera_double_tap_power_gesture_desc' has no default translation.
W: warning: string 'camera_double_tap_power_gesture_title' has no default translation.
W: warning: string 'camera_gesture_desc' has no default translation.
W: warning: string 'camera_gesture_title' has no default translation.
W: warning: string 'clear_apps_data_summary' has no default translation.
W: warning: string 'crypt_keeper_confirm_encrypt' has no default translation.
W: warning: string 'cta_category_communicate' has no default translation.
W: warning: string 'cta_category_data' has no default translation.
W: warning: string 'dialog_message' has no default translation.
W: warning: string 'dialog_title' has no default translation.
W: warning: string 'game_toolbar_app_settings_page_annotation' has no default translation.
W: warning: string 'game_toolbar_app_settings_page_title' has no default translation.
W: warning: string 'gesture_wake_up_screen' has no default translation.
W: warning: string 'in_app_toolbar_category_title' has no default translation.
W: warning: string 'keywords_color_mode' has no default translation.
W: warning: string 'master_clear_desc_take_ten_mins' has no default translation.
W: warning: string 'media_format_button_text' has no default translation.
W: warning: string 'media_format_desc' has no default translation.
W: warning: string 'media_format_final_button_text' has no default translation.
W: warning: string 'media_format_final_desc' has no default translation.
W: warning: string 'media_format_gesture_explanation' has no default translation.
W: warning: string 'media_format_summary' has no default translation.
W: warning: string 'media_format_title' has no default translation.
W: warning: string 'monotype_dialog_title' has no default translation.
W: warning: string 'monotype_restart_dialog_button_2' has no default translation.
W: warning: string 'no_all_caps' has no default translation.
W: warning: string 'notificationpanel_settings_title' has no default translation.
W: warning: string 'picture_color_mode' has no default translation.
W: warning: string 'picture_color_mode_desc' has no default translation.
W: warning: string 'pmode_set_two_passwords' has no default translation.
W: warning: string 'quick_setting' has no default translation.
W: warning: string 'quick_setting_summary' has no default translation.
W: warning: string 'security_settings_fingerprint_preference_summary_none' has no default translation.
W: warning: string 'swipe_up_to_wake_up_summary' has no default translation.
W: warning: string 'swipe_up_to_wake_up_title' has no default translation.
W: warning: string 'unlock_backup_info_summary' has no default translation.
W: warning: string 'verizon_demo_mode_factory_reset_master_clear_final_desc' has no default translation.
W: warning: string 'verizon_demo_mode_factory_reset_password_header_text' has no default translation.
W: warning: string 'yes_all_caps' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1467 
```

Took about 2 minutes over here. As Android evolves the size of the framework files grow additionally. There is already a bug report open about improving memory use and thus run time. Since this report didn't have a problem, but just optimization. Merging it into that one as a duplicate.

For reference, the framework is 10.5MB, this AsusSettings file is 20.5MB. Pretty big difference in size.

Duplicate of #1396

**Closed by iBotPeaches** 2017-04-04 11:41 UTC
Labels: Duplicate

**Comment by BORETS24** [comment] 2018-06-10 11:29
Situation is not changes even if I used lastest APKTool 2.3.3. When I try recompile AsusSettings.apk process continue 15-20 minutes. When I switch to APKTool older than 2.2.2, to 2.1.1,for example, recompile go 1-2 minutes!!! Big difference!!! Also APKTool 2.3.3 became more slowly recompile framework-res-apk(3-4 minutes a place of 1 minute on 2.1.1)
