### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by satmandu** [iBotPeaches/Apktool#2204] opened 2019-10-25 00:05 UTC
### Information
1. **Apktool Version (`apktool -version`)** -
apktool 2.0.0, 2.3.4, 2.4.0

2. **Operating System (Mac, Linux, Windows)** -
linux
3. **APK From? (Playstore, ROM, Other)** -
apkmirror

### Stacktrace/Logcat
```
apktool d com.google.android.talk_31.0.246194187-25731804_minAPI16\(arm64-v8a\)\(nodpi\)_apkmirror.com.apk 
I: Using Apktool 2.0.0 on com.google.android.talk_31.0.246194187-25731804_minAPI16(arm64-v8a)(nodpi)_apkmirror.com.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000001
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

```
apktool d com.google.android.talk_31.0.246194187-25731804_minAPI16\(arm64-v8a\)\(nodpi\)_apkmirror.com.apk 
I: Using Apktool 2.4.0 on com.google.android.talk_31.0.246194187-25731804_minAPI16(arm64-v8a)(nodpi)_apkmirror.com.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:53)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:748)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000202
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:354)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	... 8 more
```

### Steps to Reproduce
1. `apktool `

apktool d com.google.android.talk_31.0.246194187-25731804_minAPI16\(arm64-v8a\)\(nodpi\)_apkmirror.com.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

no

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/google-inc/hangouts/hangouts-31-0-246194187-release/hangouts-31-0-246194187-7-android-apk-download/download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

Maybe this is similar to https://github.com/iBotPeaches/Apktool/issues/1131 ?

**Comment by iBotPeaches** [comment] 2019-10-25 15:31
This is actually a dupe of #1874. Thanks for report, but closing as duplicate and merging into existing ticket.

**Closed by iBotPeaches** 2019-10-25 15:31 UTC
