### ISSUE TITLE
APKTool.jar Fail to build on Windows and Ubuntu 14.04 but builds on Mac OSX

### ISSUE THREAD

**Issue by raziel23x** [iBotPeaches/Apktool#949] opened 2015-05-18 23:48 UTC
When building on windows and Ubuntu I cannot get it to build it always failed to build  with clean install of the OS 

I am running VMware Workstation 11 to Run Clean installs of each OS on my windows machine and also running VMware Fusion Professional 7.1.1 on OSX to run test case

I ran the build instructions on
WINDOWS OS:
Windows 8.1 FAILED
Windows 8 FAILED
Windows 7 FAILED
Windows Vista FAILED
Window XP FAILED

WINDOWS TEST RESULTS
https://dl.dropboxusercontent.com/u/12310125/APKTOOL_FAILED_TEST/Windows_8.1_failed_build_results.zip

Linux OS:
Ubuntu 12.04 FAILED
Ubuntu 14.04 FAILED
Ubuntu 15.04 FAILED

LINUX TEST RESULTS
https://dl.dropboxusercontent.com/u/12310125/APKTOOL_FAILED_TEST/Ubuntu_14_failed_build_results.tar.gz

Mac OS X 10.10.3 Yosemite BUILD SUCCESSFUL 

For some reason I cannot rap my head around it why it is Failing to build for me on windows and linux even when I am running Clean installs of the Operating Systems but It builds just fine on MAC OSX

**Comment by iBotPeaches** [comment] 2015-05-19 11:17
Since it is a smali test, do you encounter these issues on the regular ole smali repo? https://github.com/JesusFreke/smali/issues

**Comment by raziel23x** [comment] 2015-05-19 11:57
yes i just tested it on windows 8.1 I have yet to boot up my mac or Linux boxes but why would they fail in linux and windows but compile just fine on a mac?

https://dl.dropboxusercontent.com/u/12310125/APKTOOL_FAILED_TEST/JesusFreke_smali_tests_Failure.zip

org.jf.dexlib2.AccessorTest > testAccessors FAILED
    junit.framework.AssertionFailedError at AccessorTest.java:125
:baksmali:javadocJar
:baksmali:signArchives SKIPPED
:baksmali:assemble
:baksmali:compileTestJava
:baksmali:testClasses
:baksmali:test
:baksmali:check
:baksmali:build
:smali:javadocJar
:smali:signArchives SKIPPED
:smali:assemble
:smali:build

105 tests completed, 1 failed
:baksmali:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexlib2:test'.
> There were failing tests. See the report at: file:///E:/TEST/smali/dexlib2/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by iBotPeaches** [comment] 2015-05-20 12:18
This is a smali test, so closing in favour of https://github.com/JesusFreke/smali/issues/289

**Closed by iBotPeaches** 2015-05-20 12:18 UTC

**Comment by Benjamin-Dobell** [comment] 2015-05-21 14:46
For anyone interested I've explained the root cause of the problem in the issue referenced above. Basically the test is making an assumption that the Java compiler will compile operators like ```&=``` using the specific JVM ```&=``` opcode. However, it seems the recent Java compilers are compiling this as a separate access, boolean-and (```&```), and assignment opcodes - meaning the test fails because it was looking for a ```&=``` opcode.

Consequently the test will need to be deleted, or at a minimum altered, but for now it's easiest just to comment out the contents of ```public void testAccessors() throws IOException```.

**Comment by raziel23x** [comment] 2015-05-21 15:45
https://github.com/JesusFreke/smali/issues/290
This fixed the compiling issue for me on windows for the smali building this patch may fix apktool as well for this test issue

**Comment by Benjamin-Dobell** [comment] 2015-05-21 15:51
@raziel23x To make life easy I've just submitted a corresponding pull request straight to Apktool - https://github.com/iBotPeaches/Apktool/pull/952

**Comment by raziel23x** [comment] 2015-05-23 18:38
This issue has been fixed in samli

0f1e995

https://github.com/JesusFreke/smali/commit/0f1e9950991772b8fb7c053f25e0f316999a82e1

**Comment by iBotPeaches** [comment] 2015-05-24 00:52
Don't normally merge changes until they are officially tagged in smali under a new version, but since this affected the build for a good deal of people, I've merged it into master.

**Comment by raziel23x** [comment] 2015-05-24 01:07
I can compile again outside of my mac yay!!
