### ISSUE TITLE
[BUG] Resource decoding crash

### ISSUE THREAD

**Issue by dejawho** [iBotPeaches/Apktool#2864] opened 2022-08-08 20:04 UTC
### Information
1. **Apktool Version 2.6.1** -
2. **Operating System Mac** -
3. **APK From? direct download (link below)** -

### Stacktrace/Logcat

```
ago 08, 2022 8:07:14 PM brut.androlib.ApkDecoder decode
INFORMAZIONI: Using Apktool 2.6.1 on Oathsworn-ItD-v1-2.apk
ago 08, 2022 8:07:14 PM brut.androlib.res.AndrolibResources loadMainPkg
INFORMAZIONI: Loading resource table...
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
ago 08, 2022 8:07:14 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
BUONO: Config flags size > 56, but exceeding bytes are all zero, so it should be ok.
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [ font-weight: bold] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:528)
	at brut.androlib.res.decoder.StringBlock$Tag.toString(StringBlock.java:167)
	at java.base/java.lang.String.valueOf(String.java:4213)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at brut.androlib.res.decoder.StringBlock.processStyledString(StringBlock.java:260)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:288)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:70)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
```

### Steps to Reproduce
1. `apktool -v decode Oathsworn-ItD-v1-2.apk `

### APK
[If this APK can be freely shared, please upload/attach a link to it.](https://storage.googleapis.com/oathsworn-apk-release/Oathsworn-ItD-v1-2.ap)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment] 2022-08-21 17:11
I don't have access to download that file :/

However, I am 80% sure its a duplicate of this item: https://github.com/iBotPeaches/Apktool/issues/2865

**Closed by iBotPeaches** 2022-08-21 17:11 UTC
