### ISSUE TITLE
Fail to decode manifest and resources

### ISSUE THREAD

**Issue by lucacapacci** [iBotPeaches/Apktool#1694] opened 2017-12-15 18:00 UTC
### Information
Latest ApkTool jar on debian, app available in play store: https://play.google.com/store/apps/details?id=net.pluservice.myCicero

### Stacktrace

First test:
```
java -jar "./apktool.jar" d "net.pluservice.myCicero.apk" -o "./output/"
I: Using Apktool 2.3.0 on net.pluservice.myCicero.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f070000 string/abc_action_bar_home_description, config=-sr
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:281)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:231)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:575)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:214)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
```

Second test:
```
java -jar -Xmx1024M "./apktool.jar" d -r -f "net.pluservice.myCicero.apk" -o "./output/"
I: Using Apktool 2.3.0 on net.pluservice.myCicero.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

This second test ends fine, but the AndroidManifest.xml is still in a binary format.

**Comment by iBotPeaches** [comment] 2017-12-18 12:55
Duplicate of #1684 

Another form of obfuscation/minification here. All resources have been moved out of `/res` into the root directory.

**Closed by iBotPeaches** 2017-12-18 12:55 UTC
