### ISSUE TITLE
No resource identifier found / AndrolibException

### ISSUE THREAD

**Issue by GekkeVent** [iBotPeaches/Apktool#1763] opened 2018-04-04 21:14 UTC
### Information
1. Version 2.3.1
2. Windows
3. Playstore

### Stacktrace/Logcat
```W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\color\q5.xml:4: error: No resource identifier found for attribute 'al
pha' in package 'com.zhiliaoapp.musically'
W:
W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\color\q6.xml:4: error: No resource identifier found for attribute 'al
pha' in package 'com.zhiliaoapp.musically'
W:
W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\color\q7.xml:4: error: No resource identifier found for attribute 'al
pha' in package 'com.zhiliaoapp.musically'
W:
W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\color\q7.xml:5: error: No resource identifier found for attribute 'al
pha' in package 'com.zhiliaoapp.musically'
W:
W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\color\q7.xml:6: error: No resource identifier found for attribute 'al
pha' in package 'com.zhiliaoapp.musically'
W:
W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\color\qi.xml:4: error: No resource identifier found for attribute 'al
pha' in package 'com.zhiliaoapp.musically'
W:
W: C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.mus
ically\res\menu\a.xml:4: error: No resource identifier found for attribute 'show
AsAction' in package 'com.zhiliaoapp.musically'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = 1): [C:\User
s\Home\AppData\Local\Temp\brut_util_Jar_7885346250567083458.tmp, p, --forced-pac
kage-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 2
018031901, --version-name, 6.9.0, --no-version-vectors, -F, C:\Users\Home\AppDat
a\Local\Temp\APKTOOL5255742470555709042.tmp, -0, assets/face_detect_2.0.0.model,
 -0, assets/face_track_3.3.0.model, -0, sh, -0, txt, -0, webp, -0, arsc, -I, C:\
Users\Home\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Home\Desktop\Andr
oid RE\APKs\Musically\musical.ly_com.zhiliaoapp.musically\res, -M, C:\Users\Home
\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.musically\AndroidMa
nifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
        at brut.androlib.Androlib.buildResources(Androlib.java:426)
        at brut.androlib.Androlib.build(Androlib.java:305)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\Home\AppData\Local\Temp\brut_util_Jar_788534625
0567083458.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk
-version, 23, --version-code, 2018031901, --version-name, 6.9.0, --no-version-ve
ctors, -F, C:\Users\Home\AppData\Local\Temp\APKTOOL5255742470555709042.tmp, -0,
assets/face_detect_2.0.0.model, -0, assets/face_track_3.3.0.model, -0, sh, -0, t
xt, -0, webp, -0, arsc, -I, C:\Users\Home\AppData\Local\apktool\framework\1.apk,
 -S, C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.m
usically\res, -M, C:\Users\Home\Desktop\Android RE\APKs\Musically\musical.ly_com
.zhiliaoapp.musically\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:456)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
Home\AppData\Local\Temp\brut_util_Jar_7885346250567083458.tmp, p, --forced-packa
ge-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 201
8031901, --version-name, 6.9.0, --no-version-vectors, -F, C:\Users\Home\AppData\
Local\Temp\APKTOOL5255742470555709042.tmp, -0, assets/face_detect_2.0.0.model, -
0, assets/face_track_3.3.0.model, -0, sh, -0, txt, -0, webp, -0, arsc, -I, C:\Us
ers\Home\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Home\Desktop\Androi
d RE\APKs\Musically\musical.ly_com.zhiliaoapp.musically\res, -M, C:\Users\Home\D
esktop\Android RE\APKs\Musically\musical.ly_com.zhiliaoapp.musically\AndroidMani
fest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:450)
        ... 6 more
```
### Steps to Reproduce
1. `apktool d app.apk`
2. 'apktool b app'

### APK
http://anonfile.com/M179a9eab4/musically.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
- Yes
2. If you are trying to install a modified apk, did you resign it?
- N/A
3. Are you using the latest apktool version?
- Yes

### Additional info:
Normally I would solve this by copying the raw resources with the -r parameter, but since I need to edit the AndroidManifest.xml file and add the debugging attribute I can't. Maybe you could add an option where only the AndroidManifest.xml is decoded and the rest of the resources are copied raw, or re-add the -d parameter to automatically set the debuggable attribute.

**Comment by iBotPeaches** [comment] 2018-04-06 15:58
Looks to be AndroResGuard, the newer version which we are still trying to patch. Duplicate of #1663

**Closed by iBotPeaches** 2018-04-06 15:58 UTC
