### ISSUE TITLE
Decompile Error

### ISSUE THREAD

**Issue by aclocsin** [iBotPeaches/Apktool#2507] opened 2021-01-29 16:04 UTC
### Information
1. **Apktool Version (`2.50`)** -
2. **Operating System (Windows)** -
3. **APK From? (APKPure)** -

### Stacktrace/Logcat
I: Using Apktool 2.5.0 on Lucid Adventure_v2.4.17_apkpure.com.apk
I: Copying raw resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: res
	at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:123)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: res
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:70)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:203)
	at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:121)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: color/abc_background_cache_hint_selector_material_dark.xml
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
	... 6 more
Caused by: java.io.FileNotFoundException: D:\1STUDY\DECOMPILED\Lucid Adventure_v2.4.17_apkpure.com\res\color\abc_background_cache_hint_selector_material_dark.xml (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
	... 9 more
Decompile successful.

Please read the FAQ and troubleshooting
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-57-12-june-2020.3333960/#post-65775601

Decompile failed. Please read the log

```

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? No
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

- Hello all. I was trying to learn if the rates that the developer says is real (they seem to be very shady and the maths do not add up). I plan to use real money so I wanted to make sure if the rates are real and if the money to be spent will not be of waste. Thank you.

**Comment by pashamcr** [comment] 2021-01-30 10:42
@aclocsin not supported filename: `assets/  `
- open apk in 7z, 
- rename: `assets/  `, for example, in: `assets/rename`
- decompile apk
- compiling apk - in reverse order

**Comment by aclocsin** [comment] 2021-01-30 10:56
> @aclocsin not supported filename: `assets/ �`
> 
> * open apk in 7z,
> * rename: `assets/  �`, for example, in: `assets/rename`
> * decompile apk
> * compiling apk - in reverse order

I tried doing this but ended up with the same error.

**Comment by pashamcr** [comment] 2021-01-30 11:48
@aclocsin

![Snap1](https://user-images.githubusercontent.com/36408873/106355437-bea32200-62ef-11eb-8536-06e7a8fef5ac.png)
```
D:\test>java -jar apktool_2.5.0.jar d "Lucid Adventure_v2.4.17_apkpure.com.apk"
I: Using Apktool 2.5.0 on Lucid Adventure_v2.4.17_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\pasha\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling assets/audience_network.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

**Comment by iBotPeaches** [comment] 2021-01-30 11:52
The workaround posted above will work as this will require remapping unprintable characters and quite a difficulty so merging into duplicate ticket and closing - https://github.com/iBotPeaches/Apktool/issues/1460

**Closed by iBotPeaches** 2021-01-30 11:52 UTC

**Comment by aclocsin** [comment] 2021-02-04 03:44
@pashamcr I would be grateful if you could send me the decompiled file as doing so still has not worked for me. Thank you very much.

**Comment by AndnixSH** [comment] 2021-02-11 18:05
You can delete that blank filename and it will work too

**Comment by aclocsin** [comment] 2021-02-12 02:10
@AndnixSH Sadly, still the same thing happens.

**Comment by AndnixSH** [comment] 2021-02-12 11:05
@aclocsin can you show me your another log output again?

**Comment by aclocsin** [comment] 2021-02-12 12:05
@AndnixSH Reading APK...
Done

Decompiling APK file... (Press ESC to cancel)

/c "java -Xmx2048m -jar "C:\Program Files (x86)\APK Easy Tool\Apktool\apktool_2.5.0.jar" d -f -r -s --only-main-classes -o "D:\1STUDY\DECOMPILED\Lucid Adventure_v2.4.17_apkpure.com" "D:\1STUDY\PRACTICE\NEW\Lucid Adventure_v2.4.17_apkpure.com.apk""

I: Using Apktool 2.5.0 on Lucid Adventure_v2.4.17_apkpure.com.apk
I: Copying raw resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: res
	at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:123)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: res
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:70)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:203)
	at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:121)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: color/abc_background_cache_hint_selector_material_dark.xml
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
	... 6 more
Caused by: java.io.FileNotFoundException: D:\1STUDY\DECOMPILED\Lucid Adventure_v2.4.17_apkpure.com\res\color\abc_background_cache_hint_selector_material_dark.xml (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
	... 9 more
Decompile successful.

Please read the FAQ and troubleshooting
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-57-12-june-2020.3333960/#post-65775601

Decompile failed. Please read the log

**Comment by AndnixSH** [comment] 2021-02-12 12:52
@aclocsin yeah same error, i think something wrong with your zip program. Try this file which have unnamed file deleted https://anonfiles.com/5dR3P9H8pd/lucid-adventure_2.4.17_apk

I use same tool, it works fine for me after deletion

```
/c "java -Xmx2048m -jar "E:\APK Easy Tool\Apktool\apktool_2.5.0.jar" d -f -o "E:\APK Easy Tool\1-Decompiled APKs\lucid-adventure_2.4.17" "E:\Downloads\lucid-adventure_2.4.17.apk""

I: Using Apktool 2.5.0 on lucid-adventure_2.4.17.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\andnix\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling assets/audience_network.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Decompile successful.

```

Also this game is strongly protected by Appguard, you should not waste time with it

**Comment by aclocsin** [comment] 2021-02-12 13:38
@AndnixSH same thing still happens, maybe there's something wrong with my program? Anyways, if it's okay with you, can you send the decompiled file? Thanks a lot for everything!

**Comment by AndnixSH** [comment] 2021-02-12 14:23
@aclocsin no sorry. Try to reset the tool or use apktool.jar in CMD instead

**Comment by vanlinh00** [comment] 2021-05-01 03:27
Checking for update...
Reading APK...

Decompiling APK file... (Press ESC to cancel)

Executing command: java.exe -jar "C:\down\Tutorial\APKEasyTool\Apktool\apktool_2.5.0.jar" d -f -r -s --only-main-classes -o "C:\Users\canha\Documents\APK Easy Tool\1-Decompiled APKs\FILE_20210429_141224_base" "C:\down\Tutorial\APKEasyTool\Moddables\FILE_20210429_141224_base.apk"

I: Using Apktool 2.5.0 on FILE_20210429_141224_base.apk
I: Copying raw resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: res
	at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:123)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: res
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:70)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:203)
	at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:121)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: drawable-hdpi-v4/share_button.png
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
	... 6 more
Caused by: java.io.FileNotFoundException: C:\Users\canha\Documents\APK Easy Tool\1-Decompiled APKs\FILE_20210429_141224_base\res\drawable-hdpi-v4\share_button.png (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
	... 9 more
Decompile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601

**Comment by vanlinh00** [comment] 2021-05-01 03:30
Hi everyone I am having a similar error. please help me
