### ISSUE TITLE
unsupported res type name for bags. Found: style2 on facebook

### ISSUE THREAD

**Issue by RobertRBT** [iBotPeaches/Apktool#2193] opened 2019-10-08 11:16 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - apkmirror

### Stacktrace/Logcat

```
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
	at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:115)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:748)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)

```

### Steps to Reproduce
1. `apktool  d com.facebook.katana_242.0.0.36.119.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Yes

**Comment by Ristovski** [comment] 2019-10-31 18:30
Can confirm same issue with Facebook Messenger

**Comment by Doreapp** [comment] 2020-02-27 10:14
I don't know if I come to late but I had the same issue... I just wanted the sources files and the issue was coming for a "style2" file so not a source file. Therefore, I used -r options to avoid decompiling res files, it works.

**Comment by DevCentre** [comment] 2020-03-30 20:59
@Doreapp  Not ideal, but yeah... While we wait for some fix, it's an alternative.

**Comment by iBotPeaches** [comment] 2020-04-11 11:09
Appears this is a duplicate of #1719 , all related to this new packing/obfuscation going on with additional style types that just map to a known type.

ie - I assume style2 is just style type. You may subscribe to updates on the #1719 ticket.

**Closed by iBotPeaches** 2020-04-11 11:09 UTC
