### ISSUE TITLE
Can't decompile Settings apk from CM14.1

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#1359] opened 2016-11-04 00:34 UTC
### Information
1. **Apktool Version (`apktool -version`)** -2.2.1
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -CM14.1 for Galaxy S4

### Stacktrace/Logcat
```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x3f060081
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x3f060081
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x3f060081
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresFeature, value=0x00000021
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresFeature, value=0x00000023
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresFeature, value=0x00000027
W: Could not decode attr value, using undecoded value instead: ns=cm, name=replacesKey, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresConfig, value=0x3f050001
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresFeature, value=0x00000038
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresConfig, value=0x01120046
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresConfig, value=0x01120044
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresPackage, value=0x00000019
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresOwner, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=cm, name=requiresFeature, value=0x00000025
Can't find framework resources for package of id: 63. You must install proper framework files, see project website for more info
```

### Steps to Reproduce
1. `apktool `d

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment] 2016-11-17 13:18
This stacktrace is asking for an additional framework, have you confirmed you installed all frameworks required?

```
Can't find framework resources for package of id: 63. You must install proper framework files, see project website for more info
```

CM14.1 must have an additional framework. Since this ticket doesn't have an application to investigate, I might have to find a supported device I own that has CM14 and investigate further.

**Comment by Woodzrul** [comment] 2016-11-24 09:58
@iBotPeaches Just come across the above. I also receive the same error when trying to decompile Settings.apk from CM13 & CM14.1. I have obtained the correct framework-res.apk from the ROM, but still receiving an error.

Did you ever manage to resolve? Any help is greatly appreciated.

Thanks

**Comment by Woodzrul** [comment] 2016-11-24 15:32
[Framework-Settings.zip](https://github.com/iBotPeaches/Apktool/files/611688/Framework-Settings.zip)

**Comment by Woodzrul** [comment] 2016-11-24 15:33
The above post contains framework-res.apk & settings.apk from CM13. Hope this helps with trouble shooting.

**Comment by Woodzrul** [comment] 2016-11-24 16:32
Figured this out. Found another framework file that needed to be applied.
org.cyanogenmod.platform-res.apk

**Comment by iBotPeaches** [comment] 2016-12-02 19:42
Sorry for the delay in this. Lost track of things. So it seems the issue was a framework apk hiding under the name of "org.cyanogenmod.platform-res.apk" which had the id of 63.

Closing this.

**Closed by iBotPeaches** 2016-12-02 19:42 UTC
Labels: Not a Bug
