### ISSUE TITLE
'No resource identifier found for attribute' error when decode and build

### ISSUE THREAD

**Issue by Dr-Noob** [iBotPeaches/Apktool#1697] opened 2017-12-21 21:45 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: ~/Downloads/apktool/alwaysonamoled/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5486326853008819126.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 26, --version-code, 1292, --version-name, v1.0.3, --no-version-vectors, -F, /tmp/APKTOOL7276647885712145089.tmp, -0, arsc, -0, arsc, -I, ~/.local/share/apktool/framework/1.apk, -S, ~/Downloads/apktool/alwaysonamoled/res, -M, ~/Downloads/apktool/alwaysonamoled/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5486326853008819126.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 26, --version-code, 1292, --version-name, v1.0.3, --no-version-vectors, -F, /tmp/APKTOOL7276647885712145089.tmp, -0, arsc, -0, arsc, -I, ~/.local/share/apktool/framework/1.apk, -S, ~/Downloads/apktool/alwaysonamoled/res, -M, ~/Downloads/apktool/alwaysonamoled/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5486326853008819126.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 26, --version-code, 1292, --version-name, v1.0.3, --no-version-vectors, -F, /tmp/APKTOOL7276647885712145089.tmp, -0, arsc, -0, arsc, -I, ~/.local/share/apktool/framework/1.apk, -S, ~/Downloads/apktool/alwaysonamoled/res, -M, ~/Downloads/apktool/alwaysonamoled/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
```

### Steps to Reproduce
1. `java -jar apktool_2.3.0.jar d alwaysonamoled.apk`
2. `java -jar apktool_2.3.0.jar b alwaysonamoled hacked.apk`

### APK
https://play.google.com/store/apps/details?id=com.tomer.alwayson&hl=es

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? That's exactly what I did
2. If you are trying to install a modified apk, did you resign it? -
3. Are you using the latest apktool version? Yes

### Just one thing
I saw https://github.com/iBotPeaches/Apktool/issues/1386, but I think this is different. I tried `apktool d --no-res` but i does not work either:

```
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
[Fatal Error] :1:1: Content is not allowed in prolog.
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
```

**Comment by iBotPeaches** [comment] 2017-12-21 21:48
Duplicate of #1625 & #1579

```
apktool empty-framework-dir
```

**Closed by iBotPeaches** 2017-12-21 21:48 UTC
