### ISSUE TITLE
[BUG] Failed when compiling with apktool

### ISSUE THREAD

**Issue by Nellve28** [iBotPeaches/Apktool#2498] opened 2021-01-21 05:21 UTC
When I'm trying to compiling an apk with apktool version 2.5, I got error as follows:

I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/google/android/gms/internal/drive/zznr;->values()[Lcom/google/android/gms/internal/drive/zznr;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1046)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:345)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:366)
	at brut.androlib.Androlib.build(Androlib.java:304)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:259)
	at brut.apktool.Main.main(Main.java:85)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1319)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1042)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1279)
	... 11 more

**Comment by iBotPeaches** [comment] 2021-01-21 11:50
Duplicate of https://github.com/iBotPeaches/Apktool/issues/2496#issuecomment-762803912

---

You hit method limit of dex which is unsigned short.

**Closed by iBotPeaches** 2021-01-21 11:50 UTC

**Comment by hash30** [comment] 2021-02-13 19:24
@Nellve28 You solved this error? If yes, please share the solution. I'm using msfvenom with apktool, and facing the same error. I lost my whole day searching for solution, but no luck :( 

You can see my issue [here](https://github.com/iBotPeaches/Apktool/issues/2508#issuecomment-778578091)!
