### ISSUE TITLE
Apktool improperly decodes custom namespaces

### ISSUE THREAD

**Issue by hieunp8x** [iBotPeaches/Apktool#1019] opened 2015-08-13 03:30 UTC
Hi

I'm Hieu. I use apktool_2.0.1 on Windows 8.1 (64 bit) for decode and rebuild F-Secure FSafe, JDK 8 update 25 (64 bit)
Original F-Secure FSafe apk file locate at: https://drive.google.com/open?id=0BzD1w7jyro1_WGxkT1QxYS1NRWc 
I did bellow step for decode and rebuild
+ Step1: Decode is ok
+ Step2: Rebuild APK from decode output dir with command
 > apktool.bat b F:\fsecure_fsafe -o F:\fsecure_fsafe_rebuild.apk
 Result is ERROR, output log when rebuild as bellow
```
================== Begin Result apktool 2.0.1 rebuild F-Secure Fsafe ===============
I: Using Apktool 2.0.1
I: Copying F:\fsecure_fsafe classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
F:\fsecure_fsafe\res\layout\antivirus_settings.xml:10: error: No resource identifier found for attribute 'settingItemTitle' in package 'android'

F:\fsecure_fsafe\res\layout\antivirus_settings.xml:10: error: No resource identifier found for attribute 'settingItemCheckable' in package 'android'
....
F:\fsecure_fsafe\res\layout\view_updates.xml:23: error: No resource identifier found for attribute 'settingItemCheckable' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\usr-dev\AppData\Local\Temp\brut_util_Jar_1544731412893133921.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --rename-manifest-package, com.fsecure.ms.fsafe, --version-code, 151017310, --version-name, 15.1.017310, -F, C:\Users\usr-dev\AppData\Local\Temp\APKTOOL4808454233878113389.tmp, -0, arsc, -I, C:\Users\usr-dev\apktool\framework\1.apk, -S, F:\fsecure_fsafe\res, -M, F:\fsecure_fsafe\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	at brut.androlib.Androlib.buildResources(Androlib.java:397)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\usr-dev\AppData\Local\Temp\brut_util_Jar_1544731412893133921.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --rename-manifest-package, com.fsecure.ms.fsafe, --version-code, 151017310, --version-name, 15.1.017310, -F, C:\Users\usr-dev\AppData\Local\Temp\APKTOOL4808454233878113389.tmp, -0, arsc, -I, C:\Users\usr-dev\apktool\framework\1.apk, -S, F:\fsecure_fsafe\res, -M, F:\fsecure_fsafe\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\usr-dev\AppData\Local\Temp\brut_util_Jar_1544731412893133921.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --rename-manifest-package, com.fsecure.ms.fsafe, --version-code, 151017310, --version-name, 15.1.017310, -F, C:\Users\usr-dev\AppData\Local\Temp\APKTOOL4808454233878113389.tmp, -0, arsc, -I, C:\Users\usr-dev\apktool\framework\1.apk, -S, F:\fsecure_fsafe\res, -M, F:\fsecure_fsafe\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 6 more\
```
================== End Result apktool 2.0.1 rebuild F-Secure Fsafe ===============

Please tell me why and solution for fix it!

Many Thanks!

**Comment by iBotPeaches** [comment] 2015-08-14 12:50
Bugs like this are becoming quite common. Resources that aren't found in AOSP resources. So lets walk through this. We are missing the following attributes.

```
settingItemCheckable
settingItemDescription
settingItemTitle
menuItemTitle
menuItemInMiddleSection
```

They all say that are from package "android". Now is this correct or a fault in apktool? Lets go check via `aapt`, because the apktool decoded files are pointing at an android attribute `android:settingItemTitle`.

So we find the entry via `aapt d xmltree apk res/layout/antivirus_settings.xml`

```
            E: com.fsecure.ms.ui.FsmsSettingItem (line=23)
              A: :(0x010100d0)=@0x7f0f003b
              A: :(0x7f010020)=@0x7f0902c3
              A: :(0x7f010022)=(type 0x10)0x2
```

We don't have a name of the attribute, just the ID for the first entry. So we cross reference that ID and get the name `id`.

We take another look at the Apktool decoded line for this.

```
                <com.fsecure.ms.ui.FsmsSettingItem android:id="@id/antiVirusEnabled" android:settingItemTitle="@string/ANTIVIRUS_ENABLED" android:settingItemCheckable="right" style="@style/list_item_layout_clickable_nopadding" />
```

As shown above `android:settingItemTitle` and `android:settingItemCheckable` are actually local attributes (shown by the packageId of `0x7f`).

Sure enough we peek into `res/values/attrs.xml` and find them.

```
    <attr name="settingItemTitle" format="string" />
    <attr name="settingItemDescription" format="string" />
    <attr name="settingItemCheckable">
        <enum name="none" value="0" />
        <enum name="left" value="1" />
        <enum name="right" value="2" />
    </attr>
    <attr name="menuItemTitle" format="string" localization="suggested" />
    <attr name="menuItemInMiddleSection" format="boolean" />
```

So why isn't apktool using the custom namespace instead of `android`? Well first we need the namespace defined at top of file. So lets take a look at what apktool decoded.

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout android:tag="layout/antivirus_scanning.xml" style="@style/view_root_layout"
  xmlns:android="http://schemas.android.com/apk/res/android">
```

Now lets take a look at `aapt`.

```
N: android=http://schemas.android.com/apk/res/android
  N: fsms=http://schemas.android.com/apk/res/com.fsecure.ms.fsecure_pc
    E: RelativeLayout (line=2)
```

There we go. We did not correctly decode the namespace `fsms`, which would then adapt the wrongly noted attributes to `fsms:settingItemTitle`. Then working.


So the problem is apktool is ignoring/breaking/improperly decoding custom namespaces.

**Comment by iBotPeaches** [comment] 2015-08-14 13:51
Made a custom apk to test this easier - https://github.com/iBotPeaches/TestApks/commit/98c158b72d43df0f29528dd808b29023e8041152

Yet this works 100% fine. You can see original file here: https://github.com/iBotPeaches/TestApks/blob/98c158b72d43df0f29528dd808b29023e8041152/Issue1019/app/src/main/res/layout/bar.xml

Then I decoded it and got this - 

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout android:orientation="vertical" android:layout_width="fill_parent" android:layout_height="fill_parent"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:customAttr="http://schemas.android.com/apk/res-auto">
    <com.ibotpeaches.issue1019.MyCustomElement android:layout_width="fill_parent" android:layout_height="fill_parent" customAttr:foo="120.0dip" />
</LinearLayout>
```

So this is isolated to specific apks, again making this difficult to figure out why this happens.

**Comment by lennykano** [comment] 2015-08-15 00:08
On notable difference is you used res-auto. Not sure if that is the problem but worth changing that to a package name like the problematic one.

**Comment by hieunp8x** [comment] 2015-08-15 04:42
I've try manual edit on error layout file: *res/layout/antivirus_settings.xml*
replace error attribute as bellow
> "android: settingItemTitle"  ==> "settingItemTitle"
> "android: settingItemCheckable" ==> "settingItemCheckable"
> ...
**android:local_attribute** ==> **local_attribute**

then using **aapt v.22.0.1** tool generate resource: **Result is ok** 
(so my solution in this case maybe ok)

**Comment by MysteryIII** [comment] 2015-08-16 12:16
I was looking for a way to fix my problem with recompiling my (untouched) systemui.apk and found this thread. I think I have the same problem:

http://www.multiup.org/download/557831b1344163f348395014cb969d3d/SystemUI_Framework.rar
Error-Log:
<addr>E:\Apps\decompile>apktool d systemui.apk
I: Using Apktool 2.0.1 on systemui.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Robert\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

E:\Apps\decompile>apktool b systemui -o systemui1.apk
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
E:\Apps\decompile\systemui\res\layout\system_bar_notification_panel_title.xml:14: error: Error: No r
esource found that matches the given name (at 'style' with value '@style/SystemBarNotificationText')
.

E:\Apps\decompile\systemui\res\layout\system_bar_notification_panel_title.xml:19: error: Error: No r
esource found that matches the given name (at 'style' with value '@style/SystemBarNotificationText')
.

E:\Apps\decompile\systemui\res\layout\system_bar_notification_panel_title.xml:21: error: Error: No r
esource found that matches the given name (at 'style' with value '@style/SystemBarNotificationText')
.

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:5: error: Error: No resource foun
d that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:6: error: Error: No resource foun
d that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:7: error: Error: No resource foun
d that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:10: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator')
.

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:11: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:12: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:13: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:15: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator')
.

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:16: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:17: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:18: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:21: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator')
.

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:22: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:23: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:26: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator')
.

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:27: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:28: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:29: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:32: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator')
.

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:33: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:34: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:35: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').

E:\Apps\decompile\systemui\res\layout\system_bar_settings_view.xml:37: error: Error: No resource fou
nd that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator')
.

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.co
mmon.BrutException: could not exec command: [C:\Users\Robert\AppData\Local\Temp\brut_util_Jar_418311
5934171689039.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 18, --v
ersion-code, 18, --version-name, 4.3-I9300UBUGNG1, -F, C:\Users\Robert\AppData\Local\Temp\APKTOOL804
0671361890997211.tmp, -0, arsc, -I, C:\Users\Robert\apktool\framework\1.apk, -S, E:\Apps\decompile\s
ystemui\res, -M, E:\Apps\decompile\systemui\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\U
sers\Robert\AppData\Local\Temp\brut_util_Jar_4183115934171689039.tmp, p, --forced-package-id, 127, -
-min-sdk-version, 18, --target-sdk-version, 18, --version-code, 18, --version-name, 4.3-I9300UBUGNG1
, -F, C:\Users\Robert\AppData\Local\Temp\APKTOOL8040671361890997211.tmp, -0, arsc, -I, C:\Users\Robe
rt\apktool\framework\1.apk, -S, E:\Apps\decompile\systemui\res, -M, E:\Apps\decompile\systemui\Andro
idManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Robert\AppData\Local\Temp\br
ut_util_Jar_4183115934171689039.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sd
k-version, 18, --version-code, 18, --version-name, 4.3-I9300UBUGNG1, -F, C:\Users\Robert\AppData\Loc
al\Temp\APKTOOL8040671361890997211.tmp, -0, arsc, -I, C:\Users\Robert\apktool\framework\1.apk, -S, E
:\Apps\decompile\systemui\res, -M, E:\Apps\decompile\systemui\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
        ... 6 more</addr>

**Comment by iBotPeaches** [comment] 2015-08-19 14:38
@lennykano I had hoped that would of been the reason, but still didn't change my test apk which upsets me. Means this is some isolated problem, I will have to dig into this more to figure out why the original bug report application experiences this vs my test apks.

**Comment by iBotPeaches** [comment] 2016-02-04 01:34
Closing in favour of #1157

**Closed by iBotPeaches** 2016-02-04 01:34 UTC
Labels: Accepted, bug
