### ISSUE TITLE
Unable to decompile SystemUI.apk from OEM Honor 8 ROM

### ISSUE THREAD

**Issue by Gondost** [iBotPeaches/Apktool#1445] opened 2017-03-02 03:42 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64, Lubuntu x64
3. **APK From? (Playstore, ROM, Other)** - Pulled from stock OEM ROM

### Stacktrace/Logcat
[Log.txt](https://github.com/iBotPeaches/Apktool/files/812715/Log.txt)

### Steps to Reproduce
1. `apktool if framework-res.apk`
2. `apktool if framework-res-hwext.apk`
3. `apktool d SystemUI.apk`

### Frameworks & APK
[Frameworks & APK](https://drive.google.com/open?id=0B0zE1Kk8sIB6TlZVRWdLRlR4Q2c)

### Additional information
Happened first under Lubuntu x64 16.10, then happened also on Windows 10 x64. I can decompile other APKs on each system, just not this SystemUI.apk.
Update: It looks as if I can't decompile any of the Huawei APKs, they all fail with the same error.

**Comment by iBotPeaches** [comment] 2017-03-09 12:22
Yeah there are some styles (opta## and optb###), we still don't have support for them. Sorry about that.

Until Huawei stops pulling moves that Xiaomi did 3 years ago, it won't be supported. Duplicate of #966

**Closed by iBotPeaches** 2017-03-09 12:22 UTC
Labels: Duplicate
