### ISSUE TITLE
attr value decompile error 

### ISSUE THREAD

**Issue by ALIRAQI** [iBotPeaches/Apktool#1103] opened 2015-12-13 23:13 UTC
Hi 

im trying to decompile cm13 6.0.1 systemui but i get this error

```
W: Could not decode attr value, using undecoded value instead: ns=android, name=background, value=0x01080753
W: Could not decode attr value, using undecoded value instead: ns=android, name=background, value=0x01080753
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01080753
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:46)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:47)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:105)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```
i used latest apktool

framework and Systemui
https://drive.google.com/file/d/0B0ODjuZvMeEvUWhWRTRLbG5IT3c/view?usp=sharing

**Comment by iBotPeaches** [comment] 2015-12-14 17:55
None of those resources are in the framework or apk itself. So apktool is doing exactly as intended.

**Comment by iBotPeaches** [comment] 2015-12-17 16:50
Closing as duplicate as #745

**Closed by iBotPeaches** 2015-12-17 16:50 UTC
Labels: duplicate
