### ISSUE TITLE
Loading resource table from file not working on Raspbian

### ISSUE THREAD

**Issue by necrodraco** [iBotPeaches/Apktool#1609] opened 2017-09-08 20:55 UTC
### Information
1. **Apktool Version (`apktool -version`)** -Apktool 2.2.5-e8a8b3-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** -Raspbian

Hi to the team of this awesome project. 
I love this tool really much. But now I got an bug which stops  the continuating of my own private project: 

Normally I use the apktool to de- and recompile apks on my ubuntu machines. 
But in my actual project I try to use the apktool on my raspberry pi with the raspbian OS, but it stops every time after the logging message "Loading resource table from file". 

here are the stacktrace until stopping: 
pi@raspberrypi:~/test$ java -jar apktool-cli-all.jar d ygopro_simple.apk 
I: Using Apktool 2.2.5-e8a8b3-SNAPSHOT on ygopro_simple.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/pi/.local/share/apktool/framework/1.apk
[..]Doesn't continue. Runs into a endless loop until I stop (CTRL+C)[...]

I have tested many solutions: 
-Used Version 2.2.2 and 2.2.5-Snapshot. Both don't work. Only on my PCs
-changed 1.apk with the 1.apk generated on my Tower PCs. Don't work too. 
-adding Logging-code to loadFrameworkPkg()-Method in AndroidlibResources.java. I encounter that the bug stays in getResPackagesFromApk(), because it doesn't log after running. 

I hope You can help and you understand my bug/problem. It's the first time that I post an bug and my english skills aren't really high.

**Comment by iBotPeaches** [comment] 2017-09-09 11:01
Could you upload the apk? Sounds like possibly an infinite loop in resource parsing

**Comment by necrodraco** [comment] 2017-09-09 21:00
Did you mean the 1.apk framework or the apk that I want to de- / recompile? 
I have adding both in one .tar.gz archive. 

[AppAndFramework_Raspbian.tar.gz](https://github.com/iBotPeaches/Apktool/files/1290094/AppAndFramework_Raspbian.tar.gz)

On the way: 
the problem occure every time on decompiling or recompiling. Also I tried to replace the 1.apk with the 1.apk from my Tower PC without changing the problem. 

The App itself was previously de- and recompiled with your tool from my Tower PC

**Comment by iBotPeaches** [comment] 2017-09-19 21:12
```
➜  Bug1609 apktool d ygopro_simple.apk -t 1609
I: Using Apktool 2.2.5-0a1670-SNAPSHOT on ygopro_simple.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1-1609.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1609 apktool b ygopro_simple
I: Using Apktool 2.2.5-0a1670-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1609 
```

Unfortunately couldn't duplicate this. It seems based on the fact that you have no issues on your tower PC that this is an environment problem. I don't have any means to test apktool on a raspberrypi so going to assume this is not a bug in apktool. Feel free to pull down the source and investigate on the pi directly. Building apktool directly on it may prove to expose any potential problems.

Closing for now.

**Closed by iBotPeaches** 2017-09-19 21:12 UTC
Labels: Waiting for issuer
