### ISSUE TITLE
Bug in Decompiling and Recompiling (no changes)

### ISSUE THREAD

**Issue by simoconfa** [iBotPeaches/Apktool#1158] opened 2016-02-02 15:42 UTC
Hi,
I have tried to decompile an apk and to recompile it without doing changes.
I have installed JDK v8u71 and v8u72. I have deleted the %user_name\apktool\framework before doing the process. Using the latest apktool(release).
Here there is the error occured in the messagge:
```
C:\Users\Daniele\Desktop\Android\apktool_v_2>**apktool d LuckyPatcher.apk**
I: Using Apktool 2.0.3 on LuckyPatcher.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Daniele\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\Daniele\Desktop\Android\apktool_v_2>**apktool b LuckyPatcher**
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
ERROR: input directory 'arsc' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Daniele\AppData\Local\Temp\brut_util_Jar_1249068088108616753.tmp, p, --forced-packa
ge-id, 127, --min-sdk-version, 5, --target-sdk-version, 19, --version-code, 1351, --version-name, 5.9.8, -F, C:\Users\Daniele\AppData\Local\Temp\APKTOOL4146409552306678808.tmp, -0, arsc, -0, txt, -0, bin, -0, pk8, -0, , -0, arsc, -I, C:\
Users\Daniele\apktool\framework\1.apk, -S, C:\Users\Daniele\Desktop\Android\apktool_v_2\LuckyPatcher\res, -M, C:\Users\Daniele\Desktop\Android\apktool_v_2\LuckyPatcher\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Daniele\AppData\Local\Temp\brut_util_Jar_1249068088108616753.tmp, p, --forced-package-id, 127, --min-sdk-version, 5, --target-sdk-ve
rsion, 19, --version-code, 1351, --version-name, 5.9.8, -F, C:\Users\Daniele\AppData\Local\Temp\APKTOOL4146409552306678808.tmp, -0, arsc, -0, txt, -0, bin, -0, pk8, -0, , -0, arsc, -I, C:\Users\Daniele\apktool\framework\1.apk, -S, C:\Use
rs\Daniele\Desktop\Android\apktool_v_2\LuckyPatcher\res, -M, C:\Users\Daniele\Desktop\Android\apktool_v_2\LuckyPatcher\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Daniele\AppData\Local\Temp\brut_util_Jar_1249068088108616753.tmp, p, --forced-package-id, 127, --min-sdk-version, 5, --target-sdk-version, 19, --version-code, 1351,
--version-name, 5.9.8, -F, C:\Users\Daniele\AppData\Local\Temp\APKTOOL4146409552306678808.tmp, -0, arsc, -0, txt, -0, bin, -0, pk8, -0, , -0, arsc, -I, C:\Users\Daniele\apktool\framework\1.apk, -S, C:\Users\Daniele\Desktop\Android\apktoo
l_v_2\LuckyPatcher\res, -M, C:\Users\Daniele\Desktop\Android\apktool_v_2\LuckyPatcher\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more

C:\Users\Daniele\Desktop\Android\apktool_v_2>
```

Since I cannot post the zip containing apk I have uploaded on mediafire:[http://www.mediafire.com/download/1o0i0xa9gank3w9/LuckyPatcher.apk]

**Comment by iBotPeaches** [comment] 2016-02-02 15:51
Duplicate of #1122 

Workaround in there.

**Closed by iBotPeaches** 2016-02-02 15:51 UTC
