### ISSUE TITLE
Oreo: 9patch, no marked region found along edge

### ISSUE THREAD

**Issue by KrisYarno** [iBotPeaches/Apktool#1608] opened 2017-09-04 20:51 UTC
[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/1275778/SystemUI.zip)
I've decompiled the systemui.apk on Android Oreo from the 6p. I've edited a few XML's. Upon building I get this error. If I decompile the apk and build it as is I still get the error

### Information
1. **Apktool Version (2.2.4)** -
2. **Operating System (Windows)** -
3. **APK From? (Stock Oreo system.img)** -

### Stacktrace/Logcat

```
W: ERROR: 9-patch image C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\res\drawable-xxxhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\res\drawable-xxxhdpi\pip_dismiss_scrim.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KRISY~1.DES\AppData\Local\Temp\brut_util_Jar_3948520725014907572.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\KRISY~1.DES\AppData\Local\Temp\APKTOOL2731525356834830561.tmp, -0, arsc, -0, arsc, -I, C:\Users\krisy.DESKTOP-3EFRBLR\AppData\Local\apktool\framework\1.apk, -S, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\res, -M, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KRISY~1.DES\AppData\Local\Temp\brut_util_Jar_3948520725014907572.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\KRISY~1.DES\AppData\Local\Temp\APKTOOL2731525356834830561.tmp, -0, arsc, -0, arsc, -I, C:\Users\krisy.DESKTOP-3EFRBLR\AppData\Local\apktool\framework\1.apk, -S, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\res, -M, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KRISY~1.DES\AppData\Local\Temp\brut_util_Jar_3948520725014907572.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\KRISY~1.DES\AppData\Local\Temp\APKTOOL2731525356834830561.tmp, -0, arsc, -0, arsc, -I, C:\Users\krisy.DESKTOP-3EFRBLR\AppData\Local\apktool\framework\1.apk, -S, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\res, -M, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUI.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
A subdirectory or file modified-system-apk-files-here already exists.
W: ERROR: 9-patch image C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\res\drawable-xxxhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\res\drawable-xxxhdpi\pip_dismiss_scrim.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KRISY~1.DES\AppData\Local\Temp\brut_util_Jar_7543208047023060219.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\KRISY~1.DES\AppData\Local\Temp\APKTOOL4037231958546700424.tmp, -0, arsc, -0, arsc, -I, C:\Users\krisy.DESKTOP-3EFRBLR\AppData\Local\apktool\framework\1.apk, -S, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\res, -M, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KRISY~1.DES\AppData\Local\Temp\brut_util_Jar_7543208047023060219.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\KRISY~1.DES\AppData\Local\Temp\APKTOOL4037231958546700424.tmp, -0, arsc, -0, arsc, -I, C:\Users\krisy.DESKTOP-3EFRBLR\AppData\Local\apktool\framework\1.apk, -S, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\res, -M, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KRISY~1.DES\AppData\Local\Temp\brut_util_Jar_7543208047023060219.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\KRISY~1.DES\AppData\Local\Temp\APKTOOL4037231958546700424.tmp, -0, arsc, -0, arsc, -I, C:\Users\krisy.DESKTOP-3EFRBLR\AppData\Local\apktool\framework\1.apk, -S, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\res, -M, C:\Users\krisy.DESKTOP-3EFRBLR\Desktop\APK-Multi-Tool-master\APK-Multi-Tool-master\APK-Multi-Tool-master\projects\SystemUIGoogle.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```

### Steps to Reproduce
1. `apktool b systemui`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment] 2017-09-05 01:26
Hmm. Seems to be a 9patch issue more so than related to Oreo. Recent image tickets:

https://github.com/iBotPeaches/Apktool/issues/1559
https://github.com/iBotPeaches/Apktool/issues/1522

Without the apk to investigate the 9patch image directly, there is not much I can do here :/

**Comment by KrisYarno** [comment] 2017-09-05 01:37
I attached the apk in a zip on the original post. #1522 seems to be a very similar issue

**Comment by Subinsmani** [comment] 2017-09-16 15:23
Hai m trying to recompile systemUI.apk, This error is comming,,,
Any help,
System:- Windows 10
Apktool Version:- apktool_2.2.4
Android:- Oreo
Recompile:- command:- java -jar apktool.jar b SystemUI -c

Error:-
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: 9-patch image C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\res\drawable-xhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\res\drawable-xhdpi\pip_dismiss_scrim.9.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\subin\AppData\Local\Temp\brut_util_Jar_1834093262529986261.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\subin\AppData\Local\Temp\APKTOOL1957412541163737414.tmp, -0, arsc, -0, arsc, -I, C:\Users\subin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\res, -M, C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
        at brut.androlib.Androlib.buildResources(Androlib.java:430)
        at brut.androlib.Androlib.build(Androlib.java:329)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:230)
        at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\subin\AppData\Local\Temp\brut_util_Jar_1834093262529986261.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\subin\AppData\Local\Temp\APKTOOL1957412541163737414.tmp, -0, arsc, -0, arsc, -I, C:\Users\subin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\res, -M, C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\subin\AppData\Local\Temp\brut_util_Jar_1834093262529986261.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, C:\Users\subin\AppData\Local\Temp\APKTOOL1957412541163737414.tmp, -0, arsc, -0, arsc, -I, C:\Users\subin\AppData\Local\apktool\framework\1.apk, -S, C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\res, -M, C:\Users\subin\Desktop\My project\Devices\Osprey\Oreo\Osprey\SystemUI\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more

**Comment by iBotPeaches** [comment] 2017-09-19 21:08
Confirmed

```
W: ERROR: 9-patch image /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1608/SystemUI/res/drawable-xxxhdpi/pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image /Users/connortumbleson/Desktop/Apktool/Bugs/Bug1608/SystemUI/res/drawable-xxxhdpi/pip_dismiss_scrim.9.png
```

**Comment by iBotPeaches** [comment] 2017-12-01 20:29
Confirmed duplicate of #1522. All about this stupid malformed "pip_dismiss_scrim.9.png" image.

Future details will be in #1522 . Thanks for the report.

**Closed by iBotPeaches** 2017-12-01 20:29 UTC
Labels: Bug

**Comment by ROM-PacMe** [comment] 2018-11-07 03:53
i have this another error and don't have idea why have this...

I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
S: WARNING: Could not write to (C:\Users\rafy2\AppData\Local\apktool\framework), using C:\Users\rafy2\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: ERROR: 9-patch image C:\Users\rafy2\Desktop\Apktool_By_Xianos\SystemUI\res\drawable-xxhdpi\pip_dismiss_scrim.9.png malformed.
W:        No marked region found along edge.
W:        Found along left edge.
W: ERROR: Failure processing PNG image C:\Users\rafy2\Desktop\Apktool_By_Xianos\SystemUI\res\drawable-xxhdpi\pip_dismiss_scrim.9.png
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\rafy2\AppData\Local\Temp\brut_util_Jar_4109523728293022626.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 20171030, --version-name, 8.1.0, --no-version-vectors, -F, C:\Users\rafy2\AppData\Local\Temp\APKTOOL3236394871236666726.tmp, -0, arsc, -0, webp, -0, res/drawable-ldrtl-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-mdpi-v4/ic_call_lock_normal.9.png, -0, res/drawable-mdpi-v4/ic_call_lock_pressed.9.png, -0, res/drawable-mdpi-v4/ic_email_lock_normal.9.png, -0, res/drawable-mdpi-v4/ic_email_lock_pressed.9.png, -0, png, -0, res/drawable-xhdpi-v4/ic_biometric_small_icon_bg.9.png, -0, res/drawable-xhdpi-v4/lb_card_shadow_focused.9.png, -0, res/drawable-xhdpi-v4/lb_card_shadow_normal.9.png, -0, res/drawable-xxhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-xxhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_list_divider_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_list_focused_holo.9.png, -0, res/drawable-xxhdpi-v4/abc_list_longpressed_holo.9.png, -0, res/drawable-xxhdpi-v4/abc_list_pressed_holo_dark.9.png, -0, res/drawable-xxhdpi-v4/abc_list_pressed_holo_light.9.png, -0, res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png, -0, res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_light.9.png, -0, res/drawable-xxhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png, -0, res/drawable-xxhdpi-v4/abc_popup_background_mtrl_mult.9.png, -0, res/drawable-xxhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_switch_track_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png, -0, res/drawable-xxhdpi-v4/biometric_toast_progress_bg.9.png, -0, res/drawable-xxhdpi-v4/biometric_toast_result_bg.9.png, -0, res/drawable-xxhdpi-v4/fmm_btn_k.9.png, -0, res/drawable-xxhdpi-v4/fmm_btn_w.9.png, -0, res/drawable-xxhdpi-v4/ic_notification_overlay.9.png, -0, jpg, -0, res/drawable-xxhdpi-v4/lb_action_bg_focused.9.png, -0, res/drawable-xxhdpi-v4/lb_in_app_search_bg.9.png, -0, res/drawable-xxhdpi-v4/lb_in_app_search_shadow_focused.9.png, -0, res/drawable-xxhdpi-v4/lb_in_app_search_shadow_normal.9.png, -0, res/drawable-xxhdpi-v4/nav_background.9.png, -0, res/drawable-xxhdpi-v4/pip_dismiss_scrim.9.png, -0, res/drawable-xxhdpi-v4/recents_lower_gradient.9.png, -0, res/drawable-xxhdpi-v4/recents_status_gradient.9.png, -0, res/drawable-xxhdpi-v4/recents_task_shadow.9.png, -0, res/drawable-xxhdpi-v4/screenshot_panel.9.png, -0, res/drawable-xxhdpi-v4/search_bg_transparent.9.png, -0, res/drawable-xxhdpi-v4/status_background.9.png, -0, res/drawable/bubble_03_l_bottom.9.png, -0, res/drawable/bubble_03_left.9.png, -0, res/drawable/bubble_03_right.9.png, -0, res/drawable/bubble_04_left.9.png, -0, res/drawable/bubble_04_right.9.png, -0, res/drawable/bubble_bottom_arrow_left.9.png, -0, res/drawable/bubble_bottom_arrow_right.9.png, -0, res/drawable/bubble_bottom_r_arrow_left.9.png, -0, res/drawable/bubble_bottom_r_arrow_right.9.png, -0, res/drawable/bubble_left_arrow_bottom.9.png, -0, res/drawable/bubble_left_arrow_top.9.png, -0, res/drawable/bubble_line_03_left.9.png, -0, res/drawable/bubble_line_03_right.9.png, -0, res/drawable/bubble_line_04_left.9.png, -0, res/drawable/bubble_line_04_right.9.png, -0, res/drawable/bubble_line_bottom_arrow_left.9.png, -0, res/drawable/bubble_line_bottom_arrow_right.9.png, -0, res/drawable/bubble_line_bottom_r_arrow_left.9.png, -0, res/drawable/bubble_line_bottom_r_arrow_right.9.png, -0, res/drawable/bubble_line_left_arrow_bottom.9.png, -0, res/drawable/bubble_line_left_arrow_top.9.png, -0, res/drawable/bubble_line_right_arrow_bottom.9.png, -0, res/drawable/bubble_line_right_arrow_top.9.png, -0, res/drawable/bubble_line_top_arrow_left.9.png, -0, res/drawable/bubble_line_top_arrow_right.9.png, -0, res/drawable/bubble_line_top_r_arrow_left.9.png, -0, res/drawable/bubble_line_top_r_arrow_right.9.png, -0, res/drawable/bubble_right_arrow_bottom.9.png, -0, res/drawable/bubble_right_arrow_top.9.png, -0, res/drawable/bubble_top_arrow_left.9.png, -0, res/drawable/bubble_top_arrow_right.9.png, -0, res/drawable/bubble_top_r_arrow_left.9.png, -0, res/drawable/bubble_top_r_arrow_right.9.png, -0, res/drawable/focused_bg.9.png, -0, res/drawable/homescreen_badge_bg.9.png, -0, res/drawable/homescreen_badge_multiselect_bg.9.png, -0, res/drawable/knox_scrollbar.9.png, -0, res/drawable/tw_scrollbar_mtrl.9.png, -0, ogg, -0, arsc, -I, C:\Users\rafy2\AppData\Local\Temp\1.apk, -S, C:\Users\rafy2\Desktop\Apktool_By_Xianos\SystemUI\res, -M, C:\Users\rafy2\Desktop\Apktool_By_Xianos\SystemUI\AndroidManifest.xml]
