### ISSUE TITLE
[BUG] App broken after rebuild

### ISSUE THREAD

**Issue by eroamane** [iBotPeaches/Apktool#3046] opened 2023-04-15 05:35 UTC
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Windows 7
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/tetra-filer-free/jp.main.brits.android.filer.free/download/2114322-APK

no error message on decode and rebuild
app can install and run,  but crash when open files
I decode two apk and compare it
the broken app missing some string in xml

original : style="?attr/actionButtonStyle"
rebuild  : style="?actionButtonStyle"

original apk and rebuild apk
https://mega.nz/folder/c34BiQID#L8XI9ezzQfjRqOeUTUKAFA

**Comment by iBotPeaches** [comment] 2023-04-24 10:33
Thanks for the report, looks like a duplicate of: https://github.com/iBotPeaches/Apktool/issues/2983

**Closed by iBotPeaches** 2023-04-24 10:33 UTC
