### ISSUE TITLE
Common error "error: No resource identifier found for attribute(...)"

### ISSUE THREAD

**Issue by yglo** [iBotPeaches/Apktool#1222] opened 2016-04-13 00:18 UTC
Hi! It is my first post ever, sorry for any mistakes :) SO, i try to decompile and recompile official instagram apk but i'm facing this, as i saw seeking for some help, common problem. I've tried a couple things but nothing worked. Now i don't know what do i do. Could you please help?
### Information
1. **Apktool Version (`apktool -version`)** -
`Apktool v2.0.0-RC4 - a tool for reengineering Android apk files
with smali v2.0.5 and baksmali v2.0.5`
2. **Operating System (Mac, Linux, Windows)** - Windows XP
3. **APK From? (Playstore, ROM, Other)** - let say Playstore, but i downloaded it via external website that allows to download apks manually, if it's allowed, it's called `evozi`

### Stacktrace/Logcat

```
`-------------------------------------------------------------------------- 
|2016-04-12 -- 23:00:55.25| 
-------------------------------------------------------------------------- 
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode, sharing)
warning: string 'News' has no default translation.
warning: string 'about_libraries' has no default translation.
warning: string 'add_a_comment' has no default translation.
warning: string 'add_a_location' has no default translation.
warning: string 'add_to_photo_map' has no default translation.
warning: string 'advanced_features' has no default translation.
warning: string 'advanced_resize' has no default translation.
warning: string 'advanced_resize_warning' has no default translation.
warning: string 'advisory_eating_disorder_warning' has no default translation.
warning: string 'advisory_self_harm_warning' has no default translation.
warning: string 'allow_f1gender' has no default translation.
warning: string 'allow_m2gender' has no default translation.
warning: string 'are_you_sure_f1gender' has no default translation.
warning: string 'are_you_sure_m2gender' has no default translation.
warning: string 'boost_post_f1gender' has no default translation.
warning: string 'boost_post_m2gender' has no default translation.
warning: string 'choose_a_page' has no default translation.
warning: string 'confirm_find_friends' has no default translation.
warning: string 'connect_with_facebook' has no default translation.
warning: string 'content_advisory' has no default translation.
warning: string 'create_a_custom_location' has no default translation.
warning: string 'crop_text_save' has no default translation.
warning: string 'custom_location' has no default translation.
warning: string 'delete_and_report_abuse' has no default translation.
warning: string 'delete_f1gender' has no default translation.
warning: string 'delete_m2gender' has no default translation.
warning: string 'direct_send_f1gender' has no default translation.
warning: string 'direct_send_m2gender' has no default translation.
warning: string 'directshare_action_completed' has no default translation.
warning: string 'directshare_blocking_confirm_button' has no default translation.
warning: string 'directshare_blocking_education_msg' has no default translation.
warning: string 'directshare_comment_hint' has no default translation.
warning: string 'directshare_delete' has no default translation.
warning: string 'directshare_delete_dialog_message' has no default translation.
warning: string 'directshare_delete_dialog_title' has no default translation.
warning: string 'directshare_edit_comments' has no default translation.
warning: string 'directshare_hide_dialog_message' has no default translation.
warning: string 'directshare_hide_dialog_title' has no default translation.
warning: string 'directshare_ignore_all' has no default translation.
warning: string 'directshare_inbox' has no default translation.
warning: string 'directshare_inbox_empty' has no default translation.
warning: string 'directshare_inbox_empty_call_to_action' has no default translation.
warning: string 'directshare_max_recipients_reached_body' has no default translation.
warning: string 'directshare_max_recipients_reached_title' has no default translation.
warning: string 'directshare_notification_inbox_aggregated' has no default translation.
warning: string 'directshare_notification_permalink_aggregated' has no default translation.
warning: string 'directshare_nux_para_1' has no default translation.
warning: string 'directshare_nux_para_2' has no default translation.
warning: string 'directshare_pending_requests' has no default translation.
warning: string 'directshare_permalink_title' has no default translation.
warning: string 'directshare_receive_direct_posts' has no default translation.
warning: string 'directshare_requested_direct_shares_accept_failed' has no default translation.
warning: string 'directshare_requested_direct_shares_aggregate_notification' has no default translation.
warning: string 'directshare_requested_direct_shares_confirm_ignore' has no default translation.
warning: string 'directshare_requested_direct_shares_confirm_ignore_all_msg' has no default translation.
warning: string 'directshare_requested_direct_shares_confirm_ignore_all_positive' has no default translation.
warning: string 'directshare_requested_direct_shares_confirm_ignore_msg' has no default translation.
warning: string 'directshare_requested_direct_shares_confirm_ignore_title' has no default translation.
warning: string 'directshare_requested_direct_shares_ignore_all_button' has no default translation.
warning: string 'directshare_requested_direct_shares_ignore_all_failed' has no default translation.
warning: string 'directshare_requested_direct_shares_ignore_failed' has no default translation.
warning: string 'directshare_requested_direct_shares_request_failed' has no default translation.
warning: string 'directshare_requested_direct_shares_title' has no default translation.
warning: string 'directshare_search_edit_text_hint' has no default translation.
warning: string 'directshare_sending' has no default translation.
warning: string 'directshare_sent' has no default translation.
warning: string 'directshare_title' has no default translation.
warning: string 'directshare_to' has no default translation.
warning: string 'directshare_user_list_header_following' has no default translation.
warning: string 'directshare_user_list_header_suggestions' has no default translation.
warning: string 'directshare_whats_new' has no default translation.
warning: string 'discover_new_people_description_f1gender' has no default translation.
warning: string 'discover_new_people_description_m2gender' has no default translation.
warning: string 'dismiss_f1gender' has no default translation.
warning: string 'dismiss_m2gender' has no default translation.
warning: string 'done_exclamation' has no default translation.
warning: string 'edit_sharing_settings' has no default translation.
warning: string 'email_not_sent_short' has no default translation.
warning: string 'email_reset_link' has no default translation.
warning: string 'explore_people_connect_with_facebook' has no default translation.
warning: string 'explore_people_discover_facebook_friends' has no default translation.
warning: string 'explore_people_follow_people' has no default translation.
warning: string 'explore_people_friends' has no default translation.
warning: string 'explore_people_never_post_to_facebook' has no default translation.
warning: string 'explore_people_ran_out_of_recommendations' has no default translation.
warning: string 'explore_people_recommended' has no default translation.
warning: string 'facebook_explanation_pt1' has no default translation.
warning: string 'facebook_explanation_pt2' has no default translation.
warning: string 'facebook_settings_message' has no default translation.
warning: string 'fail_confirm_email_f1gender' has no default translation.
warning: string 'fail_confirm_email_m2gender' has no default translation.
warning: string 'fail_send_confirm_email_f1gender' has no default translation.
warning: string 'fail_send_confirm_email_m2gender' has no default translation.
warning: string 'failed_to_upload' has no default translation.
warning: string 'find_contacts_promo' has no default translation.
warning: string 'find_facebook_friends_promo' has no default translation.
warning: string 'find_facebook_from_contacts' has no default translation.
warning: string 'find_friends_item_suggested_users' has no default translation.
warning: string 'find_friends_item_twitter_friends' has no default translation.
warning: string 'find_friends_menu_label' has no default translation.
warning: string 'find_vkontakte_friends_promo' has no default translation.
warning: string 'finishing_up' has no default translation.
warning: string 'followers_title' has no default translation.
warning: string 'following_title' has no default translation.
warning: string 'found_1_contact' has no default translation.
warning: string 'found_1_friend' has no default translation.
warning: string 'found_x_contacts' has no default translation.
warning: string 'found_x_friends' has no default translation.
warning: string 'full_name_optional' has no default translation.
warning: string 'hide_f1gender' has no default translation.
warning: string 'hide_m2gender' has no default translation.
warning: string 'how_would_you_like_to_reset_your_password' has no default translation.
warning: string 'incompatible_device' has no default translation.
warning: string 'instagram_camera' has no default translation.
warning: string 'instagram_camera_warning' has no default translation.
warning: string 'instagram_on_the_web' has no default translation.
warning: string 'legacy_camera_capture_options_item_gallery' has no default translation.
warning: string 'legacy_camera_capture_options_item_photo' has no default translation.
warning: string 'legacy_camera_capture_options_title' has no default translation.
warning: string 'likers_title' has no default translation.
warning: string 'main_feed_empty_state_nux_subtitle' has no default translation.
warning: string 'main_feed_empty_state_nux_title' has no default translation.
warning: string 'maps_reporter_dialog_message_f1gender' has no default translation.
warning: string 'maps_reporter_dialog_message_m2gender' has no default translation.
warning: string 'name_this_location' has no default translation.
warning: string 'nux_dayone_duplicate_email' has no default translation.
warning: string 'nux_dayone_new_account' has no default translation.
warning: string 'nux_dayone_register_email' has no default translation.
warning: string 'nux_dayone_register_facebook' has no default translation.
warning: string 'ok_i_understand' has no default translation.
warning: string 'other_issues' has no default translation.
warning: string 'other_options' has no default translation.
warning: string 'people_tagging_hide_from_my_profile' has no default translation.
warning: string 'people_tagging_learn_more' has no default translation.
warning: string 'people_tagging_manual_add_description' has no default translation.
warning: string 'people_tagging_modify_photos_of_you_failure' has no default translation.
warning: string 'people_tagging_remove_me_confirm_f1gender' has no default translation.
warning: string 'people_tagging_remove_me_confirm_m2gender' has no default translation.
warning: string 'people_tagging_search_hint' has no default translation.
warning: string 'people_tagging_settings_fetch_fail' has no default translation.
warning: string 'phone_number_email_private' has no default translation.
warning: string 'photo_maps_unavailable_on_device' has no default translation.
warning: string 'photos_of_you_empty_title' has no default translation.
warning: string 'please_choose_how_you_would_like_to_reset_your_password' has no default translation.
warning: string 'popup_photomaps_confirm_geotag_headerliner' has no default translation.
warning: string 'popup_photomaps_review_headerliner' has no default translation.
warning: string 'post_dialog_title_f1gender' has no default translation.
warning: string 'post_dialog_title_m2gender' has no default translation.
warning: string 'preferences' has no default translation.
warning: string 'privacy_fail' has no default translation.
warning: string 'profile_picture_post_message' has no default translation.
warning: string 'profile_tagged_description_f1gender' has no default translation.
warning: string 'profile_tagged_description_m2gender' has no default translation.
warning: string 'promote_f1gender' has no default translation.
warning: string 'promote_m2gender' has no default translation.
warning: string 'rate_ads_f1gender' has no default translation.
warning: string 'rate_ads_m2gender' has no default translation.
warning: string 'register' has no default translation.
warning: string 'remove_current_picture' has no default translation.
warning: string 'report_inappropriate_f1gender' has no default translation.
warning: string 'report_inappropriate_m2gender' has no default translation.
warning: string 'report_option_dialog_title_for_post_f1gender' has no default translation.
warning: string 'report_option_dialog_title_for_post_m2gender' has no default translation.
warning: string 'report_option_dialog_title_for_profile_f1gender' has no default translation.
warning: string 'report_option_dialog_title_for_profile_m2gender' has no default translation.
warning: string 'report_options_f1gender' has no default translation.
warning: string 'report_options_m2gender' has no default translation.
warning: string 'request_error_f1gender' has no default translation.
warning: string 'request_error_m2gender' has no default translation.
warning: string 'requires_google_maps_api' has no default translation.
warning: string 'resetting_password' has no default translation.
warning: string 'saving' has no default translation.
warning: string 'search_f1gender' has no default translation.
warning: string 'search_for_a_location' has no default translation.
warning: string 'search_instagram' has no default translation.
warning: string 'search_m2gender' has no default translation.
warning: string 'search_or_add_a_location' has no default translation.
warning: string 'search_places_nearby' has no default translation.
warning: string 'security_exception_f1gender' has no default translation.
warning: string 'security_exception_m2gender' has no default translation.
warning: string 'see_all_f1gender' has no default translation.
warning: string 'see_all_m2gender' has no default translation.
warning: string 'send' has no default translation.
warning: string 'sending_email' has no default translation.
warning: string 'sending_sms' has no default translation.
warning: string 'share_f1gender' has no default translation.
warning: string 'share_likes_on_facebook' has no default translation.
warning: string 'share_m2gender' has no default translation.
warning: string 'share_photo' has no default translation.
warning: string 'share_to_timeline' has no default translation.
warning: string 'share_with_followers' has no default translation.
warning: string 'share_with_specific_people' has no default translation.
warning: string 'sign_in' has no default translation.
warning: string 'sms_not_sent_short' has no default translation.
warning: string 'starred_hide' has no default translation.
warning: string 'tabbed_landing_bottom_policy' has no default translation.
warning: string 'tabbed_landing_confirmation_code_explain' has no default translation.
warning: string 'tabbed_landing_confirmation_code_header' has no default translation.
warning: string 'tabbed_landing_confirmation_code_resend' has no default translation.
warning: string 'tabbed_landing_email_hint' has no default translation.
warning: string 'tabbed_landing_full_name_hint' has no default translation.
warning: string 'tabbed_landing_log_in_with_facebook' has no default translation.
warning: string 'tabbed_landing_name_hint' has no default translation.
warning: string 'tabbed_landing_new_reg_email_hint' has no default translation.
warning: string 'tabbed_landing_password_hint' has no default translation.
warning: string 'tabbed_landing_subtitle_log_in' has no default translation.
warning: string 'tabbed_landing_subtitle_sign_up' has no default translation.
warning: string 'tabbed_landing_terms' has no default translation.
warning: string 'tabbed_landing_username_hint' has no default translation.
warning: string 'tap_to_refresh_f1gender' has no default translation.
warning: string 'tap_to_refresh_m2gender' has no default translation.
warning: string 'tap_to_retry' has no default translation.
warning: string 'thanks_for_feedback' has no default translation.
warning: string 'toggle_privacy_confirm_turning_off_body' has no default translation.
warning: string 'toggle_privacy_confirm_turning_off_title' has no default translation.
warning: string 'toggle_privacy_confirm_turning_on_body' has no default translation.
warning: string 'toggle_privacy_confirm_turning_on_title' has no default translation.
warning: string 'try_again_f1gender' has no default translation.
warning: string 'try_again_m2gender' has no default translation.
warning: string 'unable_to_add_foursquare_location_no_maps' has no default translation.
warning: string 'unable_to_find_account' has no default translation.
warning: string 'unable_to_save_full_image' has no default translation.
warning: string 'unable_to_save_upload_image' has no default translation.
warning: string 'unable_to_share_profile_photo' has no default translation.
warning: string 'unlink_your_account' has no default translation.
warning: string 'unsupported_device_message' has no default translation.
warning: string 'use_email_instead' has no default translation.
warning: string 'use_phone_number_instead' has no default translation.
warning: string 'username_x_is_not_available' has no default translation.
warning: string 'verified' has no default translation.
warning: string 'video_cover_screen_title' has no default translation.
warning: string 'video_failed_to_start' has no default translation.
warning: string 'video_preload_always' has no default translation.
warning: string 'video_preload_preference' has no default translation.
warning: string 'video_preload_preference_title' has no default translation.
warning: string 'video_preload_wifi' has no default translation.
warning: string 'video_sound_preference' has no default translation.
warning: string 'view_profile_f1gender' has no default translation.
warning: string 'view_profile_m2gender' has no default translation.
warning: string 'we_will_review_this_user_asap' has no default translation.
warning: string 'welcome_back_enter_twice' has no default translation.
warning: string 'welcome_f1gender' has no default translation.
warning: string 'xauth_security_message' has no default translation.
warning: string 'yes_im_sure_f1gender' has no default translation.
warning: string 'yes_im_sure_m2gender' has no default translation.
warning: string 'yes_skip_this_step' has no default translation.
warning: string 'zoom' has no default translation.
G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\res\layout-v21\channel_view.xml:9: error: No resource identifier found for attribute 'letterSpacing' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\DOCUME~1\admin\~1\Temp\brut_util_Jar_434910695901279912.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 27105647, --version-name, 7.20.0, -F, C:\DOCUME~1\admin\~1\Temp\APKTOOL3818622569084837983.tmp, -0, arsc, -I, C:\Documents and Settings\admin\apktool\framework\1.apk, -S, G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\res, -M, G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:442)
	at brut.androlib.Androlib.buildResources(Androlib.java:379)
	at brut.androlib.Androlib.build(Androlib.java:282)
	at brut.androlib.Androlib.build(Androlib.java:255)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\DOCUME~1\admin\~1\Temp\brut_util_Jar_434910695901279912.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 27105647, --version-name, 7.20.0, -F, C:\DOCUME~1\admin\~1\Temp\APKTOOL3818622569084837983.tmp, -0, arsc, -I, C:\Documents and Settings\admin\apktool\framework\1.apk, -S, G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\res, -M, G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:504)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:428)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\DOCUME~1\admin\~1\Temp\brut_util_Jar_434910695901279912.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 27105647, --version-name, 7.20.0, -F, C:\DOCUME~1\admin\~1\Temp\APKTOOL3818622569084837983.tmp, -0, arsc, -I, C:\Documents and Settings\admin\apktool\framework\1.apk, -S, G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\res, -M, G:\UTILITIES\ANDROID\APK-Multi-Tool\other\..\projects\instagram-7.20.0.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:498)
	... 6 more
`
```

### Steps to Reproduce
1. simple `apktool b instagram-7.20.0.apk` doesn't even work

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

i dont know  what should i put in here, but just for the information, i'm using framework right from my rom that can be found in \system\framework\framework-res.apk dir.

### APK
well,it is the latest release of the instagram's official apk 
for some reason i can't upload to github so here's the link:
http://www43.zippyshare.com/v/3f5dLir4/file.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **yes**
2. If you are trying to install a modified apk, did you resign it? **i didn't even get to this step.**
3. Are you using the latest apktool version? **yes**

Thanks!

**Comment by BurgerZ** [comment] 2016-04-13 05:19
You said that you are using the latest apktool, but in the information block we see:
`Apktool Version (apktool -version) - Apktool v2.0.0-RC4 - a tool for reengineering Android apk files with smali v2.0.5 and baksmali v2.0.5`
**Apktool v2.0.0-RC4** is not the latest version

**Comment by yglo** [comment] 2016-04-13 20:26
Indeed, my apologies for the oversight. I downloaded this version like in the mid-march and i didn't know that there was a newer release. But still, even though i tried with this v2.1.0 the problem still occurs:(. It seems to be not fixed yet. I saw the same issue in this topic #1157 so it's officially labeled as a bug.

**Comment by iBotPeaches** [comment] 2016-04-13 20:29
No problem. Thanks for following the issue guideline. I just made those about 2-3 weeks ago and you were first person to use the formatting tips I included to formatting code and more. It made it very easy to triage and investigate which helps me a ton.

This is indeed a duplicate of #1157 which is a messy one.

**Comment by yglo** [comment] 2016-04-15 10:39
@iBotPeaches My pleasure! Your guideline actually made me easier to describe the issue :) And thank you for the answer. Maybe there is any workaround that can be done to make it work by the time the issue is resolved?

**Comment by iBotPeaches** [comment] 2016-04-18 12:16
https://github.com/iBotPeaches/Apktool/issues/1157#issuecomment-179552339 That comment would explain it the best.

However, on additional testing I'm having no errors decoding this version. Delete the file at `$HOME/apktool/framework/1.apk` and try again. It seems you have an outdated framework file.

```
➜  Bug1222 apktool d instagram-7.20.0.apk 
I: Using Apktool 2.1.0-180728-SNAPSHOT on instagram-7.20.0.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1222 apktool b instagram-7.20.0
I: Using Apktool 2.1.0-180728-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'News' has no default translation.
W: warning: string 'about_libraries' has no default translation.
...
W: warning: string 'zoom' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1222 
```

**Closed by iBotPeaches** 2016-04-18 12:16 UTC
Labels: Duplicate
