### ISSUE TITLE
Two versions of apktool in linux

### ISSUE THREAD

**Issue by Nisthar** [iBotPeaches/Apktool#1679] opened 2017-12-06 17:05 UTC
I am using kali linux.

I already had an apktool of version 2.2.0 preinstalled in it. I installed Fatrat. I think it tried to update apktool.

Everytime, i run `apktool d apkname.apk` and `apktool b apkname` It uses apktool version 2.2.0

Now, the problem is:
everytime i try to update apktool by running command `sudo apt-get install apktool` or `sudo apt-get upgrade apktool`

It says, the apktool version is 2.3.0 and is already the latest version.

**Comment by iBotPeaches** [comment] 2017-12-06 17:13
I have no control sadly over the packages that kali uses and not sure how installing fatrat has anything to do with an OS package. This is a support issue regarding unix and running software. I am going to close this as it is not a bug.

**Closed by iBotPeaches** 2017-12-06 17:13 UTC

**Comment by Nisthar** [comment] 2017-12-06 17:16
@iBotPeaches Ok, Sorry. I thought its related to this package. And there is a guide for it.

**Comment by iBotPeaches** [comment] 2017-12-06 17:18
This is Apktool, but I have nothing to do with the Apktool package in kali.

**Comment by Nisthar** [comment] 2017-12-06 17:22
@iBotPeaches BTW i am trying this to fix this issue https://github.com/iBotPeaches/Apktool/issues/1157

Is the latest version still have this issue?
