### ISSUE TITLE
Apktool build fails

### ISSUE THREAD

**Issue by canyouamrit** [iBotPeaches/Apktool#2114] opened 2019-06-28 06:13 UTC
### Information
1. **Apktool Version (`2.3.4-Dirty`)** -
2. **Ubuntu 18.04** -
3. **APK From? (apkpure.com)** -

### Stacktrace/Logcat
```
I: Using Apktool 2.3.4-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:790)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:340)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
	at brut.androlib.Androlib.buildSources(Androlib.java:350)
	at brut.androlib.Androlib.build(Androlib.java:302)
	at brut.androlib.Androlib.build(Androlib.java:269)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
```

...
Notes
1. Before you ask let me tell you that, I have no idea about the tag 'Dirty' in the apktool name.
I Installed the apktool using the command **sudo apt install apktool**, the n it did everything else on itself. so I guess that it's not tampered.
2. I decompiled the apk and then tried to rebuild it without changing a single thing, but this error keep on showing up.
...

**Comment by iBotPeaches** [comment] 2019-07-14 11:49
`dirty` means the application was built without git support, so it couldn't pull snapshot information. Since this stacktrace indicates something wrong with the depedendencies/methods. I'm going to close this. It looks caused by environment and/or this dirty build.

If someone this low level was broken our automated test would be broken. You can try downloading the latest new release as currently v2.4.0 is out.

**Closed by iBotPeaches** 2019-07-14 11:49 UTC
